### ISSUE TITLE
Azure Arc enabled App Service on K3s

### ISSUE THREAD

**Issue by decibe1magic** [microsoft/azure_arc#1031]
failed deploy app services on azure arc connected k3s

I installed k3s in Azure VM (Ubuntu 20.04).
When installing k3s, I uninstalled traefik and installed it.

When you execute the command to install App Service Extension, you will receive the following error message:
![error](https://user-images.githubusercontent.com/50003981/159417535-cdf65d9a-c253-4244-a063-9e25e907b37b.PNG)

The commands entered are as follows:
az k8s-extension create
--resource-group k3s-rg
--name appservice-ext
--cluster-type connectedClusters
--cluster-name k3s-cluster
--extension-type 'Microsoft.Web.Appservice'
--release-train stable
--auto-upgrade-minor-version true
--scope cluster
--release-namespace appservice-ns
--configuration-settings "Microsoft.CustomLocation.ServiceAccount=default"
--configuration-settings "appsNamespace=appservice-ns"
--configuration-settings "clusterName=swkim-arc-function"
--configuration-settings "keda.enabled=true"
--configuration-settings "buildService.storageClassName=local-path"
--configuration-settings "buildService.storageAccessMode=ReadWriteOnce"
--configuration-settings "customConfigMap=${namespace}/kube-environment-config"
--configuration-settings "logProcessor.appLogs.destination=log-analytics"
--configuration-protected-settings "logProcessor.appLogs.logAnalyticsConfig.customerId=${logAnalyticsWorkspaceIdEnc}"
--configuration-protected-settings "logProcessor.appLogs.logAnalyticsConfig.sharedKey=${logAnalyticsKeyEnc}"

However, unlike the error message, App Service Extension appears to be installed.
![error6](https://user-images.githubusercontent.com/50003981/159419078-13975ca2-03c3-4db5-bc48-2e5148ff9dfe.PNG)
![error2](https://user-images.githubusercontent.com/50003981/159417580-710e20b8-378a-4eb9-8158-53885ea3e047.PNG)

After the extension installation, the Function App distribution seems to be successful.
![error3](https://user-images.githubusercontent.com/50003981/159418024-73da86b7-6cf3-453a-8213-b6f64e1ac3de.PNG)
![error4](https://user-images.githubusercontent.com/50003981/159418034-8872c029-1b86-4809-8795-43858f415b3d.PNG)

If you check the URL after distributing the Function App, the URL is linked to the private ip address.
![error5](https://user-images.githubusercontent.com/50003981/159418301-7f3eba14-d798-4dcf-9e43-789e4396cc2c.PNG)
Therefore, only addresses in the same band can access the Function App.

Is there a way to access this URL from outside?

**Comment by likamrat** [comment]
Thank you @decibe1magic. Although this is not a current Jumpstart scenario, I am looping @apwestgarth for some insights. Would like to assess if we should be adding this to our scenarios backlog.

**Comment by apwestgarth** [comment]
@decibe1magic this looks like everything is working correctly.  Looking at the list of services and the external IP assigned they correspond.  All inbound traffic to apps is routed through envoy which I see in your list of services:

appservice-ext-k8se-envoy - External IP 10.1.0.4

Therefore, Kubernetes has assigned that IP from the address pool available to the loadbalancer service type.  As this cluster is not exposed externally that is the address on which your function will receive requests.  You could add an entry to your local DNS/Hosts file to route (*.swkim-arc-functi-cdesf6s.eastus.k4apps.io) to 10.1.0.4
