### ISSUE TITLE
arc

### ISSUE THREAD

**Issue by iboayay** [microsoft/azure_arc#1037]
> **Disclaimer: The intent of this "Feature request" templates is to address issues related to the Azure Arc Jumpstart scenarios, ArcBox and all other project ares. The Azure Arc Jumpstart team does not handle Azure Arc core product issues, bugs and feature requests and will try to assist on a best effort basis. For a core product issue or feature request/feedback, please create an official [Azure support ticket](https://azure.microsoft.com/support/create-ticket/) or [general feedback request](https://feedback.azure.com)**

**Is your feature request related to a new Jumpstart scenario you would like to contribute?**
That's great! Use our Jumpstart Scenario Write-up Guidelines
https://azurearcjumpstart.io/scenario_guidelines

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. As a user of ... I would like to have [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dkirby-ms** [comment]
Hi @iboayay. It looks like this issue might have been created by mistake?
