### ISSUE TITLE
AMA Option

### ISSUE THREAD

**Issue by DeanGross** [microsoft/azure_arc#1042]
**Is your feature request related to a problem? Please describe.**
The discussion only mentions the Microsoft Management Agent which is being phased out, 

**Describe the solution you'd like**
Add instructions for using AMA, https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-overview?tabs=PowerShellWindows

**Comment by dkirby-ms** [comment]
Hi Dean, this is something that the Jumpstart team has discussed and is part of our backlog. AMA agent does not yet support some of the Log Analytics workspace solutions such as Update Management and Change tracking which are featured in various scenarios and in ArcBox. 

Having said that, AMA is something we will continue to evaluate for a future scenario.

**Comment by likamrat** [comment]
Related to #1131

**Comment by likamrat** [comment]
Closed via #1235
