### ISSUE TITLE
az connectedk8s fails on Ubuntu20.04 (Microk8s) - InternalError: Unable to install helm release: WARNING: Kubernetes configuration file is group-readable.

### ISSUE THREAD

**Issue by jeremytcorp** [microsoft/azure_arc#1047]
> **Disclaimer: The intent of this "Bug report" templates is to address issues related to the Azure Arc Jumpstart scenarios, ArcBox and all other project ares. The Azure Arc Jumpstart team does not handle Azure Arc core product issues, bugs and feature requests and will try to assist on a best effort basis. For a core product issue or feature request/feedback, please create an official [Azure support ticket](https://azure.microsoft.com/support/create-ticket/) or [general feedback request](https://feedback.azure.com)**

**Scenario which you are working on**
A link to the Jumpstart scenario you are working on.
https://github.com/microsoft/azure_arc/blob/8c9c988be67d1be49aa2b3a47890e8539dd919ef/docs/azure_arc_jumpstart/azure_arc_k8s/microk8s/local_microk8s/_index.md

**Describe the bug**
az connectedk8s command fails after install microk8s on ubuntu 20.04

**To Reproduce**
1. Create an Azure VM running ubuntu 20.04
2. Run "sudo snap install microk8s --classic"
3. Attempt to connect kubernetes instance using the 'az connectedk8s' command
    InternalError: Unable to install helm release: WARNING: Kubernetes configuration file is group-readable.

**Expected behavior**
Cluster to be successfully connected via the ARC resource in portal.

**Additional context**

 WARNING: cli.azext_connectedk8s.custom: Unable to fetch the Object ID of the Azure AD application used by Azure Arc service. Proceeding with the Object ID provided to enable the 'custom-locations' feature. WARNING: cli.azext_connectedk8s._utils: Please check if the azure-arc namespace was deployed and run 'kubectl get pods -n azure-arc' to check if all the pods are in running state. A possible cause for pods stuck in pending state could be insufficient resources on the kubernetes cluster to onboard to arc. DEBUG: cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception: DEBUG: cli.azure.cli.core.util: Traceback (most recent call last): File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke cmd_result = self.invocation.execute(args) File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute raise ex File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially results.append(self._run_job(expanded_arg, cmd_copy)) File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job result = cmd_copy(params) File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__ return self.handler(*args, **kwargs) File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler return op(**command_args) File "/root/.azure/cliextensions/connectedk8s/azext_connectedk8s/custom.py", line 293, in create_connectedk8s utils.helm_install_release(chart_path, subscription_id, kubernetes_distro, kubernetes_infra, resource_group_name, cluster_name, File "/root/.azure/cliextensions/connectedk8s/azext_connectedk8s/_utils.py", line 345, in helm_install_release raise CLIInternalError("Unable to install helm release: " + error_helm_install.decode("ascii")) azure.cli.core.azclierror.CLI**InternalError: Unable to install helm release: WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: ./config WARNING: Kubernetes configuration file is world-readable.** This is insecure. Location: ./config Error: timed out waiting for the condition ERROR: cli.azure.cli.core.azclierror: Unable to install helm release: WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: ./config WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: ./config Error: timed out waiting for the condition ERROR: az_command_data_logger: Unable to install helm release: WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: ./config WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: ./config Error: timed out waiting for the condition DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f35e0509790>] INFO: az_command_data_logger: exit code: 1 INFO: cli.__main__: Command ran in 657.592 seconds (init: 0.140, invoke: 657.452) INFO: telemetry.save: Save telemetry record of length 11240 in cache INFO: telemetry.check: Returns Positive. INFO: telemetry.main: Begin creating telemetry upload process. INFO: telemetry.process: Creating upload process: "/usr/bin/../../opt/az/bin/python3 /opt/az/lib/python3.8/site-packages/azure/cli/telemetry/__init__.py /root/.azure" INFO: telemetry.process: Return from creating process

**Comment by dkirby-ms** [comment]
Is this issue related to the specific microk8s Jumpstart scenario (https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/microk8s/local_microk8s/)?

**Comment by jeremytcorp** [comment]
Yes @dkirby-ms. When you get to the 'az connectedk8s' command, things will fail.

**Comment by dkirby-ms** [comment]
Thanks @jeremytcorp. After a closer review of this scenario, we will need to update/refactor it to account for some missing steps. That said, I was able to get the Azure VM running Microk8s onboarded as a connected cluster. The missing step in the Jumpstart scenario appears to be related to adding the user to the microk8s group. 

![image](https://user-images.githubusercontent.com/32211549/161821809-0e2efaa8-0f44-41a7-a0fb-473b188c0788.png)

The team will work on updating this scenario to account for the missing step.

**Comment by likamrat** [comment]
Thank you @jeremytcorp. I moved this as a backlog item for next release

**Comment by jeremytcorp** [comment]
Thanks @dkirby-ms... worked like a charm!
