### ISSUE TITLE
Arc enabled SQL Servers - missing registration for Microsoft.HybridCompute

### ISSUE THREAD

**Issue by sk-bln** [microsoft/azure_arc#1105]
> **Disclaimer: The intent of this "Bug report" templates is to address issues related to the Azure Arc Jumpstart scenarios, ArcBox and all other project ares. The Azure Arc Jumpstart team does not handle Azure Arc core product issues, bugs and feature requests and will try to assist on a best effort basis. For a core product issue or feature request/feedback, please create an official [Azure support ticket](https://azure.microsoft.com/support/create-ticket/) or [general feedback request](https://feedback.azure.com)**

**Scenario which you are working on**
Arc enabled SQL Server 

**Describe the bug**
If the Microsoft.HybridCompute provider is not registered, installing the management pack fails

**To Reproduce**
1. Have a subscription where Microsoft.HybridCompute provider is not registered
2. Go through scenario until login script runs
3. Error occurs and Arc resources are not registered

**Expected behavior**
Require registration of Microsoft.HybridCompute in the document

**Comment by sebassem** [comment]
Thanks a lot @sk-bln for your contribution, great catch. We will update the docs to point that out
