### ISSUE TITLE
Arc enables SQL Server - missing --scopes from az ad sp create-for-rbac

### ISSUE THREAD

**Issue by sk-bln** [microsoft/azure_arc#1106]
> **Disclaimer: The intent of this "Bug report" templates is to address issues related to the Azure Arc Jumpstart scenarios, ArcBox and all other project ares. The Azure Arc Jumpstart team does not handle Azure Arc core product issues, bugs and feature requests and will try to assist on a best effort basis. For a core product issue or feature request/feedback, please create an official [Azure support ticket](https://azure.microsoft.com/support/create-ticket/) or [general feedback request](https://feedback.azure.com)**

**Scenario which you are working on**
Arc enables SQL Server

**Describe the bug**
Missing --scopes from az ad sp create-for-rbac

**To Reproduce**
1. In one step, one should execute  az ad sp create-for-rbac -n "ArcSQLSP" --role contributor
2. With current az (2.35) this leads to an error about the missing --scopes option

**Expected behavior**
In the documentation, the command should be 
az ad sp create-for-rbac -n "ArcSQLSP" --role contributor --scopes /subscriptions/<subscriptionid>

**Comment by dkirby-ms** [comment]
Thank you @sk-bln. This is something we will correct in the README guides for scenarios across the Jumpstart.
