### ISSUE TITLE
Ubuntu EC2 instance

### ISSUE THREAD

**Issue by BKDude** [microsoft/azure_arc#1114]
> **Disclaimer: The intent of this "Bug report" templates is to address issues related to the Azure Arc Jumpstart scenarios, ArcBox and all other project ares. The Azure Arc Jumpstart team does not handle Azure Arc core product issues, bugs and feature requests and will try to assist on a best effort basis. For a core product issue or feature request/feedback, please create an official [Azure support ticket](https://azure.microsoft.com/support/create-ticket/) or [general feedback request](https://feedback.azure.com)**

**Scenario which you are working on**
[A link to the Jumpstart scenario you are working on.](https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_servers/aws/aws_terraform_ubuntu/)

**Describe the bug**
When doing a terraform plan it appears to hang.  Trace log in TF shows:
2022/04/19 16:44:39 [TRACE] dag/walk: vertex "azurerm_resource_group.azure_rg" is waiting for "provider.azurerm"
2022/04/19 16:44:41 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "azurerm_resource_group.azure_rg"
2022/04/19 16:44:41 [TRACE] dag/walk: vertex "root" is waiting for "provider.azurerm (close)"

**To Reproduce**
Follow the instructions and then do "terraform plan" or "terraform apply"

**Expected behavior**
scripts completed

**Screenshots**
None

**Additional context**
None

**Comment by dkirby-ms** [comment]
Can you share more about what version of Terraform you are running (terraform -v) and on what OS version?

**Comment by BKDude** [comment]
Sure:
Terraform v0.12.31
Ubuntu 20.04 LTS (GNU/Linux 5.10.102.1-microsoft-standard-WSL2 x86_64)

I am running the older version of TF because the template reported an incompatible error when I was running the most current of TF, saw this in the provider so matched to avoid the error:
terraform {
  required_version = "~> 0.12"
  required_providers {
    aws     = "~> 2.7.0"
    local   = "~> 1.4"
    http    = "~> 1.2.0"
    azurerm = "~> 2.9.0"
  }
}

Thank you!
BK

**Comment by dkirby-ms** [comment]
Hi @BKDude, we have a workstream in place to refresh Terraform scenarios and align on version and provider requirements. I am going to close this issue for now. In the meantime I suggest using latest TF version for Jumpstart scenarios.
