### ISSUE TITLE
k8s (AKS) Basic GitOps Flow - nginx issue

### ISSUE THREAD

**Issue by smitzlroy** [microsoft/azure_arc#1125]
**Scenario which you are working on**
https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/day2/aks/aks_gitops_basic/

**Describe the bug**
Following the deployment of the az_k8sconfig_aks script i notice that the documentation guide has you check for pods in both "cluster-config" and "hello-arc" namespaces. However the outputs dont match. For hello-arc specifically the nginx ingress controller pods are not deployed (they look to be deployed to cluster-mgmt namespace). 

Also "hello-arc" does not have the LoadBalancer service (to get public IP).

I cant be sure but it looks like work has been done to move to cluster level config from namespace level config but not fully complete or working. I was once able to utilise this scenario fine.

**To Reproduce**
To reproduce this follow the scenario instructions on the link above.

**Expected behavior**
I expected the behaviour to be as in the documentation guide and associated screen grabs. Essentially the nginx ingress controller at namespace level. With the hello-arc app having a LB svc.

**Screenshots**

![image](https://user-images.githubusercontent.com/11997825/165081472-206a8eb1-5b0a-44be-93df-51b90af7472c.png)

**Additional context**
It looks like in addition to this scenario, the "helm" scenario is similar. I will raise a separate issue for that (maybe PR) when i have time to double check.

**Comment by likamrat** [comment]
Thank you @smitzlroy. We are in the process of refreshing the Azure Arc-enabled Kubernetes scenarios with AKS including the GitOps ones. 

/assign @zaidmohd
