### ISSUE TITLE
Refresh Inventory Tagging scenario for Azure Arc-enabled servers 

### ISSUE THREAD

**Issue by alsanch** [microsoft/azure_arc#1132]
**Scenario which you are working on**
[Inventory Tagging](https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_servers/day2/arc_inventory_tagging/)

**Describe the bug**
Refresh the _Inventory Tagging_ scenario for Azure Arc-enabled servers.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by dkirby-ms** [comment]
Addressed in #1202
