### ISSUE TITLE
Azure ArcBox CSI Driver not installed

### ISSUE THREAD

**Issue by jbpaux** [microsoft/azure_arc#1150]
> **Disclaimer: The intent of this "Bug report" templates is to address issues related to the Azure Arc Jumpstart scenarios, ArcBox and all other project ares. The Azure Arc Jumpstart team does not handle Azure Arc core product issues, bugs and feature requests and will try to assist on a best effort basis. For a core product issue or feature request/feedback, please create an official [Azure support ticket](https://azure.microsoft.com/support/create-ticket/) or [general feedback request](https://feedback.azure.com)**

**Scenario which you are working on**
Deployment of Azure ArcBox Full flavor

**Describe the bug**
I tried to deploy twice the ArcBox full flavor without any luck. First time I thought I was doing something wrong. It was stuck during the data controller deployment so I deleted everything but the second try did the same.
I troubleshooted a bit more and saw the pods were in pending state, because the PVC cannot be done. The PVC was waiting the external provisionner to occur but there was no azure csi pods created. I installed them using Helm and it unblocked everything and I'm good to go.
Maybe you should try to redeploy an ArcBox to see if you have the same issue. I guess something changed in AKS version, engine, CLI or whatever.

**To Reproduce**
1. Deploy ArcBox full flavor
2. Connect to the VM once it's deployed
3. Wait for the remaining tasks and see it's stuck in data controller deployment

**Expected behavior**
ArcBox deployed and fully functional

**Screenshots**
Sorry I don't have any but you can trust me haha. kubectl get pods -n arc shows bootstrap running then 2 pods pending and no azure csi pods in kube-system namespace

**Additional context**

**Comment by likamrat** [comment]
Thank you @jbpaux, we are aware of the issue and are about to stage a PR to fix this. This is something we are working towards streamlining with the Cluster API team.
