### ISSUE TITLE
Owner Role But No Write permission

### ISSUE THREAD

**Issue by Abdelrahman-Kamaleldine** [microsoft/azure_arc#1165]
> **Disclaimer: The intent of this "Bug report" templates is to address issues related to the Azure Arc Jumpstart scenarios, ArcBox and all other project ares. The Azure Arc Jumpstart team does not handle Azure Arc core product issues, bugs and feature requests and will try to assist on a best effort basis. For a core product issue or feature request/feedback, please create an official [Azure support ticket](https://azure.microsoft.com/support/create-ticket/) or [general feedback request](https://feedback.azure.com)**

**Scenario which you are working on**
A link to the Jumpstart scenario you are working on.
https://azurearcjumpstart.io/azure_jumpstart_arcbox/itpro/

**Describe the bug**
I have an Owner role but when trying to activate "Onboard SQL Server", I am recieving "User ##### missing 'write' permissions to Resource Group 'ARC_BOX'. Please see the log for additional details."

**To Reproduce**
1. Go to ArcBox-Client (connect to the machine)
2. Click on "Onboard SQL sever" icon
3. paste the code and use an owner role to login
4. See error "User (AbdelRahman Kamaleldine) missing 'write' permissions to Resource Group 'ARC_BOX'"

**Expected behavior**
User (AbdelRahman Kamaleldine) has 'write' permissions to Resource Group 'ARC_BOX'

**Screenshots**

![owner_role](https://user-images.githubusercontent.com/56579982/167829675-427e4e59-28fe-4391-932b-98056f7a1e78.JPG)

![missing_write_permission](https://user-images.githubusercontent.com/56579982/167830760-2181c278-5905-4778-9903-24fe5ef2a926.JPG)

**Additional context**

**Comment by DCMattyG** [comment]
Hello @Abdelrahman-Kamaleldine, thanks for letting us know about this. How soon before running the SQL script were you assigned (or assigned yourself) as an Owner on the target Resource Group? Is this a role you had for a while (at least 15/20 minutes) prior to running the SQL script, or something you assigned just before?

**Comment by Abdelrahman-Kamaleldine** [comment]
Hello @DCMattyG, I tried first time to run the script yesterday and when I received the error, I assigned the Owner role and tried several times, but I am facing the same error till today.

**Comment by DCMattyG** [comment]
@Abdelrahman-Kamaleldine, the fix is now merged. Please let us know if you have any further issues. Thanks!
