### ISSUE TITLE
Please change the way ServicePrincipal name is given in example

### ISSUE THREAD

**Issue by SurbhiAgarwal12** [microsoft/azure_arc#1176]
> **Disclaimer: The intent of this "Bug report" templates is to address issues related to the Azure Arc Jumpstart scenarios, ArcBox and all other project ares. The Azure Arc Jumpstart team does not handle Azure Arc core product issues, bugs and feature requests and will try to assist on a best effort basis. For a core product issue or feature request/feedback, please create an official [Azure support ticket](https://azure.microsoft.com/support/create-ticket/) or [general feedback request](https://feedback.azure.com)**

**Scenario which you are working on**
https://azurearcjumpstart.io/azure_jumpstart_arcbox/full/

**Describe the bug**
To create a Service Principal the right way is - https://{tenant name}.onmicrosoft.com/{app registration name}

**Expected behavior**

Please update the documentation so that it can help others as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/54700229/168899501-fa8c8e95-79f6-4d98-aef6-0bd1df7d9cb8.png)

![image](https://user-images.githubusercontent.com/54700229/168899851-54094886-a5e4-4bab-8087-96c8a746b999.png)

**Comment by dkirby-ms** [comment]
Hi Surbhi, can you please tell me what version of Az CLI you are seeing this error? I am not able to reproduce using latest CLI (2.36.0)

**Comment by SurbhiAgarwal12** [comment]
Hi Dale, I am using the azure-cli version 2.16.0

**Comment by SurbhiAgarwal12** [comment]
As per documentation it is written that - "[Install or update Azure CLI to version 2.15.0 and above](https://docs.microsoft.com/cli/azure/install-azure-cli?view=azure-cli-latest). Use the below command to check your current installed version." So I didn't even try to update the Azure CLI version.

**Comment by likamrat** [comment]
@SurbhiAgarwal12 can you please upgrade AzCLI to the latest? I am unable to repro. Once confirmed, I will push an update.

**Comment by likamrat** [comment]
Pushed a README update
