### ISSUE TITLE
SAS Token not valid for VHDX download

### ISSUE THREAD

**Issue by Stephan2402** [microsoft/azure_arc#1180]
**Scenario which you are working on**
[A link to the Jumpstart scenario you are working on.](https://azurearcjumpstart.io/azure_jumpstart_arcbox/full/#prerequisites)

**Describe the bug**
In the Post-Deployment Script "ArcServersLogonScript" the script try to download the VHDX files for the VMs.
But the SAS Token seems to be out auf time.

_AuthenticationErrorDetail: Signature not valid in the specified time frame: Start [Thu, 19 May 2022 19:07:08 GMT] - E
xpiry [Fri, 20 May 2022 03:07:08 GMT] - Current [Fri, 20 May 2022 11:28:13 GMT]_

**To Reproduce**
Start Post-Deployment Script "ArcServersLogonScript"

**Expected behavior**
Download of the VHDX files from https://jumpstart.blob.core.windows.net/

**Screenshots**

**Additional context**
Tried in two locations East US 2 and North Europe.

**Comment by dkirby-ms** [comment]
Hi @Stephan2402, I am not able to reproduce this bug. Are you still experiencing this? Can you please share more details about your deployment such as your parameters file (be sure to remove any secrets).

Thanks

**Comment by Stephan2402** [comment]
HI @dkirby-ms, thanks for your respones. I havn`t test it since Friday. But i used the "Deploy to Azure" two times and it works well. So i didnt think the bug is from the deployment. But starting the post deployment scripts on VM Client it use a expired SAS Token from the PS Script. Didnt know how this SAS token is generated or if it is static.. 

Parameters from Portal:

{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "sshRSAPublicKey": {
            "value": null
        },
        "spnClientId": {
            "value": "08a09e3e-6ad0-4d21-a541-ec8da84cca5c"
        },
        "spnClientSecret": {
            "value": null
        },
        "spnTenantId": {
            "value": "ecd106db-905e-428b-a596-a35a36d07bb0"
        },
        "windowsAdminUsername": {
            "value": "adminazurearc"
        },
        "windowsAdminPassword": {
            "value": null
        },
        "logAnalyticsWorkspaceName": {
            "value": "law-arcworkspace"
        },
        "flavor": {
            "value": "Full"
        },
        "githubAccount": {
            "value": "microsoft"
        },
        "githubBranch": {
            "value": "arcbox_devops"
        },
        "deployBastion": {
            "value": true
        },
        "githubUser": {
            "value": "microsoft"
        }
    }
}

**Comment by Stephan2402** [comment]
Just started another deployment and it works. I saw that the one on friday was branch "arcbox-devops" and now i used branch "main". 

With this "Deploy to Azure" link from the  Azuer Arc Jumpstart Site -> https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fmicrosoft%2Fazure_arc%2Fmain%2Fazure_jumpstart_arcbox%2FARM%2Fazuredeploy.json
It isnt the branch Main!
