### ISSUE TITLE
Linux VMs fail to Register in ArcBox IT Pro

### ISSUE THREAD

**Issue by pauljemmett** [microsoft/azure_arc#1181]
Transferring installation script to nested Linux VMs...
Set-SCPItem : Could not load file or assembly 'Renci.SshNet, Version=2017.0.0.0, Culture=neutral,
PublicKeyToken=1cee9f8bde3db106' or one of its dependencies. The system cannot find the file specified.
At C:\ArcBox\ArcServersLogonScript.ps1:179 char:1
+ Set-SCPItem -ComputerName $UbuntuVmIp -Credential $linCreds -Destinat ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-SCPItem], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,SSH.SetScpItem

Set-SCPItem : Could not load file or assembly 'Renci.SshNet, Version=2017.0.0.0, Culture=neutral,
PublicKeyToken=1cee9f8bde3db106' or one of its dependencies. The system cannot find the file specified.
At C:\ArcBox\ArcServersLogonScript.ps1:180 char:1
+ Set-SCPItem -ComputerName $CentOSVmIp -Credential $linCreds -Destinat ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-SCPItem], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,SSH.SetScpItem

**Comment by dkirby-ms** [comment]
Hi @pauljemmett, I was able to reproduce the error. It looks like something upstream may have changed with one of our dependencies. We will update the issue when we have a resolution or more info to share. Thank you.

**Comment by dkirby-ms** [comment]
@pauljemmett, the upstream issue has been resolved. Can you please try another deployment? Thanks

**Comment by pauljemmett** [comment]
Hi yes that is now working thanks
