### ISSUE TITLE
Log Analytics Workspace needs to be in different region to Automation Account

### ISSUE THREAD

**Issue by pauljemmett** [microsoft/azure_arc#1187]
When creating the ArcBox via Terraform code it creates the Log Analytics Workspace and Solution in same region as Automation Account.

For eastus and eastus2 in needs to be in a linked location (if automation in eastus log analytics and solutions eastus2 and vice versa) otherwise the Update Management fails and shows the agent as not configured.

I've tested this by amending the Terraform code so log analytics and solutions go to the linked location and everything works as expected when this is set as far as I can see.

**Comment by dkirby-ms** [comment]
Thanks, we are accounting for this in ARM but missed it in Terraform.
