### ISSUE TITLE
Logon Script Failure / Build not complete

### ISSUE THREAD

**Issue by johnwildes** [microsoft/azure_arc#1260]
**Jumpstart scenario or ArcBox flavor which you are working on.**
[Azure Arc DEVOPS Jumpstart](https://azurearcjumpstart.io/azure_jumpstart_arcbox/devops/)

**Describe the bug.**
During the logon script the creation of k8s namespace was failing because the nodes behind the load balancer were not responding.  Deployed sample apps do not work, https://arcbox.devops.com does not work.

**To Reproduce.**
`###############################
# - Creating K8s Namespaces
###############################

Unable to connect to the server: dial tcp 52.184.213.183:6443: connectex: No connection could be made because the target
 machine actively refused it.
Unable to connect to the server: dial tcp 52.184.213.183:6443: connectex: No connection could be made because the target
 machine actively refused it.
Unable to connect to the server: dial tcp 52.184.213.183:6443: connectex: No connection could be made because the target
 machine actively refused it.
Unable to connect to the server: dial tcp 52.184.213.183:6443: connectex: No connection could be made because the target
 machine actively refused it.
Unable to connect to the server: dial tcp 52.184.213.183:6443: connectex: No connection could be made because the target
 machine actively refused it.

##########################################
# - Adding Bookstore Namespaces to OSM
##########################################

Error: Cannot obtain information about the mesh [osm]: [Get "https://arcbox-capi-data-2872ad9b.eastus2.cloudapp.azure.co
m:6443/apis/apps/v1/deployments?labelSelector=meshName%3Dosm": dial tcp 52.184.213.183:6443: connectex: No connection co
uld be made because the target machine actively refused it.]
Error: Cannot obtain information about the mesh [osm]: [Get "https://arcbox-capi-data-2872ad9b.eastus2.cloudapp.azure.co
m:6443/apis/apps/v1/deployments?labelSelector=meshName%3Dosm": dial tcp 52.184.213.183:6443: connectex: No connection co
uld be made because the target machine actively refused it.]

###############################
# - Applying GitOps Configs
###############################

Creating GitOps config for NGINX Ingress Controller
The command requires the extension k8s-configuration. It will be installed first.
'Microsoft.Flux' extension not found on the cluster, installing it now. This may take a few minutes...
(ExtensionCreationFailed)  unable to add the configuration with configId {extension:flux} due to error: {error while add
ing the CRD configuration: error {Post "https://10.96.0.1:443/apis/clusterconfig.azure.com/v1beta1/namespaces/flux-syste
m/extensionconfigs": dial tcp 10.96.0.1:443: connect: connection refused}}
Code: ExtensionCreationFailed
Message:  unable to add the configuration with configId {extension:flux} due to error: {error while adding the CRD confi
guration: error {Post "https://10.96.0.1:443/apis/clusterconfig.azure.com/v1beta1/namespaces/flux-system/extensionconfig
s": dial tcp 10.96.0.1:443: connect: connection refused}}
Creating GitOps config for Bookstore application
Error! 'Microsoft.Flux' extension is installed but not in a succeeded state on the cluster. Unable to proceed with Flux
v2 configuration install.
Try resolving the extension error on the cluster or removing and re-installing the extension.
Creating GitOps config for Bookstore RBAC
Error! 'Microsoft.Flux' extension is installed but not in a succeeded state on the cluster. Unable to proceed with Flux
v2 configuration install.
Try resolving the extension error on the cluster or removing and re-installing the extension.
Creating GitOps config for Bookstore Traffic Split
Error! 'Microsoft.Flux' extension is installed but not in a succeeded state on the cluster. Unable to proceed with Flux
v2 configuration install.
Try resolving the extension error on the cluster or removing and re-installing the extension.
Creating GitOps config for Hello-Arc application
Error! 'Microsoft.Flux' extension is installed but not in a succeeded state on the cluster. Unable to proceed with Flux
v2 configuration install.
Try resolving the extension error on the cluster or removing and re-installing the extension.`

**Expected behavior.**
Logon script would process successfully without errors

**Environment summary.**
Deployed using bicep

SPN has owner rights to the subscription.

I have the entire log zip file I can attach, but unclear as to what I need to remove from it for security purposes.  Please let me know if it is safe to upload it here.

**Comment by dkirby-ms** [comment]
Glad to hear you got it working. I did run a deployment today and was able to complete it without any errors.
