### ISSUE TITLE
Failed to write extensions on ArcBox-CAPI-Data

### ISSUE THREAD

**Issue by jolguk** [microsoft/azure_arc#1272]
**Jumpstart scenario or ArcBox flavor which you are working on.**
[](https://azurearcjumpstart.io/azure_jumpstart_arcbox/devops/)

**Describe the bug.**
The flux extensions have failed to install:
 "resourceId": "/subscriptions/dcc3c45e-2c3a-4cc9-8f9c-596e2c293ef6/resourceGroups/capdevrg/providers/Microsoft.Kubernetes/connectedClusters/ArcBox-CAPI-Data/providers/Microsoft.KubernetesConfiguration/extensions/flux",
    "status": {
        "value": "Failed",
        "localizedValue": "Failed"
    },
    "subStatus": {
        "value": "",
        "localizedValue": ""
    },
    "submissionTimestamp": "2022-07-05T18:46:52.2049343Z",
    "subscriptionId": "dcc3c45e-2c3a-4cc9-8f9c-596e2c293ef6",
    "tenantId": "72f988bf-86f1-41af-91ab-2d7cd011db47",
    "properties": {
        "statusMessage": "{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceOperationFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"ExtensionOperationFailed\",\"message\":\"The extension operation failed with the following error:  unable to add the configuration with configId {extension:flux} due to error: {error while adding the CRD configuration: error {Post \\\"https://10.96.0.1:443/apis/clusterconfig.azure.com/v1beta1/namespaces/flux-system/extensionconfigs\\\": dial tcp 10.96.0.1:443: connect: connection refused}}.\"}]}}",
        "eventCategory": "Administrative",

**To Reproduce.**

**Environment summary.**

**Screenshots.**

![Screenshot (157)](https://user-images.githubusercontent.com/16211493/177398804-e777572c-34ac-491a-9597-3d4a8837cab2.png)

**Additional context.**

**Comment by jolguk** [comment]
reating GitOps config for NGINX Ingress Controller
The command requires the extension k8s-configuration. It will be installed first.
'Microsoft.Flux' extension not found on the cluster, installing it now. This may take a few minutes...
(ExtensionOperationFailed) The extension operation failed with the following error:  unable to add the configuration wit
h configId {extension:flux} due to error: {error while adding the CRD configuration: error {Post "https://10.96.0.1:443/
apis/clusterconfig.azure.com/v1beta1/namespaces/flux-system/extensionconfigs": dial tcp 10.96.0.1:443: connect: connecti
on refused}}.
Code: ExtensionOperationFailed
Message: The extension operation failed with the following error:  unable to add the configuration with configId {extens
ion:flux} due to error: {error while adding the CRD configuration: error {Post "https://10.96.0.1:443/apis/clusterconfig
.azure.com/v1beta1/namespaces/flux-system/extensionconfigs": dial tcp 10.96.0.1:443: connect: connection refused}}.
Creating GitOps config for Bookstore application
Error! 'Microsoft.Flux' extension is installed but not in a succeeded state on the cluster. Unable to proceed with Flux
v2 configuration install.
Try resolving the extension error on the cluster or removing and re-installing the extension.
Creating GitOps config for Bookstore RBAC
Error! 'Microsoft.Flux' extension is installed but not in a succeeded state on the cluster. Unable to proceed with Flux
v2 configuration install.
Try resolving the extension error on the cluster or removing and re-installing the extension.
Creating GitOps config for Bookstore Traffic Split
Error! 'Microsoft.Flux' extension is installed but not in a succeeded state on the cluster. Unable to proceed with Flux
v2 configuration install.
Try resolving the extension error on the cluster or removing and re-installing the extension.
Creating GitOps config for Hello-Arc application
Error! 'Microsoft.Flux' extension is installed but not in a succeeded state on the cluster. Unable to proceed with Flux
v2 configuration install.
Try resolving the extension error on the cluster or removing and re-installing the extension.

**Comment by dkirby-ms** [comment]
@jolguk Thanks for submitting the issue. We are able to reproduce and are investigating the cause.

**Comment by dkirby-ms** [comment]
This issue is likely related to an issue with Defender on the CAPI cluster. We have disabled Defender on this cluster as a temporary fix. We will address the Defender issue in a separate fix. In the meantime, you should now be able to deploy ArcBox DevOps without issues.
