### ISSUE TITLE
Arc Agent version

### ISSUE THREAD

**Issue by BaillyAlex** [microsoft/azure_arc#1275]
**Is your feature request related to a problem? Please describe.**

I'm currently working on a way to automatically update our Arc Agent, after few tests all my agents are now on the latest version, I would like to be able to download a previous version of the agent to finish all my test.

**Describe the solution you'd like.**

Provide a link or give the possibility to download a outdated agent version for testing purposes.

**Describe alternatives you've considered.**

**Additional context.**

**Comment by dkirby-ms** [comment]
Hi, and thanks for your submission. This repo is not the source for the Azure Arc connected machine agent. 

@rpsqrd are previous agent versions something we publish somewhere else?

**Comment by rpsqrd** [comment]
Hi @BaillyAlex, you can find older versions in the Microsoft Update catalog. Inside the CAB file is the same MSI we use for fresh installs.

https://www.catalog.update.microsoft.com/Search.aspx?q=azure+connected+machine+agent

Would love to hear more about the automatic update approach you're testing!

**Comment by BaillyAlex** [comment]
Hi @dkirby-ms, @rpsqrd thank you both your help :).
