### ISSUE TITLE
Not so much a bug, but getting bash: sudo: command not found in azure cloud shell bash

### ISSUE THREAD

**Issue by jwaltireland** [microsoft/azure_arc#1285]
working on this page.
https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/aks/aks_terraform/

**Describe the bug.**
in the "Connecting to azure arc" section, uploading bash file to azure cloud shell.

when running the file, getting bash: sudo: command not found 

searched the web on this error, and pretty much what I'm seeing is If the script is run in the user home directory, it should work.

the script is in my home dir;  I've even reset my cloud shell account (creating new storage account /etc)

NOTE:  I'm doing this is azure gov cloud. however, I've tried the same steps in my commercial sub with the same error

**Comment by likamrat** [comment]
@jwaltireland can you please share a screenshot?

**Comment by jwaltireland** [comment]
I tried to use that script.  i've abandoned trying to get that script to work in azure cloud shell.  just used this page's info and got it connected to arc:

https://docs.microsoft.com/en-us/azure/azure-arc/kubernetes/quickstart-connect-cluster?tabs=azure-cli

**Comment by zaidmohd** [comment]
@jwaltireland : I did run a deployment now and it completed without any errors. 
Based on your error message, looks like you executed another script.
