### ISSUE TITLE
Bootstrapping through yaml failes

### ISSUE THREAD

**Issue by bweissman** [microsoft/azure_arc#1346]
I deployed an entirely new k8s cluster (kubeadm /  Ubuntu 20.04).

As per the guidance here (https://github.com/microsoft/azure_arc/tree/main/arc_data_services/deploy/yaml) a new arc data controller should be deployable by simply grabbing https://github.com/microsoft/azure_arc/blob/main/arc_data_services/deploy/yaml/bootstrapper-unified.yaml and replace the namespace variable accordingly. 

That however results in:

FATAL 2022/09/05 13:49:04 Error bootstrapping cluster: list: failed to list: secrets is forbidden: User "system:serviceaccount:arc:default" cannot list resource "secrets" in API group "" in the namespace "arc"

**Comment by 0xbliang** [comment]
@bweissman it should be fixed now #1352. Could you try again? Make sure you also specify the namespace on kubectl apply command, e.g.:

`kubectl apply --namespace arc -f bootstrapper-unified.yaml`

See: https://docs.microsoft.com/en-us/azure/azure-arc/data/create-data-controller-using-kubernetes-native-tools#create-the-namespace-and-bootstrapper-service
