### ISSUE TITLE
Kubeadm Data services - Scenario refactoring

### ISSUE THREAD

**Issue by pabloameijeirascanay** [microsoft/azure_arc#1366]
Jumpstart scenario or ArcBox flavor which you are working on.
https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_data/kubeadm/

Describe the bug.
Refactoring this scenario with code and screenshot updates

To Reproduce.
N/A

Expected behavior.
N/A

Environment summary.
N/A

Screenshots.
N/A

Additional context.
N/A

**Comment by likamrat** [comment]
Closed via #1396
