### ISSUE TITLE
There is no guide  for enabling Azure Arc enabled Data Services on existing K8s cluster

### ISSUE THREAD

**Issue by werton13** [microsoft/azure_arc#137]
**Is your feature request related to a problem? Please describe.**
Hello team.
I carefully read the deployment scenarios suggested. Especially i'm wondering  about Azure Arc enabled Data Services scenarios.
All those scenarios are bigin from the words "_If you do not yet have a Kubernetes cluster_"  But what if i already have a K8s cluster and  connected it to the Azure Arc? Where can i get guidance for this scenario?

My scenario - Azure Stack Hub and AKS Engine VM on Linux, so i dont want to do all deployment operations following existing guidance and i don't want to install additional Windows VMs just for installation purposes. 

 
**Describe the solution you'd like**
We need a separate ARM template to deploy  only Azure Arc Data Services on existing K8s cluster, without creating it each time from scratch and without creating WIndows VM if we already have AKS Engine VM.
```
As part of the Windows Server 2019 VM deployment, there are 2 scripts executions; First script (ClientTools.ps1) at deployment runtime using the ARM "CustomScriptExtension" module and a second script (LogonScript.ps1) on user first logon to Windows.

Runtime script will:

Inject user params values (from bullet point #1) to be used in both runtime and logon script
Install the required tools – az cli, az cli Powershell module, kube-cli (Chocolaty packages)
!Download & install the Azure Data Studio & azdata cli
!Download the Azure Data Studio Azure Data CLI, Azure Arc & PostgreSQL extensions
!Download the Postgres_Cleanup and Postgres_Deploy Powershell scripts
!Create the Postgres Connectivity script
Create the logon script
Create the Windows schedule task to run the logon script at first login
Disable Windows Server Manager from running at login
Logon script will:

Create the LogonScript.log file
!Retrieve the AKS credentials & create the kubeconfig file in user Windows profile
Create the azdata config file in user Windows profile
!Install the Azure Data Studio Azure Data CLI, Azure Arc & PostgreSQL extensions
Create the Azure Data Studio desktop shortcut
Open another Powershell session which will execute the kubectl get pods -n <Arc Data Controller namespace> -w command
!Deploy the Arc Data Controller using the user params values
?Deploy Azure Postgres server group (with 5 workers) on the AKS cluster
!Creating Postgres connectivity details using the Postgres Connectivity script
Unregister the logon script Windows schedule task so it will not run after first login
```
i think an actions which i marked with ! can be just perfomed from AKS Engine workstation.. 
So it would be great, if such additional guidance will be available.

Thanks  
**Describe alternatives you've considered**

**Additional context**

**Comment by twright-msft** [comment]
Hi @werton13  - You can find how to deploy to an existing Kubernetes cluster here:  https://docs.microsoft.com/en-us/azure/azure-arc/data/create-data-controller.  If you are familiar with using a CLI tool, I recommend using the azdata CLI tool option to deploy.  

To make the option of deploying to an existing Kubernetes cluster easier to find from the Jumpstart site I've submitted this PR:  
https://github.com/microsoft/azure_arc/pull/138

**Comment by likamrat** [comment]
@werton13 just to clarify, the side Windows VM deployment on all the data services scenarios is designed to help you manage the deployed environment with azdata CLI, Azure Data Studio and kubectl.
