### ISSUE TITLE
Deploy an Azure Virtual Machine with Windows Server & Microsoft SQL Server failing

### ISSUE THREAD

**Issue by WVDAdminTF** [microsoft/azure_arc#1393]
Hello All,

Thank you for all the Jumpstart scenarios, I am facing an issue with the Deploy an Azure Virtual Machine with Windows Server & Microsoft SQL Server and connect it to Azure Arc using Terraform after the recent update to the script, please advice

I have already supplied the same in the Paramaters.json file

    "logAnalayticsWorkspaceName": {
      "value": "LAW4mdfc"
    },

Issue
Please provide string value for 'logAnalyticsWorkspaceName' (? for help): **"LAW4mdfc"**
{"code": "InvalidTemplate", "message": "Deployment template validation failed: 'The template parameters 'logAnalayticsWorkspaceName' in the parameters file are not valid; they are not present in the original template and can therefore not be provided at deployment time. The only supported parameters for this template are 'vmName, adminUsername, adminPassword, myIpAddress, windowsOSVersion, vmSize, servicePrincipalAppId, servicePrincipalSecret, servicePrincipalTenantId, virtualNetworkName, subnetName, networkSecurityGroupName, logAnalyticsWorkspaceName, resourceTags, githubAccount, githubBranch, deployBastion, bastionHostName'. Please see https://aka.ms/arm-deploy/#parameter-file for usage details.'.", "additionalInfo": [{"type": "TemplateViolation", "info": {"lineNumber": 0, "linePosition": 0, "path": ""}}]}

Please can you advice for the same

**Comment by WVDAdminTF** [comment]
I was able to fix it, the Parameters files has incorrect spelling for LogAnalyticsWorkspace

This caused the issue - "logAnal**a**yticsWorkspaceName": {

 The Correct should be - logAnalyticsWorkspaceName

**Comment by DCMattyG** [comment]
Hi @WVDAdminTF, can you please help me understand what scenario or flavor of ArcBox you're deploying when you came across this error?

**Comment by WVDAdminTF** [comment]
> Hi @WVDAdminTF, can you please help me understand which Jumpstart scenario or flavor of ArcBox you're deploying when you came across this error?

This one - https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_sqlsrv/azure/azure_arm_template_winsrv/

The Parameter file has incorrect spelling for **logAnalyticsWorkspaceName** which cause the deployment to fail
