### ISSUE TITLE
Can we modify the specific pod (like logsdb) pvc size for azure arc data service

### ISSUE THREAD

**Issue by ronking-zhu** [microsoft/azure_arc#1413]
**Is your feature request related to a new Jumpstart scenario you would like to contribute?**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like.**

**Describe alternatives you've considered.**

**Additional context.**

**Comment by twright-msft** [comment]
What @dnethi is referring to is how you can set the spec.storage.data.size property at the time that you deploy a data controller by following the documentation to create a custom deployment profile.  https://learn.microsoft.com/en-us/azure/azure-arc/data/create-custom-configuration-template

However, this will not change the logsdb pod data persistent volume size which is what I understand that you are looking for.  The best way to do this currently is to resize the persistent volume post-deployment by following the standard Kubernetes process for persistent volume resizing:  https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/

**Comment by likamrat** [comment]
@ronking-zhu following @twright-msft, any other questions?

**Comment by likamrat** [comment]
@ronking-zhu I will go ahead and close this issue for now. Please feel free to response if further help is needed.
