### ISSUE TITLE
Azure connected machine agent is not installed

### ISSUE THREAD

**Issue by HassanAlmanasrah** [microsoft/azure_arc#1458]
**Jumpstart scenario or ArcBox flavor which you are working on.**
https://azurearcjumpstart.io/azure_jumpstart_hcibox/

**Describe the bug.**
Azure connected machine agent is not installed with the below error, which is I think related to HCI cluster resource App registration doesnt have Azure Connected Machine Role
WARNING: Failed to assign roles to service principal with object Id 86055648-5f2e-4415-9fc0-af04912f2d22. ErrorMessage: Object reference not set to an instance of an object. PositionalMessage: At C:\Program Files\WindowsPowerShell\Modules\Az.StackHCI\1.3.1\custom\stackhci.ps1:1320 char:17
+ ...             New-AzRoleAssignment -ObjectId $SpObjectId -RoleDefinitio ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

If I am not mistaken, its related to the az module version installed on the nodes for HCI 

**To Reproduce.**
we hit this issue when HCI box is installed. 

**Expected behavior.**
Nodes should have Azcmagent should be installed during deployment,

**Environment summary.**

**Screenshots.**

**Additional context.**

**Comment by dkirby-ms** [comment]
@HassanAlmanasrah still seeing this issue? Can you share logs?

**Comment by HassanAlmanasrah** [comment]
@dkirby-ms apologies for the late reply. could you guide me where to upload the logs. thanks.

**Comment by HassanAlmanasrah** [comment]
@dkirby-ms 
done.

**Comment by HassanAlmanasrah** [comment]
I will test another deployment and will let you know how it goes.

**Comment by dkirby-ms** [comment]
@HassanAlmanasrah how did you scope your SPN?

**Comment by HassanAlmanasrah** [comment]
SPN has owner permission on the subscription level as per the guide.

**Comment by dkirby-ms** [comment]
Did you encounter this issue again in your new deployment?
