### ISSUE TITLE
azure_jumpstart_hcibox/artifacts/Deploy-GitOps.ps1 errors

### ISSUE THREAD

**Issue by dmc-tech** [microsoft/azure_arc#1464]
**Jumpstart scenario or ArcBox flavor which you are working on.**
[HCIBox](https://github.com/microsoft/azure_arc/blob/main/azure_jumpstart_hcibox/artifacts/Deploy-GitOps.ps1)

**Describe the bug.**
There are a number of bugs in the PowerShell script:

Line 48 has the resource group hardcoded, causing the script to fail as the 'HCIBox' rg does not exist.
To correct this, it should be:

```
$clusterName = az connectedk8s list --resource-group $Env:resourceGroup --query "[].{Name:name} | [? contains(Name,'hcibox')]" --output tsv
```

There also seems to be duplicate code which causes errors if the ErrorActionPreference is set to stop.

Line 123 and 127 are the same purpose. Line 127 fails due to the file already existing.  To fix, remove line 123.
```
Copy-VMFile AdminCenter -SourcePath "C:\VMConfigs\$using:certname.pfx" -DestinationPath "C:\VHDs\$using:certname.pfx" -FileSource Host
```

**To Reproduce.**

1. Run the Deploy-GitOps.ps1 script as is from the main branch (with ErrorActionPreference  set to 'stop')

**Expected behavior.**
The Hello-Arc demo is deployed using Azure Arc GitOps, and the shortcut is created on the AdminCenter desktop.

**Comment by dkirby-ms** [comment]
Thanks for submitting the issue. We have a feature branch that will fix these issues incoming.
