### ISSUE TITLE
Exception calling "SafeGetValue" during logon script run

### ISSUE THREAD

**Issue by banana-joe7767** [microsoft/azure_arc#1480]
**Jumpstart scenario or ArcBox flavor which you are working on.**
https://azurearcjumpstart.io/azure_jumpstart_hcibox/
Deploy HCI box in eastus

**Describe the bug.**
Initial deployment of resourced works fine.
When I logon to the HCIBox-Client for the first time, the logon script runs, running into the following error:

#############################
# - Deploying HCI cluster
#############################

Transcript started, output file is C:\HCIBox\Logs\New-HCIBoxCluster.log
Exception calling "SafeGetValue" with "0" argument(s): "Cannot generate a Windows PowerShell object for a ScriptBlock
evaluating dynamic expressions. Dynamic expression: @{
    # This is the PowerShell datafile used to provide configuration information for the HCIBox environment. Product
keys and password are not encrypted and will be available on all hosts during installation.

[...]

    rbIp                                 = "192.168.200.201"
    rbCpip                               = "192.168.200.202"
}."
At
C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psm1:557
char:21
+                     $data.SafeGetValue()
+                     ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException

It then continues to download the VHD files, but then the script simply stops and powershell closes after about 15 minutes.
The background wallpaper did not change.
Let me know if you need further log output and how to safely supply it.
I was unable to find instructions on how to upload the logs to a storage account for review, as indicated by the documentation.

**To Reproduce.**
Was able to reproduce this thrice.
Deploy HCI box in eastus with default values. Only change being a bastion deployed (set to true in config)
Logon to HCIBox-Client for the first time.

**Expected behavior.**
Expected that the script will run successfully and continue to deploy the HCI box environment.

**Environment summary.**
using CLI version 2.40.0 as requested. Biceps deployment done via ubuntu bash under windows 11. eastus is the region
Let me know if further information or config option are needed

**Comment by dkirby-ms** [comment]
Did you deploy this from a fork where you modified any code? Or is this deployed from the main branch of this repo?

**Comment by banana-joe7767** [comment]
This is from the main branch with no modifications from my side. 
Only steps I did after ticking off all prerequisites listed:

git clone https://github.com/microsoft/azure_arc.git
az bicep upgrade
(edit the [main.parameters.json according to output)

Then create the resource group and ran the deployment as stated in docs. The deployment itself finished without any errors.

**Comment by banana-joe7767** [comment]
sorry for the delay.
in short, I cleaned up my whole env, pulled the repo again, deployed it fresh and it ran without issues.
So it was either a transient issue, or a layer 8 issue.
I still have the env with the issue up and running if you want to dig into it, but it unlikely warrants your time.

I didn't see any corruption with the file you mentioned and is identical to the one in the repo.

thank you for your support.
