### ISSUE TITLE
**C:\HCIBox** directory is not found on the HCIBox-Client VM post installation.

### ISSUE THREAD

**Issue by bniranjanbhat** [microsoft/azure_arc#1486]
**Jumpstart scenario or ArcBox flavor which you are working on.**
https://azurearcjumpstart.io/azure_jumpstart_hcibox/aks/

**Describe the bug.**
**C:\HCIBox** directory is not found on the HCIBox-Client VM post installation.

**To Reproduce.**
1. Setup the HCI cluster as described in the documentation
2. tried out VM creation successfully
3. When I went to try out AKS related guides, I could not find the C:\HCIBox directory on the HCIBoxClient VM
Note: I did see this directory when I had first logged into the HCIBoxClient  client to setup HCI custer

**Expected behavior.**
HCIBox directory should be present.

**Environment summary.**

**Screenshots.**

**Additional context.**

**Comment by dkirby-ms** [comment]
Are you sure you're checking on the HCIBox Client VM and not inside another RDP session (perhaps to Windows Admin Center vm)?
