### ISSUE TITLE
HCIBox - Bug in Deploy-GitOps.ps1 script

### ISSUE THREAD

**Issue by dmc-tech** [microsoft/azure_arc#1509]
**Jumpstart scenario or ArcBox flavor which you are working on.**
[](https://github.com/microsoft/azure_arc/tree/main/azure_jumpstart_hcibox)

**Describe the bug.**
When running the Deploy-Gitops.ps1 from the latest branch, it does not work out-of-the-bx due to the ErrorActionPreference being set to 'stop'. When the following command is run, it produces a warning via az cli, but PowerShell stops :
```
az config set extension.use_dynamic_install=yes_without_prompt
```
![image](https://user-images.githubusercontent.com/8145761/200368335-4235348f-891f-44eb-b421-6e713f3f557d.png)

It is the same when running this command:
```
$clusterName = az connectedk8s list --resource-group $Env:resourceGroup --query "[].{Name:name} | [? contains(Name,'hcibox')]" --output tsv
```
![image](https://user-images.githubusercontent.com/8145761/200368967-054ca890-ced9-48c1-afbb-aa0ac37aab64.png)

If trying to re-run the script, the following error is shown (the log file needs to be deleted to proceed):

```
Start-Transcript : Transcription cannot be started.
At C:\HCIBox\Deploy-GitOps.ps1:26 char:1
+ Start-Transcript -Path $Env:HCIBoxLogsDir\Deploy-GitOps.log
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Transcript], PSInvalidOperationException
    + FullyQualifiedErrorId : CannotStartTranscription,Microsoft.PowerShell.Commands.StartTranscriptCommand
 ```

**Expected behavior.**
Script runs with correct error trapping. I added a simple workaround, e.g.:
```
$ErrorActionPreference = "Continue" 
az config set extension.use_dynamic_install=yes_without_prompt
$ErrorActionPreference = "Stop" 
```

**Comment by dkirby-ms** [comment]
We actually are setting WarningActionPreference to SilentlyContinue at the beginning of the Deploy-GitOps script. This should account for the warning generated by the cli extension install. I will do some tests to make sure this is working correctly but in my usage of the script this warning was properly suppressed. 

For the second issue you report, this is an issue with the way Start-Transcript works by default. I will look into changing this to account for logs that may have already been in place due to previous script runs.

**Comment by dmc-tech** [comment]
> 

Setting WarningActionPreference  is not being observed as the error is not coming from an external process (az cli), not PowerShelll: https://stackoverflow.com/questions/54549573/how-to-ignore-specific-error-in-powershell-when-executing-a-command

**Comment by dkirby-ms** [comment]
I'm not able to reproduce this on a clean deployment of HCIBox. I ran the script and it completed successfully without errors. 
Snippet below is showing the script being run and the warning being suppressed. 

Did you make any changes to the Deploy-GitOps.ps1 script before running it? 

![image](https://user-images.githubusercontent.com/32211549/200678100-1946ec15-f335-494a-9329-550ba0ea9c96.png)

**Comment by dkirby-ms** [comment]
I'll add a note mentioning not to use IDE with the GitOps script.

**Comment by dmc-tech** [comment]
Adding the following to the script also prevents running if within the ISE:
```
if ($host.Name -match 'ISE') {throw "Running this script in PowerShell ISE is not supported"}
```
