### ISSUE TITLE
Unable to add Windows Images to the HCI Cluster

### ISSUE THREAD

**Issue by malcatraz** [microsoft/azure_arc#1522]
**Jumpstart scenario or ArcBox flavor which you are working on.**
(https://azurearcjumpstart.io/azure_jumpstart_hcibox/rb/)>]

**Describe the bug.**
The challenge I am having is with the Windows images.  They don’t seem to work within the HCI cluster when trying to provision a VM.  All of the Windows images time out with the following message "The resource provision operation did not complete within the allowed timeout period.  Even when trying to add a Windows image to the HCI Cluster, they all time out with the following message:  The Linux VM is the only one that deployed successfully. 

**To Reproduce.**
1. Go to 'HCIBOX-Cluster'
2. Click on 'VM Images under Resources.'
3. Select Add VM Image and Select from Azure Storage Account and Browse to your storage Blob
4. After while the deployment fails with the following error message "The resource provision operation did not complete within the allowed timeout period."

**Expected behavior.**

**Environment summary.**

**Screenshots.**
![image](https://user-images.githubusercontent.com/32576278/201355476-23f0236e-cd9b-4109-9fd4-3b0dc975260a.png)

**Additional context.**

**Comment by dkirby-ms** [comment]
This looks like the same as #1523
