### ISSUE TITLE
SSH KEY ERROR

### ISSUE THREAD

**Issue by csaadmin** [microsoft/azure_arc#1526]
**Jumpstart scenario or ArcBox flavor which you are working on.**
Full

**Describe the bug.**
I am using deploy option 1 (Azure Portal), but I am failing due to "linuxConfiguration.ssh.publicKeys.keyData is invalid."
I tried it with different SSH KEY and the result is the same

**To Reproduce.**
<!--- Steps to reproduce the behavior:
Use Azure Portal to deploy and use the below SSH key:

AAAAB3NzaC1yc2EAAAADAQABAAACAQDKz6TVb9XpyjpoZCAV6A3b8zRvV/RdkWNKykdQ69Ejs++ZNtC0MlgnxLS+qZnKqGSOKI7Jipy/4Dx68SYvOs3UzqGP3q2w/M+kFGoLoayjQq429PVnAveC3a3YvFs4nZME1l7Gn5SUUc93MsZCQc8Ul4gCgDtRT4lFYAl3MQ+rPruz8h6/AoP4Dlwt0IAl3UQcMmAI1mPZpcSw4/d+nNfRZmxHo05QrzFOGRWzb/8Huotk1ShVTMTgVZTD2fvRjKCmjoTFI8Ku2EtP5oXF0DjTmXDshXzLvmTULdtTYLvi7eKIio6wwLoQWmfbuWNxaVr1wwEU7I4BssmYNDJak6BPBH+C8jSxeGfnZmvpuYCBWzPJLEh27oN/lKXXhKkKjolokDpFS7Gt7GFNVryrZlAycYvhK5/IxnUv6O3gnLjcQZr0gVwbZ0YdrK1juyU4sh1WwQCbrfcIrvzEtQ6r9/GDvyZwbIX8R8j5Gj+A085R1F0coZIJzWS0LyoUwEFy4QQLXn9J2xNfJY/7JRbBK9RJRopHSdGzFQzw2sXnILwcumoftKxEWcRfSN3FZS1M77aXQJtwW2voelW6gdHjUqrp0qbRY9cAgL1mvGJUscLsBVOThbp6HNCTyiH9XfHhqyFqPQpqggKBIaHMXlYrt+1KmfcNZi2Aez80LQFuLMnP0Q==

**Expected behavior.**
Successfull deployment

**Environment summary.**
azure-cli 2.42.0

**Screenshots.**
![image](https://user-images.githubusercontent.com/115485825/201541599-4b88fdfe-3a90-4824-ac3f-7f6a9c582810.png)

**Comment by likamrat** [comment]
@csaadmin you please share your process for getting the **public** ssh key?

**Comment by csaadmin** [comment]
I used the command in the steps 
ssh-keygen -t rsa -b 4096 -C "your_email@example.com"

**Comment by likamrat** [comment]
So this is how you create the key pair. To get the actual public key:

**Windows**: _C:\Users\WINUSER/.ssh/id_rsa.pub_
**Linux**: _cat ~/.ssh/id_rsa.pub_

**Comment by csaadmin** [comment]
Thanks Lior for your help
