### ISSUE TITLE
Host VM deployment got failed to download the bootstrap file as it doesnt exist.

### ISSUE THREAD

**Issue by sumitmalik51** [microsoft/azure_arc#1530]
Host VM deployment got failed to download the bootstrap file as it doesn't exist. I have just cloned and triggered the deployment after making the parameter change

**Jumpstart scenario or ArcBox flavor which you are working on.**

**Describe the bug.**

**To Reproduce.**

**Expected behavior.**

**Environment summary.**

**Screenshots.**

**Additional context.**

**Comment by likamrat** [comment]
@sumitmalik51 please provide more context to what you are trying to do as asked in the issue template. This issue details are not enough.

**Comment by likamrat** [comment]
Closing this for now due to lack of context
