### ISSUE TITLE
ModuleNotFoundError: No module named 'azure.mgmt.web.v2021_01_01'

### ISSUE THREAD

**Issue by Devinwong** [microsoft/azure_arc#1549]
**Jumpstart scenario or ArcBox flavor which you are working on.**
https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_app_svc/aks/aks_app_service_arm_template

**Describe the bug.**
After the deployment, when rdp connecting to the VM client, the initial script failed with error message.
```
File "C:\Users\arcdemo\.azure\cliextensions\appservice-kube\azext_appservice_kube\custom.py", line 301, in _get_kube_client
    return client.kube_environments
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/web/_web_site_management_client.py", line 627, in kube_environments
ModuleNotFoundError: No module named 'azure.mgmt.web.v2021_01_01'
```
Not sure if I missed something or if this is a bug on dependencies.

**To Reproduce.**
Just following the doc and hit error at the section Post Deployment

**Expected behavior.**
expecting no error

**Environment summary.**
az-cli version on my WSL: 2.42.0

**Screenshots.**
<img width="739" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/13621569/203640934-6e6d069c-d751-4ef6-ac99-aaa0546cbf1b.png">
<img width="960" alt="MicrosoftTeams-image (3)" src="https://user-images.githubusercontent.com/13621569/203640945-10015d8b-e1be-4393-9312-95d743e1aa84.png">
The error is shown in this screenshot, attaching the logs too.
[logs.txt](https://github.com/microsoft/azure_arc/files/10079006/logs.txt)

Meanwhile, on Azure portal, this is what I see.
![deployment_on_portal](https://user-images.githubusercontent.com/13621569/203641521-87e21ca7-ad73-4977-b5ea-0a59e127c3c7.png)

![Screenshot_20221123_123555](https://user-images.githubusercontent.com/13621569/203641709-a0abb804-d7e7-4969-a86d-bf70b234a2d8.png)

**Additional context.**

**Comment by likamrat** [comment]
Thank you @Devinwong, I was able to repro and just submitted a new Az CLI [upstream issue](https://github.com/Azure/azure-cli/issues/24744).

/cc @apwestgarth
