### ISSUE TITLE
HCIBox | Deploying VM via RB does not get an IP and Guest Configuration is not enabled

### ISSUE THREAD

**Issue by BartRoels** [microsoft/azure_arc#1565]
**Jumpstart scenario or ArcBox flavor which you are working on.**
(https://azurearcjumpstart.io/azure_jumpstart_hcibox/)

**Describe the bug.**
When deploying a Virtual Machine from the Azure Portal into the Azure Stack HCI leveraging the Resource Bridge technology, for Windows machines I get a Deployment error telling me ""message":"Timed out installing ArcForServerAgent: The operation has timed out", and in the portal the details on that deployed VM stated the that the guest configuration has not been installed

<img width="393" alt="image" src="https://user-images.githubusercontent.com/15818583/205365029-e85bebdd-6364-44c2-9f8c-c9e082aed27a.png">

For linux machine you do not get a deployment error, but the guest configuration is not installed neither.

<img width="367" alt="image" src="https://user-images.githubusercontent.com/15818583/205364871-7c9e9797-9f8c-4583-b972-de6beca84147.png">

I noticed that while going through the Azure Portal steps on the step where you need to add an extra network interface (no network interface means no guest configuration capabilities!) you can select the "network" sdnswitch, but the IP4 settings are grayed out (but Dynamic is selected). 

<img width="425" alt="image" src="https://user-images.githubusercontent.com/15818583/205364838-958945dd-0caa-4ce8-ac2a-0da902ce776e.png">

When the deployment fails with the above-described error or if the guest configuration was not installed (linux), in both cases the deployed machine does not have any valid IP configuration on it, so I'm guessing that this is also the problem the guest configuration cannot be deployed on the VM (no way for outgoing communication to the internet).

**To Reproduce.**
1. Azure Arc virtual machines (preview)
2. +Create
3. Complete all configuration fields on tab Basics (enable guest management marked to be installed)
4. Add a Network Interface (see above example screenshot)
5. Review and Create
6. Create

**Expected behavior.**
- Guest Configuration enabled
- Network Interface configured and Ip assigned (dynamically or manually during Portal configuration)

**Environment summary.**
Happy to provide details about the current deployed HCIBox.

**Screenshots.**
See above

**Additional context.**
Happy to provide if necessary

**Comment by dkirby-ms** [comment]
@ajmfernandes Yes, I noticed the missing vlan yesterday. I also learned of an upstream issue that prevents Resource Bridge from working on vlans other than 0 or 2, and right now we are using 200 for the VM vlan. I have a branch I am working to test some changes that will add the vlan parameter to the Arc RB config and to change the default VM vlan from 200 to 2.

**Comment by ajmfernandes** [comment]
> @ajmfernandes Yes, I noticed the missing vlan yesterday. I also learned of an upstream issue that prevents Resource Bridge from working on vlans other than 0 or 2, and right now we are using 200 for the VM vlan. I have a branch I am working to test some changes that will add the vlan parameter to the Arc RB config and to change the default VM vlan from 200 to 2.

Let me know if i can help changing this settings in the existing deployment of the HCIBox, to avoid deploying a new instance.

**Comment by janegilring** [comment]
I also experience the same issue: No IP or network connectivity for both Ubuntu and Windows Server deployed via the Resource Bridge.

Will wait for a fix becoming available and try again.

**Comment by mgodfre3** [comment]
While you wait for this fix, you can in the meantime manually inject an ip in the VLAN to work around the issue.
