### ISSUE TITLE
HCIBox - Resource bridge and AKS deployments affected by upstream issue may cause HCIBox deployment failures

### ISSUE THREAD

**Issue by dkirby-ms** [microsoft/azure_arc#1568]
Currently, AKS HCI and Resource bridge configuration may fail in HCIBox due to an upstream issue with the Moc and Kva image download/cache. You may see very slow or halted downloads of the Moc and Kva images. The Jumpstart team is actively monitoring this upstream issue.

**Comment by lyledodgegh** [comment]
watching - ran into this today - happy to ping/work realtime if the team wants access to our cluster - teams alias is l dot dodge at accenture dot com.

powershell script hung on 
Invoke-MocCommand                                                                                                          
Moc - Applying configuration                                                                                                                                                                                                                Waiting on Arc Resource Bridge deployment to complete...

Digging into this a bit - on DeployArcResourceBridge.log:

Unable to find command C:\Program Files\AksHci\mocctl.exe
    + CategoryInfo          : OperationStopped: (Unable to find ...sHci\mocctl.exe:String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to find command C:\Program Files\AksHci\mocctl.exe
    + PSComputerName        : AzSHOST1

**Comment by dkirby-ms** [comment]
Thanks @lyledodgegh

We are testing a feature branch right now to resolve this.
