### ISSUE TITLE
Ubuntu Azure VM in Servers scenario fails with missing RP Microsoft.HybridCompute

### ISSUE THREAD

**Issue by shoegazerpt** [microsoft/azure_arc#157]
**Describe the bug**
When running the [Onboard an Azure Linux Server VM with Azure Arc](https://github.com/microsoft/azure_arc/blob/master/azure_arc_servers_jumpstart/docs/azure_arm_template_linux.md), it fails in subscriptions where the Microsoft.HybridCompute resource provider is not registered. After registering this RP, everything works normally.

**To Reproduce**
1. Go to https://github.com/microsoft/azure_arc/blob/master/azure_arc_servers_jumpstart/docs/azure_arm_template_linux.md
2. Run the instructions
3. In Automation Flow step 4 (ssh to VM), the generated .bash_profile execution in the VM fails if the  Microsoft.HybridCompute RP is not registered in the subscription. Full error below in Additional Context.

**Expected behavior**
Either make it explicit in the instructions that this RP needs to be registered or have the script do it (will need to wait until it's registered). 

**Additional context**
ERROR[0001] Failed to AzcmagentConnect ARM resource       Error="RequestCorrelationId:c1d985c6-de6c-47f2-a048-b064b6f234aa Message: The subscription is not registered to use namespace 'Microsoft.HybridCompute'. See https://aka.ms/rps-not-found for how to register subscriptions. Code: MissingSubscriptionRegistration httpStatusCode:409 "

FATAL[0001] RequestCorrelationId:c1d985c6-de6c-47f2-a048-b064b6f234aa Message: The subscription is not registered to use namespace 'Microsoft.HybridCompute'. See https://aka.ms/rps-not-found for how to register subscriptions. Code: MissingSubscriptionRegistration httpStatusCode:409

**Comment by likamrat** [comment]
Thank you @shoegazerpt 
This prereq is now added to all bootstrap scenarios
https://github.com/microsoft/azure_arc/commit/32ac8e265b33bed5b351b33060dc3163cad05219
