### ISSUE TITLE
Getting error when deploying Arc Sandbox

### ISSUE THREAD

**Issue by thedevopsguy** [microsoft/azure_arc#1570]
ArcBox Full

https://azurearcjumpstart.io/azure_jumpstart_arcbox/full/#deployment-option-1-azure-portal

Deployment fails at [ubuntuRancherDeployment] step.

When deploy using CLI or ARM template,  the deployment errors out at the step ubuntuRancherDeployment. The detailed error is
{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
            {
                "code": "Conflict",
                "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'installscript_k3s'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=2\\n[stdout]\\n\\n[stderr]\\n\\\"\\r\\n\\r\\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot \"\r\n      }\r\n    ]\r\n  }\r\n}"
            }
        ]
    }
}

ArcBox-K3s-9e00/installscript_k3s give a conflict in the details page. 

{
    "status": "Failed",
    "error": {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'installscript_k3s'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=2\n[stdout]\n\n[stderr]\n\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "
    }
}

**To Reproduce.**
<!--- Steps to reproduce the behavior:
1. Go to https://azurearcjumpstart.io/azure_jumpstart_arcbox/
2. Follow Arcbox Full deployment steps - I think this will also error on IT Pros deployment
3. Clock on deploy to Azure step
4. In deployment in progress window, we can see the errors/
![ARC2](https://user-images.githubusercontent.com/9168799/206553002-caa3702a-6e35-4c38-bec3-bea62aa7cb17.jpg)
![ARC1](https://user-images.githubusercontent.com/9168799/206553004-51f98a04-2c14-465e-8a94-6b7b7cc84176.jpg)

**Comment by likamrat** [comment]
@thedevopsguy can you please provide the logs as described in the readme?

**Comment by thedevopsguy** [comment]
![ARC2](https://user-images.githubusercontent.com/9168799/206589448-f0756ecc-13d9-4bc4-a0ee-b553cb320cd5.jpg)
![ARC1](https://user-images.githubusercontent.com/9168799/206589450-fbd927f6-9697-4931-b204-1f0897c7bee6.jpg)
Please find the screen shots

**Comment by thedevopsguy** [comment]
{
"status": "Failed",
"error": {
"code": "DeploymentFailed",
"message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
"details": [
{
"code": "Conflict",
"message": "{\r\n "status": "Failed",\r\n "error": {\r\n "code": "ResourceDeploymentFailure",\r\n "message": "The resource operation completed with terminal provisioning state 'Failed'.",\r\n "details": [\r\n {\r\n "code": "VMExtensionProvisioningError",\r\n "message": "VM has reported a failure when processing extension 'installscript_k3s'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=2\n[stdout]\n\n[stderr]\n\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "\r\n }\r\n ]\r\n }\r\n}"
}
]
}
}

ArcBox-K3s-9e00/installscript_k3s give a conflict in the details page.

{
"status": "Failed",
"error": {
"code": "VMExtensionProvisioningError",
"message": "VM has reported a failure when processing extension 'installscript_k3s'. Error message: "Enable failed: failed to execute command: command terminated with exit status=2\n[stdout]\n\n[stderr]\n"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "
}
}

**Comment by thedevopsguy** [comment]
I am getting this error consistently. In CLI mode and also in portal. Just followed the instructions in the documentation and upon submission, the deployment page in portal under the resource group shows this error messages.

**Comment by likamrat** [comment]
Please extract the logs as described in the Troubleshooting section [[here](https://azurearcjumpstart.io/azure_jumpstart_arcbox/full/#exploring-installation-logs-from-the-linux-virtual-machines)].

**Comment by likamrat** [comment]
Also, can you please share your deployment parameters? make sure to mask the service principal secret.
