### ISSUE TITLE
Unable to deploy HCIArcBOX

### ISSUE THREAD

**Issue by Ketilp** [microsoft/azure_arc#1573]
I am trying to deploy the HCIBox using the scripts. All goes well until the script tries to install the VM Extensions. It fails on HCIBox-Client/Bootstrap - with "Conflict"

From the log:
![image](https://user-images.githubusercontent.com/65591954/206933332-9a7cfc15-619d-4ee4-a2ca-6460eed66d48.png)

Have tried in both North Europe and East US, but the result is the same. Any clue where to start debugging this?

**Comment by Ketilp** [comment]
Looking at the scripts, the VM is created, but the extensions in "Bootstrap" fail to deploy:

Details on the extension under the VM:

Type
Microsoft.Compute.CustomScriptExtension
Version
1.10.14
Status
Provisioning failed
Status level
Error
Status message
Command execution finished, but failed because it returned a non-zero exit code of: '1'. The command had an error output of: 'The system cannot find the file specified. '

**Comment by mgodfre3** [comment]
Hello @ketlip the error indicates that the download for the required files did not complete in a timely manner. Can you redeploy the HCIBox again and see if that resolves the issue. Also can you share which Azure Region you are deploying in, to assist in replication of the issue.

**Comment by Ketilp** [comment]
Hi mgodfre3

I deployed it to North Europe, but I also tried to deploy it to East US to see if it made a difference, but it vas the same. Have been running the script both from CLI on the Azure Portal an in PowerShell locally without any visible difference.

**Comment by mgodfre3** [comment]
@ketlip  I looked into this issue and replicated the problem in EUS and North Europe and all times I was successful. I only saw your issue when working from some older code. I would suggest you  remove the cloned repo you have in your file system and run a git clone again, updates to the core Bicep files were made a few days ago to address some DNS issue and add more functions and I wonder if this is causing some problems. Please let me know how the testing goes.

**Comment by Ketilp** [comment]
Hi. I cleaned up my subscription and my local repo. Cloned the repo again and got the exact same problem.

**Comment by Ketilp** [comment]
I started looking at this once more. After downloading again, and it still failed on installing the Custom Script Extension I changed the parameter for the creation of the Bootstrap custom extension. I created a new parameter in host.bicep with the full path of the location of the Bootstrap.ps1 file. Using this parameter in the custom script creation made the whole thing work.

![image](https://user-images.githubusercontent.com/65591954/209778688-9ce6af50-b134-40fe-a175-b069ae5fb63f.png)

![image](https://user-images.githubusercontent.com/65591954/209778739-000abcbd-0d69-4e11-998f-d3151140654d.png)

**Comment by dkirby-ms** [comment]
Just ran an end-to-end deployment and everything deployed fine. Not sure what might be causing you to see this but the CSE should be able to access the script from Github directly. 

Are you using your own fork (perhaps a private fork) instead of the main Jumpstart repo?
