### ISSUE TITLE
HCIBox - HCIBoxLogonScript - NuGet/PS Timeout Errors on Deploy-AKS.ps1

### ISSUE THREAD

**Issue by kprawel-msft** [microsoft/azure_arc#1591]
**Is your issue related to a Jumpstart scenario, ArcBox, or HCIBox?**
HCIBox

**Describe the bug**
During Powershell log-on script, I started to receive:
"Provider 'PowerShellGet' is not completing the request in the time allowed..." as well as NuGet errors.  Looking through logs, it appears to be hanging in 'Deploy-AKS.ps1' at '# Install necessary AZ modules and initialize akshci on each node'

Familiar with this kind of error, I added '[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12' to Line 52 of 'Deploy-AKS.ps1'. I then commented out stages that had already ran and re-ran 'HCIBoxLogonScript.ps1' -- This seems to have solved the issue.

**To Reproduce**
You can reproduce by starting the process for HCIBox deployment from scratch. I made no custom settings upon deployment.
I added '[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12' to Line 52 of 'Deploy-AKS.ps1'. I then commented out stages that had already ran and re-ran 'HCIBoxLogonScript.ps1' -- This seems to have solved the issue.

**Expected behavior**
No errors

**Environment summary**
Native settings / config as deployed through HCIBox automation using github pull 01/08/2023@10AM MT

**Have you looked at the Troubleshooting and Logs section?**
Yes, mentioned above to find how to keep deployment working.

**Comment by likamrat** [comment]
@kprawel-msft please provide a more descriptive issue title

**Comment by dkirby-ms** [comment]
Interesting find. We are actually setting TLS to 1.2 further upstream in the automation but it seems like it might not be maintaining this across PoSH sessions. 

I will investigate and see if we can reproduce.
