### ISSUE TITLE
New Scenario for Arc enabled SQL server extension - add licenseType when create extension

### ISSUE THREAD

**Issue by YurongHe** [microsoft/azure_arc#1603]
Arc enabled SQL server extension adds a new parameter LicenseType. 

We should add it into settings. Sample settings like this.

{
	"SqlManagement": {
		"IsEnabled": true
    },
    "ExcludedSqlInstances": ["CLI"],
	"LicenseType":"PAYG"
}

az connectedmachine extension update --machine-name "test" -g "test-rg" --name "WindowsAgent.SqlServer" --type "WindowsAgent.SqlServer" --publisher "Microsoft.AzureData" --settings @settings.json

Settings.json file content is as below:

{
"SqlManagement": {
"IsEnabled": true
    },
"LiceseType":"PAYG"
}

**Comment by likamrat** [comment]
fixed via #1631
