### ISSUE TITLE
DevOps Scenario K3sGitOps.ps1 script references the CAPI cluster not the K3s cluster

### ISSUE THREAD

**Issue by colinrippeyfinarne** [microsoft/azure_arc#1607]
I've been exploring the DevOps scenario and have just executed the additional steps to configure the ArcBox-K3s cluster.

I ran the C:\ArcBox\GitOps\K3sGitOps.ps1 script and got the following results:

Transcript started, output file is C:\ArcBox\Logs\K3sGitOps.log
Login to Az CLI using the service principal
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "<tenantid>",
    "id": "<removed>",
    "isDefault": true,
    "managedByTenants": [],
    "name": "azr-dell-cls-dev-0001",
    "state": "Enabled",
    "tenantId": "<tenantid>",
    "user": {
      "name": "<removed>",
      "type": "servicePrincipal"
    }
  }
]
WARNING: Command group 'config' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus

azure-cli                         2.44.1

core                              2.44.1
telemetry                          1.0.8

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\<removed>\.azure\cliextensions'

Python (Windows) 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:37:59) [MSC v.1933 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.
✔ Switched to context "arcbox-k3s".
Creating GitOps config for NGINX Ingress Controller
WARNING: The command requires the extension k8s-configuration. It will be installed first.
WARNING: Creating the flux configuration 'config-nginx' in the cluster. This may take a few minutes...
{
  "azureBlob": null,
  "bucket": null,
  "complianceState": "Compliant",
  "configurationProtectedSettings": {},
  "errorMessage": "",
  "gitRepository": {
    "httpsCaCert": null,
    "httpsUser": null,
    "localAuthRef": null,
    "repositoryRef": {
      "branch": "main",
      "commit": null,
      "semver": null,
      "tag": null
    },
    "sshKnownHosts": null,
    "syncIntervalInSeconds": 3,
    "timeoutInSeconds": 600,
    "url": "https://github.com/<removed>/azure-arc-jumpstart-apps"
  },
  "id": "/subscriptions/<removed>/resourceGroups/<removed>/providers/Microsoft.Kubernetes/connectedClusters/ArcBox-CAPI-Data-2023/providers/Microsoft.KubernetesConfiguration/fluxConfigurations/config-nginx",
  "kustomizations": {
    "nginx": {
      "dependsOn": null,
      "force": false,
      "name": "nginx",
      "path": "./nginx/release",
      "prune": false,
      "retryIntervalInSeconds": null,
      "syncIntervalInSeconds": 600,
      "timeoutInSeconds": 600
    }
  },
  "name": "config-nginx",
  "namespace": "ingress-nginx",
  "provisioningState": "Succeeded",
  "repositoryPublicKey": "",
  "resourceGroup": "<removed>",
  "scope": "cluster",
  "sourceKind": "GitRepository",
  "sourceSyncedCommitId": "main/5567e75f55a37a598f03ba82f9d3078c348b0662",
  "sourceUpdatedAt": "2023-01-16T08:03:55+00:00",
  "statusUpdatedAt": "2023-01-16T08:04:10.350000+00:00",
  "statuses": [
    {
      "appliedBy": null,
      "complianceState": "Compliant",
      "helmReleaseProperties": null,
      "kind": "GitRepository",
      "name": "config-nginx",
      "namespace": "ingress-nginx",
      "statusConditions": [
        {
          "lastTransitionTime": "2023-01-15T13:19:37+00:00",
          "message": "stored artifact for revision 'main/5567e75f55a37a598f03ba82f9d3078c348b0662'",
          "reason": "Succeeded",
          "status": "True",
          "type": "Ready"
        },
        {
          "lastTransitionTime": "2023-01-15T13:19:37+00:00",
          "message": "stored artifact for revision 'main/5567e75f55a37a598f03ba82f9d3078c348b0662'",
          "reason": "Succeeded",
          "status": "True",
          "type": "ArtifactInStorage"
        }
      ]
    },
    {
      "appliedBy": null,
      "complianceState": "Compliant",
      "helmReleaseProperties": null,
      "kind": "Kustomization",
      "name": "config-nginx-nginx",
      "namespace": "ingress-nginx",
      "statusConditions": [
        {
          "lastTransitionTime": "2023-01-16T08:03:56+00:00",
          "message": "Applied revision: main/5567e75f55a37a598f03ba82f9d3078c348b0662",
          "reason": "ReconciliationSucceeded",
          "status": "True",
          "type": "Ready"
        },
        {
          "lastTransitionTime": "2023-01-16T08:03:56+00:00",
          "message": "Health check passed in 24.752428ms",
          "reason": "Succeeded",
          "status": "True",
          "type": "Healthy"
        }
      ]
    }
  ],
  "suspend": false,
  "systemData": {
    "createdAt": "2023-01-15T13:19:03.990909+00:00",
    "createdBy": null,
    "createdByType": null,
    "lastModifiedAt": "2023-01-16T08:03:42.600174+00:00",
    "lastModifiedBy": null,
    "lastModifiedByType": null
  },
  "type": "Microsoft.KubernetesConfiguration/fluxConfigurations"
}
Creating GitOps config for Hello-Arc application
WARNING: Creating the flux configuration 'config-helloarc' in the cluster. This may take a few minutes...
{
  "azureBlob": null,
  "bucket": null,
  "complianceState": "Compliant",
  "configurationProtectedSettings": {},
  "errorMessage": "",
  "gitRepository": {
    "httpsCaCert": null,
    "httpsUser": null,
    "localAuthRef": null,
    "repositoryRef": {
      "branch": "main",
      "commit": null,
      "semver": null,
      "tag": null
    },
    "sshKnownHosts": null,
    "syncIntervalInSeconds": 3,
    "timeoutInSeconds": 600,
    "url": "https://github.com/<removed>/azure-arc-jumpstart-apps"
  },
  "id": "/subscriptions/<removed>/resourceGroups/<removed>/providers/Microsoft.Kubernetes/connectedClusters/ArcBox-CAPI-Data-2023/providers/Microsoft.KubernetesConfiguration/fluxConfigurations/config-helloarc",
  "kustomizations": {
    "helloarc": {
      "dependsOn": null,
      "force": false,
      "name": "helloarc",
      "path": "./hello-arc/yaml",
      "prune": false,
      "retryIntervalInSeconds": null,
      "syncIntervalInSeconds": 600,
      "timeoutInSeconds": 600
    }
  },
  "name": "config-helloarc",
  "namespace": "hello-arc",
  "provisioningState": "Succeeded",
  "repositoryPublicKey": "",
  "resourceGroup": "<removed>",
  "scope": "namespace",
  "sourceKind": "GitRepository",
  "sourceSyncedCommitId": "main/5567e75f55a37a598f03ba82f9d3078c348b0662",
  "sourceUpdatedAt": "2023-01-16T08:04:55+00:00",
  "statusUpdatedAt": "2023-01-16T08:05:10.591000+00:00",
  "statuses": [
    {
      "appliedBy": null,
      "complianceState": "Compliant",
      "helmReleaseProperties": null,
      "kind": "GitRepository",
      "name": "config-helloarc",
      "namespace": "hello-arc",
      "statusConditions": [
        {
          "lastTransitionTime": "2023-01-15T13:23:39+00:00",
          "message": "stored artifact for revision 'main/5567e75f55a37a598f03ba82f9d3078c348b0662'",
          "reason": "Succeeded",
          "status": "True",
          "type": "Ready"
        },
        {
          "lastTransitionTime": "2023-01-15T13:23:39+00:00",
          "message": "stored artifact for revision 'main/5567e75f55a37a598f03ba82f9d3078c348b0662'",
          "reason": "Succeeded",
          "status": "True",
          "type": "ArtifactInStorage"
        }
      ]
    },
    {
      "appliedBy": null,
      "complianceState": "Compliant",
      "helmReleaseProperties": null,
      "kind": "Kustomization",
      "name": "config-helloarc-helloarc",
      "namespace": "hello-arc",
      "statusConditions": [
        {
          "lastTransitionTime": "2023-01-16T08:04:57+00:00",
          "message": "Applied revision: main/5567e75f55a37a598f03ba82f9d3078c348b0662",
          "reason": "ReconciliationSucceeded",
          "status": "True",
          "type": "Ready"
        },
        {
          "lastTransitionTime": "2023-01-16T08:04:57+00:00",
          "message": "Health check passed in 51.351871ms",
          "reason": "Succeeded",
          "status": "True",
          "type": "Healthy"
        }
      ]
    }
  ],
  "suspend": false,
  "systemData": {
    "createdAt": "2023-01-15T13:23:19.790147+00:00",
    "createdBy": null,
    "createdByType": null,
    "lastModifiedAt": "2023-01-16T08:04:16.536268+00:00",
    "lastModifiedBy": null,
    "lastModifiedByType": null
  },
  "type": "Microsoft.KubernetesConfiguration/fluxConfigurations"
}
Generating a TLS Certificate

    Directory: C:\Temp

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         1/16/2023   8:05 AM           2662 k3s-ingress-cert.pfx

PSPath                   : Microsoft.PowerShell.Security\Certificate::LocalMachine\Root\E7CC4C3EBD1535712B1E3EA8A589C5267C847F2B
PSParentPath             : Microsoft.PowerShell.Security\Certificate::LocalMachine\Root
PSChildName              : E7CC4C3EBD1535712B1E3EA8A589C5267C847F2B
PSIsContainer            : False
Archived                 : False
Extensions               : {System.Security.Cryptography.Oid, System.Security.Cryptography.Oid, System.Security.Cryptography.Oid, System.Security.Cryptography.Oid}
FriendlyName             :
IssuerName               : System.Security.Cryptography.X509Certificates.X500DistinguishedName
NotAfter                 : 1/16/2024 8:05:18 AM
NotBefore                : 1/16/2023 7:55:18 AM
HasPrivateKey            : True
PrivateKey               :
PublicKey                : System.Security.Cryptography.X509Certificates.PublicKey
RawData                  : {48, 130, 3, 57...}
SerialNumber             : 3E3533DD370C28904746EEEF7F89F262
SubjectName              : System.Security.Cryptography.X509Certificates.X500DistinguishedName
SignatureAlgorithm       : System.Security.Cryptography.Oid
Thumbprint               : E7CC4C3EBD1535712B1E3EA8A589C5267C847F2B
Version                  : 3
Handle                   : 2889491506160
Issuer                   : CN=arcbox.k3sdevops.com
Subject                  : CN=arcbox.k3sdevops.com
EnhancedKeyUsageList     : {Client Authentication (1.3.6.1.5.5.7.3.2), Server Authentication (1.3.6.1.5.5.7.3.1)}
DnsNameList              : {arcbox.k3sdevops.com}
SendAsTrustedIssuer      : False
EnrollmentPolicyEndPoint : Microsoft.CertificateServices.Commands.EnrollmentEndPointProperty
EnrollmentServerEndPoint : Microsoft.CertificateServices.Commands.EnrollmentEndPointProperty
PolicyId                 :

Importing the TLS certificate to Key Vault
ERROR: ActivityId: 42e50ae4-3bde-4c47-bdfe-d73264534191, ActivityName: CertificateImport
Installing Azure Key Vault Kubernetes extension instance
WARNING: The command requires the extension k8s-extension. It will be installed first.
{
  "aksAssignedIdentity": null,
  "autoUpgradeMinorVersion": true,
  "configurationProtectedSettings": {},
  "configurationSettings": {
    "secrets-store-csi-driver.enableSecretRotation": "true",
    "secrets-store-csi-driver.syncSecret.enabled": "true"
  },
  "customLocationSettings": null,
  "errorInfo": null,
  "extensionType": "microsoft.azurekeyvaultsecretsprovider",
  "id": "/subscriptions/<removed>/resourceGroups/<removed>/providers/Microsoft.Kubernetes/connectedClusters/ArcBox-CAPI-Data-2023/providers/Microsoft.KubernetesConfiguration/extensions/akvsecretsprovider",
  "identity": {
    "principalId": "9155f8d3-036f-47de-8eab-1cfee8841123",
    "tenantId": null,
    "type": "SystemAssigned"
  },
  "installedVersion": null,
  "name": "akvsecretsprovider",
  "packageUri": null,
  "provisioningState": "Succeeded",
  "releaseTrain": "Stable",
  "resourceGroup": "<removed>",
  "scope": {
    "cluster": {
      "releaseNamespace": "kube-system"
    },
    "namespace": null
  },
  "statuses": [],
  "systemData": {
    "createdAt": "2023-01-15T13:24:28.725913+00:00",
    "createdBy": null,
    "createdByType": null,
    "lastModifiedAt": "2023-01-16T08:05:36.877300+00:00",
    "lastModifiedBy": null,
    "lastModifiedByType": null
  },
  "type": "Microsoft.KubernetesConfiguration/extensions",
  "version": "1.4.0"
}
error: failed to create secret Post "https://127.0.0.1:6443/api/v1/namespaces/hello-arc/secrets?fieldManager=kubectl-create&fieldValidation=Strict": dial tcp 127.0.0.1:6443: connectex: No connection could be made because the target machine actively refused it.
E0116 08:07:12.598462    1072 memcache.go:238] couldn't get current server API group list: Get "https://127.0.0.1:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connectex: No connection could be made because the target machine actively refused it.
E0116 08:07:14.712883    1072 memcache.go:238] couldn't get current server API group list: Get "https://127.0.0.1:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connectex: No connection could be made because the target machine actively refused it.
E0116 08:07:16.743644    1072 memcache.go:238] couldn't get current server API group list: Get "https://127.0.0.1:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connectex: No connection could be made because the target machine actively refused it.
E0116 08:07:18.759899    1072 memcache.go:238] couldn't get current server API group list: Get "https://127.0.0.1:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connectex: No connection could be made because the target machine actively refused it.
E0116 08:07:20.776093    1072 memcache.go:238] couldn't get current server API group list: Get "https://127.0.0.1:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connectex: No connection could be made because the target machine actively refused it.
Unable to connect to the server: dial tcp 127.0.0.1:6443: connectex: No connection could be made because the target machine actively refused it.
Creating Secret Provider Class
Unable to connect to the server: dial tcp 127.0.0.1:6443: connectex: No connection could be made because the target machine actively refused it.
Deploying App referencing the secret
Unable to connect to the server: dial tcp 127.0.0.1:6443: connectex: No connection could be made because the target machine actively refused it.
Deploying Ingress Resource
Unable to connect to the server: dial tcp 127.0.0.1:6443: connectex: No connection could be made because the target machine actively refused it.
E0116 08:07:30.108737    4264 memcache.go:238] couldn't get current server API group list: Get "https://127.0.0.1:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connectex: No connection could be made because the target machine actively refused it.
E0116 08:07:32.165411    4264 memcache.go:238] couldn't get current server API group list: Get "https://127.0.0.1:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connectex: No connection could be made because the target machine actively refused it.
E0116 08:07:34.181496    4264 memcache.go:238] couldn't get current server API group list: Get "https://127.0.0.1:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connectex: No connection could be made because the target machine actively refused it.
E0116 08:07:36.213646    4264 memcache.go:238] couldn't get current server API group list: Get "https://127.0.0.1:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connectex: No connection could be made because the target machine actively refused it.
Unable to connect to the server: dial tcp 127.0.0.1:6443: connectex: No connection could be made because the target machine actively refused it.

When I check the K3s cluster in the portal I don't see any GitOps configurations.
When I check the K3s cluster in the portal I don't see the Flux extension.

Looking at the K3sGitOps.ps1 script line 6

$Env:k3sArcClusterName=(Get-AzResource -ResourceGroupName $Env:resourceGroup -ResourceType microsoft.kubernetes/connectedclusters).Name | Select-String "CAPI" | Where-Object { $_ -ne "" }

Should this not be referencing K3s instead of CAPI?

**Comment by colinrippeyfinarne** [comment]
I've ran the K3sGitOps.ps1 script with a tweak to line 6 from CAPI to K3s and I get a partial result.

The Extensions get installed fine and so do the GitOps configs but from what I can tell the rest of the commands running kubectl fail.

Trying to "debug", as part of the ArcBox-Client first logon it looks like the DevOpsLogonScript.ps1 goes and grabs the kube config files from the CAPI and K3s clusters and merges them together.

The K3s kube config endpoints are to the local https://127.0.0.1:6443 address/port so I'm guessing that's why any execution of kubectl fails when the context is pointing to it?

**Comment by zaidmohd** [comment]
Hi #colinrippeyfinarne,

Thank you for raising the issue, I was able to repro it. I will investigate further and get back to you.
