### ISSUE TITLE
A part of WindowsAdminPassword was dropped when set domain user password

### ISSUE THREAD

**Issue by sergeypechenkin** [microsoft/azure_arc#1616]
**Is your issue related to a Jumpstart scenario, ArcBox, or HCIBox?**

jumpstart_hcibox
https://github.com/microsoft/azure_arc/blob/main/docs/azure_jumpstart_hcibox/_index.md

**Describe the bug**

I forked a repo and set my parameters, including "windowsAdminPassword". I set it as 'vk3jyL!24dCTA1>jYrkor9'. Seems like it meets the requirements, which are the following:

Password must have 3 of the following: 1 lower case character, 1 upper case character, 1 number, and 1 special character. The value must be between 12 and 123 characters long.

Deployment went successfully, I was able to connect to HCIBox-Client for post-deployment automation, and it went successfully as well. 

Then I got a credentials error when I tried to RDP to the AdminCenter using domain name arcdemo@jumpstart.local and my windowsAdminPassword, which was 'vk3jyL!24dCTA1>jYrkor9'

I opened HCIBox-Config file and found out  SDNAdminPassword is set to 'vk3jyL!24dCTA1', which is my windowsAdminPassword but without last 8 symbols. I tried it, and it worked. 

**To Reproduce**

Set this password in azure_jumpstart_hcibox/bicep/main.parameters.json and deploy it

        "windowsAdminPassword": {
            "value": "vk3jyL!24dCTA1>jYrkor9"
        },

**Expected behavior**

According to the guide https://github.com/microsoft/azure_arc/blob/main/docs/azure_jumpstart_hcibox/_index.md

"NOTE: The password for this account is set as the same password you supplied during deployment for the local account"

but the password for domain account was not the same I supplied during deployment for the local account.

**Environment summary**

azure-cli                         2.42.0

**Have you looked at the Troubleshooting and Logs section?**
yes

**Screenshots**

**Additional context**

**Comment by dkirby-ms** [comment]
Looks like you caught a truncating error with how we are injecting the password into the psd1 or answer files. Will address this in upcoming PR.

**Comment by dkirby-ms** [comment]
@sergeypechenkin can you confirm your psd1 file has the windowsAdminPassword in single quotes? I see that you put single quotes in your comment above, but just want to confirm that is also what is in your psd1 file.

**Comment by sergeypechenkin** [comment]
single qoute

# SDN Lab Admin Password
    SDNAdminPassword                     = 'vk3jyL!24dCTA1'                  # Do not change - this value is replaced during Bootstrap with the password supplied in the ARM deployment

**Comment by dkirby-ms** [comment]
After further debugging, this is related to how Azure custom script extension is handling the parameters passed to the PowerShell script on the HCIBox-Client VM. Azure custom script extension doesnt handle some special characters like < > # and probably others. ARM seems to pass the value with special characters properly to the extension, but somewhere in the extension the value gets truncated when it hits one of the special characters. 

One workaround I am exploring is to encode the password with base64 encoding and then decode in the Powershell.

**Comment by dkirby-ms** [comment]
I also submitted this issue to the CSE team - https://github.com/Azure/custom-script-extension-linux/issues/204 to see if we can get traction there.
