### ISSUE TITLE
AKS Edge Essentials :: login script not executed on first login

### ISSUE THREAD

**Issue by phwecker** [microsoft/azure_arc#1636]
**Is your issue related to a Jumpstart scenario, ArcBox, or HCIBox?**
scenario : AKS Edge Essential 

**Describe the bug**
followed the instructions, but the described loginscript is not executed automatically. i did -however- modify the username oin the deplyoment parameters. 

**To Reproduce**
1) modify parameters (incl. admin username and password
2) enable bastion
3) run deployment
4) login via bastion 

**Expected behavior**
according to the doc, on first login the script should run. 

**Environment summary**
out of the box AKS Edge Essential install according to doc. 

**Have you looked at the Troubleshooting and Logs section?**
not a "box" setup

**Screenshots**
n/a

**Additional context**
i did download and start the script manually, still in the middle of execution, but looking good so far.

**Comment by likamrat** [comment]
@phwecker please incl. the bootstrap log as described in the [readme].(https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/aks_hybrid/aks_edge_essentials/#exploring-logs-from-the-client-vm)
