### ISSUE TITLE
Deployment failed with error

### ISSUE THREAD

**Issue by ManjulaChintharla** [microsoft/azure_arc#1637]
Deployment failed with after running thebelow command.

 az deployment group create -g azstackhci-rg001 -f main.bicep -p main.parameters.json

![image](https://user-images.githubusercontent.com/84832942/216613394-de52d4e2-8c40-4dc7-a1a9-74835197952a.png)

![image](https://user-images.githubusercontent.com/84832942/216613522-5574df01-5887-4f92-b4f0-87971b2de9b8.png)

**Comment by likamrat** [comment]
Please follow issue template and provide context and environment details.
