### ISSUE TITLE
Error Registering Windows Admin Center from Jumpstart HCIBox in Azure

### ISSUE THREAD

**Issue by StefanHorz** [microsoft/azure_arc#1658]
Hi,
wie have issues to register https://admincenter.jumpstart.local/ in Azure.
When we try create a new Active Diretory Apllication, we get:
"
_Source
Go to source. (https://admincenter.jumpstart.local/settings/azure)
Type
Error

Message
Couldn't register application 'WindowsAdminCenter-https://admincenter.jumpstart.local' in Azure Active Directory. Error: ajax error 500_

"
![1](https://user-images.githubusercontent.com/36531086/218055922-7d4dcbe8-21a4-45ce-823d-bf1912aed2ce.JPG)

When we create the Apllication WindowsAdminCenter and set the permissions we get:
_A registered application with the ID 'xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx' was not found._
![2](https://user-images.githubusercontent.com/36531086/218055926-cdfba199-8952-45e0-87bf-e5d67a46176d.JPG)

Had anyone success registering  https://admincenter.jumpstart.local/ (version 2211 Build 1.4.2212.08003) from Jumpstart HCI (22H1)?

Any hints to see in logs or something else why it fails?

Can it be redistered using a command line?

Regards,
Stefan

**Comment by dkirby-ms** [comment]
Hi StefanHorz,

Registering WAC is not in scope for HCIBox. WAC registration requires additional Azure AD permissions that are not required for deploying HCIBox, and registering WAC is not required for other HCIBox-specific features.

You can find documentation for registering WAC here - https://learn.microsoft.com/en-us/azure-stack/hci/manage/register-windows-admin-center

Hope this helps
