### ISSUE TITLE
Arc for k8s - monitoring - onboarding failing on identity checking without reason

### ISSUE THREAD

**Issue by lgmorand** [microsoft/azure_arc#166]
**Describe the bug**
I'm registered two clusters to Azure Arc:
- AKS - systemassigned
- Kubernetes (within Docker for desktop)

**To Reproduce**
follow the [documentation ](https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-enable-arc-enabled-clusters?toc=/azure/azure-arc/kubernetes/toc.yml#enable-using-bash-script)to onboard a cluster for monitoring. At the end the bash scripts gives an error about identity

> validating cluster identity
> cluster identity type: **systemassigned**
> -e only supported cluster identity is **systemassigned** for Azure Arc enabled Kubernetes cluster type

that's a weird behavior as it detects properly the identity but still fails the test

> identitytype=$(echo $identitytype | tr "[:upper:]" "[:lower:]" | tr -d '"')
>   echo "cluster identity type:" $identitytype
> 
>   if [[ "$identitytype" != "systemassigned" ]]; then
>     echo "-e only supported cluster identity is systemassigned for Azure Arc enabled Kubernetes cluster type"
>     exit 1
>   fi

**Expected behavior**
monitoring should be enabled.

I'm using WSL (ubuntu) and I still don't understand while the test if failing while value are equal

If I disable the test (in fact, just remove exit 1), the script continues with success for both clusters but after after few hours. No logs in log analytics. I don't know where to look to debug

**Comment by ganga1980** [comment]
Hi, @lgmorand , what is the version of the azure  CLI you are using?  if you are not using latest version of Azure CLI, please give a try upgrading to latest version of the azure cli and the try onboarding and it should resolve this issue. IIRC, there was an issue with CLI handling the quotes.

**Comment by lgmorand** [comment]
@ ganga1980 

> {
>   "azure-cli": "2.15.1",
>   "azure-cli-core": "2.15.1",
>   "azure-cli-telemetry": "1.0.6",
>   "extensions": {
>     "connectedk8s": "0.2.7",
>     "k8sconfiguration": "0.2.0"
>   }


but I don't see how AZ CLI could be related to an error of the onboarding bash script, especially this part.
it detects that identity is "systemassigned" but still rejects it and stops. As shown in the output

> validating cluster identity
cluster identity type: systemassigned
-e only supported cluster identity is systemassigned for Azure Arc enabled Kubernetes cluster type

**Comment by ganga1980** [comment]
Hi, @lgmorand ,  This is safety check to avoid enable monitoring initial arc k8s versions. commenting this should work monitoring. can you please share the azure arc resource id of the cluster so that i can look at why you are not seeing data in log analytics? can you please see the charts when you go to Insights page on the azure arc cluster in the Azure Portal?  and also can you please share the how you passed the parameters to bash script. I have seen weird issue with CLI when parameter passed.

**Comment by lgmorand** [comment]
Hi @ganga1980 

I understand the test, why I don't understand, is why it's failing while the scripts looks good  :) 

Regarding the parameters, I just type the commands one by one. First the exports and then the command given. I'm pretty sure that parameters were OK because if there is a typo in the resourceID, like a slash missing, there is an error message

Here is one of the non working (logs) cluster:
/subscriptions/6c9dc160-dca4-47cb-9e76-ed16a4b4edb1/resourceGroups/AzureArcTest/providers/Microsoft.Kubernetes/connectedClusters/RedTowerK8SDocker/
and
/subscriptions/6c9dc160-dca4-47cb-9e76-ed16a4b4edb1/resourceGroups/AzureArcTest/providers/Microsoft.Kubernetes/connectedClusters/AKSArcCluster

the second one is an AKS and monitoring is enabled but on a dedicated log analytics

**Comment by nyuen** [comment]
Hello @lgmorand 

Make sure that your output of Az is set to Json and not table. I've seen similar issues for a certain @squasta and his AZ configure was set to Table.

Hope it helps,

Bisou

**Comment by lgmorand** [comment]
pretty sure that's not the issue because the value is properly parsed but then configuration failed

```
cluster identity type: systemassigned => parsed
-e only supported cluster identity is systemassigned => comparison
```

edit: checked, I was in Json already. but I didn't knew this and I have some issue with other arc CLI which may come from that in some cases
