### ISSUE TITLE
Key Vault Portal UI is different from Jumpstart doc

### ISSUE THREAD

**Issue by charris-msft** [microsoft/azure_arc#1682]
**Is your issue related to a Jumpstart scenario, ArcBox, or HCIBox?**
https://azurearcjumpstart.io/azure_jumpstart_arcbox/devops/#key-vault-integration-1

**Describe the bug**
The UI example shown in the Jumpstart doc doesn't match the UI I'm seeing. This is likely due to me using the Preview portal, but I'm not sure how to turn off the Preview so I can see the default view.

Examples:
* Jumpstart says `Click “Add access policy”`, but my UI has a `+ Create` button.
* Jumpstart shows a simplified UI with dropdowns for adding the Certificate permissions, but mine is exploded showing all options.
![image](https://user-images.githubusercontent.com/74415662/219127791-8d86839c-af0f-449c-a8df-4e8c7102a469.png)

**To Reproduce**
1. Go to ArcBox-KV-[gobbldygook] > Access Policies
2. Click on '+ Create'
4. See different view

**Expected behavior**
Jumpstart doc and portal view match (at least for non-Preview case)

**Environment summary**

**Have you looked at the Troubleshooting and Logs section?**
NA

**Screenshots**
(see above)

**Additional context**

**Comment by likamrat** [comment]
Fixed via #1688
