### ISSUE TITLE
ArcBox for ITPros redirects to full ArcBox

### ISSUE THREAD

**Issue by moadus** [microsoft/azure_arc#1728]
Looks like there's a bug in our hyperlinks. I was always trying ArcBox for ITPros from this page - [Azure Arc Jumpstart](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazurearcjumpstart.io%2Fazure_jumpstart_arcbox%2Fitpro%2F&data=05%7C01%7Cmadusumilli%40microsoft.com%7C792a78f8287144f61ba208db1f9dfa08%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638138535697395206%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=snuhPWP3%2BU8%2BmnsWn3lVyzMYZWR2g5vkah7IdJRz5XI%3D&reserved=0) and was using Deployment Option 1 - [Azure Arc Jumpstart](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazurearcjumpstart.io%2Fazure_jumpstart_arcbox%2Fitpro%2F&data=05%7C01%7Cmadusumilli%40microsoft.com%7C792a78f8287144f61ba208db1f9dfa08%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638138535697395206%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=snuhPWP3%2BU8%2BmnsWn3lVyzMYZWR2g5vkah7IdJRz5XI%3D&reserved=0) and this button  was taking me to [Custom deployment - Microsoft Azure](https://ms.portal.azure.com/#create/Microsoft.Template) which is full ArcBox deployment and not ArcBox for IT Pros. Adding screenshots from the link redirection.

![image](https://user-images.githubusercontent.com/105902765/223636828-2eee3dc1-a979-4fd7-bcb1-4bb166e06702.png)

**Comment by dkirby-ms** [comment]
I dont think this is a bug, this is just how portal deployment works with respect to the different flavors. 

The flavor, in this case ITPro, is an ARM template parameter input. In the documentation for IT Pro it states to fill out the ARM template parameters and shows a screenshot with the ITPro flavor selected for the flavor parameter in the dropdown.
