### ISSUE TITLE
ArcBox Deployment Template Bad Passwords

### ISSUE THREAD

**Issue by thommck** [microsoft/azure_arc#1742]
**Is your issue related to a Jumpstart scenario, ArcBox, or HCIBox?**
ArcBox - https://azurearcjumpstart.io/azure_jumpstart_arcbox/itpro/#start-post-deployment-automation

**Describe the bug**
Password encourages poor password practices. I had to use a less secure password because whatever is checking the text didn't recognise spaces

**To Reproduce**
1. Go to Azure Portal
2. Search for Azure Arc
3. Click "Try ArcBox" on the getting started screen
4. Deploy for IT Pros
5.  Fill out password meeting all the criteria but include a space
6.  Password not expected despite meeting the criteria - See error in screenshots

**Expected behavior**
The password box to follow the same criteria as the default Azure experience (e.g. a local admin password on an Azure VM)

**Environment summary**
Built-in Azure deploy option

**Have you looked at the Troubleshooting and Logs section?**
Yes

**Screenshots**
<img width="876" alt="image" src="https://user-images.githubusercontent.com/29751878/225374081-9cb80f61-ebba-42c9-ac71-0dc0e876908b.png">

<img width="489" alt="image" src="https://user-images.githubusercontent.com/29751878/225374050-a1134f5e-63ad-4a9c-9bc5-5144bfd1112d.png">

**Additional context**
Note how the tooltip mentions both a minimum of 12 characters and 8 characters - it should only need one

**Comment by likamrat** [comment]
Thank you @thommck. Let me follow-up with the portal team and update the issue.

**Comment by unrealab** [comment]
Thanks for the report @thommck . I've updated the validations to be consistent and improved the messaging on the criteria to call out the details of the specific characters that are supported.

**Comment by likamrat** [comment]
@unrealab can you please validate fix rollout?

**Comment by likamrat** [comment]
@thommck I can confirm the fix is now rolled out and working /cc @unrealab.

Closing this issue for now, thx for flagging!

![image](https://user-images.githubusercontent.com/46730876/231769983-4ba4e370-e699-49dc-af64-33efb28c91e3.png)
