### ISSUE TITLE
What happenes with AMA once we migrate ARC VM to Azure? 

### ISSUE THREAD

**Issue by lenvolk** [microsoft/azure_arc#1750]
**Is your feature request related to a new Jumpstart scenario you would like to contribute?**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like.**

**Describe alternatives you've considered.**

**Additional context.**

**Comment by lenvolk** [comment]
we can install Azure Migrate appliance installer (zip file) right to the ArcBox-Clien hyper-v VM
In the PS script make sure to delete PowerShell-ISE in the Install-WindowsFeature

**Comment by dkirby-ms** [comment]
This doesnt seem relevant to this repo.
