### ISSUE TITLE
Issues with ArcBox

### ISSUE THREAD

**Issue by clopezf** [microsoft/azure_arc#1768]
**Is your issue related to a Jumpstart scenario, ArcBox, or HCIBox?**

Yes, this is the scenario: https://azurearcjumpstart.io/azure_jumpstart_arcbox/
**Describe the bug**

The deployment is showing this message:
{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
        "details": [
            {
                "code": "Conflict",
                "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The 'AzureAsyncOperationWaiting' resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningTimeout\",\r\n        \"message\": \"Provisioning of VM extension installscript_CAPI has timed out. Extension provisioning has taken too long to complete. The extension last reported \\\"Plugin enabled\\\".\\r\\n\\r\\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot\"\r\n      }\r\n    ]\r\n  }\r\n}"

**To Reproduce**

Successful deployment.

**Environment summary**

az --version
azure-cli                         2.47.0
core                              2.47.0
telemetry                          1.0.8
Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

**Have you looked at the Troubleshooting and Logs section?**

Yes, but didn't find anything related to it.

**Screenshots**

**Additional context**

**Comment by sebassem** [comment]
Thanks for submitting this issue, from the error it appears that something is wrong with the Service principal used to deploy ArcBox. Can you please review the [INSTALL_CAPI.LOG](https://azurearcjumpstart.io/azure_jumpstart_arcbox/full/#exploring-logs-from-the-_arcbox-client_-virtual-machine) file for errors?

**Comment by sebassem** [comment]
@clopezf have you managed to check the log mentioned above ?

**Comment by sebassem** [comment]
Closed for inactivity
