### ISSUE TITLE
Arc-enabled SQL Server best practices assessment failing with error

### ISSUE THREAD

**Issue by chintalavr** [microsoft/azure_arc#1783]
**Is your issue related to a Jumpstart scenario, ArcBox, or HCIBox?**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment summary**

**Have you looked at the Troubleshooting and Logs section?**

**Screenshots**

#1782 

**Additional context**

**Comment by likamrat** [comment]
Closed #1782
