### ISSUE TITLE
 Azure Arc Jumpstart - Arcbox full failing when deploying custom extension

### ISSUE THREAD

**Issue by Cisco-z** [microsoft/azure_arc#1787]
**Is your issue related to a Jumpstart scenario, ArcBox, or HCIBox?**
https://azurearcjumpstart.io/azure_jumpstart_arcbox/full/

**Describe the bug**
I made sure all prerequisites are in place. I have tried all three deployment methods (ARM, Bicep, Terraform, and all three fail at the same point, deploying the custom VM extension on the ArcBox-K3s-Luoy VM and ArcBox-CAPI-MGMT VM. I am creating the resources in eastus with all of the quotas in place. Nothing seems to work. Here is the error in Terraform;

Error: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded
│
│   with module.capi_vm[0].azurerm_virtual_machine_extension.custom_script,
│   on modules\kubernetes\ubuntuCapi\main.tf line 164, in resource "azurerm_virtual_machine_extension" "custom_script":
│  164: resource "azurerm_virtual_machine_extension" "custom_script" {
│
╵
╷
│ Error: Code="VMExtensionProvisioningError" Message="VM has reported a failure when processing extension 'ArcBox-K3s-Luoy'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=2\n[stdout]\n\n[stderr]\n\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "
│
│   with module.rancher_vm[0].azurerm_virtual_machine_extension.custom_script,
│   on modules\kubernetes\ubuntuRancher\main.tf line 158, in resource "azurerm_virtual_machine_extension" "custom_script":
│  158: resource "azurerm_virtual_machine_extension" "custom_script" {

**To Reproduce**
Deployment of the solution given the instructions provided in https://azurearcjumpstart.io/azure_jumpstart_arcbox/full/

**Expected behavior**
Full installation of the resources in the the resource group.

**Environment summary**
Terraform v1.4.4,Bicep CLI version 0.16.2 (de7fdd2b33)

**Have you looked at the Troubleshooting and Logs section?**
Yes, I tried all troubleshooting. Nothing has worked.

**Comment by likamrat** [comment]
Hi @Cisco-z, 

I am unable to repro the issue. Can you please share the parameters file without the spn secret?

![image](https://user-images.githubusercontent.com/46730876/233439468-67c7352d-ef4c-4bd2-9142-cce69a059d7d.png)

![image](https://user-images.githubusercontent.com/46730876/233439489-4a10ceda-617f-4ef3-8637-b93e5eb4365f.png)

**Comment by Cisco-z** [comment]
azure_location="eastus"
resource_group_name="ArcBox"
spn_client_id="e418bb14-4229-4e09-87ce-f3485e12d4e2"
spn_client_secret="" 
spn_tenant_id="3c763c20-8c2b-41c2-aa44-9231e669f7ab"
client_admin_ssh="C:/Users/*/.ssh/id_rsa.pub"
deployment_flavor="Full"
client_admin_username="arcadmin"
client_admin_password="************************" 
workspace_name="ArcBoxWorkspace"

**Comment by likamrat** [comment]
can you paste the actual _azuredeploy.parameters.json_ file you are using?

**Comment by Cisco-z** [comment]
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "sshRSAPublicKey": {
            "value": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC5X4yrY0CcAkkbsF6vJnRMovyUo0D+mnRZozUKO2E7psc1j25d8J/dh2aLp4ZiSnseREMz3O9DT9OzKVYLhbbCFTDhcj2CLyIRepBLaqeUG95E5wUXkKCwsYrVGUfd2ekcKzWFPNlfCEzcL4ACjEE0KDO0PmleB78FxhoyMnh5AczHlJhYz4mRRqQAM5qk4oehIov3X1UG7Z5CJXr1q30XUCfRu0E81A6m14Hwyh50s5x534IWvZl/PXGRZymlEKNZeNHQZ98VIg3FOnuJsR7bA0C0Q2HA+LTISqXKq2aoPhPb5U3Fc0WbChCRKEOV2jCt9DpUKvZAs/+9SX+LTR1Vk7mfpORquRCl0h8mMk+gkABigsPq4yHvzWs17uKJnEXs5n19VymrVWfN41nCBXD0ShTBGrhGoiGD9t9k1nZsG0MnVA6cfPnIVx/yiA5CiOb3KJXtrGOVq30AGz7joXGfWymQ+jgyn5Jefpfom2dJC1xmRb4mleifw1Kpeo+YSYvMCzts9zBYGX6wk0eXaoeQdNyCLve5CDI4SPfX40CLUQMX1XefE7Ok8kn7Y6C1Z+tP4GPz2bm5i1tUV+fMFTNCI3VylqUzRJLxNz6dkmHLG2ozEjMcaTH8IsNKFBiPnibo7EqwQNmVDpTvEgqQjW0oOkO4vHWA9oZg2prlrofzNQ== jfzaram@CBR-J8LGM33"
        },
        "spnClientId": {
            "value": "e418bb14-4229-4e09-87ce-f3485e12d4e2"
        },
        "spnClientSecret": {
            "value": ""
        },
        "spnTenantId": {
            "value": "3c763c20-8c2b-41c2-aa44-9231e669f7ab"
        },
        "windowsAdminUsername": {
            "value": "arcdemo"
        },
        "windowsAdminPassword": {
            "value": "ArcPassword123!!"
        },
        "logAnalyticsWorkspaceName": {
            "value": "ArcBoxDemo"
        },
        "flavor": {
            "value": "Full"
        },
        "deployBastion": {
            "value": false
        },
        "githubUser": {
            "value": "microsoft"
        }
    }
}

**Comment by likamrat** [comment]
parameters files look good. 

Can you please grab the Custom Script Extension log from the K3s VM? 

1. Enable JIT on the VM and SSH
2. Switch to _sudo_ user with the _sudo -s_ command
3. What is the output of the _ls -l /var/lib/waagent/custom-script/download/0/_ command?
4. What is the output of the _cat /var/lib/waagent/custom-script/download/0/installK3s.log_ command?


![image](https://user-images.githubusercontent.com/46730876/233788782-92cdc037-87f0-4f85-b1ba-ba9b0ae01e9a.png)

![image](https://user-images.githubusercontent.com/46730876/233788508-470d80fc-7079-4504-82d3-2c085259f22e.png)

![image](https://user-images.githubusercontent.com/46730876/233788657-8cab7ddc-4be2-4a0d-bb2d-e28ebb2203ac.png)

**Comment by Cisco-z** [comment]
I tried the install again from a different device and this time it worked. No idea why, I used the same variables. I was previously using a development environment is Azure, this time I used WSL2 on my corporate device. Just happy to have it working now. Thank you for the assistance.
