### ISSUE TITLE
VM Bootstrap extension provisioning failure,

### ISSUE THREAD

**Issue by sqlmadhadr** [microsoft/azure_arc#1792]
**Is your issue related to a Jumpstart scenario, ArcBox, or HCIBox?**
ArcBox

**Describe the bug**
I'm deploying to an empty subscription. The VM creates and the "Bootstrap" extension kicks off. However, after many minutes, it returns with a vague error. I'm not sure if the bootstrap is failing to detect that the roles install simply requires a restart, if there's an errant/unexpected hash symbol in the script, or some output contains a hash unexpectedly. Either way, it stops here. 

[
    {
        "code": "ComponentStatus/StdOut/succeeded",
        "level": "Info",
        "displayStatus": "Provisioning succeeded",
        "message": ".Core\\Alias\r\nPSIsContainer       : False\r\nReferencedCommand   : kubectl.exe\r\nResolvedCommand     : kubectl.exe\r\nDefinition          : C:\\ProgramData\\chocolatey\\lib\\kubernetes-cli\\tools\\kubernetes\\client\\bin\\kubectl.exe\r\nOptions             : None\r\nDescription         : \r\nOutputType          : {System.String}\r\nName                : kubectl\r\nCommandType         : Alias\r\nSource              : \r\nVersion             : \r\nVisibility          : Public\r\nModuleName          : \r\nModule              : \r\nRemotingCapability  : PowerShell\r\nParameters          : \r\nParameterSets       : \r\nHelpUri             : \r\nResolvedCommandName : kubectl.exe\r\nDisplayName         : kubectl -> kubectl.exe\r\n\r\n\r\nPSPath              : Microsoft.PowerShell.Core\\Alias::azdata\r\nPSDrive             : Alias\r\nPSProvider          : Microsoft.PowerShell.Core\\Alias\r\nPSIsContainer       : False\r\nReferencedCommand   : \r\nResolvedCommand     : \r\nDefinition          : C:\\Program Files (x86)\\Microsoft SDKs\\Azdata\\CLI\\wbin\\azdata.cmd\r\nOptions             : None\r\nDescription         : \r\nOutputType          : \r\nName                : azdata\r\nCommandType         : Alias\r\nSource              : \r\nVersion             : \r\nVisibility          : Public\r\nModuleName          : \r\nModule              : \r\nRemotingCapability  : PowerShell\r\nParameters          : \r\nParameterSets       : \r\nHelpUri             : \r\nResolvedCommandName : \r\nDisplayName         : azdata -> C:\\Program Files (x86)\\Microsoft SDKs\\Azdata\\CLI\\wbin\\azdata.cmd\r\n\r\n\r\nHubsSidebarEnabled : 0\r\nPSPath             : Microsoft.PowerShell.Core\\Registry::HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Edge\r\nPSParentPath       : Microsoft.PowerShell.Core\\Registry::HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\r\nPSChildName        : Edge\r\nPSDrive            : HKLM\r\nPSProvider         : Microsoft.PowerShell.Core\\Registry\r\n\r\n\r\nHideFirstRunExperience : 1\r\nPSPath                 : Microsoft.PowerShell.Core\\Registry::HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Edge\r\nPSParentPath           : Microsoft.PowerShell.Core\\Registry::HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\r\nPSChildName            : Edge\r\nPSDrive                : HKLM\r\nPSProvider             : Microsoft.PowerShell.Core\\Registry\r\n\r\nRDP port number from configuration is \r\n\r\nActions            : {MSFT_TaskExecAction}\r\nAuthor             : \r\nDate               : \r\nDescription        : \r\nDocumentation      : \r\nPrincipal          : MSFT_TaskPrincipal2\r\nSecurityDescriptor : \r\nSettings           : MSFT_TaskSettings3\r\nSource             : \r\nState              : Ready\r\nTaskName           : MonitorWorkbookLogonScript\r\nTaskPath           : \\\r\nTriggers           : {MSFT_TaskLogonTrigger}\r\nURI                : \\MonitorWorkbookLogonScript\r\nVersion            : \r\nPSComputerName     : \r\n\r\n\r\nActions            : {MSFT_TaskExecAction}\r\nAuthor             : Microsoft Corporation\r\nDate               : \r\nDescription        : Task for launching Initial Configuration Tasks or Server Manager at logon.\r\nDocumentation      : \r\nPrincipal          : MSFT_TaskPrincipal2\r\nSecurityDescriptor : D:P(A;;FA;;;BA)(A;;FA;;;SY)(A;;FR;;;BU)\r\nSettings           : MSFT_TaskSettings3\r\nSource             : Server Manager\r\nState              : Disabled\r\nTaskName           : ServerManager\r\nTaskPath           : \\Microsoft\\Windows\\Server Manager\\\r\nTriggers           : {MSFT_TaskLogonTrigger}\r\nURI                : \\Microsoft\\Windows\\Server Manager\\ServerManager\r\nVersion            : 1.0\r\nPSComputerName     : \r\n\r\nInstalling Hyper-V and restart\r\nWARNING: Restart is suppressed because NoRestart is specified.\r\n\r\nPath   : \r\nOnline : True\r\n\r\nWARNING: Restart is suppressed because NoRestart is specified.\r\n\r\nPath   : \r\nOnline : True\r\n\r\n\r\nSuccess       : True\r\nRestartNeeded : Yes\r\nFeatureResult : {Hyper-V, Hyper-V Module for Windows PowerShell, Hyper-V GUI Management Tools, Hyper-V Management \r\n                Tools}\r\nExitCode      : SuccessRestartRequired\r\n\r\nWARNING: You must restart this server to finish the installation process.\r\nClean up Bootstrap.log\r\nTranscript stopped, output file is C:\\ArcBox\\Logs\\Bootstrap.log\r\n\r\n\r\n"
    },
    {
        "code": "ComponentStatus/StdErr/succeeded",
        "level": "Info",
        "displayStatus": "Provisioning succeeded",
        "message": "'#' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"
    }
]

**To Reproduce**
1. Start Arcbox IT deployment
2. Deploy to an empty subscription
3. Allow to execute for some time, then observe failure

**Expected behavior**
No failure :)

**Environment summary**
Deployed using Azure Portal click-through.

**Have you looked at the Troubleshooting and Logs section?**
Yes, I reviewed the c:\arcbox\logs\bootstrap.txt log. It verbosely mirrors what was output by the Bootstrap extension. There doesn't *seem* to be an actual error, and no mention of the errant hash. 

**Screenshots**
Doesn't seem necessary. The text is succinct. 

**Additional context**
Again, clean environment. Seems to be a problem in the application provisioning within the VM.

**Comment by sqlmadhadr** [comment]
As an update, I created a 2nd RG and had another pass - same problem, same everything.

**Comment by alsanch** [comment]
Hi @sqlmadhadr !

I am unable to repro the issue. I've deployed it successfully in EastUS. Could you please paste the actual _azuredeploy.parameters.json_ file you are using?

Thanks!

**Comment by sqlmadhadr** [comment]
I went extremely simple mode and used just the portal.

`{
  "id": "/subscriptions/3ed56da4-39e2-47f6-b8f8-xxxxxx1b7b42/resourceGroups/lr1-sbx-arcbox-it2/providers/Microsoft.Resources/deployments/Microsoft.Template-20230423231103",
  "name": "Microsoft.Template-20230423231103",
  "type": "Microsoft.Resources/deployments",
  "properties": {
    "templateLink": {
      "uri": "https://raw.githubusercontent.com/microsoft/azure_arc/main/azure_jumpstart_arcbox/ARM/azuredeploy.json",
      "contentVersion": "1.0.0.0"
    },
    "templateHash": "2788733936666099726",
    "parameters": {
      "sshRSAPublicKey": {
        "type": "SecureString"
      },
      "spnClientId": {
        "type": "String",
        "value": "25a24e99-bc90-42fd-b80a-XxXxXxe56622"
      },
      "spnClientSecret": {
        "type": "SecureString"
      },
      "spnTenantId": {
        "type": "String",
        "value": "b3c62499-ad8f-41a7-a455-xXxXXxa3adc"
      },
      "windowsAdminUsername": {
        "type": "String",
        "value": "b.franklin"
      },
      "windowsAdminPassword": {
        "type": "SecureString"
      },
      "logAnalyticsWorkspaceName": {
        "type": "String",
        "value": "lr1-sbx-arcbox-it-law2"
      },
      "flavor": {
        "type": "String",
        "value": "ITPro"
      },
      "githubAccount": {
        "type": "String",
        "value": "microsoft"
      },
      "githubBranch": {
        "type": "String",
        "value": "main"
      },
      "deployBastion": {
        "type": "Bool",
        "value": false
      },
      "githubUser": {
        "type": "String",
        "value": "microsoft"
      },
      "addsDomainName": {
        "type": "String",
        "value": "jumpstart.local"
      },
      "guid": {
        "type": "String",
        "value": "c752"
      },
      "rdpPort": {
        "type": "String",
        "value": "3389"
      },
      "sshPort": {
        "type": "String",
        "value": "22"
      }
    },
    "mode": "Incremental",
    "debugSetting": {
      "detailLevel": "None"
    },
    "provisioningState": "Failed",
    "timestamp": "2023-04-24T03:28:31.1659681Z",
    "duration": "PT17M25.1933101S",
    "correlationId": "15b126c9-440f-484e-9a77-d4a164d204aa",
    "providers": [
      {
        "namespace": "Microsoft.Resources",
        "resourceTypes": [
          {
            "resourceType": "deployments",
            "locations": [
              null
            ]
          }
        ]
      }
    ],
    "dependencies": [
      {
        "dependsOn": [
          {
            "id": "/subscriptions/3ed56da4-39e2-47f6-b8f8-9bafa31b7b42/resourceGroups/lr1-sbx-arcbox-it2/providers/Microsoft.Resources/deployments/stagingStorageAccountDeployment",
            "resourceType": "Microsoft.Resources/deployments",
            "resourceName": "stagingStorageAccountDeployment"
          },
          {
            "id": "/subscriptions/3ed56da4-39e2-47f6-b8f8-9bafa31b7b42/resourceGroups/lr1-sbx-arcbox-it2/providers/Microsoft.Resources/deployments/mgmtArtifactsAndPolicyDeployment",
            "resourceType": "Microsoft.Resources/deployments",
            "resourceName": "mgmtArtifactsAndPolicyDeployment"
          },
          {
            "id": "/subscriptions/3ed56da4-39e2-47f6-b8f8-9bafa31b7b42/resourceGroups/lr1-sbx-arcbox-it2/providers/Microsoft.Resources/deployments/updateVNetDNSServers",
            "resourceType": "Microsoft.Resources/deployments",
            "resourceName": "updateVNetDNSServers"
          }
        ],
        "id": "/subscriptions/3ed56da4-39e2-47f6-b8f8-9bafa31b7b42/resourceGroups/lr1-sbx-arcbox-it2/providers/Microsoft.Resources/deployments/ubuntuCAPIDeployment",
        "resourceType": "Microsoft.Resources/deployments",
        "resourceName": "ubuntuCAPIDeployment"
      },
      {
        "dependsOn": [
          {
            "id": "/subscriptions/3ed56da4-39e2-47f6-b8f8-9bafa31b7b42/resourceGroups/lr1-sbx-arcbox-it2/providers/Microsoft.Resources/deployments/stagingStorageAccountDeployment",
            "resourceType": "Microsoft.Resources/deployments",
            "resourceName": "stagingStorageAccountDeployment"
          },
          {
            "id": "/subscriptions/3ed56da4-39e2-47f6-b8f8-9bafa31b7b42/resourceGroups/lr1-sbx-arcbox-it2/providers/Microsoft.Resources/deployments/mgmtArtifactsAndPolicyDeployment",
            "resourceType": "Microsoft.Resources/deployments",
            "resourceName": "mgmtArtifactsAndPolicyDeployment"
          }
        ],
        "id": "/subscriptions/3ed56da4-39e2-47f6-b8f8-9bafa31b7b42/resourceGroups/lr1-sbx-arcbox-it2/providers/Microsoft.Resources/deployments/ubuntuRancherDeployment",
        "resourceType": "Microsoft.Resources/deployments",
        "resourceName": "ubuntuRancherDeployment"
      },
      {
        "dependsOn": [
          {
            "id": "/subscriptions/3ed56da4-39e2-47f6-b8f8-9bafa31b7b42/resourceGroups/lr1-sbx-arcbox-it2/providers/Microsoft.Resources/deployments/stagingStorageAccountDeployment",
            "resourceType": "Microsoft.Resources/deployments",
            "resourceName": "stagingStorageAccountDeployment"
          },
          {
            "id": "/subscriptions/3ed56da4-39e2-47f6-b8f8-9bafa31b7b42/resourceGroups/lr1-sbx-arcbox-it2/providers/Microsoft.Resources/deployments/updateVNetDNSServers",
            "resourceType": "Microsoft.Resources/deployments",
            "resourceName": "updateVNetDNSServers"
          }
        ],
        "id": "/subscriptions/3ed56da4-39e2-47f6-b8f8-9bafa31b7b42/resourceGroups/lr1-sbx-arcbox-it2/providers/Microsoft.Resources/deployments/clientVmDeployment",
        "resourceType": "Microsoft.Resources/deployments",
        "resourceName": "clientVmDeployment"
      },
      {
        "dependsOn": [
          {
            "id": "/subscriptions/3ed56da4-39e2-47f6-b8f8-9bafa31b7b42/resourceGroups/lr1-sbx-arcbox-it2/providers/Microsoft.Resources/deployments/mgmtArtifactsAndPolicyDeployment",
            "resourceType": "Microsoft.Resources/deployments",
            "resourceName": "mgmtArtifactsAndPolicyDeployment"
          }
        ],
        "id": "/subscriptions/3ed56da4-39e2-47f6-b8f8-9bafa31b7b42/resourceGroups/lr1-sbx-arcbox-it2/providers/Microsoft.Resources/deployments/addsVmDeployment",
        "resourceType": "Microsoft.Resources/deployments",
        "resourceName": "addsVmDeployment"
      },
      {
        "dependsOn": [
          {
            "id": "/subscriptions/3ed56da4-39e2-47f6-b8f8-9bafa31b7b42/resourceGroups/lr1-sbx-arcbox-it2/providers/Microsoft.Resources/deployments/mgmtArtifactsAndPolicyDeployment",
            "resourceType": "Microsoft.Resources/deployments",
            "resourceName": "mgmtArtifactsAndPolicyDeployment"
          },
          {
            "id": "/subscriptions/3ed56da4-39e2-47f6-b8f8-9bafa31b7b42/resourceGroups/lr1-sbx-arcbox-it2/providers/Microsoft.Resources/deployments/addsVmDeployment",
            "resourceType": "Microsoft.Resources/deployments",
            "resourceName": "addsVmDeployment"
          }
        ],
        "id": "/subscriptions/3ed56da4-39e2-47f6-b8f8-9bafa31b7b42/resourceGroups/lr1-sbx-arcbox-it2/providers/Microsoft.Resources/deployments/updateVNetDNSServers",
        "resourceType": "Microsoft.Resources/deployments",
        "resourceName": "updateVNetDNSServers"
      },
      {
        "dependsOn": [
          {
            "id": "/subscriptions/3ed56da4-39e2-47f6-b8f8-9bafa31b7b42/resourceGroups/lr1-sbx-arcbox-it2/providers/Microsoft.Resources/deployments/stagingStorageAccountDeployment",
            "resourceType": "Microsoft.Resources/deployments",
            "resourceName": "stagingStorageAccountDeployment"
          },
          {
            "id": "/subscriptions/3ed56da4-39e2-47f6-b8f8-9bafa31b7b42/resourceGroups/lr1-sbx-arcbox-it2/providers/Microsoft.Resources/deployments/mgmtArtifactsAndPolicyDeployment",
            "resourceType": "Microsoft.Resources/deployments",
            "resourceName": "mgmtArtifactsAndPolicyDeployment"
          },
          {
            "id": "/subscriptions/3ed56da4-39e2-47f6-b8f8-9bafa31b7b42/resourceGroups/lr1-sbx-arcbox-it2/providers/Microsoft.Resources/deployments/updateVNetDNSServers",
            "resourceType": "Microsoft.Resources/deployments",
            "resourceName": "updateVNetDNSServers"
          }
        ],
        "id": "/subscriptions/3ed56da4-39e2-47f6-b8f8-9bafa31b7b42/resourceGroups/lr1-sbx-arcbox-it2/providers/Microsoft.Resources/deployments/aksDeployment",
        "resourceType": "Microsoft.Resources/deployments",
        "resourceName": "aksDeployment"
      }
    ],
    "error": {
      "code": "DeploymentFailed",
      "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
      "details": [
        {
          "code": "DeploymentFailed",
          "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details."
        }
      ]
    },
    "validationLevel": "Template"
  },
  "tags": {
    "marketplaceItemId": "Microsoft.Template"
  }
}`

**Comment by alsanch** [comment]
Hi! Thanks for all that info. I've deployed it again in EastUS and it worked. I have the following questions:

- Which is the subscription type you are using? (please, share a screenshot)
- Could you try to deploy it in a different subscription?
- Which region are you using?
- Do you have enough quota in that region?
![image](https://user-images.githubusercontent.com/96136892/235006072-4c4d08e2-cf4f-4d74-80c5-3d9e01a0faf4.png)

**Comment by alsanch** [comment]
Hi! Sorry, but I cannot reproduce your issue, my deployment was successful. Please, could you try to deploy it via Azure CLI? Thanks!

**Comment by likamrat** [comment]
Closing due to lack of response.
