### ISSUE TITLE
Issue while the logon scripts are running inside the HCIbox

### ISSUE THREAD

**Issue by ullasanand13** [microsoft/azure_arc#1796]
### Discussed in https://github.com/microsoft/azure_arc/discussions/1795

<div type='discussions-op-text'>

<sup>Originally posted by **ullasanand13** April 25, 2023</sup>
Hi GIT team,

"HCIBox-Client" has got deployed. However, after login to the HCIbox the logon scripts have failed due to the below error. I know this is a permissions issue. But it is trying to connect to our default subscription. How to change the subscription where the resources have to be deployed?

Message: The client 'ullas.anand@kennametal.com' with object id 'f0851858-ef81-48ef-b258-b865c3e268ce' does not have authorization to perform action 'Microsoft.GuestConfiguration/register/action' over scope '/subscriptions/7e62512b-1073-46d1-b75c-c507c9cc7eb2' or the scope is invalid. If access was recently granted, please refresh your credentials.
(AuthorizationFailed) The client 'ullas.anand@kennametal.com' with object id 'f0851858-ef81-48ef-b258-b865c3e268ce' does not have authorization to perform action 'Microsoft.Kubernetes/register/action' over scope '/subscriptions/7e62512b-1073-46d1-b75c-c507c9cc7eb2' or the scope is invalid. If access was recently granted, please refresh your credentials.
Code: AuthorizationFailed</div>

**Comment by sebassem** [comment]
Hello, thanks for reaching out. You would need to select the right subscription before deploying following this [guidance](https://learn.microsoft.com/cli/azure/manage-azure-subscriptions-azure-cli#change-the-active-subscription)

**Comment by ullasanand13** [comment]
Thank you. I was able to overcome this issue by giving contributor role to the service principal. 

Regards,
Ullas

**Comment by sebassem** [comment]
Glad to hear its resolved. Please note you need [Owner ](https://azurearcjumpstart.io/azure_jumpstart_hcibox/#prerequisites)permissions to make sure to have all the functionality working in HCIBox
