### ISSUE TITLE
HCIBox Microsoft.OperationalInsights

### ISSUE THREAD

**Issue by FallenHoot** [microsoft/azure_arc#1805]
When running the HCIBox Jumpstart I ran into a provider issue. It needs to be added to the HCIBox Jumpstart "Azure resource providers" section. 

**Describe the bug**
`{
    "status": "Failed",
    "error": {
        "code": "MissingSubscriptionRegistration",
        "message": "The subscription is not registered to use namespace 'Microsoft.OperationalInsights'. See https://aka.ms/rps-not-found for how to register subscriptions.",
        "details": [
            {
                "code": "MissingSubscriptionRegistration",
                "target": "Microsoft.OperationalInsights",
                "message": "The subscription is not registered to use namespace 'Microsoft.OperationalInsights'. See https://aka.ms/rps-not-found for how to register subscriptions."
            }
        ]
    }
}`

**To Reproduce**
Fresh Tenant, Fresh Subscription
Follow steps https://azurearcjumpstart.io/azure_jumpstart_hcibox/

**Fix**
az provider register --namespace Microsoft.OperationalInsights

**Comment by sebassem** [comment]
Thank you for flagging this issue. It's now added to the docs
