### ISSUE TITLE
Terraform template error creating aws sql server with arc agent (Error: timeout - last error: http response error: 401 - invalid content type)

### ISSUE THREAD

**Issue by karthick-kk** [microsoft/azure_arc#191]
**Describe the bug**
Terraform workflow fails to complete running https://github.com/microsoft/azure_arc/blob/master/azure_arc_sqlsrv_jumpstart/docs/aws_terraform_winsrv.md

**To Reproduce**
1. export terraform vars
2. terraform apply --auto-approve

**Expected behavior**
output with public ip

**Screenshots**
```
aws_instance.windows: Creating...
aws_default_route_table.route_table: Creation complete after 5s [id=rtb-0b7a708ff46138b2d]
aws_instance.windows: Still creating... [10s elapsed]
aws_instance.windows: Still creating... [20s elapsed]
aws_instance.windows: Still creating... [30s elapsed]
aws_instance.windows: Still creating... [40s elapsed]
aws_instance.windows: Still creating... [50s elapsed]
aws_instance.windows: Still creating... [1m0s elapsed]
aws_instance.windows: Still creating... [1m10s elapsed]
aws_instance.windows: Still creating... [1m20s elapsed]
aws_instance.windows: Still creating... [1m30s elapsed]
aws_instance.windows: Still creating... [1m40s elapsed]
aws_instance.windows: Still creating... [1m50s elapsed]
aws_instance.windows: Provisioning with 'file'...
aws_instance.windows: Still creating... [2m0s elapsed]
aws_instance.windows: Still creating... [2m10s elapsed]
aws_instance.windows: Still creating... [2m20s elapsed]
aws_instance.windows: Still creating... [2m30s elapsed]
aws_instance.windows: Still creating... [2m40s elapsed]
aws_instance.windows: Still creating... [2m50s elapsed]
aws_instance.windows: Still creating... [3m0s elapsed]
aws_instance.windows: Still creating... [3m10s elapsed]
aws_instance.windows: Still creating... [3m20s elapsed]
aws_instance.windows: Still creating... [3m30s elapsed]
aws_instance.windows: Still creating... [3m40s elapsed]
aws_instance.windows: Still creating... [3m50s elapsed]
aws_instance.windows: Still creating... [4m0s elapsed]
aws_instance.windows: Still creating... [4m10s elapsed]
aws_instance.windows: Still creating... [4m20s elapsed]
aws_instance.windows: Still creating... [4m30s elapsed]
aws_instance.windows: Still creating... [4m40s elapsed]
aws_instance.windows: Still creating... [4m50s elapsed]
aws_instance.windows: Still creating... [5m0s elapsed]
aws_instance.windows: Still creating... [5m10s elapsed]
aws_instance.windows: Still creating... [5m20s elapsed]
aws_instance.windows: Still creating... [5m30s elapsed]
aws_instance.windows: Still creating... [5m40s elapsed]
aws_instance.windows: Still creating... [5m50s elapsed]
aws_instance.windows: Still creating... [6m0s elapsed]
aws_instance.windows: Still creating... [6m10s elapsed]
aws_instance.windows: Still creating... [6m20s elapsed]
aws_instance.windows: Still creating... [6m30s elapsed]
aws_instance.windows: Still creating... [6m40s elapsed]
aws_instance.windows: Still creating... [6m50s elapsed]
aws_instance.windows: Still creating... [7m0s elapsed]
aws_instance.windows: Still creating... [7m10s elapsed]
aws_instance.windows: Still creating... [7m20s elapsed]
aws_instance.windows: Still creating... [7m30s elapsed]
aws_instance.windows: Still creating... [7m40s elapsed]
aws_instance.windows: Still creating... [7m50s elapsed]
aws_instance.windows: Still creating... [8m0s elapsed]
aws_instance.windows: Still creating... [8m10s elapsed]
aws_instance.windows: Still creating... [8m20s elapsed]
aws_instance.windows: Still creating... [8m30s elapsed]
aws_instance.windows: Still creating... [8m40s elapsed]
aws_instance.windows: Still creating... [8m50s elapsed]
aws_instance.windows: Still creating... [9m0s elapsed]
aws_instance.windows: Still creating... [9m10s elapsed]
aws_instance.windows: Still creating... [9m20s elapsed]
aws_instance.windows: Still creating... [9m30s elapsed]
aws_instance.windows: Still creating... [9m40s elapsed]
aws_instance.windows: Still creating... [9m50s elapsed]
aws_instance.windows: Still creating... [10m0s elapsed]
aws_instance.windows: Still creating... [10m10s elapsed]
aws_instance.windows: Still creating... [10m20s elapsed]
aws_instance.windows: Still creating... [10m30s elapsed]
aws_instance.windows: Still creating... [10m40s elapsed]
aws_instance.windows: Still creating... [10m50s elapsed]
aws_instance.windows: Still creating... [11m0s elapsed]
aws_instance.windows: Still creating... [11m10s elapsed]
aws_instance.windows: Still creating... [11m20s elapsed]
aws_instance.windows: Still creating... [11m30s elapsed]
aws_instance.windows: Still creating... [11m40s elapsed]
aws_instance.windows: Still creating... [11m50s elapsed]


Warning: Interpolation-only expressions are deprecated

  on main.tf line 101, in locals:
 101:     admin_user     = "${var.admin_user}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.

(and 5 more similar warnings elsewhere)


Error: timeout - last error: http response error: 401 - invalid content type

```

**Additional context**
AWS resources are created successfully

**Comment by likamrat** [comment]
@karthick-kk can you check your local firewall? it looks like the plan is not coping the local file which relies on winrm at port 5985/5986.

Plan executed correctly on my end with public IP output

aws_instance.windows: Creation complete after 8m0s [id=i-0cf6985b7628327c3]

Apply complete! Resources: 9 added, 0 changed, 0 destroyed.

Outputs:

public_ip = [
  "35.163.84.33",
]

I will also update tf expressions regardless so it will match >v0.11

**Comment by karthick-kk** [comment]
@likamrat Thanks for checking on this. I could see the security group rules does exist for port 5985/5986 for 0.0.0.0/0 cidr on the aws console. I did a telnet to the port 5985 and it connects. 
This looks like some winrm setting missing on the image that is not allowing us to establish the connection and run remote scripts.
I manged to collect some trace for your reference.

`2020/12/04 21:01:02 [TRACE] EvalWriteState: recording 5 dependencies for aws_instance.windows
2020/12/04 21:01:02 [TRACE] EvalWriteState: writing current state object for aws_instance.windows
2020/12/04 21:01:02 [TRACE] EvalApplyProvisioners: provisioning aws_instance.windows with "file"
aws_instance.windows: Provisioning with 'file'...
2020-12-04T21:01:02.733+0530 [DEBUG] plugin.terraform: file-provisioner (internal) 2020/12/04 21:01:02 [DEBUG] connecting to remote shell using WinRM
2020/12/04 21:01:06 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "output.public_ip"
2020/12/04 21:01:07 [TRACE] dag/walk: vertex "output.public_ip" is waiting for "aws_instance.windows"
2020/12/04 21:01:07 [TRACE] dag/walk: vertex "provisioner.remote-exec (close)" is waiting for "aws_instance.windows"
2020/12/04 21:01:07 [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/aws\"] (close)" is waiting for "aws_instance.windows"
2020/12/04 21:01:07 [TRACE] dag/walk: vertex "provisioner.file (close)" is waiting for "aws_instance.windows"
2020/12/04 21:01:07 [TRACE] dag/walk: vertex "root" is waiting for "meta.count-boundary (EachMode fixup)"
2020-12-04T21:01:10.525+0530 [DEBUG] plugin.terraform: file-provisioner (internal) 2020/12/04 21:01:10 [ERROR] error creating shell: http response error: 401 - invalid content type
2020-12-04T21:01:10.525+0530 [DEBUG] plugin.terraform: file-provisioner (internal) 2020/12/04 21:01:10 [WARN] retryable error: http response error: 401 - invalid content type
2020-12-04T21:01:10.525+0530 [DEBUG] plugin.terraform: file-provisioner (internal) 2020/12/04 21:01:10 [INFO] sleeping for 1s
2020-12-04T21:01:11.525+0530 [DEBUG] plugin.terraform: file-provisioner (internal) 2020/12/04 21:01:11 [DEBUG] connecting to remote shell using WinRM
2020/12/04 21:01:11 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "output.public_ip"
aws_instance.windows: Still creating... [2m10s elapsed]
2020/12/04 21:01:12 [TRACE] dag/walk: vertex "provisioner.file (close)" is waiting for "aws_instance.windows"
2020/12/04 21:01:12 [TRACE] dag/walk: vertex "output.public_ip" is waiting for "aws_instance.windows"
2020/12/04 21:01:12 [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/aws\"] (close)" is waiting for "aws_instance.windows"
2020/12/04 21:01:12 [TRACE] dag/walk: vertex "provisioner.remote-exec (close)" is waiting for "aws_instance.windows"
2020/12/04 21:01:12 [TRACE] dag/walk: vertex "root" is waiting for "meta.count-boundary (EachMode fixup)"
2020-12-04T21:01:15.225+0530 [DEBUG] plugin.terraform: file-provisioner (internal) 2020/12/04 21:01:15 [ERROR] error creating shell: http response error: 401 - invalid content type
2020-12-04T21:01:15.225+0530 [DEBUG] plugin.terraform: file-provisioner (internal) 2020/12/04 21:01:15 [WARN] retryable error: http response error: 401 - invalid content type
2020-12-04T21:01:15.225+0530 [DEBUG] plugin.terraform: file-provisioner (internal) 2020/12/04 21:01:15 [INFO] sleeping for 2s
2020/12/04 21:01:16 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "output.public_ip"
2020-12-04T21:01:17.225+0530 [DEBUG] plugin.terraform: file-provisioner (internal) 2020/12/04 21:01:17 [DEBUG] connecting to remote shell using WinRM
2020/12/04 21:01:17 [TRACE] dag/walk: vertex "provisioner.file (close)" is waiting for "aws_instance.windows"
2020/12/04 21:01:17 [TRACE] dag/walk: vertex "root" is waiting for "meta.count-boundary (EachMode fixup)"
2020/12/04 21:01:17 [TRACE] dag/walk: vertex "output.public_ip" is waiting for "aws_instance.windows"
2020/12/04 21:01:17 [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/aws\"] (close)" is waiting for "aws_instance.windows"
2020/12/04 21:01:17 [TRACE] dag/walk: vertex "provisioner.remote-exec (close)" is waiting for "aws_instance.windows"
2020/12/04 21:01:21 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "output.public_ip"
`

**Comment by karthick-kk** [comment]
The issue was neither with the templates nor the firewall. I had a simple password that didn't meet the password complexity of windows image. Therefore user creation failed and subsequent file copy and other remote execution failed due to invalid authentication.
