### ISSUE TITLE
runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized

### ISSUE THREAD

**Issue by Chevron94** [microsoft/azure_arc#192]
**Describe the bug**
We are going through the guide of deploying Azure Arc in EKS (https://github.com/microsoft/azure_arc/blob/master/azure_arc_data_jumpstart/docs/eks_dc_vanilla_terraform.md), but for some reasons "terraform apply" step from this guild finished with an error:
`
Error: error waiting for EKS Node Group (arc-data-eks:arc-eks-demo) creation: NodeCreationFailure: Unhealthy nodes in the kubernetes cluster. Resource IDs: [i-0f6cc2577b851a182 i-0939c79f9073f7bd4]`

As I can see, in AWS EKS cluster and Node Group were created but all nodes were in Not Ready state with next error message:
`runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized`

**To Reproduce**
1. Go through https://github.com/microsoft/azure_arc/blob/master/azure_arc_data_jumpstart/docs/eks_dc_vanilla_terraform.md

**Expected behavior**
Cluster should be successfully deployed

**Comment by likamrat** [comment]
Hi @Chevron94 I was able to deploy the EKS cluster but did found a bug around Azure Data Studio in the logon script which I will PR. 

Can you maybe share some more details on region, EKS version, etc.?

Here is the terraform output (certificate-authority-data and password are masked out):

```console
Apply complete! Resources: 26 added, 0 changed, 0 destroyed.

Outputs:

config_map_aws_auth =

apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::529318042936:role/terraform-eks-arcdemo-node
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

kubeconfig =

apiVersion: v1
clusters:
- cluster:
    server: https://57F49F5F51F2B38D163FCA88E86E5ED0.gr7.us-west-2.eks.amazonaws.com    
    certificate-authority-data: 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "arc-data-eks"

password_decrypted = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

**Comment by Chevron94** [comment]
Kubernetes version: 1.18
Platform version: eks.3
Region: us-east-1
CNI version: 1.7.5
AMI release version: 1.18.9-20201126
Kubelet version: v1.18.9-eks-d1db3c
Architecture: amd64

**Comment by likamrat** [comment]
Can you also share the output of ```kubectl describe node``` on one of the nodes?

**Comment by Chevron94** [comment]
We found an issue. It was permissions issue. Now it was fixed and we can deploy Azure arc in AWS EKS. Thank you!

**Comment by likamrat** [comment]
Thanks for the update @Chevron94 . I will close this for now.
