### ISSUE TITLE
Upgrade to .NET from .NET Core which has reached end of support

### ISSUE THREAD

**Issue by DanteMustCode** [microsoft/azure_arc#1941]
**Is your feature request related to a new Jumpstart scenario you would like to contribute?**

**Is your feature request related to a problem? Please describe.**

.NET Core has reached end of support since 2022-12-13.
A naive search of `dotnetcore` in this repository yields 15 PowerShell scripts using it.

**Describe the solution you'd like.**

Upgrade to .NET 6 LTS or .NET 7 STS.

**Describe alternatives you've considered.**

Remove if it is not necessary.

**Additional context.**

**Comment by janegilring** [comment]
@DanteMustCode Thank you for bringing this to our attention. We will assess the use of outdated .NET Core versions and create a plan for testing and upgrading the affected scenarios to supported versions.

**Comment by janegilring** [comment]
Agora, ArcBox & HCIBox has been updated.
Remaining work for this issue will be tracked internally by the Jumpstart team, which will make sure to update remaining scenarios to Azure CLI to 64-bit.
