### ISSUE TITLE
Azure Kubernetes Service (AKS) hybrid possible race condition in ScaleConfigJoin.json creation

### ISSUE THREAD

**Issue by ajoint** [microsoft/azure_arc#1957]
Using aks_hybrid/aks_edge_essentials_full jumpstart I encountered a one-time failure. The AKS cluster failed to complete/join. 
LogonScript.log shows the following: 

INFO: Node1's kubeconfig is ready - copying over config-node1
INFO: Waiting on kubeconfig files took 532.3553327 seconds.
INFO: 
[06/22/2023 16:01:25]
INFO: Please create a deployment before using this commandlet.
INFO: INFO: Node1's ScaleConfigJoin.json is ready
Copy-Item : Cannot find path 'C:\Deployment\ScaleConfigJoin.json' because it does not exist.
At C:\Temp\LogonScript.ps1:388 char:1
+ Copy-Item -FromSession $s -Path $path -Destination $destinationPath
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (C:\Deployment\ScaleConfigJoin.json:String) [Copy-Item], 
ArgumentException
    + FullyQualifiedErrorId : RemotePathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand
Copy-Item : Cannot find path 'C:\Deployment\ScaleConfigJoin.json' because it does not exist.
At C:\Temp\LogonScript.ps1:388 char:1
+ Copy-Item -FromSession $s -Path $path -Destination $destinationPath
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (C:\Deployment\ScaleConfigJoin.json:String) [Copy-Item], ArgumentExcept
   ion
    + FullyQualifiedErrorId : RemotePathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

Get-Content : Cannot find path 'C:\Temp\ScaleConfigJoin.json' because it does not exist.

This is the first time I have encountered this error. I had previously created clusters using this bicep. Creating a new instance in a new resource group with no other changes immediately following this failure succeeded.

**Comment by lanicolas** [comment]
hi @ajoint 

thanks for using jumpstart and flagging this, I was not able to reproduce the error. As you mentioned this might be a one time thing could we close the issue?

**Comment by ajoint** [comment]
Since neither of us can reproduce this issue, I'm going to close it. Should it occur again, the issue may be reopened.
