### ISSUE TITLE
SQL Managed Instance ARM Template

### ISSUE THREAD

**Issue by kprpg** [microsoft/azure_arc#1971]
After following the steps to create the Arc Data Box (did this twice and got the same error), and once the initial ARM template is done, and then logging into the Arc Data Client VM, the PS launches and then gets hung.

![image](https://github.com/microsoft/azure_arc/assets/11221387/72ab6797-c9c4-4927-8258-33be80ea07e7)

![image](https://github.com/microsoft/azure_arc/assets/11221387/1a0c3cad-5916-4c88-8a64-ea7ff412d89d)

If you wanted to check, I can share the screen - gpillai@microsoft.com

Thanks,
Girish.

**Comment by likamrat** [comment]
Hi @kprpg, the fix for this one is now merged. Feel free to test.
