### ISSUE TITLE
APIM Self Host Extension

### ISSUE THREAD

**Issue by duongthaiha** [microsoft/azure_arc#1974]
**Is your feature request related to a new Jumpstart scenario you would like to contribute?**

The feature can be use for HCIBox or ArcBox please
**Is your feature request related to a problem? Please describe.**

No it is not a problem. The idea is extension of what already available
**Describe the solution you'd like.**

As user I can select an option to provision API management instance with self host gateway so that I can centralise my API control.
This also include example API workload to write to a managed sql instance.

The idea is to be able show in temporary disconnected scenario where user can use API workload with APIM

**Describe alternatives you've considered.**

Alternative can be different APIM product where there self host capability can be deployed. However I want to concentrated on Azure Product

**Additional context.**
![Diagram](https://github.com/microsoft/azure_arc/assets/2048899/82850cc1-32a3-4256-a9a1-593800b8ea34)

I have been able to demonstrate this with manual configuration however it is not fully scripted to be repeatable. However I want to check if this is something can be useful to the team. This is come from a practical use case where the internet connection is not stable.

**Comment by janegilring** [comment]
Thanks for providing this suggestion.

After review this request it has been decided that it makes good sense to create a new scenario for this, and @duongthaiha has agreed to start working on it.

**Comment by duongthaiha** [comment]
Hi This is still being working on please. I can give update in couple days

**Comment by likamrat** [comment]
Closed via #2332 #2316 
https://github.com/Azure/arc_jumpstart_docs/pull/186
https://github.com/Azure/arc_jumpstart_docs/pull/187
https://github.com/Azure/arc_jumpstart_docs/pull/188
https://github.com/Azure/arc_jumpstart_docs/pull/190
https://github.com/Azure/arc_jumpstart_docs/pull/191
https://github.com/Azure/arc_jumpstart_docs/pull/192

**Comment by likamrat** [comment]
Great work @duongthaiha and thank you for your Jumpstart contribution!
