### ISSUE TITLE
Azure Arc on Linux unattended-upgrade package installed with AZCMAGENT

### ISSUE THREAD

**Issue by likamrat** [microsoft/azure_arc#1981]
### Discussed in https://github.com/microsoft/azure_arc/discussions/1769

<div type='discussions-op-text'>

<sup>Originally posted by **KajSoren** April  6, 2023</sup>
Within 24 hours of installing Azure Arc on Linux our internal team noticed an issue regarding Tomcat.  After reviewing the logs, we found that the base installation appears to do the following.  In debian, the **default** configuration for installing recommendations in apt is set to **true**.  Can the script be changed so that packages are not installed/updated/upgraded inadvertently? 

`This is the apt log of the azcmagent install script (install_linux_azcmagent.sh)

Start-Date: 2023-03-28  11:57:06
Commandline: apt install -y software-properties-common
Requested-By:
Install: python3-distro-info:amd64 (0.21, automatic), libpackagekit-glib2-18:amd64 (1.1.12-5, automatic), python3-software-properties:amd64 (0.96.20.2-2, automatic), libgirepository-1.0-1:amd64 (1.58.3-2, automatic), packagekit-tools:amd64 (1.1.12-5, automatic), gir1.2-glib-2.0:amd64 (1.58.3-2, automatic), libglib2.0-bin:amd64 (2.58.3-2+deb10u4, automatic), packagekit:amd64 (1.1.12-5, automatic), python3-dbus:amd64 (1.2.8-3, automatic), python3-gi:amd64 (3.30.4-1, automatic), gir1.2-packagekitglib-1.0:amd64 (1.1.12-5, automatic), unattended-upgrades:amd64 (1.11.2, automatic), libappstream4:amd64 (0.12.5-1, automatic), libyaml-0-2:amd64 (0.2.1-1, automatic), libstemmer0d:amd64 (0+svn585-1+b2, automatic), libgstreamer1.0-0:amd64 (1.14.4-1, automatic), software-properties-common:amd64 (0.96.20.2-2)
End-Date: 2023-03-28  11:57:15

Start-Date: 2023-03-28  11:57:23
Commandline: apt install -y azcmagent
Requested-By:
Install: azcmagent:amd64 (1.28.02260.736)
End-Date: 2023-03-28  11:57:38

Start-Date: 2023-03-29  06:51:48
Commandline: /usr/bin/unattended-upgrade
Upgrade: tzdata:amd64 (2021a-0+deb10u8, 2021a-0+deb10u10)
End-Date: 2023-03-29  06:51:53

software-properties-common package depends on/replaces python3-software-properties which recommends unattended-upgrades

# apt-cache depends software-properties-common
software-properties-common
  Depends: ca-certificates
  Depends: gir1.2-glib-2.0
  Depends: gir1.2-packagekitglib-1.0
  Depends: python-apt-common
  Depends: python3
  Depends: python3-dbus
  Depends: python3-gi
  Depends: python3-software-properties
  Depends: <python3:any>
    python3
  Breaks: <python-software-properties>
  Breaks: python3-software-properties
  Recommends: packagekit
  Replaces: <python-software-properties>
  Replaces: python3-software-properties

# apt-cache depends python3-software-properties
python3-software-properties
  Depends: iso-codes
  Depends: lsb-release
  Depends: python3
  Depends: python3-apt
  Depends: python3-pycurl
  Depends: <python3:any>
    python3
  Recommends: unattended-upgrades
`</div>

**Comment by rpsqrd** [comment]
@KajSoren Thanks for flagging this -- our engineers have reviewed the feedback and are exploring options to avoid pulling in these dependencies with our default install script. I can't promise if/when it will be fixed at this time, but keep an eye out in our release notes for any changes: https://learn.microsoft.com/en-us/azure/azure-arc/servers/agent-release-notes

**Comment by likamrat** [comment]
closing this for now
