### ISSUE TITLE
AKS Edge Essentials single node deployment

### ISSUE THREAD

**Issue by mahomedalid** [microsoft/azure_arc#1991]
**Is your issue related to a Jumpstart scenario, ArcBox, or HCIBox?**

Scenario: https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/aks_hybrid/aks_edge_essentials_single/

**Describe the bug**

While following the tutorial it throws an error in the LoginScript.ps1 step. The error is related to az-cli connectedk8s extension when is trying to do the step "The required pre-checks for onboarding have succeeded.":

**FileNotFoundError: [WinError 2] The system cannot find the file specified**

**To Reproduce**

We were just following the tutorial https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/aks_hybrid/aks_edge_essentials_single/ step by step.

**Expected behavior**

No error

**Have you looked at the Troubleshooting and Logs section?**

This is part of the LoginScript_log.txt

```
Onboarding the AKS Edge Essentials cluster to Azure Arc...

This operation might take a while...

Downloading kubectl client for first time. This can take few minutes...
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues


Downloading helm client for first time. This can take few minutes...
An exception has occured while saving the cluster diagnostic checks pod description in the local machine. Exception: [Wi
nError 2] The system cannot find the file specified

The required pre-checks for onboarding have succeeded.
The command failed with an unexpected error. Here is the traceback:
[WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line
663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line
726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line
697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line
333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.p
y", line 121, in handler
  File "C:\Users\akseeadmin\.azure\cliextensions\connectedk8s\azext_connectedk8s\custom.py", line 336, in create_connect
edk8s
    crd_cleanup_force_delete(kubectl_client_location, kube_config, kube_context)
  File "C:\Users\akseeadmin\.azure\cliextensions\connectedk8s\azext_connectedk8s\custom.py", line 2434, in crd_cleanup_f
orce_delete
    response_helm_delete = Popen(cmd_helm_delete, stdout=PIPE, stderr=PIPE)
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1440, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
```

We actually got a workaround after some troubleshooting. Seems that .azure\cliextensions\connectedk8s\azext_connectedk8s\custom.py is looking for kubectl in a location inside .azure\cliextensions\connectedk8s\kubectl_client but kubectl is located in other location (seems that the scripts used chocolatey to install it). After manually copying kubectl client in the extension where azext_connectedk8s\custom.py is looking for, and executing manually the LoginScript.ps1 everything worked smoothly.

**Comment by lanicolas** [comment]
Hi @mahomedalid 

Thank you for your contribution and using jumpstart. I am hitting the issue just like you and reported [here](https://github.com/Azure/azure-cli/issues/26965) as well. Would you mind sharing where did you copy the file to? I was not able to work around the error as you described so I may be missing something.

**Comment by mahomedalid** [comment]
Thank you @lanicolas, I will verify it soon. Thank you for the PR.

**Comment by mahomedalid** [comment]
@lanicolas confirming it works. Thank you!

![image](https://github.com/microsoft/azure_arc/assets/952392/0c63c432-5bb6-49a9-8c2a-41bb81bce6b9)

**Comment by lanicolas** [comment]
thanks for confirming @mahomedalid closing this issue
