### ISSUE TITLE
Documentation: update link to deployment folder in AKS Edge Essentials multi-node deployment tutorial

### ISSUE THREAD

**Issue by yanichka99** [microsoft/azure_arc#2030]
**Is your issue related to a Jumpstart scenario, ArcBox, or HCIBox?
https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/aks_hybrid/aks_edge_essentials_full/

**Describe the bug**
- In the documentation for the AKS EE multi-node deployment, a link indicating the deployment folder navigates to the parameters.json file and is difficult for the user to see which folder they should navigate to to execute the deployment. This is correct in the AKS EE single node deployment doc. 

**To Reproduce**
1. Go to the Deployment section at https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/aks_hybrid/aks_edge_essentials_full/
2. Click on "deployment folder" in the last bullet point. 
3. See the following: [https://raw.githubusercontent.com/microsoft/azure_arc/main/azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials_full/bicep_template/main.parameters.json](https://raw.githubusercontent.com/microsoft/azure_arc/main/azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials_full/bicep_template/main.parameters.json)

**Expected behavior**
See https://github.com/microsoft/azure_arc/tree/main/azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials_full/bicep_template after clicking on "deployment folder" to allow the user to see what folder they should navigate to to execute the deployment.

**Comment by yanichka99** [comment]
Unsure of how to add the correct documentation label to this issue and https://github.com/microsoft/azure_arc/issues/2031.

**Comment by lanicolas** [comment]
Thanks for your feedback @yanichka99 we are fixing the problem
