### ISSUE TITLE
Jumpstart Agora - saw an error as the AgLogonScript was running

### ISSUE THREAD

**Issue by colinrippeyfinarne** [microsoft/azure_arc#2033]
I deployed the new Agora scenario today.

I ran the deployment and then RDP'd onto the client VM.

As the AgLogonScript was running I noticed an error flash up on the screen, the pertinent part of the log is as follows:

INFO: GitHub repo configuration complete!

[1:58 PM] INFO: Creating Azure IoT resources (Step 5/17)
[1:58 PM] INFO: Create an Azure IoT device for each site
[1:58 PM] INFO: Azure IoT Hub configuration complete!

INFO: Loaded Module 'Az.Kusto'
[1:58 PM] INFO: Configuring L1 virtualization infrastructure (Step 6/17)
[1:58 PM] INFO: Enabling Enhanced Session Mode on Hyper-V host
New-NetNat : You were not connected because a duplicate name exists on the network. If joining a domain, go to System 
in Control Panel to change the computer name and try again. If joining a workgroup, choose another workgroup name.

At C:\Ag\PowerShell\AgLogonScript.ps1:607 char:1
+ New-NetNat -Name $AgConfig.L1SwitchName -InternalIPInterfaceAddressPr ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_NetNat:root/StandardCimv2/MSFT_NetNat) [New-NetNat], CimException
    + FullyQualifiedErrorId : Windows System Error 52,New-NetNat
New-NetNat : You were not connected because a duplicate name exists on the network. If joining a domain, go to System
in Control Panel to change the computer name and try again. If joining a workgroup, choose another workgroup name.

At C:\Ag\PowerShell\AgLogonScript.ps1:607 char:1
+ New-NetNat -Name $AgConfig.L1SwitchName -InternalIPInterfaceAddressPr ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_NetNat:root/StandardCimv2/MSFT_NetNat) [New-NetNat], CimException
    + FullyQualifiedErrorId : Windows System Error 52,New-NetNat

[1:58 PM] INFO: Fetching Windows 11 IoT Enterprise VM image from Azure storage. This may take a few minutes.
[2:00 PM] INFO: Creating Chicago disk.
[2:01 PM] INFO: Creating and configuring Chicago virtual machine.

The deployment did continue and seems to have succeeded but I've not as yet done any testing.

I've attached the log bundle.
[LogsBundle-4uzobs.zip](https://github.com/microsoft/azure_arc/files/12262028/LogsBundle-4uzobs.zip)

**Comment by dkirby-ms** [comment]
I've just tried to repro this with default parameters and default AgConfig.psd1 and did not see this error. 

I did review your logs and I saw the error you mentioned. Did you deploy this with default settings in AgConfig.psd1? 

Did you deploy this off your own fork of the code or off of the main branch in the Jumpstart repo?

**Comment by colinrippeyfinarne** [comment]
HI, I deployed using this repo not a fork.

I've only looked a the first couple of scenarios to test the adx reports etc. and everything seems to work just fine.

I'll try to do the CICD at some point this week and let you know.

The "only" thing I can think of was I used JIT RDP and the first time I tried to login the RDP client gave me an error, I tried again after checking I'd setup Defender for Cloud correctly and the RDP client worked the second time. 

So unless the first login actually succeeded and kicked off the script in the background?

**Comment by colinrippeyfinarne** [comment]
Adding a comment in this issue in case it is somehow related (if you'd prefer I raise a separate issue let me know)

On the Freezer Monitor scenario when viewing the Freezer Monitoring dashboard in ADX I don't see the Site filter:

![image](https://github.com/microsoft/azure_arc/assets/37219358/e6189d36-0725-4137-80b0-5bc47a830fc0)

**Comment by likamrat** [comment]
@colinrippeyfinarne can you please redeploy? @charris-msft just pushed a fix to address the dashboard issue.

**Comment by colinrippeyfinarne** [comment]
I've redeployed and saw no errors so happy at my end.
