### ISSUE TITLE
Azure Jumpstart HCIBOX Bicep Post-deployment template is failing

### ISSUE THREAD

**Issue by WVDAdminTF** [microsoft/azure_arc#2040]
@dkirby-ms 
@mtodd 
@sebassem
@radical 
@sverrejoh 
@alloy 

**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**

https://github.com/microsoft/azure_arc/tree/main/azure_jumpstart_hcibox/bicep

**Describe the bug**

The Azure Jumpstart HCIBOX Bicep Post-deployment template is failing after # - Registering Providers

I have confirmed the Prerequisite as per - https://azurearcjumpstart.io/azure_jumpstart_hcibox/#prerequisites

**To Reproduce**

After 3-4 hours the deployment should complete with the nested VM resources.

 I have the below file in the folders
 
 C:\HCIBox\agentScript
C:\HCIBox\Deploy-AKS.ps1
C:\HCIBox\Deploy-ArcResourceBridge.ps1
C:\HCIBox\Deploy-GitOps.ps1
C:\HCIBox\Deploy-SQLMI.ps1
C:\HCIBox\GetServiceAccountBearerToken.ps1
C:\HCIBox\HCIBox-Config.psd1
C:\HCIBox\HCIBoxLogonScript.ps1
C:\HCIBox\Icons
C:\HCIBox\jumpstart-user-secret.yaml
C:\HCIBox\KeyVault
C:\HCIBox\Logs
C:\HCIBox\New-HCIBoxCluster.ps1
C:\HCIBox\Register-AzSHCI.ps1
C:\HCIBox\SDN
C:\HCIBox\Uninstall-AKS.ps1
C:\HCIBox\Uninstall-ResourceBridge.ps1
C:\HCIBox\VHD
C:\HCIBox\Virtual Machines
C:\HCIBox\wallpaper.png
C:\HCIBox\Windows Admin Center
C:\HCIBox\Logs\Bootstrap.log
C:\HCIBox\Logs\HCIBoxLogonScript.log
C:\HCIBox\Logs\LogInstructions.txt
C:\HCIBox\Logs\LogsBundle-wvdadmintf.zip
C:\HCIBox\Logs\New-HCIBoxCluster.log
C:\HCIBox\SDN\CertHelpers.ps1
C:\HCIBox\SDN\HCIBox-Config.psd1
C:\HCIBox\SDN\NetworkControllerRESTWrappers.ps1
C:\HCIBox\SDN\NetworkControllerWorkloadHelpers.psm1
C:\HCIBox\SDN\SDNExplorer.ps1
C:\HCIBox\SDN\SDNExpress.ps1
C:\HCIBox\SDN\SDNExpressModule.psm1
C:\HCIBox\SDN\SDNExpressUI.psm1
C:\HCIBox\SDN\Single-NC.psd1
C:\HCIBox\VHD\AZSHCI.vhdx
C:\HCIBox\VHD\GUI.vhdx
C:\HCIBox\VHD\livecd.ubuntu-desktop-hyperv.vhdx
C:\HCIBox\VHD\Ubuntu.vhdx
C:\HCIBox\VHD\Ubuntu.vhdx.zip
C:\HCIBox\Windows Admin Center\WindowsAdminCenter.msi 
 

**Environment summary**

The Environment is as per the template, no customization.

**Have you looked at the Troubleshooting and Logs section?**

**Screenshots**

![image](https://github.com/microsoft/azure_arc/assets/84956733/51cab2b9-ac74-48b1-87f0-94576568c58b)
![HCIBOX issue](https://github.com/microsoft/azure_arc/assets/84956733/ad9f6858-3dcc-474f-ad46-34fca45e5486)

**Additional context**
[New-HCIBoxCluster.log](https://github.com/microsoft/azure_arc/files/12287640/New-HCIBoxCluster.log)
[Bootstrap.log](https://github.com/microsoft/azure_arc/files/12287641/Bootstrap.log)
[HCIBoxLogonScript.log](https://github.com/microsoft/azure_arc/files/12287642/HCIBoxLogonScript.log)

![image](https://github.com/microsoft/azure_arc/assets/84956733/4b7afee8-b9d3-4f67-820c-36da7b58330f)
![image](https://github.com/microsoft/azure_arc/assets/84956733/ad5c5b98-3233-4712-80ee-01f6e2e845b3)

Please advice

**Comment by dkirby-ms** [comment]
Please upload the logs zip file found in the C:\HCIBox\Logs folder. We need to see the entire log file to understand where this may have failed.

**Comment by WVDAdminTF** [comment]
> Please upload the logs zip file found in the C:\HCIBox\Logs folder. We need to see the entire log file to understand where this may have failed.
[LogsBundle-wvdadmintf.zip](https://github.com/microsoft/azure_arc/files/12298177/LogsBundle-wvdadmintf.zip)

Zip is attached as requested

**Comment by dkirby-ms** [comment]
I've reviewed the logs. It looks like after first login to the client VM, the session was somehow disconnected before the automation finished running. Then, another connection to the client VM was made and the automation kicked off again and resulted in a corrupted automation run. 

I suggest deleting this deployment and redeploying. After connecting to the client VM for the first time, dont disconnect from it until the automation has fully run its course and the PowerShell windows have closed. You should see the HCIBox desktop background (if not using Azure Bastion) when automation is completed successfully.

**Comment by dkirby-ms** [comment]
It looks like you may also be seeing #2050. Working on a fix for this now.

**Comment by dkirby-ms** [comment]
Any update @WVDAdminTF?

**Comment by WVDAdminTF** [comment]
> Any update @WVDAdminTF?

Hi @dkirby-ms

Thank you for the update will redeploy and confirm if the deployment goes through.

**Comment by WVDAdminTF** [comment]
Hi @dkirby-ms

Still it is failing about an hour after the post-deployment script starts, attached is the zip file
[Logs-18-aug-2023.zip](https://github.com/microsoft/azure_arc/files/12378478/Logs-18-aug-2023.zip)
