### ISSUE TITLE
Windows Server Virtual Machine

### ISSUE THREAD

**Issue by AndreasSemmelmann** [microsoft/azure_arc#2048]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
It is a documentation improvement topic for Jumpstart Scenarios]\[Azure Arc-enabled servers]\[Microsoft Azure]\[Windows Server Virtual Machine]

**Describe the issue or the bug**
It would be useful to have a reference to https://learn.microsoft.com/en-us/azure/azure-arc/servers/plan-evaluate-on-azure-virtual-machine to not run into installation issues (Azure Connected Machine Agent -- Error 1920)

**Comment by lanicolas** [comment]
hi @AndreasSemmelmann thank you for your feedback, we do have an scenario for Azure VMs both for Linux and Windows, you can find them here: https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_servers/azure/

I think these are aligned with what you are looking for, if not please let us know

**Comment by AndreasSemmelmann** [comment]
Hi Laura

My concern is that we could improve our documentation to make it easier for the people to follow along with. I am aware of the scenario but it is needed to do additional configuration to evaluate Azure Arc on a Azure VM. This is what it is described in the dos article I have shared. My intention was to add a reference to the scenario as I spent a few hours to figure it out what was not working for me.

Regards

Andreas Semmelmann
Cloud Solution Architect
M:  +49 151 4401 1970
***@***.***<https://microsoft.com/services>
Support for Mission Critical
Microsoft Services<https://microsoft.com/services> / Customer Experience & Success
W: +49 89 3176 4934
***@***.******@***.***>

#GernePerDu // #CallMeByMyFirstName

Microsoft Deutschland GmbH | Walter-Gropius-Straße 5 | 80807 München
Microsoft – Offizielle Website<https://www.microsoft.com/de-de?ql=2>
Home | News Center Microsoft<https://news.microsoft.com/de-de/>
Datenschutzerklärung von Microsoft – Microsoft-Datenschutz<https://privacy.microsoft.com/de-DE/privacystatement>

Geschäftsführer*in: Dr. Marianne Janik (Vorsitzende), Florian Deter, Benjamin O. Orndorff, Keith Dolliver | Amtsgericht München, HRB 70438

**Comment by lanicolas** [comment]
as discussed the scenario does take into account the required steps to onboard an Azure VM both Linux and Windows. We can close the issue as it was a misunderstanding
