### ISSUE TITLE
Agora - Unable to view Ag-AKS-Staging resources in Azure portal. 

### ISSUE THREAD

**Issue by bpersino** [microsoft/azure_arc#2053]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
Agora

**Describe the issue or the bug**
Unable to view Ag-AKS-Staging resources in Azure portal. 

**To Reproduce**
deploy via azd up via VScode dev containers.

**Expected behavior**
I expect to be able to view Ag-AKS-Staging resources in Azure portal. 

**Environment summary**

**Have you looked at the Troubleshooting and Logs section?**

**Screenshots**
![image](https://github.com/microsoft/azure_arc/assets/12070082/3858ebc0-a1a5-4868-9748-3025473fc1f1)

**Additional context**

**Comment by sebassem** [comment]
Hello @bpersino , thanks for reaching out. This is one of the security capabilites of Azure Kubernetes Service , you would need to grant yourself the right authorization to view the different AKS resources in the Azure portal following this [guidance](https://learn.microsoft.com/azure/azure-arc/kubernetes/cluster-connect?tabs=azure-cli%2Cagent-version)

**Comment by sebassem** [comment]
Hello @bpersino , thanks for reaching out. This is one of the security capabilities of Azure Kubernetes Service , you would need to grant yourself the right authorization to view the different AKS resources in the Azure portal following this [guidance](https://learn.microsoft.com/azure/azure-arc/kubernetes/cluster-connect?tabs=azure-cli%2Cagent-version)

**Comment by bpersino** [comment]
@sebassem  Understood. I had assumed the bicep deployment would automate this step. Now that I'm aware it doesn't, I've managed to get it working. You can close the case, and thank you for your support.

**Comment by sebassem** [comment]
> @sebassem Understood. I had assumed the bicep deployment would automate this step. Now that I'm aware it doesn't, I've managed to get it working. You can close the case, and thank you for your support.

Thank you for the confirmation, we will add a note in the readme for this
