### ISSUE TITLE
AKS Edge Essentials single node deployment failure on Helm and Arc Agent installation

### ISSUE THREAD

**Issue by renato-marciano** [microsoft/azure_arc#2059]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**

https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/aks_hybrid/aks_edge_essentials_single/#post-deployment

**Describe the issue or the bug**

During the logon script execution, it fails to install helm and arc agent. As a result the kube-aad-proxy pod's status "ContainerCreating". 

**To Reproduce**

```log
....
The required pre-checks for onboarding have succeeded.
Azure resource provisioning has begun.
Azure resource provisioning has finished.
'Custom-locations' feature couldn't be enabled on this cluster as the pre-requisite registration of 'Microsoft.ExtendedL
ocation' was not met. More details for enabling this feature later on this cluster can be found here - https://aka.ms/En
ableCustomLocations
Starting to install Azure arc agents on the Kubernetes cluster.
Please check if the azure-arc namespace was deployed and run 'kubectl get pods -n azure-arc' to check if all the pods ar
e in running state. A possible cause for pods stuck in pending state could be insufficient resources on the kubernetes c
luster to onboard to arc.
**Unable to install helm release: Error: timed out waiting for the condition**

Create Azure Monitor for containers Kubernetes extension instance

Ignoring name, release-namespace and scope parameters since microsoft.azuremonitor.containers only supports cluster scop
e and single instance of this extension.
....
```

4. Open a new cmd terminal after LogonScript is done.
5. Run `kubectl describe pods -l app.kubernetes.io/component=kube-aad-proxy -n azure-arc` 
6. Scroll down to events and see Error -->

```kubectl
Events:
  Type     Reason       Age                    From     Message
  ----     ------       ----                   ----     -------
  Warning  FailedMount  38m (x6 over 136m)     kubelet  Unable to attach or mount volumes: unmounted volumes=[kube-aad-proxy-tls], unattached volumes=[kube-api-access-6895q varlog varlibdockercontainers fluentbit-clusterconfig kube-aad-proxy-tls]: timed out waiting for the condition
  Warning  FailedMount  34m (x11 over 145m)    kubelet  Unable to attach or mount volumes: unmounted volumes=[kube-aad-proxy-tls], unattached volumes=[fluentbit-clusterconfig kube-aad-proxy-tls kube-api-access-6895q varlog varlibdockercontainers]: timed out waiting for the condition
  Warning  FailedMount  13m (x10 over 147m)    kubelet  Unable to attach or mount volumes: unmounted volumes=[kube-aad-proxy-tls], unattached volumes=[varlog varlibdockercontainers fluentbit-clusterconfig kube-aad-proxy-tls kube-api-access-6895q]: timed out waiting for the condition
  Warning  FailedMount  9m27s (x77 over 149m)  kubelet  MountVolume.SetUp failed for volume "kube-aad-proxy-tls" : secret "kube-aad-proxy-certificate" not found
  Warning  FailedMount  4m43s (x20 over 143m)  kubelet  Unable to attach or mount volumes: unmounted volumes=[kube-aad-proxy-tls], unattached volumes=[kube-aad-proxy-tls kube-api-access-6895q varlog varlibdockercontainers fluentbit-clusterconfig]: timed out waiting for the condition
```

**Expected behavior**

Helm installed on the Windows VM and kubectl-aad-proxy pod in "Running" state

**Environment summary**

azure-cli: "2.51.0"
Params provided in az deployment cli script (same as defaults):
kubernetesDistribution: "k3s"
vmSize: "Standard_D8s_v3"

**Have you looked at the Troubleshooting and Logs section?**

**Screenshots**

**Additional context**

This has not been duplicated yet. My colleagues have tried the Jumpstart Docs and did not face the same issue.

**Comment by lanicolas** [comment]
hi @renato-marciano 

thank you for using jumpstart

I tried the scenario 4 times and I was not able to reproduce the issue. I do get an exception that I will forward internally, but the pods run correctly, the cluster is properly enabled. 


Downloading helm client for first time. This can take few minutes...
An exception has occured while saving the cluster diagnostic checks pod description in the local machine. Exception: [Wi
nError 2] The system cannot find the file specified

PS C:\Users\arcdemo> kubectl get pods -n azure-arc
NAME                                         READY   STATUS    RESTARTS   AGE
cluster-metadata-operator-7895c564fb-g8smr   2/2     Running   0          4m56s
clusterconnect-agent-5bdd9865ff-csp6q        3/3     Running   0          4m55s
clusteridentityoperator-7b98b7bdd4-2vzh8     2/2     Running   0          4m55s
config-agent-566b79b5bc-xxtfl                2/2     Running   0          4m55s
controller-manager-5d5d6c7f78-2jx78          2/2     Running   0          4m56s
extension-events-collector-595f487cf-xsq9q   2/2     Running   0          4m55s
extension-manager-78bfc6cd5d-xwq6j           3/3     Running   0          4m55s
flux-logs-agent-d497655f-m5wj9               1/1     Running   0          4m56s
kube-aad-proxy-77f7d66489-wqfs8              2/2     Running   0          4m56s
metrics-agent-694b86454c-z5krx               2/2     Running   0          4m56s
resource-sync-agent-869d58b6b7-lb6v9         2/2     Running   0          4m55s

I see in your traces that custom location is being enabled, did you make any changes to the script? we do not enable this feature on the automation, so I am trying to understand where the message comes from.

**Comment by renato-marciano** [comment]
I did not change anything on the script. Where is it possible to enable the feature "Custom Location"?

**Comment by lanicolas** [comment]
it is not part of the automation. But I do see this: 'Custom-locations' feature couldn't be enabled on this cluster as the pre-requisite registration of 'Microsoft.ExtendedLocation' was not met.

would you mind checking if you have the Microsoft.ExtendedLocation provider enabled in your subscription?

**Comment by renato-marciano** [comment]
I have registered the Custom locations to my subscription and retried. The arc agents were installed and kube-aad-pods are now running. I am although unsure if registering Custom Locations was the fix for the helm issue or the pod's not being able to run since the logs as shown below indicate that the 'Custom-locations' still was not enabled.

```
The required pre-checks for onboarding have succeeded.
Azure resource provisioning has begun.
Azure resource provisioning has finished.
Unable to fetch the Object ID of the Azure AD application used by Azure Arc service. Unable to enable the 'custom-locati
ons' feature. Insufficient privileges to complete the operation.
Starting to install Azure arc agents on the Kubernetes cluster.
{
  "agentPublicKeyCertificate": "xxxxxx",
  "agentVersion": null,
  "connectivityStatus": "Connecting",
```

![image](https://github.com/microsoft/azure_arc/assets/7683165/3bd751eb-e607-4c31-a460-ba438efbbaf5)

**Comment by renato-marciano** [comment]
I unregistered Custom Locations provider but could not reproduce my error. All the pods are successfully running and arc agent is installed even with the original error on Custom Locations.

```
The required pre-checks for onboarding have succeeded.
Azure resource provisioning has begun.
Azure resource provisioning has finished.
Unable to fetch the Object ID of the Azure AD application used by Azure Arc service. Unable to enable the 'custom-locati
ons' feature. Insufficient privileges to complete the operation.
Starting to install Azure arc agents on the Kubernetes cluster.
{
  "agentPublicKeyCertificate": "xxxxx",
  "agentVersion": null,
  "connectivityStatus": "Connecting",
```
