### ISSUE TITLE
Agora - AGLogonScript Errors Prevent Environment Setup

### ISSUE THREAD

**Issue by bpersino** [microsoft/azure_arc#2064]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
https://azurearcjumpstart.io/azure_jumpstart_ag/contoso_supermarket/deployment/

**Describe the issue or the bug**
Because it's expensive to keep this environment online, I often use "azd up" and "azd down". The deployment finishes successfully but the AGLogonScript inside the VM errors out.

**To Reproduce**
1) azd up
2) RDP into the VM-Client to start AGLogonScript.ps1
3) check the bottom of the AGLogonScript.log and see the errors.

**Expected behavior**
I expect the environment to be setup correctly. I can tell the run once PowerShell script AGLogonScript  failed since the background image didn't change in the VM.

**Environment summary**
I deployed the environment using github codespace with dev containers running "azd up".  The deployment was successful, it's the PowerShell script that had issues.

**Have you looked at the Troubleshooting and Logs section?**
Here are the last lines of AGLogonScript.log

[3:40 PM] INFO: Waiting for AKS Edge Essentials kubeconfig to be available on Seattle.
[3:40 PM] INFO: Seattle's kubeconfig is ready - copying over config-Seattle
[3:40 PM] ERROR: Kubeconfig on Seattle is corrupt. This error is unrecoverable. Exiting.
PS>TerminatingError(): "System error."

Here is the log for the VM-Client
[AgLogonScript.log](https://github.com/microsoft/azure_arc/files/12371593/AgLogonScript.log)

Here are the L1 log Deployment logs for Seattle VM
[Deployment.zip](https://github.com/microsoft/azure_arc/files/12371633/Deployment.zip)

**Screenshots**
Not applicable as the attached log files show the error.

**Additional context**
n/a

**Comment by likamrat** [comment]
@bpersino please follow the Issue templates and provide more details!

**Comment by bpersino** [comment]
@likamrat I have updated the issue using the provided template.

**Comment by sebassem** [comment]
@bpersino  Thanks for submitting this issue. Can you try a new clean deployment and let us know if you face the same issue? We are working to add more optimizations to overcome the error you reported.

**Comment by bpersino** [comment]
I did two new deployments today and they both were successful.  So, whatever changed fixed the problem.  Thank you.
