### ISSUE TITLE
Azure Arc ML Setup

### ISSUE THREAD

**Issue by akshata29** [microsoft/azure_arc#2072]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
Yes - Azure Arc ML Jumpstart scenario -https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_ml/aks/aks_blob_mnist_arm_template/

**Describe the issue or the bug**

Artifact deployment is successful, but the post deployment script is failing with the error.
<img width="733" alt="error" src="https://github.com/microsoft/azure_arc/assets/18509807/2083fa5a-04d3-4167-98a3-3505c8cff0fa">

**To Reproduce**
Follow through the documentation until opening up the VM and the Post deployment script is failing.

**Expected behavior**
Successful deployment of the jumpstart

**Environment summary**

az cli 2.51.0
connectedk8s 1.4.0
k8s-extension 1.4.2
python 3.10.10

**Comment by danielsegan** [comment]
Hi. Any update here. My deployment is failing with the same issue.

**Comment by dkirby-ms** [comment]
Hi @danielsegan,

We are in the process of refactoring this entire scenario which will address the outstanding issues. Please stay tuned.
