### ISSUE TITLE
SQL Managed Instance ARM Template on Azure Red Hat Openshift, AMA-logs pods failing, Data controller pods not coming up.

### ISSUE THREAD

**Issue by warrendt** [microsoft/azure_arc#2077]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?** 

This issue is related to the Azure Red Hat OpenShift deployment with SQL MI.

**Describe the issue or the bug**
The issue occurs when deploying the data controller for the custom location. The data controller gets stuck in the "creating resource state"
![CleanShot 2023-08-30 at 09 38 03](https://github.com/microsoft/azure_arc/assets/193215/7944dabf-8cd3-4351-9792-e789b39d9082)
This occurs after the creation of the custom location.
The containers for the namespace are not coming up correctly. 
![CleanShot 2023-08-30 at 10 22 22](https://github.com/microsoft/azure_arc/assets/193215/f76652e2-fa84-49b9-ad47-84f6779feda0)

I see that the ama-logs containers are also failing. 
![CleanShot 2023-08-30 at 10 23 09](https://github.com/microsoft/azure_arc/assets/193215/eae29f83-7c16-464c-87ab-2c51c47c67b2)

![CleanShot 2023-08-30 at 13 30 26](https://github.com/microsoft/azure_arc/assets/193215/0efd1015-d13a-426d-8e8c-65cc1a654cf6)

I am unsure why these pods are failing, I cannot see the logging information here either. 

With regards to the data controller, I am seeing this in the logs 
The required pre-checks for onboarding have succeeded.
Azure resource provisioning has begun.
Azure resource provisioning has finished.
Unable to fetch the Object ID of the Azure AD application used by Azure Arc service. Unable to enable the 'custom-locati
ons' feature. Insufficient privileges to complete the operation.

I am using an owner role on the subscription, same I used for ArcBox, so it should work, its more than the required roles in the documentation.

az ad sp create-for-rbac -n "<Unique SP Name>" --role "Contributor" --scopes /subscriptions/$subscriptionId
az ad sp create-for-rbac -n "<Unique SP Name>" --role "Security admin" --scopes /subscriptions/$subscriptionId
az ad sp create-for-rbac -n "<Unique SP Name>" --role "Security reader" --scopes /subscriptions/$subscriptionId
az ad sp create-for-rbac -n "<Unique SP Name>" --role "Monitoring Metrics Publisher" --scopes /subscriptions/$subscriptionId

![image](https://github.com/microsoft/azure_arc/assets/193215/9692a6e6-34de-44f2-b87a-a078ddc805ad)

I have tried deploying into two separate locations. West Europe and North Europe. 
I have tried deploying with failover and without failover group for MI.
I have also disabled PostgreSQL part of the deployment as well. 

**To Reproduce**

I deploy the template using the following options in the parameter file, I deploy using the az CLI to deploy the ARM template. 

    },
    "windowsAdminUsername": {
      "value": "wadutoit-admin"
    },
    "windowsAdminPassword": {
      "value": "ArcPassword123!!"
    },
    "logAnalyticsWorkspaceName": {
      "value": "wadutoit-aro-la"
    },
    "deploySQLMI": {
      "value": true
    },
    "SQLMIHA": {
      "value": false
    },
    "deployPostgreSQL": {
      "value": false
    },
    "bastionHostName": {
      "value": "Arc-Data-Demo-Bastion"
    },
    "deployBastion": {
      "value": false
    },

Once template is deployed, you login to the Arc-Data-Client
Let the login script run and it never completes. 

**Expected behavior**
Expected for the script to complete and deploy the ARO cluster with custom location, data controller, and SQL MI. 

**Environment summary**
AZ CLI is up to date. Repo was synced about 2 weeks ago. However the template command refers to the github repo directly. its only the parameter file that is local. 

az group create --name wadutoit-aro-demo-rg --location northeurope
az deployment group create \
--resource-group wadutoit-aro-demo-rg \
--name wadutoit-aro-demo \
--template-uri https://raw.githubusercontent.com/microsoft/azure_arc/main/azure_arc_data_jumpstart/aro/ARM/azuredeploy.json \
--parameters azuredeploy.parameters.json

It also seems that the created log analytics workspace is not being used for the deployment ? 
![CleanShot 2023-08-30 at 13 37 09](https://github.com/microsoft/azure_arc/assets/193215/b590307f-2be9-4542-97b3-fdd635b15ee1)

From the logs 

Enabling Container Insights cluster extensions
Ignoring name, release-namespace and scope parameters since microsoft.azuremonitor.containers only supports cluster scop
e and single instance of this extension.
Defaulting to extension name 'azuremonitor-containers' and release-namespace 'azuremonitor-containers'
(ExtensionOperationFailed) The extension operation failed with the following error:  Error: [ InnerError: [Helm installa
tion failed : Timed out waiting for the resource to come to a ready/completed stateDaemonSet is not ready: kube-system/a
ma-logs. 0 out of 5 expected pods are ready : Recommendation Please contact Microsoft support for further inquiries : In
nerError [release azuremonitor-containers failed, and has been uninstalled due to atomic being set: timed out waiting fo
r the condition]]] occurred while doing the operation : [Create] on the config.
Code: ExtensionOperationFailed
Message: The extension operation failed with the following error:  Error: [ InnerError: [Helm installation failed : Time
d out waiting for the resource to come to a ready/completed stateDaemonSet is not ready: kube-system/ama-logs. 0 out of
5 expected pods are ready : Recommendation Please contact Microsoft support for further inquiries : InnerError [release
azuremonitor-containers failed, and has been uninstalled due to atomic being set: timed out waiting for the condition]]]
 occurred while doing the operation : [Create] on the config.

**Have you looked at the Troubleshooting and Logs section?**
There is no troubleshooting section for ARO and the pods failing 

**Screenshots**
Screenshots have been added inline.

**Additional context**

Please find the logs below. 

[Logs.zip](https://github.com/microsoft/azure_arc/files/12475267/Logs.zip)

**Comment by sebassem** [comment]
@warrendt Thanks for submitting this issue. It has now been resolved
