### ISSUE TITLE
Error while registering HCI-Box Windows Admin Center with Azure

### ISSUE THREAD

**Issue by khq5801** [microsoft/azure_arc#2088]
Hi, hope you are doing well.

To use Azure Services with Windows Admin Center, I was trying to register Windows Admin Center with Azure in hciboxcluster.jumpstart.local (Image1), after entering the AppID when I am trying to Sign into Azure, I encountered an error stating - id_token is not enabled for the application (Image2)
![Image1](https://github.com/microsoft/azure_arc/assets/84763417/03441367-4e57-490d-b1ff-7db68cd98c27)
![Image2](https://github.com/microsoft/azure_arc/assets/84763417/afc8c2c9-d53a-47b7-8afc-49fa8788a06a)
). 

Kindly check and do the needful.

**Comment by dkirby-ms** [comment]
Registering WAC is not a supported scenario for HCIBox. We'll add a note to make this more explicit.
