### ISSUE TITLE
Copy-VMFile failed due to "The device is not ready for use".

### ISSUE THREAD

**Issue by ebibibi** [microsoft/azure_arc#2091]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
[Agora](https://azurearcjumpstart.io/azure_jumpstart_ag/contoso_supermarket/)

**Describe the issue or the bug**
After logon to the Agora-Client-VM, script is runnning and error is happen during the process.
failed to copy the source file 'C:\Windows\System32\WindowsPowerShell\v1.0\Profile.ps1' to the destination

**To Reproduce**
just do deployment steps in https://azurearcjumpstart.io/azure_jumpstart_ag/contoso_supermarket/deployment/.
log into the Agora-Client-VM,

**Expected behavior**
no error.
'C:\Windows\System32\WindowsPowerShell\v1.0\Profile.ps1' can copy to the guest vm.

**Environment summary**
vm environment that just created by code.

**Have you looked at the Troubleshooting and Logs section?**
error:
[4:30 AM] INFO: Creating and configuring Dev virtual machine.
Copy-VMFile : Failed to initiate copying files to the guest.
Failed to copy the source file 'C:\Windows\System32\WindowsPowerShell\v1.0\Profile.ps1' to the destination
'C:\Deployment\Profile.ps1' in the guest.
'Dev' failed to initiate copying files to the guest: The device is not ready for use. (0x800710DF). (Virtual machine
ID 63E71B62-4C5C-4467-A2E1-62377AE28C31)
'Dev' failed to copy the source file 'C:\Windows\System32\WindowsPowerShell\v1.0\Profile.ps1' to the destination
'C:\Deployment\Profile.ps1' in the guest: The device is not ready for use. (0x800710DF). (Virtual machine ID
63E71B62-4C5C-4467-A2E1-62377AE28C31)
At C:\Ag\PowerShell\AgLogonScript.ps1:653 char:5
+     Copy-VMFile $VM -SourcePath "$PsHome\Profile.ps1" -DestinationPat ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-VMFile], VirtualizationException
    + FullyQualifiedErrorId : OperationFailed,Microsoft.HyperV.PowerShell.Commands.CopyVMFile

source:
AgLogonScript.ps1:653

Start-Sleep -Seconds 20
# Create an array with VM names
$VMnames = (Get-VM).Name
foreach ($VM in $VMNames) {
    Copy-VMFile $VM -SourcePath "$PsHome\Profile.ps1" -DestinationPath "C:\Deployment\Profile.ps1" -CreateFullPath -FileSource Host -Force
}

**Screenshots**

**Additional context**
script should wait more longer or repeat process until file copy is success.
just re-run the code, it succeeded.

**Comment by janegilring** [comment]
@ebibibi Thanks for reporting the issue. We have now added error handling and retry-logic for Copy-VMFile in the Agora logonscript.
