### ISSUE TITLE
ERROR: Kubeconfig on Chicago is corrupt.

### ISSUE THREAD

**Issue by ebibibi** [microsoft/azure_arc#2095]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
Agora Contoso Supermarket
[Contoso Supermarket](https://azurearcjumpstart.io/azure_jumpstart_ag/contoso_supermarket/)

**Describe the issue or the bug**
AgLogonScript.ps1 failed with the error below.
ERROR: Kubeconfig on Chicago is corrupt. This error is unrecoverable. Exiting.

**To Reproduce**
just deploy as documented.

**Expected behavior**
kubeconfig file is successfully copied to the Chicago vm.

**Environment summary**
deployed by IaC.

**Have you looked at the Troubleshooting and Logs section?**
[5:21 AM] INFO: Installing AKS Edge Essentials (Step 7/17)
[5:21 AM] INFO: Rebooting Chicago.
[5:21 AM] INFO: Rebooting Dev.
[5:21 AM] INFO: Rebooting Seattle.
[5:21 AM] INFO: Sleeping for three (3) minutes to allow for AKS EE installs to complete.
[5:24 AM] INFO: Chicago's kubeconfig is ready - copying over config-Chicago
[5:24 AM] ERROR: Kubeconfig on Chicago is corrupt. This error is unrecoverable. Exiting.

**Screenshots**
![image](https://github.com/microsoft/azure_arc/assets/322947/b4bd10ca-1a88-4d3a-8898-6a504722d65f)

**Additional context**
This issue is occur below in AgLogonScript.ps1

```
#####################################################################
# Monitor until the kubeconfig files are detected and copied over
#####################################################################
$elapsedTime = Measure-Command {
    foreach ($VMName in $VMNames) {
        $path = "C:\Users\Administrator\.kube\config-" + $VMName.ToLower()
        $user = $AgConfig.L1Username
        [securestring]$secStringPassword = ConvertTo-SecureString $AgConfig.L1Password -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential($user, $secStringPassword)
        Start-Sleep 5
        while (!(Invoke-Command -VMName $VMName -Credential $credential -ScriptBlock { Test-Path $using:path })) {
            Start-Sleep 30
            Write-Host "[$(Get-Date -Format t)] INFO: Waiting for AKS Edge Essentials kubeconfig to be available on $VMName." -ForegroundColor Gray
        }

        Write-Host "[$(Get-Date -Format t)] INFO: $VMName's kubeconfig is ready - copying over config-$VMName" -ForegroundColor DarkGreen
        $destinationPath = $Env:USERPROFILE + "\.kube\config-" + $VMName
        $s = New-PSSession -VMName $VMName -Credential $credential
        Copy-Item -FromSession $s -Path $path -Destination $destinationPath
        $file = Get-Item $destinationPath
        if ($file.Length -eq 0) {
            Write-Host "[$(Get-Date -Format t)] ERROR: Kubeconfig on $VMName is corrupt. This error is unrecoverable. Exiting." -ForegroundColor White -BackgroundColor Red
            exit 1
        }
    }
}

```
$destinationPath = $Env:USERPROFILE + "\.kube\config-" + $VMName

I checked destinationPath. there is a file named config-Chicago but it's size is 0kb.
![image](https://github.com/microsoft/azure_arc/assets/322947/45be2f1d-9c15-4294-8ba2-8bfb252bff16)

Actually, length of Chicago vm's C:\Users\Administrator\.kube\config-chicago is 0.
![image](https://github.com/microsoft/azure_arc/assets/322947/f684de45-0e09-4493-bd1a-9daaa7cc6036)

**Comment by ebibibi** [comment]
I did deploy again from scratch with latest repogitory, this issue doesn't happened.
This issue might already resolved with latest repogitory.

**Comment by sebassem** [comment]
@ebibibi  thanks for submitting this issue. Glad to hear that a redeployment solved the issue. We are working to investigate this problem to prevent it from happening again
