### ISSUE TITLE
AgLogonScript is not finish. "Test-NetConnection - 172.20.1.91:6443" is not finish.

### ISSUE THREAD

**Issue by ebibibi** [microsoft/azure_arc#2096]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
Agora Contoso Supermarket
[Contoso Supermarket](https://azurearcjumpstart.io/azure_jumpstart_ag/contoso_supermarket/)

**Describe the issue or the bug**
AgLogonScript.ps1 didn't finish over 20 hours.

It seemd wait response from 172.20.1.91:6443

```
Test-NetConnection - 172.20.1.91:6443
Attempting TCP connect
Waiting for response
```

**To Reproduce**
just deploy as documented.

**Expected behavior**
deployment is successfully finish.

**Environment summary**
deployed by IaC.

**Have you looked at the Troubleshooting and Logs section?**
INFO: [3:28 AM] INFO: Creating GitOps config for config-sensormonitor on Ag-ArcK8s-Seattle-e0c40
INFO: [3:29 AM] INFO: GitOps configuration config-supermarket-ai is ready on Ag-ArcK8s-Dev-e0c40
INFO: [3:29 AM] INFO: Creating GitOps config for config-supermarket-queue-frontend on Ag-ArcK8s-Dev-e0c40
INFO: [3:30 AM] INFO: GitOps configuration config-supermarket-queue-frontend is ready on Ag-ArcK8s-Dev-e0c40
INFO: [3:30 AM] INFO: Creating GitOps config for config-sensormonitor on Ag-ArcK8s-Dev-e0c40
INFO: [3:31 AM] INFO: GitOps configuration config-sensormonitor is ready on Ag-AKS-Staging
INFO: [3:31 AM] INFO: GitOps configuration config-sensormonitor is ready on Ag-ArcK8s-Dev-e0c40

**Screenshots**
![image](https://github.com/microsoft/azure_arc/assets/322947/3f78851f-e473-491d-abf8-683b0bc5429c)

**Additional context**
"Test-NetConnection 172.20.1.91 -Port 6443" is succeeded in another PowerShell console.
![image](https://github.com/microsoft/azure_arc/assets/322947/665ea3be-ebd7-49dc-9ab0-381019a8982f)

**Comment by ebibibi** [comment]
I removed resourcegroup and re-run deployment.
deployment is finished successfully.

This issue looks like timing issue.

**Comment by sebassem** [comment]
Hi @ebibibi Thanks for submitting this issue. The reason this happened to you is sometimes the GitOps configuration takes time to deploy the applications to the clusters so you see the test-netconnection output hangning but actually there is work in the background to redeploy the failed applications.
