### ISSUE TITLE
Azure Data Explorer reports doesn't show data. Principal xxx is not authorized to read database 'Oders'.

### ISSUE THREAD

**Issue by ebibibi** [microsoft/azure_arc#2098]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
Agora
Data pipeline and reporting across cloud and edge for store orders
https://azurearcjumpstart.io/azure_jumpstart_ag/contoso_supermarket/data_pos/

**Describe the issue or the bug**
Azure Data Explorer reports doesn't show data.

**To Reproduce**
Proceed steps in a document below by MSA account.
https://azurearcjumpstart.io/azure_jumpstart_ag/contoso_supermarket/data_pos/

**Expected behavior**
Azure Data Explorer reports show data.

**Environment summary**
N/A

**Have you looked at the Troubleshooting and Logs section?**
Yes

**Screenshots**
![image](https://github.com/microsoft/azure_arc/assets/322947/d8fdbd09-19e2-4ffa-b56c-9a0ea2bd3256)

the user deployed environment is added as database admin.
![image](https://github.com/microsoft/azure_arc/assets/322947/4e4b31d2-c974-43cf-849b-5eaae8714700)

same user can query to the database in Query in Azure Management Portal.
![image](https://github.com/microsoft/azure_arc/assets/322947/1ac07f2a-7cbf-405e-84b1-c1f68d4d21ed)

**Additional context**
I added another organization **guest** user to access rights but same result.

I tried by another organization user which created in the same AAD tenant that subscription trusts and the user can see report **without error**.

Is guest user is not allowed to access data through Azure Data Explorer dashboards?
If so, document should mention about it.

**Comment by chintalavr** [comment]
@ebibibi, can you please confirm exact Azure RBAC permissions granted to the guest user at the subscription or resource group or ADX resource?

**Comment by chintalavr** [comment]
We are able to reproduce this error. This user type (using personal email to create Azure subscription and Azure AD tenant) scenario hasn't been tested yet. Currently investigating to find a solution and fix this issue. As a workaround, please create member account in Azure AD tenant and grant subscription owner permissions to continue using Jumpstart Agora.
