### ISSUE TITLE
The hcibox azd provision scripts is checking DSv5 cores quota instead of ESv5 cores (As documented).

### ISSUE THREAD

**Issue by dickeyf** [microsoft/azure_arc#2100]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
HCIBox

**Describe the issue or the bug**
When I type "azd up" to deploy azure_jumpstart_hcibox, I get a "There is not enough VM capacity in the eastus2 region to deploy the Jumpstart environment." error despite the fact that I have the necessary resources:
```
az vm list-usage --location eastus2 --output table | grep ESv5
Standard ESv5 Family vCPUs                0               64

az vm list-usage --location eastus2 --output table | grep "Total Regional vCPUs"
Total Regional vCPUs                      139             900
```

**To Reproduce**
To reproduce, you'll need to have enough quota for "Standard ESv5 Family vCPUs" and "Total Regional vCPUs".  But not have quotas for "Standard DSv5".  The script will check for "Standard DSv5", instead of esv5 and fail..

**Expected behavior**
I expect this check to pass when I do have enough quotas

**Comment by dickeyf** [comment]
See : https://github.com/microsoft/azure_arc/blob/b150383481cb61d056e6b5f1b0a6bbae1bd93397/azure_jumpstart_hcibox/scripts/preprovision.ps1#L102

Is where the wrong check is being done.

**Comment by dickeyf** [comment]
I patched the code so it checks for e32s v5 instead and it unblocked me.

**Comment by dkirby-ms** [comment]
Good catch, we will patch this.
