### ISSUE TITLE
Deploy-ArcResourceBridge.ps1 fails to install the arcappliance extension

### ISSUE THREAD

**Issue by dickeyf** [microsoft/azure_arc#2102]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
HCIBox related, when ArcResourceBridge is enabled.

**Describe the issue or the bug**
I see this error much later, when arc bridge is being configured:

```
ERROR: Version '0.2.29' not found for extension 'arcappliance'
    + CategoryInfo          : NotSpecified: (ERROR: Version ... 'arcappliance':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
    + PSComputerName        : AzSHOST1
ERROR: Version '0.2.29' not found for extension 'arcappliance'
    + CategoryInfo          : NotSpecified: (ERROR: Version ... 'arcappliance':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
    + PSComputerName        : AzSHOST1
``` 

It happens twice, for each AzSHOST1 and AzSHOST2

I checked, as the latest is now 0.2.33.  I tested 0.2.30 onward, and 0.2.31 is the oldest available version.  I think the script needs to install the latest, or, get updated as older versions are pulled.

Then, I see logs indicating that deployment is ongoing (which seems to be helm chart deployment in a cluster), but some failure occurs about a timeout during deployment (Which I cannot be sure whether is caused by the errors I report here as bug): 
```
2023-09-07T11:37:30-07:00	INFO	successfully created/upgraded KVA Image Operator!
2023-09-07T11:37:30-07:00	INFO	core: Waiting for deployment 'kvaio-controller-manager' to be ready
2023-09-07T11:38:11-07:00	INFO	azurestackhciProvider: PerformPostOperations
2023-09-07T11:38:11-07:00	INFO	azurestackhciProvider: Waiting for pod 'AzureStackHCI Provider' to be ready...
2023-09-07T11:38:24-07:00	INFO	Creating AutoScalerProfile default
2023-09-07T11:38:24-07:00	INFO	Successfully created AutoScalerProfile default
2023-09-07T11:38:24-07:00	INFO	core: Waiting for Cluster '77aad1cebb175c58586c84667441f3c221ddbfa4b86c2' to be provisioned
{"file":"/mnt/vss/_work/1/s/pkg/appliance/client.go:99","func":"Deploy","level":"error","msg":"Error details, Provider: azurestackhci, Command: Deploy, Msg: Error while deploying appliance via kva, ErrorCode: DeployKvaError, Error: {\n  \"code\": \"ContextError\",\n  \"message\": \"Context timed out during phase 'Deploying'\"\n }","time":"2023-09-07T12:01:04-07:00"}
ERROR: {
ERROR: {
"errorCode": "ContextError",
"errorCode": "ContextError",
"errorResponse": "{\n\"message\": \"Context timed out during phase 'Deploying'\"\n}"
"errorResponse": "{\n\"message\": \"Context timed out during phase 'Deploying'\"\n}"
}
}
```

**To Reproduce**
I simply deploy HCIBox, by default ArcResourceBridge gets deployed.  I see those two error messages and the script waits indefinitely for resource bridge to deploy:
```
ERROR: (ResourceNotFound) The Resource 'Microsoft.ResourceConnector/appliances/HCIBox-ResourceBridge' under resource 
group 'fdickey-hci-box-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
ERROR: (ResourceNotFound) The Resource 'Microsoft.ResourceConnector/appliances/HCIBox-ResourceBridge' under resource
group 'fdickey-hci-box-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
INFO: Waiting on Arc Resource Bridge deployment to complete...
D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\cryptography/hazmat/backends/openssl/backend.py:27:
 UserWarning: You are using cryptography on a 32-bit Python on a 64-bit Windows Operating System. Cryptography will be 
significantly faster if you switch to using a 64-bit Python.
    + CategoryInfo          : NotSpecified: (D:\a\_work\1\s\... 64-bit Python.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
    + PSComputerName        : AzSHOST1
D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\cryptography/hazmat/backends/openssl/backend.py:27
: UserWarning: You are using cryptography on a 32-bit Python on a 64-bit Windows Operating System. Cryptography will
be significantly faster if you switch to using a 64-bit Python.
    + CategoryInfo          : NotSpecified: (D:\a\_work\1\s\... 64-bit Python.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
    + PSComputerName        : AzSHOST1
```
  

**Expected behavior**
I expect no error logs (I think there's a problem if any show up).  And also, the deployment to complete eventually.

**Comment by dickeyf** [comment]
I manually opened an interactive session with the VM using `Enter-PSSession`, and then reran that script using `0.2.31` instead.  This time, I see success for the `az arcappliance deploy hci` command.  So it seems my issues were actually caused by this.

**Comment by jjindrich** [comment]
Failing for me as well. I tried to change extension to version 0.2.31 or latest, still fails.
Hangs in deployment process:
2023-09-08T03:01:27-07:00       INFO    core: Waiting for Cluster 'e6ff62640e4e4c14a7bd34a7711d20ea78af5a9ab5c5c' to be provisioned
{"file":"/mnt/vss/_work/1/s/pkg/appliance/client.go:99","func":"Deploy","level":"error","msg":"Error details, Provider: azurestackhci, Command: Deploy, Msg: Error while deploying appliance via kva, ErrorCode: DeployKvaError, Error: {\n  \"code\": \"ContextError\",\n  \"message\": \"Context timed out during phase 'Deploying'\"\n }","time":"2023-09-08T03:20:11-07:00"}
{
"errorCode": "ContextError",
"errorResponse": "{\n\"message\": \"Context timed out during phase 'Deploying'\"\n}"
}
Tried to delete it and run again (https://learn.microsoft.com/en-us/azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line?tabs=for-static-ip-address-1%2Cfor-static-ip-address-2#set-up-arc-vm-management), still failing.

**Comment by dkirby-ms** [comment]
Testing a fix now for this
