### ISSUE TITLE
HCIBox deployment mixing Azure Powershell context and AZ cli context

### ISSUE THREAD

**Issue by jjindrich** [microsoft/azure_arc#2103]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
HCIBox

I used Azure Developer CLI for deployment. I have Powershell and AZ CLI on my computer. My context was different - using diffrerent tenants. I failed but errors was strange.

Please add validation if both installed as ask for new context.

**Comment by dkirby-ms** [comment]
I am trying to understand what issue you faced. Do you have a screenshot of an error or other failure you can share?

**Comment by jjindrich** [comment]
Powershell scripts are combining AZ CLI commands and Powershell commands. I got strange errors because of my Powershell context was existing but with old one.

Maybe add comments into guide that Azure Powershell is needed.
