### ISSUE TITLE
Deploying Agora via Azure Developer CLI using WSL Ubuntu Distro

### ISSUE THREAD

**Issue by LucaOtto** [microsoft/azure_arc#2105]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
[](https://azurearcjumpstart.io/azure_jumpstart_ag/contoso_supermarket/deployment/#deployment-via-azure-developer-cli)

**Describe the issue or the bug**
I'm running the Azd up command from a WSL Ubuntu environment: the command hangs and shows Logging to Azure

**To Reproduce**

**Screenshots**

<img width="845" alt="image" src="https://github.com/microsoft/azure_arc/assets/42404744/68397a7b-5912-463f-b2eb-a35029b4e85d">

**Comment by dkirby-ms** [comment]
At this step it should be installing the Az PowerShell module, which can take some time. Did it ever recover from this?

**Comment by LucaOtto** [comment]
it did install the AZ Pwsh module and the continued on.

Luca
________________________________

**Comment by dkirby-ms** [comment]
Great, so it sounds like your issue is resolved. Can we close this?

**Comment by likamrat** [comment]
@LucaOtto any updates?
