### ISSUE TITLE
Unable to enable Insights after HCIBox cluster registration 

### ISSUE THREAD

**Issue by hgeorges** [microsoft/azure_arc#2114]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**

https://azurearcjumpstart.io/azure_jumpstart_hcibox/

**Describe the issue or the bug**

After applying Windows updates to the cluster hosts and Az.StackHCI, I ran successfully the re-registration of the cluster, and expeced to be able to to enable Insights in Azure portal. That didn't happen.

**To Reproduce**

I was expecting to be able to use Insights.
**Environment summary**

**Have you looked at the Troubleshooting and Logs section?**

**Screenshots**

![InsightsNotAvailable](https://github.com/microsoft/azure_arc/assets/7623171/fce056f8-8474-4604-9287-586dd45a5d64)

**Additional context**

**Comment by dkirby-ms** [comment]
This issue is now resolved and Insights can be turned on by redeploying. If you dont want to redeploy you can run Windows update on the HCI nodes (AzSHOST1 and AzSHOST2) and then unregister and re-register the cluster.
