### ISSUE TITLE
Deploy-ArcResourceBridge.ps1 fails 

### ISSUE THREAD

**Issue by ninadkk** [microsoft/azure_arc#2116]
Deploy-ArcResourceBridge script is getting stuck at the "Waiting on Arc Resource Bridge deployment complete"

Can you please guide on the above issue?

Waiting on Arc Resource Bridge deployment to complete...
The term 'az' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (az:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : AzSHOST1
 
Waiting on Arc Resource Bridge deployment to complete...
The term 'az' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (az:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : AzSHOST1
 
Waiting on Arc Resource Bridge deployment to complete...
The term 'az' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (az:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : AzSHOST1
 
Waiting on Arc Resource Bridge deployment to complete...

**Comment by dkirby-ms** [comment]
This failure looks catastrophic, as if something on the host VM is corrupt. Please share the rest of your logs as indicated in the troubleshooting section.

However, you'll likely need to teardown and redeploy the environment.

**Comment by ninadkk** [comment]
Hi Dale,

There issue with Subscription selection . I have redeploy the setup is working now

Regards,
Ninad Kapse
***@***.******@***.***>
+919769431815
