### ISSUE TITLE
Upgrade packages in scenario "Integrate Microsoft Defender for SQL servers with Azure Arc-enabled SQL Server"

### ISSUE THREAD

**Issue by janegilring** [microsoft/azure_arc#2136]
**Is your feature request related to a new Jumpstart scenario you would like to contribute?**
No, existing scenario: [Integrate Microsoft Defender for SQL servers with Azure Arc-enabled SQL Server](https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_sqlsrv/azure/azure_arm_template_sqlsrv_winsrv_defender/)

**Is your feature request related to a problem? Please describe.**

Yes, the following issues
- https://github.com/microsoft/azure_arc/issues/1941
- https://github.com/microsoft/azure_arc/issues/2093

**Describe the solution you'd like.**
Upgrade Azure CLI to 64-bit and replace .NET Core 3.1 with .NET Core (7) .

**Comment by janegilring** [comment]
@Aditya-Narayan-Nayak Here is the issue we discussed you can give a go at

**Comment by Aditya-Narayan-Nayak** [comment]
@janegilring Sure I will look into this

**Comment by likamrat** [comment]
@Aditya-Narayan-Nayak any update?

**Comment by Aditya-Narayan-Nayak** [comment]
Not yet @likamrat
