### ISSUE TITLE
Problems to build ARC Jumpstart full

### ISSUE THREAD

**Issue by ms-pabloar** [microsoft/azure_arc#2175]
Hello team. I am trying to launch the Jumpstart demo but I am getting these errors:

![image](https://github.com/microsoft/azure_arc/assets/117193341/395344f5-ad0c-4efd-8e3f-f465704ae707)
![image](https://github.com/microsoft/azure_arc/assets/117193341/0e50e87c-2e1b-4bbc-8708-6894280cadb4)

I am trying the full version in East US, I am wondering if this is a known issue.

**Comment by likamrat** [comment]
@ms-pabloar can you please follow the Troubleshooting instructions and share logs?

**Comment by ms-pabloar** [comment]
> @ms-pabloar can you please follow the Troubleshooting instructions and share logs?
Hello please take a look at the deployment errors, I'll paste the error details from top to bottom in the following posts: 
![image](https://github.com/microsoft/azure_arc/assets/117193341/904157b7-30ac-4bbb-b688-e1cc42de4f2b)

**Comment by ms-pabloar** [comment]
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
  "details": [
    {
      "code": "VMExtensionProvisioningError",
      "message": "VM has reported a failure when processing extension 'installscript_k3s' (publisher 'Microsoft.Azure.Extensions' and type 'CustomScript'). Error message: \"Enable failed: failed to execute command: command terminated with exit status=2\n[stdout]\n\n[stderr]\n\". More information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot. "
    }
  ]
}

**Comment by ms-pabloar** [comment]
{
  "code": "DeploymentFailed",
  "target": "/subscriptions/0e873953-193e-497e-aaf2-ea0d00418b86/resourceGroups/Azure-ARC-Demo/providers/Microsoft.Resources/deployments/Microsoft.Template-20231018164621",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
  "details": [
    {
      "code": "ResourceDeploymentFailure",
      "target": "/subscriptions/0e873953-193e-497e-aaf2-ea0d00418b86/resourceGroups/Azure-ARC-Demo/providers/Microsoft.Resources/deployments/ubuntuCAPIDeployment",
      "message": "The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'."
    },
    {
      "code": "ResourceDeploymentFailure",
      "target": "/subscriptions/0e873953-193e-497e-aaf2-ea0d00418b86/resourceGroups/Azure-ARC-Demo/providers/Microsoft.Resources/deployments/ubuntuRancherDeployment",
      "message": "The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'."
    }
  ]
}

**Comment by likamrat** [comment]
These are not the logs i am looking for. See the [Troubleshooting](https://azurearcjumpstart.io/azure_jumpstart_arcbox/full/#exploring-installation-logs-from-the-linux-virtual-machines) section.

**Comment by ms-pabloar** [comment]
> These are not the logs i am looking for. See the [Troubleshooting](https://azurearcjumpstart.io/azure_jumpstart_arcbox/full/#exploring-installation-logs-from-the-linux-virtual-machines) section.

I fixed the problem, my service principal was wrongly created, I created a new one and everything is working as expected.

**Comment by likamrat** [comment]
Happy to hear that. We are working on a new azd implementation for ArcBox that will eliminate such user errors. 

I will go ahead and close this issue for now.
