### ISSUE TITLE
Control Plane not getting ready - Arc DC on AKS

### ISSUE THREAD

**Issue by PraveenAnil** [microsoft/azure_arc#219]
**Control Plane is not getting ready**
The data Controller deployment is not getting completed for me

**To Reproduce**
1. Go to "https://github.com/microsoft/azure_arc/blob/master/azure_arc_data_jumpstart/docs/aks_dc_vanilla_arm_template.md"
2. Deploy the template and move to https://github.com/microsoft/azure_arc/blob/master/azure_arc_data_jumpstart/docs/aks_dc_vanilla_arm_template.md#windows-login--post-deployment   step
3.  Upon initiation, the script is stuck at 5 out of 9 resources are ready
![Snag_eaf19a6](https://user-images.githubusercontent.com/7903608/101393953-dcef3180-38ed-11eb-9fa9-e59abcfa0c0d.png)

4. When we run the command: az arc dc status show

![Snag_eafbfba](https://user-images.githubusercontent.com/7903608/101394026-f5f7e280-38ed-11eb-985c-d4d50634b5a6.png)

**Expected behavior**
This was working till Friday and seems to be not working all of a sudden.

**Additional Check**
We ran a few other commands and got the response control plane is not ready.
![Snag_eb0087b](https://user-images.githubusercontent.com/7903608/101394060-027c3b00-38ee-11eb-9bbd-0577b09480a2.png)

**Comment by likamrat** [comment]
@PraveenAnil can you share your ARM template parameter file?

**Comment by sumitmalik51** [comment]
Hello @likamrat, this is the link for the parameter file,
https://storagesasd.blob.core.windows.net/arcdc/deploy.parameters.json
please let us know if you need any additional info.

**Comment by likamrat** [comment]
Can you please try with a 1.18.x version of AKS?
@thomasmaurer has same experience so I want to verify.
/cc @twright-msft

**Comment by sumitmalik51** [comment]
okay I will try, but for your information this was working till Friday.

**Comment by likamrat** [comment]
Same region/version?

**Comment by sumitmalik51** [comment]
region eastus, version 1.19.3 usiing the same version now also

**Comment by likamrat** [comment]
OK allow me some time to reproduce

**Comment by sumitmalik51** [comment]
Sure, Also I am trying with 1.18.8 version.

**Comment by twright-msft** [comment]
@sumitmalik51 - can you please get the controller logs using this command and see if there is anything unusual in there?

```
kubectl logs control-ktwdt -c controller -n arcdc
```

That should tell you where in the process the monitoring deployment is at currently.

**Comment by sumitmalik51** [comment]
The Data controller is in ready state using 1.18.8 kebernetes version.

**Comment by sumitmalik51** [comment]
The DC got deployed in kuberenetes 1.18.8 version.

**Comment by likamrat** [comment]
Update
---------
So looks like the issue with AKS 1.19 is the fact the container runtime has changed from docker to containerd. We are working on a fix but for now, stay on 1.18 and I will make a PR to point that out in the guide.

**Comment by sumitmalik51** [comment]
Thanks
