### ISSUE TITLE
[HCIBox] Resource bridge fails to deploy

### ISSUE THREAD

**Issue by dkirby-ms** [microsoft/azure_arc#2199]
Resource bridge fails with a timeout error when generating the kubeconfig file for the arcappliance.

Arcappliance logs indicate a timeout generating the kubeconfig

**Comment by avooca** [comment]
I'm stuck with this issue over multiple deployment attempts.  Do you need any data / logs?

ERROR: [Errno 2] No such file or directory: 'C:\\Users\\Administrator.jumpstart\\.kube\\config'
