### ISSUE TITLE
Update Azure Arc-enabled vSphere  resource bridge scenario

### ISSUE THREAD

**Issue by lanicolas** [microsoft/azure_arc#2202]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
Do a refresh of the Azure Arc-enabled vSphere Jumpstart scenario (https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_vsphere/resource_bridge/powershell/)

**Describe the issue or the bug**
Refresh scenario to latest versions

**To Reproduce**
No need

**Comment by dkirby-ms** [comment]
Closed by #2315
