### ISSUE TITLE
JumpStart HCIBox - Missing Azure Stack HCI Gallery images (win and ubuntu)

### ISSUE THREAD

**Issue by khq5801** [microsoft/azure_arc#2204]
Hi, 
I've deployed JumpStart HCIBox, the deployment was successful. However, in the resource group, I did not find the Azure Stack HCI Gallery images (win and ubuntu). 
![2023-10-26_00h49_05](https://github.com/microsoft/azure_arc/assets/84763417/9867960e-0e91-4a95-8d1c-dd3964fa4cd0)

**Comment by dkirby-ms** [comment]
Was the resource bridge created? This is likely related to the other HCIBox issue #2199

**Comment by khq5801** [comment]
Hi,
Yes, the resource bridge was successfully created.

![image](https://github.com/microsoft/azure_arc/assets/84763417/a42bbf91-143b-44e8-a7f1-4cd2e514f25b)

**Comment by WVDAdminTF** [comment]
Hi @dkirby-ms 
I am also facing the same issue, I have deployed twice and the custom location does not get created neither the two images. so total of 3 resources are missing.
![missing resources](https://github.com/microsoft/azure_arc/assets/84956733/58d7556e-029d-475f-9363-1ae8cf62e2db)

Note - upon re-running the **Deploy-ArcResourceBridge.ps1** script the Custom location gets created, but the images still do not get created.

**Comment by dkirby-ms** [comment]
As part of the release of HCI 23h2 the resource bridge capability of Stack HCI has changed. In response we are updating the HCIBox featureset to support 23h2 and the new resource bridge experience. Resource bridge will no longer work in 22h2 HCIBox deployments.

**Comment by dkirby-ms** [comment]
Consolidating this with #2304
