### ISSUE TITLE
JumpStart HCIBox - Deployment completes with 3 Missing resources, Custom location and Azure Stack HCI Gallery images (win2k22 and ubuntu20)

### ISSUE THREAD

**Issue by WVDAdminTF** [microsoft/azure_arc#2207]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
https://azurearcjumpstart.io/azure_jumpstart_hcibox/

**Describe the issue or the bug**
JumpStart HCIBox - Deployment completes with 3 Missing resources, 
Custom location and Azure Stack HCI Gallery images (win2k22 and ubuntu20)

**To Reproduce**
Deploy the HCIBox normally

**Expected behavior**
Deployment will complete with 3 Missing resources, Custom location and Azure Stack HCI Gallery images (win2k22 and ubuntu20)

**Environment summary**
Fresh Azure Environment with no other deployments

**Have you looked at the Troubleshooting and Logs section?**
yes

**Screenshots**
![image](https://github.com/microsoft/azure_arc/assets/84956733/7546f4d8-2df3-44c4-a4ba-cd8b91c35620)
![image](https://github.com/microsoft/azure_arc/assets/84956733/9dcf0d2d-8832-41b3-9d0e-94522615930a)
[HCIBox Issue Logs26 oct 2023.zip](https://github.com/microsoft/azure_arc/files/13176100/HCIBox.Issue.Logs26.oct.2023.zip)

**Additional context**
**Note** - upon re-running the Deploy-ArcResourceBridge.ps1 script the Custom location gets created, but the images still do not get created.

**Comment by dkirby-ms** [comment]
Thanks for reporting. With the release of 23h2 there are some things we are working on to update the HCIBox experience. As part of that we are reworking how AKS and Resource Bridge work in HCIBox to align with the 23h2 featureset. 

Having said that, the error you see here may be related to insufficient permissions on the service principal you are using. The service principal requires Owner role (or contributor and user access administrator). Can you share the RBAC roles of your SPN?

**Comment by dkirby-ms** [comment]
Some more details here on progress on HCI 23H2 support - https://github.com/microsoft/azure_arc/discussions/1454

**Comment by dkirby-ms** [comment]
Consolidating this issue with #2304
