### ISSUE TITLE
Adding "Server Clusters" post deployment dows not show up.

### ISSUE THREAD

**Issue by kprpg** [microsoft/azure_arc#2214]
Once the HCI box is setup per the Arc JumpStart HCI box setup, and one goes to Windows Admin Center it does not show the option to add "Server Clusters". It shows the other three - namely Servers, Windows PCs and Azure VMs,.

**Comment by dkirby-ms** [comment]
Can you share a screenshot please?

**Comment by dkirby-ms** [comment]
@kprpg? Any update?

**Comment by dkirby-ms** [comment]
Checking once more for any update? See here for additional discussion on current status of HCIBox - https://github.com/microsoft/azure_arc/discussions/1454
