### ISSUE TITLE
Azure Arc Powerpoint slides still references AAD RBAC (not Entra ID)

### ISSUE THREAD

**Issue by lukemurraynz** [microsoft/azure_arc#2216]
Azure Arc Powerpoint slides still references AAD RBAC (not Entra ID)

- Particularly noticed in the arc_library.pptx

Although could be in others.

**Comment by likamrat** [comment]
Hi @lukemurraynz thank you. 

The old website is no longer, see our new website at https://aka.ms/ArcJumpstart.com. 

New Diagrams are available at https://aka.ms/JumpstartDiagrams
