### ISSUE TITLE
High Security Vulnerability when deploying ASKEE Single Node

### ISSUE THREAD

**Issue by renato-marciano** [microsoft/azure_arc#2261]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
[Single Node Deployment AKSEE](https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/aks_hybrid/aks_edge_essentials_single/#aks-edge-essentials-single-node-deployment-with-azure-arc-using-arm-template)

**Describe the issue or the bug**
There are security vulnerabilities when deploying AKSEE for the Single Node

**To Reproduce**

1. Deploy AKS Edge Essentials Single Arm deployment using the jumpstart documentation.
2. After deployment, go to your VM on Azure Portal
3. There will be an advisor note, you can click. 

**Expected behavior**
No high security vulnerabilities.

**Screenshots**
![image](https://github.com/microsoft/azure_arc/assets/7683165/9b037ac4-1501-4205-8151-0061a37f303e)

![image](https://github.com/microsoft/azure_arc/assets/7683165/2d59c8c0-372b-463b-b32b-fb7b51580820)

**Comment by likamrat** [comment]
Hi @renato-marciano thank you. a couple of things with regard to the issue. 
1. These are not security vulnerabilities, it is remediation recommendations.
2. I would like to refer you to our [Our mission and principles](https://azurearcjumpstart.com/mission#getting-started-with-the-jumpstart-universe) page. Please refer to the below disclaimer. 

![image](https://github.com/microsoft/azure_arc/assets/46730876/13cf3d9a-a4aa-497d-ab20-f2b95fc83558)

The VMs getting deployed in each scenario or solution are sandboxed VMs, and applying each VM remediation recommendation is out of scope for the Jumpstart, unless it serves the actual scenario or solution. 

I will fo ahead and close this for now. Thank you!
