### ISSUE TITLE
details

### ISSUE THREAD

**Issue by ingebeumer** [microsoft/azure_arc#2284]
Hi,
[Community decks](https://azurearcjumpstart.io/overview/#community-decks) in Azure Arc Jumpstart has an image with small typo's. It mentions **on-premesis** instead of **on-premises**.  

![image](https://github.com/microsoft/azure_arc/assets/40343254/2ae4b7e3-9935-40b9-b2ea-18c9e07e3772)

**Comment by likamrat** [comment]
The old website is no longer, see our new website @ https://aka.ms/ArcJumpstart.com.

Thank you!

**Comment by ingebeumer** [comment]
@likamrat thank you. Just found it right before the new website went live, which I knew nothing about at that time :)
enjoy your December holidays.
