### ISSUE TITLE
Cloning the repository for deployment is overkill

### ISSUE THREAD

**Issue by dohughes-msft** [microsoft/azure_arc#2286]
**Is your feature request related to a problem? Please describe.**
The instructions to deploy Arcbox via ARM, Bicep or Terraform specify as a first step to clone the repo, which results in over 5GB of artifacts and thousands of files landing on the local computer or in the Azure Cloud Shell. None of them are necessary to actually run the deployment via any of these tools. Please consider a better way.

**Describe the solution you'd like.**
Deployment instructions without a lot of unnecessary time spent cloning the repo and copying unnecessary artifacts.

**Describe alternatives you've considered.**
Simply copying the ARM/Terraform/etc subfolders would work a lot better.

**Comment by likamrat** [comment]
Hi @dohughes-msft, 

Last week we announced our [new website](https://aka.ms/ArcJumpstart). As part of it, we also now have a dedicated docs repo and no longer host this content next to the source code.

**Comment by dohughes-msft** [comment]
Hi @likamrat 

The new website still contains the same instructions for cloning the repo giving the same result of unwanted extra material:

```
donovan [ ~ ]$ git clone https://github.com/microsoft/azure_arc.git
Cloning into 'azure_arc'...
remote: Enumerating objects: 94745, done.
remote: Counting objects: 100% (4733/4733), done.
remote: Compressing objects: 100% (1742/1742), done.
Receiving objects:  19% (18628/94745), 1.67 GiB | 4.44 MiB/s B/s
```

**Comment by likamrat** [comment]
@dohughes-msft The issue is not the instructions, we need to finish the repo history pruning which we overlooked. Working on it...
