### ISSUE TITLE
InfluxDB setup container in error

### ISSUE THREAD

**Issue by arfontai** [microsoft/azure_arc#2303]
**Bug related to the Azure IoT Operations - Manufacturing - jumpstart scenario - in the post deployment phase**

after the end of the execution of the post-deployment scripts, I see the **influxdb-setup** remaining in Error.
Running the kubectl logs influxdb-setup-xxxx -n azure-iot-operations
I received the following error message: 

Error: failed to check if already set up: Get "http://192.168.0.5:8086/api/v2/setup": dial tcp 192.168.0.5:8086: connect: connection refused

For the moment it seems this error does not have impact on InfluxDB, I can see the data flowing in the prepared dashboard.

I followed the azd deployment option

**Comment by sebassem** [comment]
@arfontai Thanks for submitting this issue, this error has no effect on the automation. This is a batch job and it automatically retries creating another pod

![image](https://github.com/microsoft/azure_arc/assets/38246040/7cb4bf15-d25e-499e-b472-1359a2dd86f1)
