### ISSUE TITLE
AIO - Manufacturing JumpStart - No data in ADX

### ISSUE THREAD

**Issue by jochemdevos** [microsoft/azure_arc#2317]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
https://azurearcjumpstart.com/azure_arc_jumpstart/azure_edge_iot_ops/aio_manufacturing

**Describe the issue or the bug**
After deploying the jumpstart, services seem to start correctly as there's data being shown in the MQTT explorer as well as the influxdb/grafana dashboard. However Data explorer cluster does not receive any data, as well as the two topic subscriptions (storage account and eventhub).

When looking at the custom topic resource 'aiotopic42fd6', I see no traffic in the monitoring widget.

When looking at the event grid namespace 'aioeventgridns42fd6', I see traffic when checking the MQTT bullet as well as some publishing errors.

![image](https://github.com/microsoft/azure_arc/assets/12514622/32790f1c-03f8-42c2-8355-4fceefa22173)
![image](https://github.com/microsoft/azure_arc/assets/12514622/ce258fee-f3df-4e20-842b-ec1dbc862341)

The routing pane of grid namespace complains of lack of permissions

![image](https://github.com/microsoft/azure_arc/assets/12514622/cfa571d5-d243-4b87-8072-a83a87da3b48)

However I believe the appropiate permission is in place:
![image](https://github.com/microsoft/azure_arc/assets/12514622/f6634ea1-9e79-429d-830f-a6a8bc3eb15d)

We did have a failed initialization via de CLI provisioning. We didn't yet have the Resource providers enabled for the subscription, resulting in a failed bootstrap on the VM.

Any advice for me?

Kind regards,
Jochem

**Comment by sebassem** [comment]
@jochemdevos Thanks for submitting this issue, can you please share a screenshot of your adx dashboard ? I tried to repro the issue but I can see data flowing into data explorer. Also do you see the resource providers in the Azure portal ? they are registered during the logon scripts not the bootstrap.

**Comment by jochemdevos** [comment]
> @jochemdevos Thanks for submitting this issue, can you please share a screenshot of your adx dashboard ? I tried to repro the issue but I can see data flowing into data explorer. Also do you see the resource providers in the Azure portal ? they are registered during the logon scripts not the bootstrap.

No data:

![image](https://github.com/microsoft/azure_arc/assets/12514622/d9fbb6e3-79a7-45e9-80cd-2603fb45d1d2)

data connection:
![image](https://github.com/microsoft/azure_arc/assets/12514622/15d0bffa-d098-4fee-be10-a35bcfcfafa4)

Afaik it should flow eventgrid -> topic -> eventhub. But it seems to not publish to topic. The eventgrid data sender seems to be misconfigured (by Default it's on 'None' but I cannot set it to System managed identity with the error displayed in the screenshot in OP).

**Comment by sebassem** [comment]
@jochemdevos can you share the C:\AIO\Logs\LogonScript.log ?

**Comment by jochemdevos** [comment]
@sebassem Here you go. Ive justed redacted my email adress in tags and the printing of all subscriptions after login.
[LogonScript_SomeRedacted.log](https://github.com/microsoft/azure_arc/files/13583078/LogonScript_SomeRedacted.log)

**Comment by sebassem** [comment]
@jochemdevos I see errors in registering the resource providers, it seems the service principal doesn't have owner permissions on the subscription. Can you grant owner permissions and perform a fresh deployment ?

**Comment by jochemdevos** [comment]
@sebassem Working now.

- I've forked the repo and emptied the AzureProviders aioConfig as we already have the providers registered on subscription
- Instead of Owner role on subscription I've used Contributor role on Resource Group for the SP (shared R&D subscription).
- Did a clean deployment (also removed hidden resources in Azure).

Can see data now in ADX and Grafana. Many thanks :)
