### ISSUE TITLE
LogonScript k3s installation (intermittent failiure)

### ISSUE THREAD

**Issue by renato-marciano** [microsoft/azure_arc#2320]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**

https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/aks_hybrid/aks_edge_essentials_single/#post-deployment

**Describe the issue or the bug**
When LogonScript executes, it failed to download k3s. This could be just an intermittent network failure. The script continues to run with "Deployment successful", even though k3s failed to install. See logs below. At the very least, I think this should throw an exception or even better, maybe have a retry logic.

I did create another VM and was successful the second time.

**To Reproduce**
1. Follow the Jumpstart to deploy an AKSEE VM
2. Log In to trigger the LogonScript
3. Watch script logs

**Expected behavior**
Installation of k3s successful

**Screenshots**
LogonScript logs excerpt

```log
--- Verifying AksEdge Install Configuration...
* AKS Edge Essentials - K3s to be installed
*** No errors found in the Install Configuration.
Installing AKS Edge Essentials - K3s from https://aka.ms/aks-edge/k3s-msi
PS>TerminatingError(Invoke-WebRequest): "Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host."
failed to download from https://aka.ms/aks-edge/k3s-msi
Deployment Successful.

Checking kubernetes nodes
```
Full log attached below
[LogonScript.txt](https://github.com/microsoft/azure_arc/files/13602813/LogonScript.txt)

**Comment by dkirby-ms** [comment]
Thank you for the feedback. 

This message in your logs indicates some kind of network interruption. As part of our ongoing development we will continue to add additional error handling and retry logic where possible. Glad to hear that retrying the script was successful and thank you again for your feedback.

Installing AKS Edge Essentials - K3s from https://aka.ms/aks-edge/k3s-msi
PS>TerminatingError(Invoke-WebRequest): "Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host."
