### ISSUE TITLE
AIO - Prerequisite for the subscription to have the Microsoft.Kusto resource provider registered

### ISSUE THREAD

**Issue by colinrippeyfinarne** [microsoft/azure_arc#2326]
I deployed the AIO Manufacturing scenario today using bicep but saw a failure on the DataExplorer deployment with the error:

"the subscription <subscription_id> is not registered"

Quick search suggests that the Microsoft.Kusto resource provider needs to be registered, the deployment did in fact cause the Microsoft.Kusto resource provider to be registered but (I think) because it initially was not the DataExplorer specific deployment failed after a few seconds.

I re-ran the entire bicep deployment and it succeeded the second time now going to do the post-deployment steps.

**Comment by sebassem** [comment]
@colinrippeyfinarne Thanks for submitting this issue, we have pushed an update to our docs to include registering the necessary providers
