### ISSUE TITLE
Jumpstart to deploy an Arc-enabled k3s cluster on an Azure VM fails if the password of the service principal starts with "-"

### ISSUE THREAD

**Issue by magencio** [microsoft/azure_arc#2331]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**

Jumpstart scenario: [Deploy Rancher k3s on an Azure VM and connect it to Azure Arc using Azure ARM template](https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/rancher_k3s/azure_arm_template/)

**Describe the issue or the bug**

When following the steps in the Jumpstart scenario above and using **Deployment Option 2: ARM template with Azure CLI**, the deployment failed.

Further investigation revealed that the deployment failed to install k3s in the VM. [ARM Template being used](https://github.com/microsoft/azure_arc/blob/main/azure_arc_k8s_jumpstart/rancher_k3s/azure/arm_template/azuredeploy.json#L292) failed to execute [installk3s.sh script](https://github.com/microsoft/azure_arc/blob/main/azure_arc_k8s_jumpstart/rancher_k3s/azure/arm_template/scripts/installK3s.sh), specifically [when running az login command](https://github.com/microsoft/azure_arc/blob/main/azure_arc_k8s_jumpstart/rancher_k3s/azure/arm_template/scripts/installK3s.sh#L68). 

Az login failed because the password of the service principal created with `az ad sp create-for-rbac -n "JumpstartArcK8s" --role "Contributor" --scopes /subscriptions/$subscriptionId` (as per the Jumpstart steps) started with `-` character.

If you try to run az login with a password that starts with `-`, you will see an error like the following:

```pwsh
PS C:\> az login --user johndoe@contoso.com --password "-VerySecret"
argument --password/-p: expected one argument

Examples from AI knowledge base:
az login -u johndoe@contoso.com -p VerySecret
Log in with user name and password. This doesn't work with Microsoft accounts or accounts that have two-factor authentication enabled. Use -p=secret if the first character of the password is '-'.

az login --service-principal -u http://azure-cli-2016-08-05-14-31-15 -p VerySecret --tenant contoso.onmicrosoft.com
Log in with a service principal using client secret. Use -p=secret if the first character of the password is '-'.

az login --service-principal -u http://azure-cli-2016-08-05-14-31-15 -p ~/mycertfile.pem --tenant contoso.onmicrosoft.com
Log in with a service principal using client certificate.

https://aka.ms/cli_ref
Read more about the command in reference docs
```

The solution to the problem as per the error message is to use `--password=secret` or `-p=secret`.

I can also imagine this issue could happen with other Jumpstarts, as `az login` is used in many scripts.

**To Reproduce**

1. Create a service principal which password starts with `-`.
2. Follow the rest of the steps in the Jumpstart [Deploy Rancher k3s on an Azure VM and connect it to Azure Arc using Azure ARM template](https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/rancher_k3s/azure_arm_template/)

**Expected behavior**

Deployment should work regardless of the password starting with `-`.

**Environment summary**

Not sure which version of az cli is used during the deployment, but I can reproduce this error when using az cli 2.53.0.

**Have you looked at the Troubleshooting and Logs section?**

I found the issue by troubleshooting the VM Extension execution as per the instructions here: [Run Custom Script Extension on Linux VMs in Azure - Azure Virtual Machines: Troubleshooting](https://learn.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-linux#troubleshooting)

**Comment by sebassem** [comment]
@magencio can you share the azure cli version you are using ?

**Comment by sebassem** [comment]
@magencio Thanks for submitting this issue, can you share the Azure CLI version on the machine where you create the service principal?

**Comment by magencio** [comment]
> @magencio Thanks for submitting this issue, can you share the Azure CLI version on the machine where you create the service principal?

@sebassem, az cli version is the same one I specified in the Environment summary: 2.53.0.
