### ISSUE TITLE
ArcBox Deployment Failure

### ISSUE THREAD

**Issue by Franck-WRui** [microsoft/azure_arc#2354]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**

ArcBox

**Describe the issue or the bug**

Tried to deploy the Jumpstart ArcBox solution but failed.
During the self accreditation process for the WorkshopPLUS-Azure Arc. In the Lab instruction, the link provided for the ARM template was:  https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fmicrosoft%2Fazure_arc%2Fmain%2Fazure_jumpstart_arcbox%2FARM%2Fazuredeploy.json (which doesn't have SSH RSA Public Key and Flavor fields in the template)
However, the ARM template link provided in the page https://azurearcjumpstart.com/azure_jumpstart_arcbox/ITPro#deployment-option-1-azure-portal refers to the below link:
https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Farc_jumpstart_levelup%2Fmain%2Fazure_arc_servers_jumpstart%2FARM%2Fazuredeploy.json

I've tried both deployment options but failed, the error messages that I got are like below:

_{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'Bootstrap' (publisher 'Microsoft.Compute' and type 'CustomScriptExtension'). Error message: [\\\"Command](file:///%22Command) execution finished, but failed because it returned a non-zero exit code of: '1'. The command had an error output of: ''12109455' is not recognized as an internal or external command,\\r\\noperable program or batch file.\\r\\n'\\\". More information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot. \"\r\n      }\r\n    ]\r\n  }\r\n}"}]}_

Note: 12109455 was part of the password that I set for the VM as required in the ARM template
The deployment chosen is ArcBox for IT Pros, as mentioned in the Lab instructions and in the link https://azurearcjumpstart.com/azure_jumpstart_arcbox/ITPro, it requires 16 DSv4-series vCPUs, the instructions mentioned in the lab to raise quotas were correctly followed.

**To Reproduce**

**Expected behavior**

The full infrastructure should be deployed in the target subscription successfully.

**Environment summary**

**Have you looked at the Troubleshooting and Logs section?**

Yes 
<img width="526" alt="Arc01" src="https://github.com/microsoft/azure_arc/assets/120719383/8e0752e7-a793-4156-8235-1692702d62c2">
![Arc02](https://github.com/microsoft/azure_arc/assets/120719383/a685d5ab-6a06-4380-90ef-d8e9ca4e4a63)
<img width="404" alt="Arc03" src="https://github.com/microsoft/azure_arc/assets/120719383/012dadee-6aae-469f-bb8a-6345184a2ee7">

**Screenshots**

**Additional context**

**Comment by zaidmohd** [comment]
@Franck-WRui : I didn't encounter the first issue when clicking on the WorkshopPLUS link, i was able to see both the params.

Also, regarding the deployment error, I was able to successfully deploy the ArcBox ITPro flavor using the portal link you shared.
![image](https://github.com/microsoft/azure_arc/assets/25724349/a98193d9-a4c9-4324-9e2d-aea72a318394)

Could you please retry the password param as per the requirements?
_Password for Windows account. Password must have 3 of the following: 1 lower case character, 1 upper case character, 1 number, and 1 special character. The value must be between 12 and 123 characters long_
![image](https://github.com/microsoft/azure_arc/assets/25724349/a91b9de1-472b-48b5-bb78-a7fc17f6af09)

**Comment by zaidmohd** [comment]
@Franck-WRui: Did you try as per the password requirement? Let us know if you facing any issue.

**Comment by likamrat** [comment]
Closing for now. @Franck-WRui please let us know if you still face issues.
