### ISSUE TITLE
Missing images in jumpstart "Deploy AKS cluster on Azure IoT Edge and connect it to Azure Arc using Terraform"

### ISSUE THREAD

**Issue by sandervandevelde** [microsoft/azure_arc#2390]
The last section of "Deploy AKS cluster on Azure IoT Edge and connect it to Azure Arc using Terraform" has a number of missing images:

![image](https://github.com/microsoft/azure_arc/assets/694737/b9a2394a-5140-47ac-ae41-1fca1c2e8507)

and

![image](https://github.com/microsoft/azure_arc/assets/694737/35f00505-fb6c-411c-a868-60137d901b3c)

**Is your feature request related to a new Jumpstart scenario you would like to contribute?**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like.**

**Describe alternatives you've considered.**

**Additional context.**

**Comment by lanicolas** [comment]
Hello @sandervandevelde 

Thank you for using Jumpstart and flagging this. I am addressing this in a new PR

**Comment by sandervandevelde** [comment]
Thanks. Let me know when it's done.

**Comment by likamrat** [comment]
Closed via [#232](https://github.com/Azure/arc_jumpstart_docs/pull/232)
