### ISSUE TITLE
HCI cluster deployment failed but validation passed. 

### ISSUE THREAD

**Issue by hungry1526** [microsoft/azure_arc#2411]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**

HCIBox

**Describe the issue or the bug**

HCI Cluster ARM template is validated but deployment failed. It timed out on "Deploy Arc infrastructure components".  Where can I find more log? The error from the portal seems vague and it may be related to service principal but I never configure this parameter. How can I find more logs? 

**To Reproduce**

It failed on this step: 
![image](https://github.com/microsoft/azure_arc/assets/1637753/fb1f95f6-493b-4a12-9f41-1675df7d8881)

Error from portal:
Type 'DeployArb' of Role 'MocArb' raised an exception: Exception while installing ARB in step [DeployArb:Doing AZ Login using service principal] AZ Login using SP failed after 15 retries. Aborting Arb deployment - Error = at at DeployArbInternal, C:\NugetStore\Microsoft.AzureStack.MocArb.LifeCycle.1.2311.0.30\content\Scripts\MocArbHelper.psm1: line 1124 at DeployArb, C:\NugetStore\Microsoft.AzureStack.MocArb.LifeCycle.1.2311.0.30\content\Scripts\MocArbLifeCycleManager.psm1: line 127 at <ScriptBlock>, C:\CloudDeployment\ECEngine\InvokeInterfaceInternal.psm1: line 127 at Invoke-EceInterfaceInternal, C:\CloudDeployment\ECEngine\InvokeInterfaceInternal.psm1: line 123 Command Arguments ------- --------- DeployArbInternal {Parameters=CloudEngine.Configurations.EceInterfaceParameters} {} <ScriptBlock> {CloudEngine.Configurations.EceInterfaceParameters, MocArb, DeployArb, C:\NugetStore\Micr... Invoke-EceInterfaceInternal {CloudDeploymentModulePath=C:\NugetStore\Microsoft.AzureStack.Solution.Deploy.CloudDeploy... at Trace-Error, C:\NugetStore\Microsoft.AzureStack.MocArb.LifeCycle.1.2311.0.30\content\Scripts\Common\Tracer.psm1: line 63 at DeployArbInternal, C:\NugetStore\Microsoft.AzureStack.MocArb.LifeCycle.1.2311.0.30\content\Scripts\MocArbHelper.psm1: line 1402 at DeployArb, C:\NugetStore\Microsoft.AzureStack.MocArb.LifeCycle.1.2311.0.30\content\Scripts\MocArbLifeCycleManager.psm1: line 127 at <ScriptBlock>, C:\CloudDeployment\ECEngine\InvokeInterfaceInternal.psm1: line 127 at Invoke-EceInterfaceInternal, C:\CloudDeployment\ECEngine\InvokeInterfaceInternal.psm1: line 123

**Expected behavior**

**Environment summary**

I am using AZD on east us. 

**Have you looked at the Troubleshooting and Logs section?**

**Screenshots**

**Additional context**

**Comment by dkirby-ms** [comment]
Is it possible you can redeploy the environment? This looks like its possibly something upstream related in ARB deployment process but hard to say for sure.

**Comment by dkirby-ms** [comment]
I tried reproducing this and am not able to. Having said that, we pushed an updated build this morning that uses the latest HCI OS 2311.2 build. I would suggest completely tearing down the environment and redeploy from scratch.
