### ISSUE TITLE
Typo in Documentation - AKS on Azure Stack HCI

### ISSUE THREAD

**Issue by chrismihm-ms** [microsoft/azure_arc#2415]
**Is your feature request related to a new Jumpstart scenario you would like to contribute?**

**Is your feature request related to a problem? Please describe.**
I think there is a type in the AKS on Azure Stack HCI section of your online documentation screenshot and in the "Configure-AKSWorkloadCluster" ps script. I believe its missing a $ in front of the variable for the aadgroupID=""

![Screenshot 2024-02-13 102307](https://github.com/microsoft/azure_arc/assets/123748115/1190e9ee-c29e-4591-b948-7827cff71854)

**Describe the solution you'd like.**

**Describe alternatives you've considered.**

**Additional context.**

**Comment by dkirby-ms** [comment]
Good catch!

**Comment by dkirby-ms** [comment]
Closed via https://github.com/Azure/arc_jumpstart_docs/pull/252
