### ISSUE TITLE
ArcBox-Client VM automated scripts errors

### ISSUE THREAD

**Issue by dalemagna** [microsoft/azure_arc#2420]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
https://azurearcjumpstart.io/azure_jumpstart_arcbox/ITPro

**Describe the issue or the bug**
The automated scripts run within the ArcBox-Client VM are failed

**To Reproduce**
The steps are reported here: https://azurearcjumpstart.io/azure_jumpstart_arcbox/ITPro#:~:text=The%20Logon%20scripts,deployment%20is%20complete

**Screenshots**
![image](https://github.com/microsoft/azure_arc/assets/77403781/c61f23be-11b7-41a3-af87-e297d4fa875a)
![image](https://github.com/microsoft/azure_arc/assets/77403781/70e81f71-58f9-484e-bfdf-7dced1a04604)

**Additional context**
ArcBox-Client VM log folder: https://1drv.ms/f/s!AsTKD3oIqrLpgppQHx5AzKl06GFM1g?e=W5u2lV

**Comment by janegilring** [comment]
@dalemagna Hi, could you run the following from Azure CLI (either from your local machine or from Cloud Shell) to determine the RBAC permissions assigned to the service principal used by the deployment?

1) Retrieve object ID for your deployment SPN
`az ad sp list --filter "appId eq 'f70cd6ff-a098-4383-9ea6-036a24a1464d'"`

2) Retrieve the subscription RBAC assignments for the SPN on the subscription scope
`az role assignment list --scope /subscriptions/5d3ddfde-0c18-468c-8563-a74d7aa56a1b--assignee <insert-id>`

Expected output is similar to this:
```
[
  {
    "condition": null,
    "conditionVersion": null,
    "createdBy": "af606f84-8942-408c-9a52-4b478a693b18",
    "createdOn": "2022-12-27T15:27:48.400727+00:00",
    "delegatedManagedIdentityResourceId": null,
    "description": null,
    "id": "/subscriptions/87b8def0-f5cf-402e-a8db-10e0ee958565/providers/Microsoft.Authorization/roleAssignments/27a7589f-4ad0-4bae-9981-440ffd081091",
    "name": "27a7589f-4ad0-4bae-9981-440ffd081091",
    "principalId": "b3f148d2-c92b-43d6-afe4-89ec76277630",
    "principalName": "545e3c87-82b6-4658-948f-52974b28aa50",
    "principalType": "ServicePrincipal",
    "roleDefinitionId": "/subscriptions/87b8def0-f5cf-402e-a8db-10e0ee958565/providers/Microsoft.Authorization/roleDefinitions/8e3af657-a8ff-443c-a75c-2fe8c4bcb635",
    "roleDefinitionName": "Owner",
    "scope": "/subscriptions/87b8def0-f5cf-402e-a8db-10e0ee958565",
    "type": "Microsoft.Authorization/roleAssignments",
    "updatedBy": "af606f84-8942-408c-9a52-4b478a693b18",
    "updatedOn": "2022-12-27T15:27:48.400727+00:00"
  }
]
```

**Comment by janegilring** [comment]
@dalemagna Any updates from your side?

**Comment by likamrat** [comment]
Closing this for now. @dalemagna please feel free to comment if you need further assistant
