### ISSUE TITLE
Azure ArcBox Jumpstart Dependency Agent incompatible with Ubuntu 22.04.3 LTS

### ISSUE THREAD

**Issue by datoront** [microsoft/azure_arc#2423]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
Yes

**Describe the issue or the bug**
Azure Arc Jumpstart ArcBox Full edition deploys 2x Ubuntu 22.04.3 LTS versions which are not compatible with the Dependency Agent:  https://learn.microsoft.com/en-us/azure/azure-monitor/vm/vminsights-dependency-agent-maintenance#dependency-agent-linux-support

**To Reproduce**
1. Deploy ArcBox Full edition
2. From Azure Portal go to Azure Arc
4. Click on Machines
5. Choose either Arcbox-Ubuntu-01 or Arcbox-Ubuntu-02
6. Select 'Extensions' from the left hand side
7. Click on the 'Status' Section of the DependencyAgentLinux.  Details can be found here.

**Expected behavior**
I expect the Dependency Agent to be installed on ArcBox Full edition as part of the deployment process.

**Environment summary**
I am using the Azure Arc Jumpstart Arcbox Full version as my environment

**Have you looked at the Troubleshooting and Logs section?**
Yes: https://learn.microsoft.com/en-us/azure/azure-monitor/vm/vminsights-dependency-agent-maintenance#dependency-agent-linux-support

**Screenshots**
![Screenshot 2024-02-15 165249](https://github.com/microsoft/azure_arc/assets/75295303/bfdf9585-08c5-4b38-b9af-bca342ab568c)

**Additional context**

**Comment by rahulbagaria** [comment]
Hi! Dependency Agent (DA) from Azure Monitor VM Insights is only supported for a very limited set of OS versions and distros: https://learn.microsoft.com/azure/azure-monitor/vm/vminsights-dependency-agent-maintenance#dependency-agent-linux-support.

We do not have any plans currently to extend support beyond the current list, including Ubuntu 22. If you might need similar functionality for your OS, you could explore an alternative solution from Azure Marketplace (some of our ISV partners might have relevant solutions there), to supplement Azure Monitor data collection.

**Comment by likamrat** [comment]
Thank you @rahulbagaria and as discussed, we will be deprecating the Dependency Agent implementation from the Jumpstart. 

I will go ahead and close this issue now.

**Comment by stevedistef** [comment]
I just installed the Arcbox and the Dependence agent was still attempted to be deployed.   I am also not sure I agree with deprecating it since one of the largest control plane benefits is AzMon, and without the DA, we miss alot.   I understand it might not be supported on this particular distro, but would think I rather have it on all the other machines where it can be supported.   Unless I misunderstood what you meant by 'deprecating the DA'?
