### ISSUE TITLE
Arc AWS Scaled Deployment out of date

### ISSUE THREAD

**Issue by 430am** [microsoft/azure_arc#2424]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
https://arcjumpstart.com/azure_arc_jumpstart/azure_arc_servers/scaled_deployment/aws_scaled_ansible

**Describe the issue or the bug**
Multiple issues with Dynamic scaled onboarding of AWS EC2 instances to Azure Arc using Ansible scenario:

1. Terraform files for building ansible server "server_ansible.tf" and "aws_infra.tf" are out of date. It is trying to use a CentOS AMI which AWS does not support any more.
2. Terraform code is out of date. The Terraform file and remote-exec provisioners have been changed in version 1.1x to no longer support expansion of directories with special metacharacters (~) as documented here https://developer.hashicorp.com/terraform/language/v1.1.x/upgrade-guides/1-1#interpretation-of-remote-file-paths-in-the-remote-exec-and-file-provisioners

**To Reproduce**
1. Run through the script and when you get to this step:
![image](https://github.com/microsoft/azure_arc/assets/13786181/232589f6-1f8e-47f2-b6bf-8cfa3bfe6389)

when it tries to plan the Ansible server, you get this error:
![image](https://github.com/microsoft/azure_arc/assets/13786181/c825ffc4-0838-4399-bc24-3d97965743d3)

This stems from this chunk of the aws_infra.tf
![image](https://github.com/microsoft/azure_arc/assets/13786181/159723cd-d300-45f7-9980-33bd02f05b2d)

2. If we fix the data block in aws_infra.tf to anything that is currently supported by AWS, we then run into the issue with the file and remote-exec provisioners in the server_ansible.tf file:

![image](https://github.com/microsoft/azure_arc/assets/13786181/f173de36-d987-46ce-86a3-c09759399fb0)

This stems from these blocks in the server_ansible.tf file:
![image](https://github.com/microsoft/azure_arc/assets/13786181/95d3e7a9-90f1-4b01-b4de-e2c2dfdc40ba)

**Expected behavior**
This scenario should deploy 9 servers in AWS, 1 centos server, 4 ubuntu servers, and 4 Windows servers. It does not, currently :)

**Environment summary**
![image](https://github.com/microsoft/azure_arc/assets/13786181/9f78acc4-47ce-4947-960f-6fd9574d7ecd)
![image](https://github.com/microsoft/azure_arc/assets/13786181/da801ed4-a3be-4cae-a992-5290eb76c176)
![image](https://github.com/microsoft/azure_arc/assets/13786181/04f71aa0-b1ee-416f-82ba-6a4a35130944)

**Screenshots**
included above

**Additional context**
I've cleaned up the terraform code to get it to work, I'd like to clean this up further to remove the file and remote-exec provisioners and replace with cloud-init, but I have gotten it to run correctly with minor changes

**Comment by 430am** [comment]
Yes @likamrat. Planning on putting together a PR this week. Currently traveling for customer commitments which has slowed down my time to dev :)

My plan is to get it working, then to open a new issue tied to cleaning up the Ansible and Terraform code to bring the project inline with current best practices

**Comment by likamrat** [comment]
awesome! Assigning this issue to you.

**Comment by likamrat** [comment]
Thank you for addressing the issue @430am. Can you please assess if there is a doc/screenshots update needed? /cc @dkirby-ms

**Comment by 430am** [comment]
I already updated the documentation and submitted a pull request.

Thanks, Jack

Jack Wade | ***@***.***
