### ISSUE TITLE
HCI Host not member of the domain

### ISSUE THREAD

**Issue by jsporbert** [microsoft/azure_arc#2429]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
[
(https://github.com/microsoft/azure_arc/tree/main/azure_jumpstart_hcibox)
**Describe the issue or the bug**
Infrastuctrue installation  reported successfull. Yet both Azure Stack host are still in Workgroup and not member of the jumpstart.local domain. Is this expected ?

**To Reproduce**

**Expected behavior**

**Environment summary**

**Have you looked at the Troubleshooting and Logs section?**

**Screenshots**

**Additional context**

**Comment by dkirby-ms** [comment]
This is expected. The hosts do not get joined to the domain until deployment time. The LCM deployment process is what does the actual domain join for the nodes.

**Comment by jsporbert** [comment]
Yes I have realized afterwards 🙂
________________________________
De : Dale Kirby ***@***.***>
Envoyé : vendredi 1 mars 2024 15:24
À : microsoft/azure_arc ***@***.***>
Cc : Jerome Sporbert ***@***.***>; Author ***@***.***>
Objet : Re: [microsoft/azure_arc] HCI Host not member of the domain (Issue #2429)


This is expected. The hosts do not get joined to the domain until deployment time. The LCM deployment process is what does the actual domain join for the nodes.
