### ISSUE TITLE
Deployment fails with error message "'pwsh' is not recognized as an internal or external command, operable program or batch file."

### ISSUE THREAD

**Issue by Chrisflyckelen** [microsoft/azure_arc#2430]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
https://arcjumpstart.com/azure_jumpstart_hcibox/deployment_azd

**Describe the issue or the bug**
After initialization and trying start the deployment I was able to select the subscription and the Azure region. I have only one subscription in my tenant and I chose the East US region as mentioned in the documention. I created a password and didn't save these values for futures use. After hitting 'Enter' the scrips stops with the error message "'pwsh' is not recognized as an internal or external command, operable program or batch file."

**To Reproduce**

**Expected behavior**
The script should be executed.

**Environment summary**
PowerShell version 
Name                           Value
----                           -----
PSVersion                      5.1.22621.2506
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2506
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

azd version 161 (commit eba2c978b5443fdb002c95add4011d9e63c2e76f)

**Have you looked at the Troubleshooting and Logs section?**
 Yes 

**Screenshots**
![image](https://github.com/microsoft/azure_arc/assets/49276141/2669ef88-843c-493c-981b-665c338fc246)

**Additional context**

**Comment by dkirby-ms** [comment]
Sounds like you might be doing this in a Linux environment. You need to have PowerShell for Linux installed. Please review the prerequisites https://arcjumpstart.com/azure_jumpstart_hcibox/deployment_azd and make sure you have PowerShell available in your LInux shell.

**Comment by Chrisflyckelen** [comment]
@dkirby-ms Thanks for your help! 👍 I have overseen that a Linux environment is used to deploy. Everything works fine! 💯
