### ISSUE TITLE
Azure HCIBox - After logon script runs on HCIBox-Client I don't see the hosts in ARC Machines

### ISSUE THREAD

**Issue by jgarland-Insight** [microsoft/azure_arc#2434]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**

        HCIBox
        
        https://arcjumpstart.com/azure_jumpstart_hcibox/cloud_deployment

**Describe the issue or the bug**

          Using the Azure CLI Deployment instructions and Bicep template. All resources deploy correctly.   I log into the HCIBox-Client and the logon script runs and completes.  The next step in the instructions state: 

        In Azure portal, validate that both HCI nodes have been created as Arc-enabled servers.

        I don't see the nodes in Arc - Machines as shown in the accompanying photo.

**To Reproduce**

        According to the instructions, the nodes AzSHOST1 and AzHOST2 should be registered as ARC machines.  They aren't.

**Environment summary**

          az 2.57.0

**Have you looked at the Troubleshooting and Logs section?**

          Yes.  I see nothing related to ARC.

**Screenshots**

**Additional context**

**Comment by dkirby-ms** [comment]
This is because of the 2402 release changing the New-HciAdObjectsPreCreation command. I am working on a fix right now which should be available early next week.
