### ISSUE TITLE
HCIBox Bicep fails on CustomScriptExtension

### ISSUE THREAD

**Issue by jgarland-Insight** [microsoft/azure_arc#2441]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**

HCIBox
**Describe the issue or the bug**

When running the Bicep script, the deployment fails on HCIBox-Client/Bootstrap with the following error:

{"customHtml":{"htmlTemplate":"<code><div><div>VM has reported a failure when processing extension 'Bootstrap' (publisher 'Microsoft.Compute' and type 'CustomScriptExtension'). Error message: 'Command execution finished, but failed because it returned a non-zero exit code of: '1'. The command had an error output of: 'The system cannot find the file specified.\r\n''. More information on troubleshooting is available at <a target=\"_blank\" class=\"msportalfx-ext-link\" href=\"https://aka.ms/VMExtensionCSEWindowsTroubleshoot\">https://aka.ms/VMExtensionCSEWindowsTroubleshoot</a>. </div></div></code>","viewModel":null}}
**To Reproduce**

A working deployment of all resources without errors
**Environment summary**

az 2.57.0
**Have you looked at the Troubleshooting and Logs section?**

**Screenshots**

![image](https://github.com/microsoft/azure_arc/assets/134438777/fc049ee7-54d7-477e-86a5-1150dcfd2922)

**Additional context**

**Comment by dkirby-ms** [comment]
Looks like the Custom script extension could not find the Bootstrap.ps1 file. Did you use a different branch/repo for deploying by specifying the githubBranch and githubAccount parameters in your deployment? 

Please share your parameters file used for deploy minus any user credentials.

**Comment by jgarland-Insight** [comment]
You pointed me in the right direction.  I validated my parameters file and found an issue that I corrected.  My subsequent deployment worked fine.  Feel free to close the issue.

> Looks like the Custom script extension could not find the Bootstrap.ps1 file. Did you use a different branch/repo for deploying by specifying the githubBranch and githubAccount parameters in your deployment?
> 
> Please share your parameters file used for deploy minus any user credentials.
