### ISSUE TITLE
HCIBox: Cloud Deployment ARM Validation Failing

### ISSUE THREAD

**Issue by mmorrison57** [microsoft/azure_arc#2444]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**

https://github.com/Azure/arc_jumpstart_docs/tree/main/docs/azure_jumpstart_hcibox

**Describe the issue or the bug**
ARM validation using the custom deployment steps in Cloud Deployment section is failing. 

**To Reproduce**

**Have you looked at the Troubleshooting and Logs section?**

Yes

**Screenshots**
<img width="763" alt="image" src="https://github.com/microsoft/azure_arc/assets/116121519/01bed274-9f7f-472e-985a-72ec5a687c35">
![image](https://github.com/microsoft/azure_arc/assets/116121519/9db46e86-0ca1-4f20-aa0e-101164998e7e)
<img width="1838" alt="image" src="https://github.com/microsoft/azure_arc/assets/116121519/fc2315fe-c8a3-4d1e-a0d2-c197bdf3435b">

**Additional context**
I followed the guide directly to create a deployment using the custom template and values in the hci.json and hci.parameters.json files. Both I triple checked but to no avail getting a successful deployment.

**Comment by dkirby-ms** [comment]
We've observed this happening frequently since 2402 release. Use the "Try Again" button from the validation page in portal to retry the validation and it should go through without issue.

**Comment by mmorrison57** [comment]
Unfortunately the "Try Again" button is grayed out, since the validation itself is not successful. I have redeployed new HCI Boxes a few times and still am hitting errors in the validation phase. THe other error I am seeing multiple times is below:

`(401) {"error":"invalid_client","error_description":"AADSTS7000229: The client application 8XXXXXXXXXXXXXXXXXXXX is missing service principal in the tenant 7XXXXXXXXXXXXXXXXXXXXXXXX. See instructions here: https://go.microsoft.com/fwlink/?linkid=2225119 Trace ID: 8fb4398a-b57b-459e-9dc9-31750c300300 Correlation ID: 4e5443f9-e414-4e22-bbc7-827335333a7d Timestamp: 2024-03-07 01:12:53Z","error_codes":[7000229],"timestamp":"2024-03-07 01:12:53Z","trace_id":"8fb4398a-b57b-459e-9dc9-31750c300300","correlation_id":"4e5443f9-e414-4e22-bbc7-827335333a7d","error_uri":"https://login.microsoftonline.com/error?code=7000229"} (Code: InternalHttpClientError)`

**Comment by dkirby-ms** [comment]
Please check other permissions too against this list. https://learn.microsoft.com/en-us/azure-stack/hci/deploy/deployment-arc-register-server-permissions

In particular check that Microsoft.AzureStackHCI provider has been assigned properly per the doc. 

Please also share your C:\HCIBox\Logs\ folder zipped up here.

**Comment by matthansen0** [comment]
@mmorrison57 I had this same issue, once I assigned myself ``Key Vault Administrator`` and ``Storage Account Contributor``, then did another custom template deployment, and incremented the storage account and key vault values by 1 (or just delete the ones that were created in the past deployment) it still failed but it at least created the resources. After that, go to the re-validation page and hit "try again" and it will assign the key vault permissions and pass the Azure Resource validation, then you can hit try again (again) and it will pass the cluster validation. :) 

cc: @dkirby-ms, the deploy doc for jumpstart only says key vault admin right now, it should also include storage account contributor like is listed in the hci docs.

**Comment by dkirby-ms** [comment]
Addressed and closed in #2456
