### ISSUE TITLE
Issue while validating ARM template deployment for hciboxcluster

### ISSUE THREAD

**Issue by tarunjain123** [microsoft/azure_arc#2457]
I am following the guide here - https://azurearcjumpstart.io/azure_jumpstart_hcibox/cloud_deployment, section - "Validate cluster in Azure portal"

Deployment fails with the below error : 
`{
  "code": "DeploymentFailed",
  "target": "/subscriptions/4cb13157-1c3c-41ac-!!!!!!!!!/resourceGroups/tarun2hcibox-rg/providers/Microsoft.Resources/deployments/Microsoft.Template-20240315152702",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
  "details": [
    {
      "code": "ResourceDeploymentFailure",
      "target": "/subscriptions/4cb13157-1c3c-41ac-!!!!!!!!!!!/resourceGroups/tarun2hcibox-rg/providers/microsoft.azurestackhci/clusters/hciboxcluster/deploymentSettings/default",
      "message": "The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'."
    }
  ]
}`

If I go to the exact resource where the validation failed, i see the error below in hciboxcluster/default resource.

`{
  "code": "UpdateDeploymentSettingsDataFailed",
  "message": "Deployment Settings validation failed.",
  "details": [
    {
      "code": "UpdateDeploymentSettingsDataFailed",
      "target": "/subscriptions/4cb13157-1c3c-41ac-!!!!!!!!!!!!/resourceGroups/tarun2hcibox-rg/providers/Microsoft.AzureStackHCI/clusters/hciboxcluster",
      "message": "Failed to create deployment settings."
    }
  ]
}`

I have added both keyvault admin and storage account contributor roles in the resource group. I also tried adding few more permissions on hciboxcluster but the error persists.

**Comment by dkirby-ms** [comment]
Have you tried using the "try again" button from the deployments page of the hciboxcluster resource?

**Comment by tarunjain123** [comment]
I tried redeploying the template which didn't work. However, trying again in the hciboxcluster resource worked. Thanks for your help!
