### ISSUE TITLE
hciboxcluster deployment failing

### ISSUE THREAD

**Issue by tarunjain123** [microsoft/azure_arc#2466]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
https://azurearcjumpstart.io/azure_jumpstart_hcibox/cloud_deployment

**Describe the issue or the bug**
I am trying to complete the "Deploy cluster in Azure portal" section from the above guide. However, I am getting the below failure. I tried rerunning the deployment 3 times over the past couple of days, but I am getting the same error. 

I looked at a somewhat related issue here -> https://github.com/microsoft/azure_arc/issues/2411  which suggests that I need to start from scratch? Just wanted to double check on that before tearing down my environment. Thanks

`Name
Deploy Azure Stack HCI

Status
Error

Description
Deploy the Azure Stack HCI system.

Start Time
3/18/2024, 12:52:40 PM

End Time
3/19/2024, 4:13:53 PM

Exception
Type 'DeployArb' of Role 'MocArb' raised an exception: Exception while installing ARB in step [DeployArb:Calling Install-ArcHciMgmt] Correlation ID: 382dcbe3-1c02-4ce6-bcbe-3ea04ce7c252. C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd arcappliance prepare hci --config-file "C:\ClusterStorage\Infrastructure_1\Shares\SU1_Infrastructure_1\MocArb\WorkingDirectory\Appliance\hci-appliance.yaml" --only-show-errors returned a non empty error stream [ERROR: { "errorCode": "PrepareKvaTimeoutError", "errorResponse": "{\n\"message\": \"Appliance Prepare timed out\"\n}" }] at [at Invoke-ArcHciAzCommandLine, C:\Program Files\WindowsPowerShell\Modules\ArcHci\0.2.44\ArcHci.psm1: line 3046 at Invoke-ArcHciAzCommand, C:\Program Files\WindowsPowerShell\Modules\ArcHci\0.2.44\ArcHci.psm1: line 2972 at Install-ArcHciResourceBridge, C:\Program Files\WindowsPowerShell\Modules\ArcHci\0.2.44\ArcHci.psm1: line 3472 at Install-ArcHciMgmt, C:\Program Files\WindowsPowerShell\Modules\ArcHci\0.2.44\ArcHci.psm1: line 5478 at DeployArbInternal, C:\NugetStore\Microsoft.AzureStack.MocArb.LifeCycle.1.2402.0.16\content\Scripts\MocArbHelper.psm1: line 1444 at DeployArb, C:\NugetStore\Microsoft.AzureStack.MocArb.LifeCycle.1.2402.0.16\content\Scripts\MocArbLifeCycleManager.psm1: line 131 at <ScriptBlock>, C:\CloudDeployment\ECEngine\InvokeInterfaceInternal.psm1: line 127 at Invoke-EceInterfaceInternal, C:\CloudDeployment\ECEngine\InvokeInterfaceInternal.psm1: line 123] at at Install-ArcHciMgmt, C:\Program Files\WindowsPowerShell\Modules\ArcHci\0.2.44\ArcHci.psm1: line 5508 at DeployArbInternal, C:\NugetStore\Microsoft.AzureStack.MocArb.LifeCycle.1.2402.0.16\content\Scripts\MocArbHelper.psm1: line 1444 at DeployArb, C:\NugetStore\Microsoft.AzureStack.MocArb.LifeCycle.1.2402.0.16\content\Scripts\MocArbLifeCycleManager.psm1: line 131 at <ScriptBlock>, C:\CloudDeployment\ECEngine\InvokeInterfaceInternal.psm1: line 127 at Invoke-EceInterfaceInternal, C:\CloudDeployment\ECEngine\InvokeInterfaceInternal.psm1: line 123 Command Arguments ------- --------- DeployArbInternal {Parameters=CloudEngine.Configurations.EceInterfaceParameters} {} <ScriptBlock> {CloudEngine.Configurations.EceInterfaceParameters, MocArb, DeployArb, C:\NugetStore\Micr... Invoke-EceInterfaceInternal {CloudDeploymentModulePath=C:\NugetStore\Microsoft.AzureStack.Solution.Deploy.CloudDeploy... at Trace-Error, C:\NugetStore\Microsoft.AzureStack.MocArb.LifeCycle.1.2402.0.16\content\Scripts\Common\Tracer.psm1: line 63 at DeployArbInternal, C:\NugetStore\Microsoft.AzureStack.MocArb.LifeCycle.1.2402.0.16\content\Scripts\MocArbHelper.psm1: line 1512 at DeployArb, C:\NugetStore\Microsoft.AzureStack.MocArb.LifeCycle.1.2402.0.16\content\Scripts\MocArbLifeCycleManager.psm1: line 131 at <ScriptBlock>, C:\CloudDeployment\ECEngine\InvokeInterfaceInternal.psm1: line 127 at Invoke-EceInterfaceInternal, C:\CloudDeployment\ECEngine\InvokeInterfaceInternal.psm1: line 123`

**Screenshots**
![ScreenshotHciDeployError](https://github.com/microsoft/azure_arc/assets/82963626/9dc78cb2-f7c6-493d-a1fd-ebaf32eee9e4)

**Comment by dkirby-ms** [comment]
Probably easiest to redeploy if you've had multiple failures. There was also another issue with a build from last week #2462 that could be related if you deployed this before Monday.

**Comment by tarunjain123** [comment]
Redeploying did succeed. Thanks!
