### ISSUE TITLE
HCIBox Cluster failing at Deploy Arc Infrastructure have tried deployment several times

### ISSUE THREAD

**Issue by jostelma** [microsoft/azure_arc#2468]
### Discussed in https://github.com/microsoft/azure_arc/discussions/2467

<div type='discussions-op-text'>

<sup>Originally posted by **johnstel** March 22, 2024</sup>
I have deployed the HCIBox several times now and it gets stuck at Deploy Arc Infrastructure Management Components.  Can someone please help me with what node or server to start looking on to troubleshoot?

Type 'DeployArb' of Role 'MocArb' raised an exception: Exception while installing ARB in step [DeployArb:Calling Install-ArcHciMgmt] Correlation ID: a074e5a3-d7bb-4e44-9828-3d3d230c61e1. C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd arcappliance prepare hci --config-file "C:\ClusterStorage\Infrastructure_1\Shares\SU1_Infrastructure_1\MocArb\WorkingDirectory\Appliance\hci-appliance.yaml" --only-show-errors returned a non empty error stream [ERROR: { "errorCode": "PrepareKvaTimeoutError", "errorResponse": "{\n\"message\": \"Appliance Prepare timed out\"\n}" }] at [at Invoke-ArcHciAzCommandLine, C:\Program Files\WindowsPowerShell\Modules\ArcHci\0.2.44\ArcHci.psm1: line 3046 at Invoke-ArcHciAzCommand, C:\Program Files\WindowsPowerShell\Modules\ArcHci\0.2.44\ArcHci.psm1: line 2972 at Install-ArcHciResourceBridge, C:\Program Files\WindowsPowerShell\Modules\ArcHci\0.2.44\ArcHci.psm1: line 3472 at Install-ArcHciMgmt, C:\Program Files\WindowsPowerShell\Modules\ArcHci\0.2.44\ArcHci.psm1: line 5478 at DeployArbInternal, C:\NugetStore\Microsoft.AzureStack.MocArb.LifeCycle.1.2402.0.16\content\Scripts\MocArbHelper.psm1: line 1444 at DeployArb, C:\NugetStore\Microsoft.AzureStack.MocArb.LifeCycle.1.2402.0.16\content\Scripts\MocArbLifeCycleManager.psm1: line 131 at <ScriptBlock>, C:\CloudDeployment\ECEngine\InvokeInterfaceInternal.psm1: line 127 at Invoke-EceInterfaceInternal, C:\CloudDeployment\ECEngine\InvokeInterfaceInternal.psm1: line 123] at at Install-ArcHciMgmt, C:\Program Files\WindowsPowerShell\Modules\ArcHci\0.2.44\ArcHci.psm1: line 5508 at DeployArbInternal, C:\NugetStore\Microsoft.AzureStack.MocArb.LifeCycle.1.2402.0.16\content\Scripts\MocArbHelper.psm1: line 1444 at DeployArb, C:\NugetStore\Microsoft.AzureStack.MocArb.LifeCycle.1.2402.0.16\content\Scripts\MocArbLifeCycleManager.psm1: line 131 at <ScriptBlock>, C:\CloudDeployment\ECEngine\InvokeInterfaceInternal.psm1: line 127 at Invoke-EceInterfaceInternal, C:\CloudDeployment\ECEngine\InvokeInterfaceInternal.psm1: line 123 Command Arguments ------- --------- DeployArbInternal {Parameters=CloudEngine.Configurations.EceInterfaceParameters} {} <ScriptBlock> {CloudEngine.Configurations.EceInterfaceParameters, MocArb, DeployArb, C:\NugetStore\Micr... Invoke-EceInterfaceInternal {CloudDeploymentModulePath=C:\NugetStore\Microsoft.AzureStack.Solution.Deploy.CloudDeploy... at Trace-Error, C:\NugetStore\Microsoft.AzureStack.MocArb.LifeCycle.1.2402.0.16\content\Scripts\Common\Tracer.psm1: line 63 at DeployArbInternal, C:\NugetStore\Microsoft.AzureStack.MocArb.LifeCycle.1.2402.0.16\content\Scripts\MocArbHelper.psm1: line 1512 at DeployArb, C:\NugetStore\Microsoft.AzureStack.MocArb.LifeCycle.1.2402.0.16\content\Scripts\MocArbLifeCycleManager.psm1: line 131 at <ScriptBlock>, C:\CloudDeployment\ECEngine\InvokeInterfaceInternal.psm1: line 127 at Invoke-EceInterfaceInternal, C:\CloudDeployment\ECEngine\InvokeInterfaceInternal.psm1: line 123</div>

**Comment by petos32** [comment]
Hello,
I have the similar problem on the same step "Deploy the Arc infrastructure management components". Trying to redeploy cluster few times. Also redeploy the nested environment. The source of "how to: is here https://github.com/bfrankMS/CreateHypervVms/tree/master
Any Ideas or maybe you resolve the issue?
![image](https://github.com/microsoft/azure_arc/assets/110098628/17a96ff4-2f77-422d-a3c2-22bcd1795208)

**Comment by dkirby-ms** [comment]
The issue for the OP was that the VM host was deployed using the latest WS image and not the current pinned version used by the main branch. To fix this you will need to redeploy the environment from the latest main branch to ensure you are getting the pindown version of the VM host.

**Comment by petos32** [comment]
Finally the solution for me was to run hyper-v nested deployment on the vmware vsphere with the newest verision 23H2.

**Comment by dkirby-ms** [comment]
Apologies for the acronym usage. 

OP = original poster, the author of this issue. 
WS = windows server.
