### ISSUE TITLE
PowerShell error when running the configure-AKSWorkloadCluser.ps1

### ISSUE THREAD

**Issue by IAmITGeek84** [microsoft/azure_arc#2469]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
[](https://azurearcjumpstart.io/azure_jumpstart_hcibox)

**Describe the issue or the bug**
I have sucessfully deployed the HCI box in my Azure subscriptiona and followed the pre-requisite steps to setup a Kubernetes Cluster. I have updated the ps1 file with the Object ID of my security group, however when I run the PowerShell script to setup the AKS cluster I get the following error:

2024-03-23 21:49:29.047726 Error: BadRequest
Detail: admission webhook "vhybridakscluster.kb.io" denied the request: Logical network hcibox-aks-lnet-vlan110 does not have an ippool.

The AKS cluster gets created but in a failed state

**To Reproduce**
Running this scrip should successfully create the AKS cluster in an active state

**Environment summary**

**Have you looked at the Troubleshooting and Logs section?**

**Screenshots**

**Additional context**

**Comment by dkirby-ms** [comment]
This looks like a similar issues to #2474

**Comment by IAmITGeek84** [comment]
Apologies I am not familiar with the process of logging a support issue in GitHub. Can you explain what the resolution is for this? What do I need to do to get this working in my environment?

From: Dale Kirby ***@***.***>
Date: Tuesday, 26 March 2024 at 15:35
To: microsoft/azure_arc ***@***.***>
Cc: IAmITGeek84 ***@***.***>, Author ***@***.***>
Subject: Re: [microsoft/azure_arc] PowerShell error when running the configure-AKSWorkloadCluser.ps1 (Issue #2469)

Closed #2469<https://github.com/microsoft/azure_arc/issues/2469> as completed via #2475<https://github.com/microsoft/azure_arc/pull/2475>.

**Comment by dkirby-ms** [comment]
Apologies @IAmITGeek84 

Try the following to fix the issue in your environment.

1) Grab the latest version of [Configure-AKSWorkloadCluster.ps1](https://github.com/microsoft/azure_arc/blob/main/azure_jumpstart_hcibox/artifacts/PowerShell/Configure-AKSWorkloadCluster.ps1)
2) From Azure portal, delete the _hcibox-aks-lnet-vlan110_ Az Stack HCI Logical network
3) Uncomment and add your AAD groupID to the script
4) re-run the script
