### ISSUE TITLE
Bug HCIBox failing at cluster validation

### ISSUE THREAD

**Issue by jonathan-vella** [microsoft/azure_arc#2470]
After submitting the custom deployment I'm getting the following error:

![extensions](https://github.com/microsoft/azure_arc/assets/25802147/10249388-5c4f-408e-a25b-2061b061bdf0)
Exception encountered while adding node to cluster [Resource validation failed. Details: [{"Code":"ValidationFailed","Message":"Arc extensions installed on Arc Machine  /subscriptions/my-sub-id
![extensions](https://github.com/microsoft/azure_arc/assets/25802147/9fc29cb0-c958-46ac-9169-56ea3c290385)
/resourceGroups/hcibox-rg/providers/Microsoft.HybridCompute/machines/AzSHOST2 are DeviceManagementExtension, TelemetryAndDiagnostics, EdgeRemoteSupport while required list of mandatory arc extensions are TelemetryAndDiagnostics, DeviceManagementExtension, LcmController","Target":null,"Details":null}

**Comment by jonathan-vella** [comment]
Udate: Validation was successful after retrying the same but waiting for 10-15mins before kicking off validation.

**Comment by dkirby-ms** [comment]
Thanks, perhaps extensions were not fully installed yet.
