### ISSUE TITLE
AKS on HCI setup failing

### ISSUE THREAD

**Issue by tarunjain123** [microsoft/azure_arc#2476]
I am following the guide here - https://azurearcjumpstart.com/azure_jumpstart_hcibox/AKS

My AKS cluster status is showing as 'Connecting' from past 1 day and Provisioning State as 'Failed'

![image](https://github.com/microsoft/azure_arc/assets/82963626/33df9df6-881d-48c0-a472-3bf749efae73)

[Configure-AKSWorkloadCluster.log](https://github.com/microsoft/azure_arc/files/14791444/Configure-AKSWorkloadCluster.log)

**Comment by dkirby-ms** [comment]
Hi @tarunjain123, is this still something you are seeing? I would recommend a full redeploy, or you can delete the AKS cluster and logical network and reprovision it.
