### ISSUE TITLE
Jumpstart HCIBox 23H2 Deployment - Where or how to get Windows Admin Center

### ISSUE THREAD

**Issue by WVDAdminTF** [microsoft/azure_arc#2490]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
https://azurearcjumpstart.com/azure_jumpstart_hcibox

**Describe the issue or the bug**
I have deployed twice and in both instances, the Windows Admin Center is missing, additionally I am not able to get the Windows Admin Center from the Azure Portal to connect to the Jumpstart HCIBox deployled PERFECTLY/Flawlessly with all features enabled as per the link - https://azurearcjumpstart.com/azure_jumpstart_hcibox/AKS
![Jumpstart HCIBox](https://github.com/microsoft/azure_arc/assets/84956733/2ac45382-f9d1-42f9-a44c-7fdec62b14fc)

**To Reproduce**
Follow the link - https://azurearcjumpstart.com/azure_jumpstart_hcibox

**Expected behavior**
Is the Expected behavior

**Environment summary**
![Jumpstart HCIBox](https://github.com/microsoft/azure_arc/assets/84956733/1f4b8132-e636-4dfd-b20c-91c4c84fd9c2)

**Have you looked at the Troubleshooting and Logs section?**
all logs seems fine

**Screenshots**
![Screenshot 2024-04-05 124937](https://github.com/microsoft/azure_arc/assets/84956733/9ccc749d-4993-403e-9e64-b7e1447fb3af)
**Additional context**
![Windows Admin Center not-included why](https://github.com/microsoft/azure_arc/assets/84956733/3d19d19b-01e5-47ba-b91b-9681a212e46d)

@dkirby-ms
Please advice

**Comment by WVDAdminTF** [comment]
![Screenshot 2024-04-05 130302](https://github.com/microsoft/azure_arc/assets/84956733/202125e2-afd5-4e5a-aa5e-38677023a3b3)

**Comment by dkirby-ms** [comment]
Hi @WVDAdminTF

You found a documentation bug in that diagram you posted. The diagram needs to be updated as HCIBox no longer includes the WAC gateway server. WAC can be used from Azure portal with HCIBox as the default option. Configuring a WAC gateway server is no longer included.

We can fix the documentation to reflect this to update the diagram and table.

As far as WAC portal experience not working, do you have any error messages showing on the extension failure?

**Comment by dkirby-ms** [comment]
Will be addressed by this https://github.com/Azure/arc_jumpstart_docs/pull/279

**Comment by WVDAdminTF** [comment]
Hi Dale @dkirby-ms 

Apologies as I could not reply earlier, yes I have the same error in both instances of the Extension, I had posted the error on Friday below my post, 

please advice

![image](https://github.com/microsoft/azure_arc/assets/84956733/cd5acea8-8f41-428e-bfaa-0f38983271bd)

AdminCenter
Type
Microsoft.AdminCenter.AdminCenter
Status
Failed
Automatic upgrade
Enabled
Version
0.0.0.340
Status level
Error
Status message
Extension Message: Enabling Windows Admin Center, SearchingForWindowsAdminCenter: Windows Admin Center is not installed, CheckingIfWindowsAdminCenterInstalled: Windows Admin Center is not installed
Resource ID
/subscriptions/04f8237b-238d-4ddf-89a5-d504a132476c/resourceGroups/[RG4HCIBox](https://portal.azure.com/#@M365x83150050.onmicrosoft.com/resource/subscriptions/04f8237b-238d-4ddf-89a5-d504a132476c/resourceGroups/RG4HCIBox/overview)/providers/Microsoft.HybridCompute/machines/AzSHOST1/extensions/AdminCenter

**Comment by dkirby-ms** [comment]
Uninstall the WAC extensions and try to reinstall.

**Comment by sumitmalik51** [comment]
Hi @WVDAdminTF , were you able to resolve this this issue? Getting the same in my cluster as well.

**Comment by janegilring** [comment]
@sumitmalik51 We currently have a known issue regarding WAC on HCI:

The WAC .MSI installer temp file is blocked by the Windows Defender Application Control (WDAC), which causes the WAC installation failure.

Changing the policy to Audit mode will make it possible to install the MSI-fil, so you can use this as a temporary workaround until an updated WAC extension is published.
