### ISSUE TITLE
After successful installation of HCIBOX : VM Images : There was an error while fetching Images.

### ISSUE THREAD

**Issue by jbthefish** [microsoft/azure_arc#2501]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**

HCIBox

https://arcjumpstart.com/azure_jumpstart_hcibox

**Describe the issue or the bug**

After successful installation of HCIBOX : VM Images : There was an error while fetching Images. Therefore i can not deploy any VM
![2024-04-16 12_57_43-hciboxcluster - Microsoft Azure](https://github.com/microsoft/azure_arc/assets/71874172/03494f24-2d9d-4e93-9594-1d19cdb90bb1)

**To Reproduce**
I just did a simple installation with biceps as stated in the documentation. The installation in deployment in the cloud was WITHOUT any error.

**Expected behavior**
I would expect to be able to add images as basis for a deployment of a VM.

![image](https://github.com/microsoft/azure_arc/assets/71874172/89e9efa7-be75-4eac-9d10-516b323f226a)

**Environment summary**
OS Build : 25398.763
Cluster name : hciboxcluster
OS name : Azure Stack HCI
OS version : 23H2

Thanks,
JB

**Comment by janegilring** [comment]
@jbthefish Could you try to reboot the Azure Resource Bridge appliance VM which is running in the cluster, wait 5-10 minutes and then retry the process of adding a VM image?

**Comment by jbthefish** [comment]
@janegilring : Thanks for your response. I do not know how to restart the Azure Resource Bridge appliance VM.

Is see the bridge in the portal in the RG - see picture, but there is NOT restart button / function.

![image](https://github.com/microsoft/azure_arc/assets/71874172/c34760a0-e922-446a-8239-b27fe4225048)

I do NOT see the brigde on the on the cluster - see picture.

![image](https://github.com/microsoft/azure_arc/assets/71874172/9e076570-0fac-4cb8-8299-4a5ca74616b6)


Please advice.
Thanks a lot.
JB

**Comment by janegilring** [comment]
@jbthefish Sorry for not providing detailed steps, however, you are in the right place. The resource bridge is the VM starting with the name _f59e_. If you stop/start that VM and try again to download images 10-15 minutes later - let us see what happens.

**Comment by jbthefish** [comment]
@janegilring : It did not help.  If want to create an image from the marketplace the image section is not filled. How ever i was now able to create an image from a Storage account i have in the cloud. I need to use the public images as well.

Thanks,JB

![image](https://github.com/microsoft/azure_arc/assets/71874172/cb64bc2c-485e-4a72-ab50-687bfaf30c39)

**Comment by janegilring** [comment]
@jbthefish Interesting, could you try to see if it works when using the Azure CLI in order to determine whether the issue is a portal issue or a resource bridge issue?

`az stack-hci-vm image create --subscription $subscription --resource-group $resource_group --custom-location $customLocationID --location $location --name "<VM image name>" --os-type $ostype --offer "windowsserver" --publisher "<Publisher name>" --sku "<SKU>" --version "<Version number>" --storage-path-id $storagepathid`

Complete instructions is available [here](https://learn.microsoft.com/en-us/azure-stack/hci/manage/virtual-machine-image-azure-marketplace?tabs=azurecli).

**Comment by jbthefish** [comment]
@janegilring : I ran the command as requested: 

PS C:\Users\siemens> az stack-hci-vm image create --subscription $subscription --resource-group $resource_group --custom-location $customLocationID --location $location --name "Win11E" --os-type $ostype --offer "windowsserver" --publisher "microsoftwindowsdesktop" --sku "win11-22h2-avd-m365" --version "22621.382.220810"
Command group 'stack-hci-vm' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus

Deployment failed. Correlation ID: e580a2a8-28cb-4614-b121-07041875ea2b. Failed to generate SAS token for the URN: microsoftwindowsdesktop:windowsserver. Status code: InternalServerError, Error details: {"error":{"code":"AadTokenAcquisitionFailed","message":"Failed to send request to Microsoft.EdgeMarketPlace due to aad authentication error."}}

For your information:  I was able to add an image from a storage account. and there prob. create a VM. The problem seems to be limited to the Marketplace images. 

![image](https://github.com/microsoft/azure_arc/assets/71874172/5d1513e8-b807-423f-b4d9-e4846d19fb84)

**Comment by janegilring** [comment]
@jbthefish Thanks, that helps with regards to understanding the culprit. After checking internally, the advise is to create a support ticket to investigate the root cause of the issue.

Feel free to re-open this issue if it turns out to be related to our automations.
Regardless, it would be good if you circle back with information about the outcome of the ticket.

**Comment by jbthefish** [comment]
@janegilring : Yes, i tried that and the ticket was NOT accepted. It was open and closed right away, with reference that they (MS official support) do not support this solution and that the only way i would get any support would be via Github. So i tried with you . The funny thing is, i have various Azure HCI Stack enviroments running, none with fully qualified hardware, all with VM based on Hyper-V like the approach you used. In the cloud i would be able to run a bigger VM for more intensive testing....but without an image, no testing. Please advice what to do next.

Thank you very much,
JB

**Comment by janegilring** [comment]
@jbthefish Sorry to hear that. Could you reach out to me via LinkedIn (search for Jan Egil Ring, Microsoft) so we can work on the issue and I will try to bring the issue to the product group?

We will update this GitHub issue after resolving the problem.
