### ISSUE TITLE
VM has reported a failure when processing extension 'Bootstrap' (publisher 'Microsoft.Compute' and type 'CustomScriptExtension')

### ISSUE THREAD

**Issue by potejasw** [microsoft/azure_arc#2503]
**Is your issue related to a Jumpstart scenario, HCIBox**

**Describe the issue or the bug**

**To Reproduce**

**Environment summary**

azure-cli                         2.56.0 *

core                              2.56.0 *
telemetry                          1.1.0

Extensions:
init                               0.1.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2
>>
**Have you looked at the Troubleshooting and Logs section?**

**Screenshots**

**Additional context**

**Comment by sebassem** [comment]
can you share more information, screenshots on the error ? Have you tried a redeployment ?

**Comment by potejasw** [comment]
Yes, I have tried the redeployment its failed with same error. 
![image](https://github.com/microsoft/azure_arc/assets/167393722/61d467f5-5377-4924-99e2-331782209a9a)

**Comment by sebassem** [comment]
this looks like a problem with the service principal credentials. Please double check that you have [provided the right SPN credentials](https://azurearcjumpstart.com/azure_jumpstart_hcibox/troubleshooting) with the right permissions. If all looks good please RDP into the machine and share the `bootstrap.log`

**Comment by potejasw** [comment]
I tried to build the HCIBox from the begging as a fresh deployment. Again its failed with same error.
This time I made sure provided the SPN ID and details.

![image](https://github.com/microsoft/azure_arc/assets/167393722/6f05a7d4-c9ce-4c62-9cd5-b98f79fad9d9)
![image](https://github.com/microsoft/azure_arc/assets/167393722/ebc31d2d-10d7-48a6-8ab9-08a7906b6c5c)
![image](https://github.com/microsoft/azure_arc/assets/167393722/e02c64f3-05b0-4f4c-a19f-93c11cb1cac0)

VM has deployed and I don't see the Bootstrap log under this location: C:\HCIBox\Logs\Bootstrap.log
![image](https://github.com/microsoft/azure_arc/assets/167393722/46cb1f5f-2086-4eec-aea1-1e461c6acf78)

![image](https://github.com/microsoft/azure_arc/assets/167393722/9f7234ff-c5ee-4664-b82f-9c19c3ab03ae)

**Comment by sebassem** [comment]
can you share your parameters file with obfuscating the secrets ?

**Comment by potejasw** [comment]
[main.parameters.json](https://github.com/microsoft/azure_arc/files/15076654/main.parameters.json)

Attached.

**Comment by sebassem** [comment]
When did you clone the repo? I assume it's an old copy since there are [some parameters](https://azurearcjumpstart.com/azure_jumpstart_hcibox/deployment_az#deploy-the-bicep-template) not available in your file. Also please double check in the `main.bicep` file that the `githubAccount` is set to microsoft and `githubBranch` is set to main. If that's the case, please perform a new clone

**Comment by sebassem** [comment]
have you changed the property `imageReference` in the host.bicep file ?

**Comment by sebassem** [comment]
@dkirby-ms any thoughts on this ?

**Comment by dkirby-ms** [comment]
@potejasw you need to revoke/rotate your SPN secret immediately if you havent already.

**Comment by potejasw** [comment]
Yes, Wiped out all RG and starting the new build.

**Comment by sebassem** [comment]
Hello @potejasw , what is your current status?

**Comment by sebassem** [comment]
Thanks for the update, glad you got it working. Will close the issue now as resolved.
