### ISSUE TITLE
Linux nested VMs do not automatically onboard to Arc

### ISSUE THREAD

**Issue by soderholmd** [microsoft/azure_arc#2516]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
ArcBox

**Describe the issue or the bug**
When deploying ArcBox for IT Pros, the Windows virtual machines are automatically onboarded to Arc but the Linux ones are not. On investigation, I found that the Linux repo for azcmagent is not trusted and so the installation script exits with an error message:

```
Get:1 https://packages.microsoft.com/ubuntu/22.04/prod jammy main
Err:1 https://packages.microsoft.com/ubuntu/22.04/prod jammy main
Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)

```
The same occurs with a manual installation (downloading and running the public Arc installation script). A temporary workaround is to add `[trusted=yes]` to the `/etc/apt/sources.list.d/microsoft-prod.list` file but this is not recommended for security reasons.

Once agent was manually installed using above workaround, Arc functioned normally.

**To Reproduce**
1. Observe that a newly deployed ArcBox installation creates Arc objects for Windows but not Linux
2. Verify installation status of azcmagent on Linux nested VMs
3. Attempt to follow manual installation steps in https://learn.microsoft.com/en-us/azure/azure-arc/servers/onboard-portal

**Expected behavior**
Linux virtual machine resources should be created automatically on ArcBox deployment

**Environment summary**
AZ CLI version 2.59; ArcBox deployment carried out via portal method.

**Comment by janegilring** [comment]
Hi @soderholmd - I have now deployed two instances of ArcBox without being able to repro.

![image](https://github.com/microsoft/azure_arc/assets/2039662/7314e661-b704-4a57-8327-a7c558b0409d)

Could you double check that you are deploying from the latest version of the code from the main branch, and if so - try a new deployment to see if it was an intermittent issue or whether it is reproducible? If so, we can connect 1:1 and compare our environments.

**Comment by janegilring** [comment]
Closing the issue for now, feel free to re-open if you still encounter the issue.
