### ISSUE TITLE
providers/Microsoft.EventGrid/eventSubscriptions/StorageAntimalwareSubscription' doesn't exist

### ISSUE THREAD

**Issue by Lucas-Edson** [microsoft/azure_arc#2521]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
HCIBox

**Describe the issue or the bug**
When deploying HCIBox,  deployment process fails at "Deploy Arc infrastructure components", even though Defender for Cloud services are fully enabled on the subscription

**To Reproduce**
After the cluster verification process, the following error occurs and is unable to complete the process: 

providers/Microsoft.EventGrid/eventSubscriptions/StorageAntimalwareSubscription' doesn't exist

Environment summary
Azure Portal

**Comment by dkirby-ms** [comment]
Any chance you can share a screenshot of this error? We have not seen something like this specifically before related to StorageAntimalware

**Comment by Lucas-Edson** [comment]
After going through everything, bringing down the environment several times and re-trying. I finally got it to finish by removing all Azure Policies from the RG created (with exceptions). – Therefore, the issue was a policy conflict, however, I don’t know exactly which one, as there are no error messages pointing to any specific setting.

[A black background with red text  Description automatically generated]
  Lucas Edson
  Azure Solutions & Cybersecurity Architect Expert, MCSE, CCIE, CISSP
  IS Architect
  E: ***@***.***
1935 Medical District Drive | Dallas, TX 75235
Follow Children’s Health℠ childrens.com<https://www.childrens.com/>  ***@***.*** <https://www.facebook.com/childrens>  ***@***.*** <https://twitter.com/Childrens>  ***@***.*** <https://www.youtube.com/user/ChildrensMedical>  ***@***.*** <https://www.linkedin.com/company/childrenshealth/?original_referer=https%3A%2F%2Fwww.childrens.com%2F>  ***@***.*** <https://www.instagram.com/childrens/> ***@***.*** ***@***.***>
