### ISSUE TITLE
Cannot RDP/Bastion into a stack HCI vm ceated on a logical network on a HCIBOX environment from the HCIBox-Client

### ISSUE THREAD

**Issue by mukundansampath** [microsoft/azure_arc#2566]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
HCIBox

**Describe the issue or the bug**
Following https://azurearcjumpstart.com/azure_jumpstart_hcibox/RB I am able to create windows vms using the HCIBox with a marketplace image with a logical network. However the vms are not reachable via RDP or bastion.
I can see that they have IPs like 192.168.200.2 and so on

**To Reproduce**
1. Import a stack HCI image from marketplace(Say Win10 multi session)
2. Create the logical network using the Configure-VmLogicalNetwork.ps1
3. Create vms on the logical network with the above image created in step 1
4. The vms are spun with IP addresses say 192.168.200.2 and so on
5. The vms are unreachable from the HCIBox-Client
6. So the vms are pretty much useless

From the HCIBox-Client I tried RDP and also tried using the bastion client - 
Sample - 
 az network bastion rdp --name HCIBox-Bastion --resource-group msam-azurearc-rg --target-resource-id /subscriptions/<xyx>/resourceGroups/msamAzureArcPoolRg/providers/Microsoft.HybridCompute/machines/msamStackHciPool000

 az network bastion rdp --name HCIBox-Bastion --resource-group msam-azurearc-rg --target-ip-address 192.168.200.2

**Expected behavior**
Steps to RDP/Bastion into these vms to unblock our development.

**Environment summary**
AZ version - PS C:\Users\msampathkumar> az --version
azure-cli                         2.60.0
core                              2.60.0
telemetry                          1.1.0
Extensions:
bastion                            0.3.0

**Have you looked at the Troubleshooting and Logs section?**
Yes

**Screenshots**
<img width="1712" alt="Screenshot 2024-05-20 at 7 11 01 PM" src="https://github.com/microsoft/azure_arc/assets/8877470/c04c58c6-31c0-434a-9e86-2f1a128b5e48">

**Additional context**
Steps to RDP/Bastion into these vms to unblock our development.
The tutorial needs to have this updated as the new logical switch and logical network seem to be isolated

**Comment by mukundansampath** [comment]
This bug is lying around for sometime. And help will be really appreciated. Is a virtual switch the missing link https://learn.microsoft.com/en-us/azure-stack/hci/manage/create-logical-networks?tabs=azurecli?

**Comment by mukundansampath** [comment]
[janegilring](https://github.com/janegilring) Can you please help?

**Comment by codykal** [comment]
Having the same issue.  I've tried RDP and and no matter what cannot get a connection to the VM's, even from within AZMSMGT. Even tried pinging the VMs from within the nodes themselves with no success, although with the complex VLAN setup, I could be messing something up.

I tried to get around this by using Windows Admin Center to connect correctly via Azure Portal to get into the VM's that way. The Windows Admin Center Extension supposedly installs correctly, but whenever I try to access it, it says Access denied even though I have Windows Admin Center Administrator Login Permission on the Resource group and specific cluster resource. 

I've tried accessing admin center through the arc connected nodes themselves as well, but I get an odd error:

<img width="480" alt="Error" src="https://github.com/microsoft/azure_arc/assets/95980305/c660e0b5-6cc0-4865-84a2-2e581af97407">

I looked through the New-HCIBoxCluster.ps1 file and it looks like provisioning a dedicated WAC VM was commented out at some point. 

So as of now, we have no access to any of the provisioned VMs either.

Any help would be greatly appreciated :)

**Comment by janegilring** [comment]
As the subnet the HCI VMs resides on is on the second nested layer, it is necessary to connect to the AzSMGMT machine to be able to connect to those VMs:

![image](https://github.com/microsoft/azure_arc/assets/2039662/1cd81a40-7808-49cd-9f77-2ba81f83cf00)

The subnet is also not routable into the Azure Virtual Network, hence it won`t be possible to connect to virtual machines on the HCI cluster using Azure Bastion.

You can run `mstsc /v:192.168.1.11` from HCIBox-Client to connect to the AzSMGMT nested VM.
From there, run `mstsc /v:192.168.200.x `to connect to the HCI VMs (replace x with the IP of your deployed VM):

![image](https://github.com/microsoft/azure_arc/assets/2039662/9a0fc7a6-d707-45cd-846a-80b3335dc84e)

**Comment by mukundansampath** [comment]
That worked. Please consider including this in the documentation going forward. Hard for newbies to hyper V and stack HCI to figure this out. Had to try out various approaches for 4 weeks....

Feel free to close this bug. Thanks

**Comment by janegilring** [comment]
@mukundansampath Thanks for the update and the feedback, we will take this into consideration.

**Comment by likamrat** [comment]
Re-open for future docs enhancement tracking

**Comment by ldabas-msft** [comment]
This issue has been resolved:
https://github.com/Azure/arc_jumpstart_docs/pull/423
