### ISSUE TITLE
HCI box unable to create RG - Unable to acquire a token error.

### ISSUE THREAD

**Issue by potejasw** [microsoft/azure_arc#2571]
**Is your issue related to a Jumpstart scenario, HCIBox?**

https://arcjumpstart.com/azure_jumpstart_hcibox/deployment_azd

**Describe the issue or the bug**

**To Reproduce**

**Expected behavior**

**Environment summary**

**Have you looked at the Troubleshooting and Logs section?**
<!Its in the initial stage of creating RG

**Screenshots**

![image](https://github.com/microsoft/azure_arc/assets/167393722/ef548a00-9bd8-45f4-8b8a-987542dfe3c1)

**Additional context**

**Comment by janegilring** [comment]
@potejasw Could you do a git pull and try again?

We just merged this enhancement: https://github.com/microsoft/azure_arc/pull/2573

I tested locally using the following conditions:
- Windows 11
- Azure CLI 2.61
- Azure PowerShell 12.00
- Azure Developer CLI 1.9.3

![image](https://github.com/microsoft/azure_arc/assets/2039662/3dcce844-aece-4c4a-b5a3-2928afc9c436)

Triggering the deployment went fine when using the updated logic:
![image](https://github.com/microsoft/azure_arc/assets/2039662/2b471557-0ffe-4f11-b39e-a19bf0661f79)

**Comment by potejasw** [comment]
@janegilring I will check on this and update you.

**Comment by potejasw** [comment]
@janegilring We have passed the stage of tenant issue and we are stuck with number CPU's in eastUS region are seeing less when customer execute the command. With other region also customer sees less CPUs.
But when I execute at my laptop it shows normal. 

Current error we are getting is “There is not enough VM capacity in the eastus region to deploy the Jumpstart environment”.
Checking other regions in the same geography with enough capacity (32 cores)

![image](https://github.com/microsoft/azure_arc/assets/167393722/249e66ee-40f5-4ba1-8208-9c952e2546b5)

Output when I executed from my machine.


PS C:\Users\Username> az vm list-usage --location EastUS --output table --query "[].{Name:localName, Current:currentValue, Limit:limit, Unit:unit, Status:status}"
Name                                      Current    Limit
----------------------------------------  ---------  -------
Availability Sets                         0          2500
Total Regional vCPUs                      64         100
Virtual Machines                          2          25000
Virtual Machine Scale Sets                0          2500
Dedicated vCPUs                           0          3000
Cloud Services                            0          2500
Total Regional Low-priority vCPUs         0          100
**Standard ESv5 Family vCPUs                64         100**

**Comment by dkirby-ms** [comment]
Customer needs to increase their vCPU quota. They are showing a limit of 20 regional vCPU. This is an issue with the vCPU quota on the targeted subscription.

**Comment by potejasw** [comment]
Thank you for your response. I will share the same with customer and update you.

**Comment by janegilring** [comment]
@potejasw In the Azure portal, go the subscription targeted for HCIBox deployment, select `Usage + Quotas`, select `Provider:Compute`, select the target Azure region and request increasing the relevant quotas by clicking the button in the column `Adjustable` :

![image](https://github.com/microsoft/azure_arc/assets/2039662/83ad4b26-491a-43de-9cdf-f338839e2cd3)

**Comment by potejasw** [comment]
Thank you for your update and the screenshot. I will share the same with customer and share you the results

**Comment by janegilring** [comment]
@potejasw Any updates or are we good to close this issue?

**Comment by potejasw** [comment]
I apologise for not responding to this thread. The issue has been resolved. You can go ahead and close the case.

**Comment by janegilring** [comment]
No worries, thanks for the update.
