### ISSUE TITLE
Azure Kubernetes Service on Azure Stack HCI - connectK8 Guidance

### ISSUE THREAD

**Issue by ddesonier** [microsoft/azure_arc#2578]
**Is your feature request related to a new Jumpstart scenario you would like to contribute?**

No

**Is your feature request related to a problem? Please describe.**

When deploying AKS as described in the Azure Kubernetes Service on Azure Stack HCI section, the command 
`az connectedk8s proxy -n hcibox-aks -g <name of your resource group>`
resulted in an error in az cli
`Failed to post access token to client proxyFailed to connect to MSI. Please make sure MSI is configured correctly.
Get Token request returned: <Response [400]>`
From Az Powershell the error was
`The command failed with an unexpected error. Here is the traceback:
Cannot load native module 'Crypto.Hash._MD5': Not found '_MD5.cp311-win_amd64.pyd', Cannot load '_MD5.pyd': cannot load library 'C:\Users\ddesonier\.azure\cliextensions\connectedk8s\Crypto\Util\..\Hash\_MD5.pyd': error 0xc1`

**Describe the solution you'd like.**

This is easily resolved when updating connectedK8s
`az extension update --name connectedk8s`
Suggest adding a call out box or add to trouble shooting

**Describe alternatives you've considered.**

**Additional context.**

**Comment by likamrat** [comment]
Re-open for future docs enhancement tracking

**Comment by ldabas-msft** [comment]
Adding a callout in the docs to run ```az extension update --name connectedk8s``` before running connectedk8s
