### ISSUE TITLE
Need the steps to restart the HCIBox ArcBridge

### ISSUE THREAD

**Issue by mukundansampath** [microsoft/azure_arc#2585]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
HCIBox

**Describe the issue or the bug**
The HCIBox arcbridge goes offline often and affects new vm creation in the Stack HCI cluster. Need a way to restart the underlying linux vm whenever it goes offline.
Screenshot below - 
<img width="1699" alt="Screenshot 2024-06-21 at 11 25 10 AM" src="https://github.com/microsoft/azure_arc/assets/8877470/05687b25-4152-4efb-9473-bda0952560ed">

**To Reproduce**
1. After setting up the HCIBox leave after a few days check the status of the ArcBridge. Notice that it goes offline

**Expected behavior**
Need a way to restart the underlying vm 
Is it a nested vm inside the AzMgmt Appliance? Cannot find it anywhere

**Environment summary**
All envs

**Have you looked at the Troubleshooting and Logs section?**
Yes

**Screenshots**
Attached above

**Additional context**

**Comment by janegilring** [comment]
@mukundansampath The Resource Bridge VM runs inside of the Azure Stack HCI cluster. One option to reach the management plane of cluster is to logon to the domain controller VM, which you can find in Hyper-V Manager on the AzMgmt virtual machine. When logged on to the domain controller, open Failover Cluster Manager (you might need to install the Failover Clustering management tools to see this tool within Server Manager). When connected to the cluster, you will see a virtual machine resource with a GUID as its name. That is the Resource Bridge, which you can then stop/start as needed.

**Comment by mukundansampath** [comment]
Thanks. Will try this out....

**Comment by janegilring** [comment]
Great, closing for now - feel free to re-open if needed.
