### ISSUE TITLE
Example of a Supported Linux Box Build 

### ISSUE THREAD

**Issue by MBCloudTeck** [microsoft/azure_arc#2594]
Please advise examples of building suitable boxes to be able to install these commands on. 

Explain this with zero knowledge assumed. - Even if it points to a standard build video. There are variables that are required to get the point of install, that are not obvious to a windows admin, working on a Linux box, for example. 

Existing Linux server
Existing Windows server

**Comment by likamrat** [comment]
@MBCloudTeck i will go ahead and close this for now. Please reply if you have more questions.
