### ISSUE TITLE
Upcoming breaking change in Get-AzAccessToken

### ISSUE THREAD

**Issue by sebassem** [microsoft/azure_arc#2611]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
ArcBox and HciBox

**Describe the issue or the bug**
[Get-AzAccessToken](https://learn.microsoft.com/powershell/azure/upcoming-breaking-changes?view=azps-12.1.0#get-azaccesstoken)
Cmdlet breaking-change will happen to all parameter sets
The Token property of the output type will be changed from String to SecureString. Add the [-AsSecureString] switch to avoid the impact of this upcoming breaking change.
This change is expected to take effect from Az.Accounts version: 4.0.0 and Az version: 13.0.0

**To Reproduce**
N/A

**Expected behavior**
N/A

**Environment summary**
N/A
**Have you looked at the Troubleshooting and Logs section?**

**Screenshots**

**Additional context**

**Comment by dadthiele** [comment]
Will there be a way to get the plain text version? eg. for use with invoke-sql which does not use securestring

**Comment by sebassem** [comment]
> Will there be a way to get the plain text version? eg. for use with Invoke-Sqlcmd which does not use securestring
> 
> https://learn.microsoft.com/en-us/powershell/module/sqlserver/invoke-sqlcmd?view=sqlserver-ps $access_token = (Get-AzAccessToken -ResourceUrl https://database.windows.net).Token

Yes its passed as plain text
