### ISSUE TITLE
New-HCIBoxCluster Script Fails at Step 6 of 11

### ISSUE THREAD

**Issue by rbrk-tpm-jshaver** [microsoft/azure_arc#2617]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
HCIBox

**Describe the issue or the bug**
During the New-HCIBoxCluster script execution on HCIBox-Client, the script fails during step 6 with the following error:
[Build cluster - Step 6/11] Configuring host networking and storage...
Testing whether VMs are available...
VM AzSMGMT is now online
VM AzSHOST1 is now online
VM AzSHOST2 is now online
PS>TerminatingError(): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The credential is invalid."
>> TerminatingError(): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The credential is invalid."
>> TerminatingError(): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The credential is invalid."
>> TerminatingError(): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The credential is invalid."
>> TerminatingError(): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The credential is invalid."
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The credential is invalid.
The credential is invalid.
At C:\HCIBox\New-HCIBoxCluster.ps1:511 char:9
+         Invoke-Command -VMName $VM -Credential $Credential -ScriptBlo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (AzSMGMT:String) [], PSDirectException
    + FullyQualifiedErrorId : PSSessionStateBroken

PS>$global:?
False
**********************
Windows PowerShell transcript end
End time: 20240719031524

**To Reproduce**
After Bicep template execution, log into HCIBox-Client, as new-HCIBoxCluster script is running, it fails during step 6 of 11.

**Expected behavior**
Script should complete execution

**Environment summary**
 AZ --version 2.59.0 *

**Have you looked at the Troubleshooting and Logs section?**
Yes, the logs show the above message regarding invalid credentials

- [Jumpstart ArcBox "Full" troubleshooting](https://azurearcjumpstart.com/azure_jumpstart_arcbox/Full#basic-troubleshooting)
- [Jumpstart ArcBox for IT Pros troubleshooting](https://azurearcjumpstart.com/azure_jumpstart_arcbox/ITPro#basic-troubleshooting)
- [Jumpstart ArcBox for DevOps troubleshooting](https://azurearcjumpstart.com/azure_jumpstart_arcbox/DevOps#basic-troubleshooting)
- [Jumpstart ArcBox for DataOps troubleshooting](https://azurearcjumpstart.com/azure_jumpstart_arcbox/DataOps#basic-troubleshooting)
- [HCIBox troubleshooting](https://azurearcjumpstart.com/azure_jumpstart_hcibox/getting_started#basic-troubleshooting)
- [Agora - Contoso Supermarket troubleshooting](https://azurearcjumpstart.com/azure_jumpstart_ag/retail/contoso_supermarket/troubleshooting)
--->

**Screenshots**

**Additional context**

**Comment by dkirby-ms** [comment]
This looks like you might have an empty or somehow invalid windowsAdminPassword parameter in your bicep deployment. Can you share deployment details? Did you use azd and specify a password?

**Comment by rbrk-tpm-jshaver** [comment]
dkirby-ms, you are correct. I was leaving the default password in the param's file. Once I changed it, it completed deployment without issue.
