### ISSUE TITLE
JumpStart HCI Box: unable to install the DataDog agent and getting error "system administrator has set the policies to prevent this installation"

### ISSUE THREAD

**Issue by rohillalakhan** [microsoft/azure_arc#2618]
Hi Team,

I am trying to install DataDog Agent on HCI node and unable to install. Getting error  "system administrator has set the policies to prevent this installation".

I have created a GPO for Windows Installer and set the settings as attached. GPO settings are also applied at Node level still no luck. Please help in installing the same in HCI Box Node if at all possible.

![AzSHOST1_InstallError](https://github.com/user-attachments/assets/df2977db-7438-41ee-80a9-78335e289ebd)
![GPO](https://github.com/user-attachments/assets/9adcdd05-82b7-494e-9988-169f7272a4ef)
![GPO_Applied](https://github.com/user-attachments/assets/c452823f-4cb0-4b57-9ae2-f57d01205b22)

**Comment by dkirby-ms** [comment]
What user context are you using to attempt the install on the HCI node? Also, how are you accessing the node? Hyper-V console? PowerShell?

**Comment by rohillalakhan** [comment]
Hi Dale,
Thanks for your email.

I am using local admin account created as a part of Cluster deployment in jumpstart.local domain.

To connect to node, am using Hyper-V and then logging onto node.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mgodfre3** [comment]
It’s the wdac policy. You can’t install 3p solutions on ashci without making the wdac policy exception.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
