### ISSUE TITLE
cannot provision k8s on the hci box cluster

### ISSUE THREAD

**Issue by lixianelite** [microsoft/azure_arc#2628]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**

**Describe the issue or the bug**

**To Reproduce**

**Expected behavior**

**Environment summary**

**Have you looked at the Troubleshooting and Logs section?**

**Screenshots**
![image](https://github.com/user-attachments/assets/5a7d6172-0a37-4175-9ddd-b3619994f0fe)

**Additional context**
{
    "status": "Failed",
    "error": {
        "code": "BadRequest",
        "message": "admission webhook \"vhybridakscluster.kb.io\" denied the request: Kubernetes version 1.27.9 is not ready for use on Linux"
    }
}

**Comment by dkirby-ms** [comment]
It may be possible that the script was run before the cluster was ready. Are you still seeing the issue? Have you tried re-running the script?

**Comment by dkirby-ms** [comment]
No response here, and this is similar so closing this and combining with #2654
