### ISSUE TITLE
Line |  214 |  Throw "An error occurred creating the service principal.  … | An error occurred creating the service principal. Error:Values of identifierUris property must use a verified domain      | of the organization or its subdomain: 'http://admin-jumpstart-spn-2309'

### ISSUE THREAD

**Issue by LucaOtto** [microsoft/azure_arc#2629]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
(https://azurearcjumpstart.io/azure_jumpstart_hcibox/deployment_azd)

**Describe the issue or the bug**
azd up fails to deploy the environment.

**To Reproduce**
I followed the steps in the https://azurearcjumpstart.io/azure_jumpstart_hcibox/deployment_azd#deploy-hcibox-infrastructure-with-azure-developer-cli section, then the error.

**Expected behavior**
azd up command deploys the environment.

**Environment summary**
latest versions of the tools installed

**Have you looked at the Troubleshooting and Logs section?**

**Screenshots**

![image](https://github.com/user-attachments/assets/c5b356de-c7a1-4ed1-b656-ef59462fe23b)

**Additional context**

**Comment by likamrat** [comment]
@LucaOtto can i plz ask to update the issue title to something more manageable and shorter?

**Comment by LucaOtto** [comment]
Closing this issue because deployment to Australia East worked.
