### ISSUE TITLE
AzHOST1 /AzHOST2 missing required extensions / Can't validate cluster deployment error : The provided location 'eastus2' is not available for resource type 'Microsoft.AzureStackHCI/clusters'

### ISSUE THREAD

**Issue by LucaOtto** [microsoft/azure_arc#2632]
Hi, 

I redeployed the HCI Stack env using the https://azurearcjumpstart.io/azure_jumpstart_hcibox/deployment_az guide.

I'm still seeing errors in the New-HCIBoxCluster logs, see below

INFO: Loaded Module 'Az.Storage'
[Build cluster - Step 10/11] Validate cluster deployment...
PS>TerminatingError(New-AzResourceGroupDeployment): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 4:41:54 PM - Error: Code=LocationNotAvailableForResourceType; Message=The provided location 'eastus2' is not available for resource type 'Microsoft.AzureStackHCI/clusters'. List of available regions for the resource type is 'australiaeast,southcentralus,eastus,westeurope,southeastasia,canadacentral,japaneast,centralindia'.
"
>> TerminatingError(New-AzResourceGroupDeployment): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 4:41:54 PM - Error: Code=LocationNotAvailableForResourceType; Message=The provided location 'eastus2' is not available for resource type 'Microsoft.AzureStackHCI/clusters'. List of available regions for the resource type is 'australiaeast,southcentralus,eastus,westeurope,southeastasia,canadacentral,japaneast,centralindia'.
"
>> TerminatingError(New-AzResourceGroupDeployment): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 4:41:54 PM - Error: Code=LocationNotAvailableForResourceType; Message=The provided location 'eastus2' is not available for resource type 'Microsoft.AzureStackHCI/clusters'. List of available regions for the resource type is 'australiaeast,southcentralus,eastus,westeurope,southeastasia,canadacentral,japaneast,centralindia'.
"
>> TerminatingError(New-AzResourceGroupDeployment): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 4:41:54 PM - Error: Code=LocationNotAvailableForResourceType; Message=The provided location 'eastus2' is not available for resource type 'Microsoft.AzureStackHCI/clusters'. List of available regions for the resource type is 'australiaeast,southcentralus,eastus,westeurope,southeastasia,canadacentral,japaneast,centralindia'.
"
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 4:41:54 PM - Error: Code=LocationNotAvailableForResourceType; Message=The provided location 'eastus2' is not available for resource type 'Microsoft.AzureStackHCI/clusters'. List of available regions for the resource type is 'australiaeast,southcentralus,eastus,westeurope,southeastasia,canadacentral,japaneast,centralindia'.
New-AzResourceGroupDeployment : 4:41:54 PM - Error:
Code=LocationNotAvailableForResourceType; Message=The provided location
'eastus2' is not available for resource type
'Microsoft.AzureStackHCI/clusters'. List of available regions for the
resource type is 'australiaeast,southcentralus,eastus,westeurope,southeastasi
a,canadacentral,japaneast,centralindia'.

At C:\HCIBox\New-HCIBoxCluster.ps1:1783 char:1
+ New-AzResourceGroupDeployment -Name 'hcicluster-validate' -ResourceGr ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzResourceGroupDeployme
   nt], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdle
   ts.Implementation.NewAzureResourceGroupDeploymentCmdlet

PS>$global:?
False
**********************
Windows PowerShell transcript end
End time: 20240729164154
**********************

I'm also still seeing the same issue with the extensions, they are not installed at AzHOST1 / HOST2

![image](https://github.com/user-attachments/assets/b8454f98-9cb0-4f34-b787-059738c91407)

**Comment by likamrat** [comment]
@LucaOtto can i plz ask to update the issue title to something more manageable and shorter?

**Comment by janegilring** [comment]
@LucaOtto Can we close this one if it is the same deployment as being troubleshooted in #2633 ?

**Comment by LucaOtto** [comment]
Hi @janegilring ,

yes this issue can be closed.
