### ISSUE TITLE
HCIBox-Client post deployment automation issues

### ISSUE THREAD

**Issue by dkirrane** [microsoft/azure_arc#2671]
> **Note:** For ease of issues and pull requests management and tracking, we kindly ask you to provide a meaningful and concise title to this issue and answer all questions to the best of your ability.

**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
HCIBox

**Describe the issue or the bug**
Cluster is already registered, Unregister cluster to start re-deployment.
&
AksWorkloadCluster.ps1 fails with ResourceGroupNotFound

**To Reproduce**
1. Following the steps as outlined in https://arcjumpstart.com/azure_jumpstart_hcibox
2. Deployed with azd up
3. HCIBoxLogonScript scripts complete.
4. Issues below with post-deployment automation

**Expected behavior**
Expect HCI AKS cluster

**Environment summary**
`azure_jumpstart_hcibox` from https://github.com/microsoft/azure_arc (Git SHA 19c979d336f9a07ae9a701ba15acfd7f102c270d)

**Have you looked at the Troubleshooting and Logs section?**

**Additional context**
1. Section `Validate cluster in Azure portal` in https://arcjumpstart.com/azure_jumpstart_hcibox/cloud_deployment

The custom Deployment of the `hci.json` and `hci.parameters.json` fails with below. I took the scripts from the HCIBox-Client as outlined in the docs.

```
{"code":"DeploymentFailed","target":"/subscriptions/XXXX/resourceGroups/dkhcibox-rg/providers/Microsoft.Resources/deployments/Microsoft.Template-20240814095822",
"message":"At least one resource deployment operation failed. 
Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":
[{"code":"ValidationFailed","target":"/subscriptions/XXXX/resourceGroups/dkhcibox-rg/providers/Microsoft.AzureStackHCI/clusters/hciboxcluster",
"message":"Cluster [/subscriptions/XXXX/resourceGroups/dkhcibox-rg/providers/Microsoft.AzureStackHCI/clusters/hciboxcluster] 
is already registered, Unregister cluster to start re-deployment."}]}
```

![image](https://github.com/user-attachments/assets/cdfafb68-a0fd-475a-962e-c11bd421f64c)

2. The docs [using_hcibox](https://arcjumpstart.com/azure_jumpstart_hcibox/using_hcibox) states `HCIBox comes pre-configured with Azure Kubernetes Service on Azure Stack HCI`. But this resource `hciboc-aks` resource does not get created in my `dkhcibox-rg` resource group.
I also tried run the `AksWorkloadCluster.ps1` script from the HCIBox-Client virtual machine, but it fails to find my resource group:

![image](https://github.com/user-attachments/assets/a3f5c190-2ffe-4e80-b102-5252acb71e69)

**Comment by dkirby-ms** [comment]
Hi @Dkirrane. Its unclear what you exactly you are trying to do. So you created a cluster with HCIBox, then unregistered it? And now AKS is missing? 

To clarify on the AKS process in HCIBox - the AKS management components are what automatically get created as part of the HCI registration process. An AKS workload cluster is NOT created automatically as part of this process, only the underlying AKS management components. To create an AKS workload cluster, you need to modify and run the ConfigureAKSWorkloadCluster.ps1 script in c:\HCIBox folder. https://azurearcjumpstart.io/azure_jumpstart_hcibox/AKS

**Comment by dkirby-ms** [comment]
This is caused by a change to the RP which no longer works with the old version we are using. The fix is submitted and being tested now.
