### ISSUE TITLE
admin name and password fail to logon

### ISSUE THREAD

**Issue by ricardov28** [microsoft/azure_arc#2674]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
no, Arcbox

**Describe the issue or the bug**
my template to install Arcbox deployed successfully, machine up and running. 
When tried to RDP via port or bastion with the given admin/password it fails as if the password was wrong.
tried to change the password with azure portal, no luck.
created a new admin with azure portal and I logged in successfully but the automatic powershell scripts dont run.

**Environment summary**
azure portal

**Have you looked at the Troubleshooting and Logs section?**
no reference to my problem there.

**Screenshots**
![image](https://github.com/user-attachments/assets/7f17d6e7-1454-415c-bf25-3eaf7d71fd28)

**Additional context**
ping me on Teams rivazque

**Comment by janegilring** [comment]
Thanks for the update
