### ISSUE TITLE
customLocationRPOID aio_manufacturing

### ISSUE THREAD

**Issue by pinirob** [microsoft/azure_arc#2686]
> **Note:** For ease of issues and pull requests management and tracking, we kindly ask you to provide a meaningful and concise title to this issue and answer all questions to the best of your ability.
Parameter 'customLocationRPOID' missing

**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**

https://azurearcjumpstart.com/azure_arc_jumpstart/azure_edge_iot_ops/aio_manufacturing

**Describe the issue or the bug**

I have followed the instructions as specified here "https://azurearcjumpstart.com/azure_arc_jumpstart/azure_edge_iot_ops/aio_manufacturing" following the Deployment via Azure Developer CLI.
But during the configuration of the VM it raise an error about missing a parameter "customLocationRPOID".
Here the details:

  You can view detailed progress in the Azure Portal:
  https://portal.azure.com/#view/HubsExtension/DeploymentDetailsBlade/~/overview/id/%2Fsubscriptions%2F0a7b6fa8-1a48-4262-91b5-e3ffa04f08e9%2FresourceGroups%2Frg-JumpstartAIO%2Fproviders%2FMicrosoft.Resources%2Fdeployments%2FJumpstartAIO-1725176189

  (✓) Done: Virtual Network: AIO-Demo-VNET
  (✓) Done: Storage account: aiostge053c
  (✓) Done: Key Vault: aioakve053c
  |    ===| Creating/Updating resources
ERROR: error executing step command 'provision': deployment failed: error deploying infrastructure: deploying to resource group:

Deployment Error Details:
VMExtensionProvisioningError: VM has reported a failure when processing extension 'Bootstrap' (publisher 'Microsoft.Compute' and type 'CustomScriptExtension'). Error message: 'Command execution finished, but failed because it returned a non-zero exit code of: '1'. The command had an error output of: 'C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.10.17\Downloads\0\Bootstrap.ps1 : Missing an argument
for parameter 'customLocationRPOID'. Specify a parameter of type 'System.String' and try again.
    + CategoryInfo          : InvalidArgu...' For more information, check the instance view by executing Get-AzVmssVm or Get-AzVm (https://aka.ms/GetAzVm). These commands can be executed using CloudShell (https://aka.ms/CloudShell)'. More information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot.

TraceID: 9f094b24c4761032f3a26e675757cd1f

**To Reproduce**

**Expected behavior**

The script should complete successfully as per the documentation.

**Environment summary**

PowerShell 7.4.5, git version 2.46.0.windows.1, dotnet 8.0.401, 
{
  "azure-cli": "2.63.0",
  "azure-cli-core": "2.63.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {}
}

**Have you looked at the Troubleshooting and Logs section?**

**Screenshots**

![image](https://github.com/user-attachments/assets/234d12c6-34eb-4a32-935f-ad5dcf8282d9)

**Additional context**

**Comment by sebassem** [comment]
@pinirob  Thanks for opening this issue, can you validate that this command returns a value ? If you don't see any value, please register the customlocation resource provider and try again.

`(Get-AzADServicePrincipal -DisplayName 'Custom Locations RP').Id`

**Comment by sebassem** [comment]
@pinirob any chance you tested the resolution above ?

**Comment by pinirob** [comment]
Hi Seif,
Thank you for the suggestion.
I haven't tried yet since I tested IoT operations with GitHub Codespaces with K3s.
I will give a try tomorrow and I will let you know.
Thank you,Roberto

    On Tuesday, 3 September 2024 at 15:16:00 CEST, Seif Bassem ***@***.***> wrote:  
 
 


@pinirob any chance you tested the resolution above ?

**Comment by sebassem** [comment]
@pinirob just checking if you got a chance to test ?

**Comment by sebassem** [comment]
Closing this issue. Please feel free to reopen if you are still facing problems
