### ISSUE TITLE
Logon script error in AKS Edge Essentials single node deployment with Azure Arc using ARM Template

### ISSUE THREAD

**Issue by bastyuchenko** [microsoft/azure_arc#2688]
I try to reproduce the steps mentioned in "[AKS Edge Essentials single node deployment with Azure Arc using ARM Template](https://azurearcjumpstart.com/azure_arc_jumpstart/azure_edge_iot_ops/aks_edge_essentials_single)". 

I cloned https://github.com/microsoft/azure_arc.git repository and changed file ....\azure_arc\azure_arc_k8s_jumpstart\aks_hybrid\aks_edge_essentials_single\arm_template\azuredeploy.parameters.json
to the values that are pretty sililar to example (see attached [azuredeploy.parameters.json](https://github.com/user-attachments/files/16830596/azuredeploy.parameters.json)).

However, I receive the error (see attached [LogonScript.log](https://github.com/user-attachments/files/16830588/LogonScript.log) with full result) when I open my newly created VM through RDP and LogonScript started automatically:

`TerminatingError(New-AksEdgeConfig): "Cannot validate argument on parameter 'NodeType'. The argument "" does not belong to the set "Linux,Windows,LinuxAndWindows" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again."
New-AksEdgeConfig : Cannot validate argument on parameter 'NodeType'. The argument "" does not belong to the set 
"Linux,Windows,LinuxAndWindows" specified by the ValidateSet attribute. Supply an argument that is in the set and then 
try the command again.`

**Comment by janegilring** [comment]
@bastyuchenko Thanks for reporting this. The issue is now resolved, so you may pull the latest changes and try a new depeloyment.
