### ISSUE TITLE
Refactor ESA Scenario 

### ISSUE THREAD

**Issue by dkirby-ms** [microsoft/azure_arc#2704]
From the logs: 

Checking if Edge Storage Accelerator Arc Extension is installed...
Installing Edge Storage Accelerator Arc Extension...
(ExtensionOperationFailed) The extension operation failed with the following error:  Failed to resolve the extension ver
sion from the given values. InnerError:[ '{0}' ]. Please refer https://aka.ms/k8s-extension-type-versions to find the co
rrect version for your installation, For general troubleshooting visit: https://aka.ms/k8s-extensions-TSG.
Code: ExtensionOperationFailed
Message: The extension operation failed with the following error:  Failed to resolve the extension version from the give
n values. InnerError:[ '{0}' ]. Please refer https://aka.ms/k8s-extension-type-versions to find the correct version for
your installation, For general troubleshooting visit: https://aka.ms/k8s-extensions-TSG.
Edge Storage Accelerator Arc Extension installed successfully.

Its reporting success but is not successful.

**Comment by ldabas-msft** [comment]
Updating this scenario to use edge vols, and to reflect the new name in the docs
