### ISSUE TITLE
Jumpstart HCI Box: Exception encountered while adding node to cluster

### ISSUE THREAD

**Issue by mshamim69** [microsoft/azure_arc#2732]
**Describe the issue or the bug**
I am following the instruction https://azurearcjumpstart.com/azure_jumpstart_hcibox/deployment_az to setup Jumpstart HCIBox.

**Region: WestEurope**

**I am the owner of the subscription.** 

Have following configuration in ..\azure_arc\azure_jumpstart_hcibox\bicep\main.parameters.json

 "deployBastion": {
        "value": false
  },
  "autoDeployClusterResource": {
        "value": true
  },
  "autoUpgradeClusterResource": {
       "value": true
  }
But I am getting following error:
![hci-error](https://github.com/user-attachments/assets/4ed4b4ac-3819-4443-b028-f0fd7b76e818)

Windows PowerShell transcript start
Start time: 20240929162039
Username: HCIBox-Client\hciboxdemo
RunAs User: HCIBox-Client\hciboxdemo
Configuration Name: 
Machine: HCIBox-Client (Microsoft Windows NT 10.0.20348.0)
Host Application: PowerShell.exe C:\HCIBox\HCIBoxLogonScript.ps1
Process ID: 7932
PSVersion: 5.1.20348.2652
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.20348.2652
BuildVersion: 10.0.20348.2652
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\HCIBox\Logs\Generate-ARM-Template.log
**[Build cluster - Step 10/11] Validate cluster deployment...**
PS>TerminatingError(New-AzResourceGroupDeployment): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 4:21:51 PM - The deployment 'hcicluster-validate' failed with error(s). Showing 1 out of 1 error(s).

Status Message: Exception encountered while adding node to cluster [Failed to fetch all machines. Machines requested 2, fetched: 0. Please make sure all the required permissions are assigned.] at [   at Microsoft.AzureStackHCI.ResourceProvider.Services.ClusterNodeManager.GetEdgeDeviceIds(ClusterDeploymentWorkItem workItem, ResourceCollection`1 machines) in C:\__w\1\s\src\rp\Services\ClusterNodeManager.cs:line 269
   at Microsoft.AzureStackHCI.ResourceProvider.Services.ClusterNodeManager.AddARCNodesToCluster(ClusterDeploymentWorkItem workItem, ResourceCollection`1 machines) in C:\__w\1\s\src\rp\Services\ClusterNodeManager.cs:line 92] (Code: ValidationFailed)
 - Exception encountered while adding node to cluster [Failed to fetch all machines. Machines requested 2, fetched: 0. Please make sure all the required permissions are assigned.] at [   at Microsoft.AzureStackHCI.ResourceProvider.Services.ClusterNodeManager.GetEdgeDeviceIds(ClusterDeploymentWorkItem workItem, ResourceCollection`1 machines) in C:\__w\1\s\src\rp\Services\ClusterNodeManager.cs:line 269
   at Microsoft.AzureStackHCI.ResourceProvider.Services.ClusterNodeManager.AddARCNodesToCluster(ClusterDeploymentWorkItem workItem, ResourceCollection`1 machines) in C:\__w\1\s\src\rp\Services\ClusterNodeManager.cs:line 92] (Code:ValidationFailed)

**What should be the step forward to fix this issue and have a successful deployment? I have Storage Account Contributor and Key Vault Administrator role to the RG. What are the additional requirements?**
![hci-error](https://github.com/user-attachments/assets/c05baa30-7128-458d-9465-8c8ebb1e6ed7)

**Comment by mshamim69** [comment]
Log:
[Logs.zip](https://github.com/user-attachments/files/17185581/Logs.zip)

**Comment by mshamim69** [comment]
I have also tried the following with a new resource group:
"deployBastion": {
"value": false
},
"autoDeployClusterResource": {
"value": false
},
"autoUpgradeClusterResource": {
"value": false
}
- Added Key Vault Administrator on the HCIBox resource group.
- Add "Storage Account Contributor" on the HCIBox resource group.
- Navigated to Azure portal and type "custom deployment" in the search bar, then select "Deploy a custom template".
- Used hci.json and hci.parameters.json from File Explorer on HCIBox-Client and navigate to the C:\HCIBox folder.
- I have same error.
![hci-error-new](https://github.com/user-attachments/assets/fb72ce05-55c9-47eb-9f54-326ae99799f2)
My role in resource-group:
![myrole](https://github.com/user-attachments/assets/2a484d60-39f9-4855-a1c0-7a40d7de2500)

**Comment by dkirby-ms** [comment]
We have addressed changes to ARM deployment with #2750. Please redeploy.
