### ISSUE TITLE
Support Arc-enabled SQL Server least privilege, automated backups, and performance dashboards

### ISSUE THREAD

**Issue by chintalavr** [microsoft/azure_arc#2733]
> **Note:** For ease of issues and pull requests management and tracking, we kindly ask you to provide a meaningful and concise title to this feature request and answer all questions to the best of your ability.

**Is your feature request related to a new Jumpstart scenario you would like to contribute?**

Yes

**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like.**

Support Arc-enabled SQL Server least privilege, automated backups, and performance dashboards in Jumpstart ArcBox

**Describe alternatives you've considered.**

**Additional context.**

**Comment by likamrat** [comment]
Related to [#409](https://github.com/Azure/arc_jumpstart_docs/pull/409)
