### ISSUE TITLE
HCIBox Step 10/11 [Build Cluster validate cluster deployment] is failing 

### ISSUE THREAD

**Issue by stefanstranger** [microsoft/azure_arc#2737]
I've tried to deploy the HCIBox Jumpstart in different regions (Australia and Canadawest) and both are failing on step 10 after the creation of the ARM template.

![image](https://github.com/user-attachments/assets/ee7aaa7f-1428-44ff-8a18-05cb03af4e98)

Somehow only one node of the cluster is found and added to the ARM Template while it expects an array.

As you see only one node is added in the parameter file, while the template expects an array...

![image](https://github.com/user-attachments/assets/629b76a4-1c79-4c4c-8f25-a99b1b3a9b21)

How can this be resolved?

**Comment by stefanstranger** [comment]
I tried to continue with the validate cluster deployment step (10) using a single arcnode in the acrNodesResourceIds parameter value but that deployment also failed.

![image](https://github.com/user-attachments/assets/fb8fda21-3ce9-466f-bfa0-321644e27940)

**Comment by luvijiia** [comment]
Hi, I have the same issue with the deployment. It fails at step 10/11 when is about to validate the cluster. 
The error I am getting is the following:
![image](https://github.com/user-attachments/assets/01257629-f678-4353-9b45-019a6625b181)
I tried to deploy multiple times in both North Europe and West Europe region. One of my colleagues also tried in his tenant and got exactly the same issue.

**Comment by dkirby-ms** [comment]
We have pushed some fixes to account for changes in the ARM deployment process. Can you please try to redeploy with the latest update?
