### ISSUE TITLE
Jumpstart HCI Box - Failure during HCI cluster provisioning

### ISSUE THREAD

**Issue by fourier134949** [microsoft/azure_arc#2748]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
HCIBox

**Describe the issue or the bug**
Failure during Stack HCI cluster validation and deployment phase
https://azurearcjumpstart.com/azure_jumpstart_hcibox/cloud_deployment

**To Reproduce**
I've followed all the steps described in the links
https://azurearcjumpstart.com/azure_jumpstart_hcibox/deployment_az
https://azurearcjumpstart.com/azure_jumpstart_hcibox/cloud_deployment

This is our main.parameters.json we used to trigger the deployment on East US region

{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "spnClientId": {
            "value": "xxxxxx"
        },
        "spnClientSecret": {
            "value": "xxxxxx"
        },
        "spnTenantId": {
            "value": "xxxxxx"
        },
        "spnProviderId": {
            "value": "xxxx"
        },
        "windowsAdminUsername": {
            "value": "hciboxdemo"
        },
        "windowsAdminPassword": {
            "value": "xxxx"
        },
        "logAnalyticsWorkspaceName": {
            "value": "xxxxx"
        },
        "deployBastion": {
            "value": false
        },
        "autoDeployClusterResource": {
            "value": true
        },
        "autoUpgradeClusterResource": {
            "value": false
        }
    }
}

The first phase went OK, the HCIBox-Client VM has been created successfully.
We then logged into the HCIBox-Client and the second phase for the script started. 
When we reached the execution of the template hci.json the process failed with the following errors (on the log file Generate-ARM-Template.log), in attach the file hci.parameters.json:

**********************
Windows PowerShell transcript start
Start time: 20241008132245
Username: HCIBox-Client\hciboxdemo
RunAs User: HCIBox-Client\hciboxdemo
Configuration Name: 
Machine: HCIBox-Client (Microsoft Windows NT 10.0.20348.0)
Host Application: PowerShell.exe C:\HCIBox\HCIBoxLogonScript.ps1
Process ID: 7488
PSVersion: 5.1.20348.2652
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.20348.2652
BuildVersion: 10.0.20348.2652
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\HCIBox\Logs\Generate-ARM-Template.log
[Build cluster - Step 10/11] Validate cluster deployment...
PS>TerminatingError(New-AzResourceGroupDeployment): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 1:42:04 PM - The deployment 'hcicluster-validate' failed with error(s). Showing 1 out of 1 error(s).
Status Message: Deployment Settings validation failed. (Code: UpdateDeploymentSettingsDataFailed)
 - Failed to create deployment settings. 
Validation status is {Status=Error, Steps={Name=Azure Stack HCI Connectivity, Description=Check external connectivity requirements, FullStepIndex=0, StartTimeUtc=2024-10-08T13:24:28, EndTimeUtc=2024-10-08T13:25:21, Status=Success, Exception=, Steps=}, {Name=Azure Stack HCI External Active Directory, Description=Check external active directory preparation, FullStepIndex=1, StartTimeUtc=2024-10-08T13:25:21, EndTimeUtc=2024-10-08T13:25:46, Status=Success, Exception=, Steps=}, {Name=Azure Stack SBE Health, Description=Check SBE health requirements, FullStepIndex=2, StartTimeUtc=2024-10-08T13:25:46, EndTimeUtc=2024-10-08T13:25:50, Status=Success, Exception=, Steps=}, {Name=Azure Stack HCI Hardware, Description=Check hardware requirements, FullStepIndex=3, StartTimeUtc=2024-10-08T13:25:50, EndTimeUtc=2024-10-08T13:25:57, Status=Success, Exception=, Steps=}, {Name=Azure Stack HCI Network, Description=Check network requirements, FullStepIndex=4, StartTimeUtc=2024-10-08T13:25:57, EndTimeUtc=2024-10-08T13:40:54, Status=Error, Exception=System.Collections.Generic.List`1[System.String], Steps=}, {Name=Azure Stack HCI Observability, Description=Check Log Collection and Remote Support requirements, FullStepIndex=5, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=, Steps=}, {Name=Azure Stack HCI Software, Description=Check Operating System requirements, FullStepIndex=6, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=, Steps=}, {Name=Azure Stack HCI MOC Stack, Description=Check Moc Stack requirements, FullStepIndex=7, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=, Steps=}, {Name=Azure Stack HCI Arc Integration, Description=Evaluate interface ValidateArcIntegration, FullStepIndex=8, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=, Steps=}, {Name=Azure Stack HCI Cluster Witness, Description=Check cluster witness requirements, FullStepIndex=9, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=, Steps=}}. 
Deployment Status is {Status=, Steps=null} (Code:UpdateDeploymentSettingsDataFailed)

CorrelationId: bf6c1e58-xxxxxx"
>> TerminatingError(New-AzResourceGroupDeployment): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 1:42:04 PM - The deployment 'hcicluster-validate' failed with error(s). Showing 1 out of 1 error(s).
Status Message: Deployment Settings validation failed. (Code: UpdateDeploymentSettingsDataFailed)
 - Failed to create deployment settings. 
Validation status is {Status=Error, Steps={Name=Azure Stack HCI Connectivity, Description=Check external connectivity requirements, FullStepIndex=0, StartTimeUtc=2024-10-08T13:24:28, EndTimeUtc=2024-10-08T13:25:21, Status=Success, Exception=, Steps=}, {Name=Azure Stack HCI External Active Directory, Description=Check external active directory preparation, FullStepIndex=1, StartTimeUtc=2024-10-08T13:25:21, EndTimeUtc=2024-10-08T13:25:46, Status=Success, Exception=, Steps=}, {Name=Azure Stack SBE Health, Description=Check SBE health requirements, FullStepIndex=2, StartTimeUtc=2024-10-08T13:25:46, EndTimeUtc=2024-10-08T13:25:50, Status=Success, Exception=, Steps=}, {Name=Azure Stack HCI Hardware, Description=Check hardware requirements, FullStepIndex=3, StartTimeUtc=2024-10-08T13:25:50, EndTimeUtc=2024-10-08T13:25:57, Status=Success, Exception=, Steps=}, {Name=Azure Stack HCI Network, Description=Check network requirements, FullStepIndex=4, StartTimeUtc=2024-10-08T13:25:57, EndTimeUtc=2024-10-08T13:40:54, Status=Error, Exception=System.Collections.Generic.List`1[System.String], Steps=}, {Name=Azure Stack HCI Observability, Description=Check Log Collection and Remote Support requirements, FullStepIndex=5, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=, Steps=}, {Name=Azure Stack HCI Software, Description=Check Operating System requirements, FullStepIndex=6, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=, Steps=}, {Name=Azure Stack HCI MOC Stack, Description=Check Moc Stack requirements, FullStepIndex=7, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=, Steps=}, {Name=Azure Stack HCI Arc Integration, Description=Evaluate interface ValidateArcIntegration, FullStepIndex=8, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=, Steps=}, {Name=Azure Stack HCI Cluster Witness, Description=Check cluster witness requirements, FullStepIndex=9, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=, Steps=}}. 
Deployment Status is {Status=, Steps=null} (Code:UpdateDeploymentSettingsDataFailed)

CorrelationId: bf6c1e58-xxxxx"
>> TerminatingError(New-AzResourceGroupDeployment): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 1:42:04 PM - The deployment 'hcicluster-validate' failed with error(s). Showing 1 out of 1 error(s).
Status Message: Deployment Settings validation failed. (Code: UpdateDeploymentSettingsDataFailed)
 - Failed to create deployment settings. 
Validation status is {Status=Error, Steps={Name=Azure Stack HCI Connectivity, Description=Check external connectivity requirements, FullStepIndex=0, StartTimeUtc=2024-10-08T13:24:28, EndTimeUtc=2024-10-08T13:25:21, Status=Success, Exception=, Steps=}, {Name=Azure Stack HCI External Active Directory, Description=Check external active directory preparation, FullStepIndex=1, StartTimeUtc=2024-10-08T13:25:21, EndTimeUtc=2024-10-08T13:25:46, Status=Success, Exception=, Steps=}, {Name=Azure Stack SBE Health, Description=Check SBE health requirements, FullStepIndex=2, StartTimeUtc=2024-10-08T13:25:46, EndTimeUtc=2024-10-08T13:25:50, Status=Success, Exception=, Steps=}, {Name=Azure Stack HCI Hardware, Description=Check hardware requirements, FullStepIndex=3, StartTimeUtc=2024-10-08T13:25:50, EndTimeUtc=2024-10-08T13:25:57, Status=Success, Exception=, Steps=}, {Name=Azure Stack HCI Network, Description=Check network requirements, FullStepIndex=4, StartTimeUtc=2024-10-08T13:25:57, EndTimeUtc=2024-10-08T13:40:54, Status=Error, Exception=System.Collections.Generic.List`1[System.String], Steps=}, {Name=Azure Stack HCI Observability, Description=Check Log Collection and Remote Support requirements, FullStepIndex=5, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=, Steps=}, {Name=Azure Stack HCI Software, Description=Check Operating System requirements, FullStepIndex=6, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=, Steps=}, {Name=Azure Stack HCI MOC Stack, Description=Check Moc Stack requirements, FullStepIndex=7, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=, Steps=}, {Name=Azure Stack HCI Arc Integration, Description=Evaluate interface ValidateArcIntegration, FullStepIndex=8, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=, Steps=}, {Name=Azure Stack HCI Cluster Witness, Description=Check cluster witness requirements, FullStepIndex=9, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=, Steps=}}. 
Deployment Status is {Status=, Steps=null} (Code:UpdateDeploymentSettingsDataFailed)

CorrelationId: bf6c1e58-xxxxx"
>> TerminatingError(New-AzResourceGroupDeployment): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 1:42:04 PM - The deployment 'hcicluster-validate' failed with error(s). Showing 1 out of 1 error(s).
Status Message: Deployment Settings validation failed. (Code: UpdateDeploymentSettingsDataFailed)
 - Failed to create deployment settings. 
Validation status is {Status=Error, Steps={Name=Azure Stack HCI Connectivity, Description=Check external connectivity requirements, FullStepIndex=0, StartTimeUtc=2024-10-08T13:24:28, EndTimeUtc=2024-10-08T13:25:21, Status=Success, Exception=, Steps=}, {Name=Azure Stack HCI External Active Directory, Description=Check external active directory preparation, FullStepIndex=1, StartTimeUtc=2024-10-08T13:25:21, EndTimeUtc=2024-10-08T13:25:46, Status=Success, Exception=, Steps=}, {Name=Azure Stack SBE Health, Description=Check SBE health requirements, FullStepIndex=2, StartTimeUtc=2024-10-08T13:25:46, EndTimeUtc=2024-10-08T13:25:50, Status=Success, Exception=, Steps=}, {Name=Azure Stack HCI Hardware, Description=Check hardware requirements, FullStepIndex=3, StartTimeUtc=2024-10-08T13:25:50, EndTimeUtc=2024-10-08T13:25:57, Status=Success, Exception=, Steps=}, {Name=Azure Stack HCI Network, Description=Check network requirements, FullStepIndex=4, StartTimeUtc=2024-10-08T13:25:57, EndTimeUtc=2024-10-08T13:40:54, Status=Error, Exception=System.Collections.Generic.List`1[System.String], Steps=}, {Name=Azure Stack HCI Observability, Description=Check Log Collection and Remote Support requirements, FullStepIndex=5, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=, Steps=}, {Name=Azure Stack HCI Software, Description=Check Operating System requirements, FullStepIndex=6, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=, Steps=}, {Name=Azure Stack HCI MOC Stack, Description=Check Moc Stack requirements, FullStepIndex=7, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=, Steps=}, {Name=Azure Stack HCI Arc Integration, Description=Evaluate interface ValidateArcIntegration, FullStepIndex=8, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=, Steps=}, {Name=Azure Stack HCI Cluster Witness, Description=Check cluster witness requirements, FullStepIndex=9, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=, Steps=}}. 
Deployment Status is {Status=, Steps=null} (Code:UpdateDeploymentSettingsDataFailed)

CorrelationId: bf6c1e58-xxxxx"
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 1:42:04 PM - The deployment 'hcicluster-validate' failed with error(s). Showing 1 out of 1 error(s).
Status Message: Deployment Settings validation failed. (Code: UpdateDeploymentSettingsDataFailed)
 - Failed to create deployment settings. 
Validation status is {Status=Error, Steps={Name=Azure Stack HCI Connectivity, Description=Check external connectivity requirements, FullStepIndex=0, StartTimeUtc=2024-10-08T13:24:28, EndTimeUtc=2024-10-08T13:25:21, Status=Success, Exception=, Steps=}, {Name=Azure Stack HCI External Active Directory, Description=Check external active directory preparation, FullStepIndex=1, StartTimeUtc=2024-10-08T13:25:21, EndTimeUtc=2024-10-08T13:25:46, Status=Success, Exception=, Steps=}, {Name=Azure Stack SBE Health, Description=Check SBE health requirements, FullStepIndex=2, StartTimeUtc=2024-10-08T13:25:46, EndTimeUtc=2024-10-08T13:25:50, Status=Success, Exception=, Steps=}, {Name=Azure Stack HCI Hardware, Description=Check hardware requirements, FullStepIndex=3, StartTimeUtc=2024-10-08T13:25:50, EndTimeUtc=2024-10-08T13:25:57, Status=Success, Exception=, Steps=}, {Name=Azure Stack HCI Network, Description=Check network requirements, FullStepIndex=4, StartTimeUtc=2024-10-08T13:25:57, EndTimeUtc=2024-10-08T13:40:54, Status=Error, Exception=System.Collections.Generic.List`1[System.String], Steps=}, {Name=Azure Stack HCI Observability, Description=Check Log Collection and Remote Support requirements, FullStepIndex=5, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=, Steps=}, {Name=Azure Stack HCI Software, Description=Check Operating System requirements, FullStepIndex=6, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=, Steps=}, {Name=Azure Stack HCI MOC Stack, Description=Check Moc Stack requirements, FullStepIndex=7, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=, Steps=}, {Name=Azure Stack HCI Arc Integration, Description=Evaluate interface ValidateArcIntegration, FullStepIndex=8, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=, Steps=}, {Name=Azure Stack HCI Cluster Witness, Description=Check cluster witness requirements, FullStepIndex=9, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=, Steps=}}. 
Deployment Status is {Status=, Steps=null} (Code:UpdateDeploymentSettingsDataFailed)

CorrelationId: bf6c1e58-xxxxx
New-AzResourceGroupDeployment : 1:42:04 PM - The deployment 'hcicluster-validate' failed with error(s). Showing 1 out
of 1 error(s).
Status Message: Deployment Settings validation failed. (Code: UpdateDeploymentSettingsDataFailed)
 - Failed to create deployment settings.
Validation status is {Status=Error, Steps={Name=Azure Stack HCI Connectivity, Description=Check external connectivity
requirements, FullStepIndex=0, StartTimeUtc=2024-10-08T13:24:28, EndTimeUtc=2024-10-08T13:25:21, Status=Success,
Exception=, Steps=}, {Name=Azure Stack HCI External Active Directory, Description=Check external active directory
preparation, FullStepIndex=1, StartTimeUtc=2024-10-08T13:25:21, EndTimeUtc=2024-10-08T13:25:46, Status=Success,
Exception=, Steps=}, {Name=Azure Stack SBE Health, Description=Check SBE health requirements, FullStepIndex=2,
StartTimeUtc=2024-10-08T13:25:46, EndTimeUtc=2024-10-08T13:25:50, Status=Success, Exception=, Steps=}, {Name=Azure
Stack HCI Hardware, Description=Check hardware requirements, FullStepIndex=3, StartTimeUtc=2024-10-08T13:25:50,
EndTimeUtc=2024-10-08T13:25:57, Status=Success, Exception=, Steps=}, {Name=Azure Stack HCI Network, Description=Check
network requirements, FullStepIndex=4, StartTimeUtc=2024-10-08T13:25:57, EndTimeUtc=2024-10-08T13:40:54, Status=Error,
Exception=System.Collections.Generic.List`1[System.String], Steps=}, {Name=Azure Stack HCI Observability,
Description=Check Log Collection and Remote Support requirements, FullStepIndex=5, StartTimeUtc=NA, EndTimeUtc=NA,
Status=, Exception=, Steps=}, {Name=Azure Stack HCI Software, Description=Check Operating System requirements,
FullStepIndex=6, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=, Steps=}, {Name=Azure Stack HCI MOC Stack,
Description=Check Moc Stack requirements, FullStepIndex=7, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=,
Steps=}, {Name=Azure Stack HCI Arc Integration, Description=Evaluate interface ValidateArcIntegration,
FullStepIndex=8, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=, Steps=}, {Name=Azure Stack HCI Cluster Witness,
Description=Check cluster witness requirements, FullStepIndex=9, StartTimeUtc=NA, EndTimeUtc=NA, Status=, Exception=,
Steps=}}.
Deployment Status is {Status=, Steps=null} (Code:UpdateDeploymentSettingsDataFailed)

CorrelationId: bf6c1e58-xxxxx
At C:\HCIBox\New-HCIBoxCluster.ps1:1783 char:1
+ New-AzResourceGroupDeployment -Name 'hcicluster-validate' -ResourceGr ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDep
   loymentCmdlet

PS>$global:?
False
**********************
Windows PowerShell transcript end
End time: 20241008134204
**********************

**Expected behavior**
The HCI cluster registered and provisioned on azure portal

**Additional context**
The service principal used for executing the script inside the VM has the following Azure Roles:

- Owner of the subscription
- Storage Account Contributor on the resource group used for deploying the HCI resources
- Azure Stack HCI Administrator on the resource group used for deploying the HCI resources
- Key Vault Administrator on the resource group used for deploying the HCI resources
- Storage Account Contributor on the resource group used for deploying the HCI resources

**Comment by fourier134949** [comment]
Attaching the hci.parameters.json file 
[hci.parameters.json](https://github.com/user-attachments/files/17296719/hci.parameters.json)

**Comment by dkirby-ms** [comment]
We have pushed fixes to address changes in ARM deployment parameters. Please redeploy.

**Comment by fourier134949** [comment]
I've pulled the updated code and triggered again the process (same main.parameters.json in input). 
First step ok, the HCIBox-Client has been created with success.

When I log into the VM and the second script is starts executing , it reach the step 7 and remains stuck there. Here's the log of New-HCIBoxCluster.log

**********************
PowerShell transcript start
Start time: 20241009092124
Username: HCIBox-Client\hciboxdemo
RunAs User: HCIBox-Client\hciboxdemo
Configuration Name: 
Machine: HCIBox-Client (Microsoft Windows NT 10.0.20348.0)
Host Application: C:\Program Files\PowerShell\7\pwsh.dll C:\HCIBox\HCIBoxLogonScript.ps1
Process ID: 3812
PSVersion: 7.4.5
PSEdition: Core
GitCommitId: 7.4.5
OS: Microsoft Windows 10.0.20348
Platform: Win32NT
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1, 6.0, 7.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
WSManStackVersion: 3.0
**********************
Transcript started, output file is C:\HCIBox\Logs\New-HCIBoxCluster.log
Creating WACDir path at C:\HCIBox\Windows Admin Center
Creating DSCDir path at C:\HCIBox\DSC
Creating TempDir path at C:\Temp
Creating LogsDir path at C:\HCIBox\Logs
Creating VMDir path at C:\HCIBox\Virtual Machines
Creating TestsDir path at C:\HCIBox\Tests
Creating SDNDir path at C:\HCIBox\SDN
Creating ToolsDir path at C:\Tools
Creating AgentScriptDir path at C:\HCIBox\agentScript
Creating VHDDir path at C:\HCIBox\VHD
Creating IconDir path at C:\HCIBox\Icons
Creating VMPath path at C:\VMs
Creating KVDir path at C:\HCIBox\KeyVault
[Build cluster - Step 1/11] Downloading HCIBox VHDs
Downloading nested VMs VHDX files. This can take some time, hold tight...
INFO: Scanning...
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

Job 35c2ac21-5c22-4d45-7c6f-b64410ff96ad has started
Log file is located at: C:\Users\hciboxdemo\.azcopy\35c2ac21-5c22-4d45-7c6f-b64410ff96ad.log

100.0 %, 1 Done, 0 Failed, 0 Pending, 0 Skipped, 1 Total,


Job 35c2ac21-5c22-4d45-7c6f-b64410ff96ad summary
Elapsed Time (Minutes): 0.4684
Number of File Transfers: 1
Number of Folder Property Transfers: 0
Number of Symlink Transfers: 0
Total Number of Transfers: 1
Number of File Transfers Completed: 1
Number of Folder Transfers Completed: 0
Number of File Transfers Failed: 0
Number of Folder Transfers Failed: 0
Number of File Transfers Skipped: 0
Number of Folder Transfers Skipped: 0
Total Number of Bytes Transferred: 13291749376
Final Job Status: Completed
INFO: Scanning...
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

Job 1ef11e1f-9148-1a46-6281-6eccedd1f8c1 has started
Log file is located at: C:\Users\hciboxdemo\.azcopy\1ef11e1f-9148-1a46-6281-6eccedd1f8c1.log

100.0 %, 1 Done, 0 Failed, 0 Pending, 0 Skipped, 1 Total, 2-sec Throughput (Mb/s): 0.0003


Job 1ef11e1f-9148-1a46-6281-6eccedd1f8c1 summary
Elapsed Time (Minutes): 0.0334
Number of File Transfers: 1
Number of Folder Property Transfers: 0
Number of Symlink Transfers: 0
Total Number of Transfers: 1
Number of File Transfers Completed: 1
Number of Folder Transfers Completed: 0
Number of File Transfers Failed: 0
Number of Folder Transfers Failed: 0
Number of File Transfers Skipped: 0
Number of Folder Transfers Skipped: 0
Total Number of Bytes Transferred: 64
Final Job Status: Completed
AZSCHI.vhdx has valid checksum. Continuing...
INFO: Scanning...
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

Job a6353d7f-278a-1747-4080-5015e79ea10a has started
Log file is located at: C:\Users\hciboxdemo\.azcopy\a6353d7f-278a-1747-4080-5015e79ea10a.log

76.9 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 2-sec Throughput (Mb/s): 4058.3073 (PageBlobService may be limi
80.9 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 2-sec Throughput (Mb/s): 3101.4418 (Disk may be limiting speed)
87.3 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 2-sec Throughput (Mb/s): 4997.7107 (PageBlobService may be limi
92.8 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 2-sec Throughput (Mb/s): 4101.1402 (PageBlobService may be limi
98.1 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 2-sec Throughput (Mb/s): 4151.2824 (PageBlobService may be limi
100.0 %, 1 Done, 0 Failed, 0 Pending, 0 Skipped, 1 Total, 2-sec Throughput (Mb/s): 1417.1631



Job a6353d7f-278a-1747-4080-5015e79ea10a summary
Elapsed Time (Minutes): 0.6687
Number of File Transfers: 1
Number of Folder Property Transfers: 0
Number of Symlink Transfers: 0
Total Number of Transfers: 1
Number of File Transfers Completed: 1
Number of Folder Transfers Completed: 0
Number of File Transfers Failed: 0
Number of Folder Transfers Failed: 0
Number of File Transfers Skipped: 0
Number of Folder Transfers Skipped: 0
Total Number of Bytes Transferred: 19599982592
Final Job Status: Completed
INFO: Scanning...
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

Job ab107b60-f40d-3a4e-43f4-0071a16b48d3 has started
Log file is located at: C:\Users\hciboxdemo\.azcopy\ab107b60-f40d-3a4e-43f4-0071a16b48d3.log

100.0 %, 1 Done, 0 Failed, 0 Pending, 0 Skipped, 1 Total, 2-sec Throughput (Mb/s): 0.0003


Job ab107b60-f40d-3a4e-43f4-0071a16b48d3 summary
Elapsed Time (Minutes): 0.0334
Number of File Transfers: 1
Number of Folder Property Transfers: 0
Number of Symlink Transfers: 0
Total Number of Transfers: 1
Number of File Transfers Completed: 1
Number of Folder Transfers Completed: 0
Number of File Transfers Failed: 0
Number of Folder Transfers Failed: 0
Number of File Transfers Skipped: 0
Number of Folder Transfers Skipped: 0
Total Number of Bytes Transferred: 64
Final Job Status: Completed
GUI.vhdx has valid checksum. Continuing...
[Build cluster - Step 2/11] Preparing Azure VM virtualization host...
Enabling PS Remoting on client...
WARNING: PowerShell remoting has been enabled only for PowerShell 6+ configurations and does not affect Windows PowerShell remoting configurations. Run this cmdlet in Windows PowerShell to affect all PowerShell remoting configurations.
WinRM is already set up to receive requests on this computer.
WinRM is already set up for remote management on this computer.

cfg         : http://schemas.microsoft.com/wbem/wsman/1/config/client/auth
lang        : en-US
Basic       : true
Digest      : true
Kerberos    : true
Negotiate   : true
Certificate : true
CredSSP     : true

Checking internet connectivity
Creating Internal Switch
Creating NAT Switch
Creating NAT Switch: InternalNAT
Applying IP Address to NAT Switch: InternalNAT
Creating new Net NAT
Configuring HCIBox-Client Hyper-V host
Copying VHDX Files to Host virtualization drive
[Build cluster - Step 3/11] Creating Management VM (AzSMGMT)...
Creating VM AzSMGMT
Performing offline installation of Hyper-V on AzSMGMT
Mounting VHDX file at \\localhost\V$\VMs\AzSMGMT.vhdx
Injecting answer file to \\localhost\V$\VMs\AzSMGMT.vhdx
Mounted Disk Volume is: X
Creating VMs\Base folder structure on AzSMGMT
Injecting files into \\localhost\V$\VMs\AzSMGMT.vhdx
Dismounting VHDX File at path \\localhost\V$\VMs\AzSMGMT.vhdx
[Build cluster - Step 4/11] Creating HCI node VMs (AzSHOSTx)...
Creating VM AzSHOST1
Performing offline installation of Hyper-V on AzSHOST1
Installing and Configuring Failover Clustering on AzSHOST1
Mounting VHDX file at \\localhost\V$\VMs\AzSHOST1.vhdx
Injecting answer file to \\localhost\V$\VMs\AzSHOST1.vhdx
Mounted Disk Volume is: E
Dismounting VHDX File at path \\localhost\V$\VMs\AzSHOST1.vhdx
Creating VM AzSHOST2
Performing offline installation of Hyper-V on AzSHOST2
Installing and Configuring Failover Clustering on AzSHOST2
Mounting VHDX file at \\localhost\V$\VMs\AzSHOST2.vhdx
Injecting answer file to \\localhost\V$\VMs\AzSHOST2.vhdx
Mounted Disk Volume is: E
Dismounting VHDX File at path \\localhost\V$\VMs\AzSHOST2.vhdx
[Build cluster - Step 5/11] Starting VMs...
Starting VM: AzSMGMT
Starting VM: AzSHOST1
Starting VM: AzSHOST2
[Build cluster - Step 6/11] Configuring host networking and storage...
Testing whether VMs are available...
VM AzSMGMT is now online
VM AzSHOST1 is now online
VM AzSHOST2 is now online
Setting NICs on VM AzSHOST1
Enabling Windows Remoting in AZSHOST1
Setting NICs on VM AzSHOST2
Enabling Windows Remoting in AZSHOST2
Restarting VM: AzSHOST1
Restarting VM: AzSHOST2
Restarting VM: AzSMGMT
Testing whether VMs are available...
VM AzSMGMT is now online
VM AzSHOST1 is now online
VM AzSHOST2 is now online
Creating NAT Switch on switch InternalSwitch
Configuring Fabric network on Management VM
Enabling PSRemoting on AZSMGMT
Creating VM Switch on AZSMGMT
Configuring NAT on AZSMGMT
Configuring Provider NIC on AZSMGMT
Configuring VLAN200 NIC on AZSMGMT
Configuring VLAN110 NIC on AZSMGMT
Configuring simulatedInternet NIC on AZSMGMT
Configuring NAT
Removing Gateway from Fabric NIC
[Build cluster - Step 7/11] Build router VM...

**Comment by fourier134949** [comment]
![Image](https://github.com/user-attachments/assets/40895dab-b157-4da6-aa03-88db3597fb02)

**Comment by dkirby-ms** [comment]
This step often takes quite a long time. Please ensure the script can continue to run at this step. 

Also, there are some cases where a user clicks on the PowerShell window it will pause the PowerShell execution and you must hit space to resume. This can be detected by the presence of a block cursor on the PowerShell window, which i dont see in your screenshot but I'll mention it anyway. 

Please give us an update if you are still stuck at that step and have confirmed that PowerShell execution is not paused.

**Comment by fourier134949** [comment]
After a while (a couple of hours at least) the script managed to complete all the steps. The HCI Cluster seems now healthy, up and running.
Thanks a lot for the support

**Comment by likamrat** [comment]
Awesome @fourier134949 . Closing this for now.
