### ISSUE TITLE
HCIBox feature request - Graceful shutdown of HCIBox-Client-VM

### ISSUE THREAD

**Issue by JozoSlejko** [microsoft/azure_arc#2751]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
HCIBox

**Describe the issue or the bug**
After starting the HCIBox VM which was shut down for a couple of days, the Arc Resource Bridge does not go online.

**To Reproduce**
1. Start the HCIBox VM
2. Wait for 30 minutes
3. Arc Resource Bridge shows offline
4. Reboot Arc Resource Bridge VM
5. Wait for 30 minutes
6. Arc Resource Bridge is still showing offline

**Expected behavior**
Arc Resource Bridge is online 30 minutes after starting HCIBox VM

**Environment summary**
Latest HCIBox on Azure

**Have you looked at the Troubleshooting and Logs section?**
Yes

**Comment by dkirby-ms** [comment]
Hi @JozoSlejko, this is because of the shutdown of the HCIBox host. The resource bridge will often not recover properly when the host is shutdown. Unfortunately there is no HCIBox workaround for this other than redeploying the cluster.

**Comment by JozoSlejko** [comment]
@dkirby-ms thanks for the quick reply and explanation. Given the time needed and potential errors with greenfield HCIBox deployment, that is most unfortunate. Are we to expect the same problem with unplanned reboot/shutdown of production Arc resource bridge VMs? If possible, can this be added to list of improvements for HCI/HCIbox? Cheers

**Comment by dkirby-ms** [comment]
Yes its one of the features in the backlog
