### ISSUE TITLE
Can't deploy JumpStart DataOps. Fails retrieving contents from registry MCR.MICROSOFT.COM

### ISSUE THREAD

**Issue by sammesel** [microsoft/azure_arc#2775]
When deploying DataOps jumpstart, it works well and it gets to deploy all resources
But when launching the ArcBox client VM, connecting via BASTION (username@jumpstart.local) we can see the autoexecute script running, and at a given point when it tries to obtain contents from MCR.Microsoft.com it fails. From that point on, everything shows an error message

![Image](https://github.com/user-attachments/assets/43c00768-cd60-4a16-9533-cd1f65b2c02b)

today, after trying the same DataOps jumpstart I was able to move a little bit further and there was no issues accessing the MCR registry, but the process failed again, at this time on another point shown below:

ERROR: Deployment failed. Correlation ID: e40e5345-4a36-4d67-9545-094fb6ad02b6. "Microsoft.ExtendedLocation" resource provider does not have the required permissions to create a namespace on the cluster. Refer to https://aka.ms/ArcK8sCustomLocationsDocsEnableFeature to provide the required permissions to the resource provider.
ERROR: Deployment failed. Correlation ID: 589d0be0-4c47-4fb1-ad71-5b9e5271e187. "Microsoft.ExtendedLocation" resource provider does not have the required permissions to create a namespace on the cluster. Refer to https://aka.ms/ArcK8sCustomLocationsDocsEnableFeature to provide the required permissions to the resource provider.
Deploying arc data controller on ArcBox-K3s-Data-3874
 
 
Deploying arc data controller on ArcBox-AKS-DR-Data-3874

![Image](https://github.com/user-attachments/assets/66e2d330-be9a-4184-aa9e-07d7b8ceedc8)

![Image](https://github.com/user-attachments/assets/edb4669d-8bf8-4e94-a7dc-802e9e5a4f64)

**Comment by janegilring** [comment]
Hi @sammesel , 

Could you verify that this resource provider is registered in the subscription?
`az provider show -n Microsoft.ExtendedLocation -o table`

If not, you can register it using this command:
`az provider register --namespace Microsoft.ExtendedLocation`


Also to make sure, did you run the below command and pass in the returned value to the Custom Location RPOID parameter in the ArcBox deployment?

`customLocationRPOID=$(az ad sp list --filter "displayname eq 'Custom Locations RP'" --query "[?appDisplayName=='Custom Locations RP'].id" -o tsv)`

**Comment by janegilring** [comment]
@sammesel Any updates from your side?

**Comment by janegilring** [comment]
Closing this issue as there has been no updates for the past couple of weeks. Feel free to re-open if needed.
