### ISSUE TITLE
HCIBox - autoDeployClusterResource set to true / Enable Storage Auto IP

### ISSUE THREAD

**Issue by TimAbmgf** [microsoft/azure_arc#2780]
In my parameters file this is how I have "autoDeployClusterResource" it set:
![Image](https://github.com/user-attachments/assets/5d772e3e-8f2d-4781-a210-6d7cfd41ed4f)

However, when I sign into my HCIBox-Client, I still need to deploy a custom template.

This is the Syntax from the site https://azurearcjumpstart.com/azure_jumpstart_hcibox/cloud_deployment :
_If everything looks good, and you did not choose to configure the autoDeployClusterResource parameter with the value true in your deployment, proceed to the next section to validate and deploy your cluster. If you did enable this parameter, you may proceed to the section Deployment complete at the end of this page. Visit troubleshooting if needed for deployment issues._

It seems that if I have the setting in my parameters, this should happen automatically. I am not sure if there is a case sensitivity that causes me to need to deploy the 'custom template' manually.

The other thing I run into is, each time I try to deploy the template (with the parameters). 
![Image](https://github.com/user-attachments/assets/8b5e78c0-d3fd-43c5-b4e3-c71ca77cdb1d)

**To Reproduce**

**Expected behavior**

**Environment summary**

**Have you looked at the Troubleshooting and Logs section?**

**Screenshots**

**Additional context**

**Comment by janegilring** [comment]
Hi @TimAbmgf , could you share the log-files from `C:\HCOBox\Logs`? When we get that we can try to look at what might have happened.

Also, could you elaborate what was the issue related to the `enableStorageAutoIp` parameter?

**Comment by janegilring** [comment]
@TimAbmgf Any updates from your side?

**Comment by janegilring** [comment]
Closing this issue as there has been no updates for the past couple of weeks. Feel free to re-open if needed.
