### ISSUE TITLE
Feature Request: Azure vNET connectivity to HCI Jumpstart environment

### ISSUE THREAD

**Issue by Arnth** [microsoft/azure_arc#2795]
**Is your feature request related to a problem? Please describe.**
As as user of the Arc Jumpstart HCI project, I would like the ability to allow other resources in the Azure subscription/HCI vNET connectivity to the HCI cluster resources.  Currently, no traffic will route into the HCIClient VM to the 192.168.x.x networks.

**Describe the solution you'd like.**
Allow routing of traffic on the HCI-vNET to allow for bi-directional traffic between Azure resources/VMs hosted in the same vNET to the nested environment on the HCIClient VM, specifically the Azure Stack HCI cluster nodes and the nested domain controller.

**Describe alternatives you've considered.**
I've tried deploying RRAS at the top level of the HCIClient VM instance, with a new NETNAT object. I've tried creating an alternate NIC and NAT Subnet on the vNET to direct all traffic.  I've tried deploying a VNG with a LNG connection to RRAS at the root of the HCIClient VM.

**Additional context.**
Traffic will currently go outbound, but trying to route traffic from the vNET for 192.168.1.x or other subnets inbound to the HCIClient VM and further into the nested environment terminates at the HCIClient.  It won't go deeper.  If I setup a NetNatStatic mapping, I can NAT ports deeper into the environment.  What I'd like is for all traffic to be redirected into the HCI nested networks.

**Comment by janegilring** [comment]
Hi @Arnth 

Thanks for the feature request as well as additional details on what you have tried.

We will explore options for this request as we start planning for the next iteration of HCIBox in the coming 1-2 months.

**Comment by dkirby-ms** [comment]
This is tracked in our backlog and we will close this issue as tracked.
