### ISSUE TITLE
Type 'ValidateAzureStackNetworkATCSettings' of Role 'HostNetwork' raised an exception:

### ISSUE THREAD

**Issue by henrikmotzkus** [microsoft/azure_arc#2861]
DONE

> **Note:** For ease of issues and pull requests management and tracking, we kindly ask you to provide a meaningful and concise title to this issue and answer all questions to the best of your ability.

**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
HCIBox

**Describe the issue or the bug**
At cluster deployment phase deployment stucks at "Configure the host networking settings."

**To Reproduce**
Deploy HCIBox to region West Europe

**Expected behavior**
Cluster configuration runs through

**Environment summary**

- Deployment in region westeurope
- azd version 1.11.0

**Have you looked at the Troubleshooting and Logs section?** DONE

**Screenshots**
![Image](https://github.com/user-attachments/assets/2b42d64b-ccdd-4816-98e3-4aa7f3d779ab)

**Additional context**
Exception
Type 'ValidateAzureStackNetworkATCSettings' of Role 'HostNetwork' raised an exception: Connecting to remote server localhost failed with the following error message : The WinRM client cannot process the request. A computer policy does not allow the delegation of the user credentials to the target computer. Use gpedit.msc and look at the following policy: Computer Configuration -> Administrative Templates -> System -> Credentials Delegation -> Allow Delegating Fresh Credentials. Verify that it is enabled and configured with an SPN appropriate for the target computer. For example, for a target computer name "myserver.domain.com", the SPN can be one of the following: WSMAN/myserver.domain.com or WSMAN/*.domain.com. For more information, see the about_Remote_Troubleshooting Help topic. at Invoke-ValidateAzureStackNetworkATCSettings, C:\NugetStore\Microsoft.AS.Network.Deploy.HostNetwork.1.2411.0.38\content\Powershell\Roles\HostNetwork\HostNetwork.psm1: line 3872 at ValidateAzureStackNetworkATCSettings, C:\NugetStore\Microsoft.AS.Network.Deploy.HostNetwork.1.2411.0.38\content\Powershell\Classes\HostNetwork\HostNetwork.psm1: line 82 at <ScriptBlock>, C:\CloudDeployment\ECEngine\InvokeInterfaceInternal.psm1: line 139 at Invoke-EceInterfaceInternal, C:\CloudDeployment\ECEngine\InvokeInterfaceInternal.psm1: line 134

**Comment by kvieracloud** [comment]
I am also able to reproduce this, deploying to East US. 

I tried adding wsman/localhost to the 'Allow Delegating Fresh Credentials' policy like the error message says, but this did not resolve the issue.

![Image](https://github.com/user-attachments/assets/8107d3a9-9c9a-434d-a33a-2fa079f5cf5c)

**Comment by PennyMa427** [comment]
The script failed at 
Invoke-Command -ComputerName localhost -Credential $credHCIBoxDeployUser -ScriptBlock {$script} -Authentication Credssp

and I can reproduce the Error Message with 
Test-WSMan -ComputerName localhost -Authentication Credssp -Credential $credHCIBoxDeployUser

I tried these:
winrm quickconfig
Enable-WSManCredSSP -Role Client -DelegateComputer * -Force
$PolicyPath = "HKLM:\SOFTWARE\Policies\Microsoft\Windows\CredentialsDelegation"
Set-ItemProperty -Path $PolicyPath -Name AllowFreshCredentialsWhenNTLMOnly  -Value "wsman/AzSHOST1" -Force
reboot server 

Not sure which one helps, but the deployment goes through.

**Comment by dkirby-ms** [comment]
This was addressed with #2865. Please redeploy.
