### ISSUE TITLE
Cannot delete Azure Arc AKS cluster in JumpStartHCIBox

### ISSUE THREAD

**Issue by mshamim69** [microsoft/azure_arc#2862]
> **Note:** For ease of issues and pull requests management and tracking, we kindly ask you to provide a meaningful and concise title to this issue and answer all questions to the best of your ability.

**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**

JumpStart HCIBox

**Describe the issue or the bug**
Cannot delete the AKS cluster created by the Configure-AKSWorkloadCluster.ps1 of JumpStart HCIBox. I have been successful to delete and recreate the cluster couple of times earlier. But now there is timeout in deleting Nodepool. Even GitOps configuration and flux extension cannot be deleted.

**To Reproduce**
1. Go to 'Azure Arc cluster from Portal'
2. Click on 'Delete'
3. Delete jobs keeps on running and fails
4. Tried also with *az aksarc delete ..* command from HCIBox-Client machine. No success. Timeout.

**Expected behavior**
The AKS cluster is deleted and removed from the Resource Group.

**Environment summary**

PS C:\HCIBox> az --version
azure-cli                         2.65.0 *
core                                2.65.0 *
telemetry                        1.1.0
Extensions:
aksarc                              1.4.23
customlocation                0.1.3
Dependencies:
msal                                 1.31.0
azure-mgmt-resource      23.1.1

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\hciboxdemo\.azure\cliextensions'

Python (Windows) 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]

**Have you looked at the Troubleshooting and Logs section?**

**Screenshots**
![Image](https://github.com/user-attachments/assets/1405ae80-7dec-4aa5-80fc-cf78caacb7aa)

**Additional context**

I have another JumpStart HCIBox AKS cluster running in another resource group. Tried to delete that. No success.

**Comment by dkirby-ms** [comment]
Are you still seeing this issue? I dont think this is related to HCIBox specifically. Try deleting the resource group.

**Comment by mshamim69** [comment]
> Are you still seeing this issue? I dont think this is related to HCIBox specifically. Try deleting the resource group.

Hi! Yes, the issue is still valid. All the resources related to HCIBox are deleted in the Resource Group except the AKS cluster. Deleting the resource group and recreate the AKS cluster resource from scratch (HCIBox cluster -> ) is time consuming (approx: 5/6 hrs) for development work. Also, sometimes the resource group is associated with other resources for other purpose.

**Comment by dkirby-ms** [comment]
Hi @mshamim69 . I am not able to reproduce this. Can you please share the error you get?

**Comment by mshamim69** [comment]
> Hi [@mshamim69](https://github.com/mshamim69) . I am not able to reproduce this. Can you please share the error you get?

Hi! We need to close the issue as the resource is not available anymore though the resource group has it listed still. I cannot get the error code.
