### ISSUE TITLE
Agora-HyperMarket Deployment Issue

### ISSUE THREAD

**Issue by mgodfre3** [microsoft/azure_arc#2863]
> **Note:** For ease of issues and pull requests management and tracking, we kindly ask you to provide a meaningful and concise title to this issue and answer all questions to the best of your ability.

**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
https://jumpstart.azure.com/azure_jumpstart_ag/contoso_hypermarket/deployment

**Describe the issue or the bug**
When Deploying the Initial Template, I am seeing a capacity error, but not on a DS Family CPU as the documentation mentions, I am seeing it on the 
Standard_B4ms family. 

See Error message below:

PS C:\Users\migodfre> az deployment group create --resource-group $rg --template-file $template --parameters $param -p customLocationRPOID="$customLocationRPOID"
{"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/fbaf508b-cb61-4383-9cda-a42bfa0c7bc9/resourceGroups/AdaptiveCloud-AgoraHyper/providers/Microsoft.Resources/deployments/main","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"InvalidTemplateDeployment","message":"The template deployment 'ubuntuRancherK3sDeployment' is not valid according to the validation procedure. The tracking id is 'a4573123-87c1-48aa-bdc4-9980ccf7fbd6'. See inner errors for details.","details":[{"code":"SkuNotAvailable","message":"The requested VM size for resource 'Following SKUs have failed for Capacity Restrictions: Standard_B4ms' is currently not available in location 'eastus'. Please try another size or deploy to a different location or different zone. See https://aka.ms/azureskunotavailable for details."}]},{"code":"InvalidTemplateDeployment","message":"The template deployment 'ubuntuRancherK3s2Deployment' is not valid according to the validation procedure. The tracking id is '76ec001b-ede3-4520-b8f6-102369118d88'. See inner errors for details.","details":[{"code":"SkuNotAvailable","message":"The requested VM size for resource 'Following SKUs have failed for Capacity Restrictions: Standard_B4ms' is currently not available in location 'eastus'. Please try another size or deploy to a different location or different zone. See https://aka.ms/azureskunotavailable for details."}]}]}}

**To Reproduce**

$rg="AdaptiveCloud-AgoraHyper"
$param="C:\Users\migodfre\Documents\GitHub\azure_arc\azure_jumpstart_ag\contoso_hypermarket\bicep\main.bicepparam"
$template="C:\Users\migodfre\Documents\GitHub\azure_arc\azure_jumpstart_ag\contoso_hypermarket\bicep\main.bicep"
$customLocationRPOID=(az ad sp list --filter "displayname eq 'Custom Locations RP'" --query "[?appDisplayName=='Custom Locations RP'].id" -o tsv)

az deployment group create --resource-group $rg --template-file $template --parameters $param -p customLocationRPOID="$customLocationRPOID"

**Expected behavior**
Deployment would proceed.

**Environment summary**

**Have you looked at the Troubleshooting and Logs section?**
Yes and no mention of that  Family Size needed. 

**Screenshots**

**Additional context**

**Comment by dkirby-ms** [comment]
Hi Mike, this is a capacity issue. Please try a different region.

**Comment by dkirby-ms** [comment]
Deployment doc reflect need for D and B series VMs
