### ISSUE TITLE
ArcBox Deployment from Azure Portal does not work

### ISSUE THREAD

**Issue by sforstre** [microsoft/azure_arc#2870]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
ArcBox Full

**Describe the issue or the bug**
When deploying ArcBox Full via Azure Portal, Validation failed witr Error code "{
  "code": "InvalidTemplate",
  "message": "Deployment template validation failed: 'The following parameters were supplied, but do not correspond to any parameters defined in the template: 'spnTenantId'. The parameters defined in the template are: 'sshRSAPublicKey, spnClientId, spnClientSecret, tenantId, windowsAdminUsername, windowsAdminPassword, logAnalyticsWorkspaceName, flavor, githubAccount, githubBranch, deployBastion, githubUser, principalId, securityAdminRoleGuid, contributorRoleGuid, securityReaderRoleGuid, monitoringMetricsRoleGuid, userAccessAdministratorRoleGuid, epochTime'. Please see https://aka.ms/arm-pass-parameter-values for usage details.'."
}"

**To Reproduce**
1. Go to 'AzureArc'
2. Click on 'Try ArcBox'
3. Select "ArcBox Full"
4. Click on Next
5. Fill in mandatory parameter
6. Click on Next
7. Validation fails

**Expected behavior**
Deployment of Arc Box starting

**Additional context**
Applies to both ArcBox Deployment types Full and IT-Pros

**Comment by chintalavr** [comment]
ArcBox Full flavor is no longer supported. Please use ITPro or DataOps instead, depending on the experience looking for using ArcBox deployment.

**Comment by chintalavr** [comment]
ArcBox Full flavor is no longer supported. Please use ITPro or DataOps instead, depending on the experience looking for using ArcBox deployment. Please visit https://azurearcjumpstart.io/azure_jumpstart_arcbox/getting_started for supported ArcBox flavors and get started with ArcBox deployment.
