### ISSUE TITLE
Not able to onboard OKE cluster to azure ARC

### ISSUE THREAD

**Issue by roshithrajan** [microsoft/azure_arc#2881]
> **Note:** For ease of issues and pull requests management and tracking, we kindly ask you to provide a meaningful and concise title to this issue and answer all questions to the best of your ability.

**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
no

**Describe the issue or the bug**
when i tried to onboard OKE cluster to Azure ARC getting below error 

 az connectedk8s connect --name test --resource-group test-rg
This operation might take a while...

Step: 2024-12-13T12-35-25Z: Validating custom access token
Step: 2024-12-13T12-35-25Z: Checking Provider Registrations
Step: 2024-12-13T12-35-26Z: Setting KubeConfig
Step: 2024-12-13T12-35-26Z: Escape Proxy Settings, if passed in
Step: 2024-12-13T12-35-26Z: Checking Connectivity to Cluster
Unable to verify connectivity to the Kubernetes cluster.
Error occured while connecting to the kubernetes cluster:
Error Response: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}

**To Reproduce**

**Expected behavior**

**Environment summary**

**Have you looked at the Troubleshooting and Logs section?**

**Screenshots**

**Additional context**

**Comment by sebassem** [comment]
@roshithrajan  Thanks for opening the issue, can you share the link to the scenario you a referencing ?

**Comment by roshithrajan** [comment]
Any idea when OKE will support ARC 
https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/validation-program

**Comment by sebassem** [comment]
> Any idea when OKE will support ARC https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/validation-program

Unfortunately not, you can submit this feedback here https://feedback.azure.com/d365community/forum/5c778dec-0625-ec11-b6e6-000d3a4f0858
