### ISSUE TITLE
Pre-deployment script fails on Hyper-V attaching wrong vhdx file

### ISSUE THREAD

**Issue by Ventilios** [microsoft/azure_arc#2886]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
ArcBox for IT Pros

**Describe the issue or the bug**
The pre-deployment script _ArcServersLogonScript.ps1_ is downloading nested VMs vhdx-file for SQL. The vhdx-file is downloaded to F:\Virtual Machines\ and trying to attach the vhdx-file to Hyper-V. 
This results into a file not found error in the error log (replaced the prefix I used with [prefix]. Three letters in my case):

```
Apply :: VMHyperV [[prefix]-SQL]
  Configure VM [prefix]-SQL
  Module: HyperVDsc by DSC Community [Local]
    https://github.com/dsccommunity/HyperVDsc
    This module contains DSC resources for deployment and configuration of Microsoft Hyper-V.
  Settings:
    StartupMemory: 6GB
    Path: F:\Virtual Machines
    SecureBoot: true
    SwitchName: InternalNATSwitch
    State: Running
    Name: [prefix]-SQL
    VhdPath: F:\Virtual Machines\ArcBox-SQL.vhdx
    RestartIfNeeded: true
    EnableGuestService: true
    ProcessorCount: 2
    Generation: 2
_[text snip]_
Apply :: VMHyperV [[prefix]-SQL]
  The configuration unit failed while attempting to apply the desired state.
Failed to add device 'Virtual Hard Disk'.
Attachment 'F:\Virtual Machines\ArcBox-SQL.vhdx' not found. Error: 'The system cannot find the file specified.'.
'[prefix]-SQL' failed to add device 'Virtual Hard Disk'. (Virtual machine ID _[ID]_)…
```
When reviewing the log files it seems the Hyper-V deployment is trying to attach a vhdx-file with a fixed value of _ArcBox-SQL.vhdx_ but the vhdx-file has been downloaded with _ArcServersLogonScript.ps1_ to _$SQLvmvhdPath = "$Env:ArcBoxVMDir\$namingPrefix-SQL.vhdx"_ 
When looking at the DSC files it seems to be pointing to a fixed filename _virtual_machines_sql.dsc.yml_ parameter _VhdPath: F:\Virtual Machines\ArcBox-SQL.vhdx_ 

**To Reproduce**
Getting the issue after deploying the ARC environment using this BICEP-template: https://github.com/microsoft/azure_arc/tree/main/azure_jumpstart_arcbox/bicep.
Template parameters used: 
using 'main.bicep'
param tenantId = ''
param windowsAdminUsername = ''
param windowsAdminPassword = ''
param logAnalyticsWorkspaceName = ''
param flavor = 'ITPro'
param deployBastion = true
param namingPrefix = '[prefix]'
param vmAutologon = true
param resourceTags = {
  Solution: 'jumpstart_arcbox'
  Environment: 'sandbox'
  CostCenter: 'it'
} // Add tags as needed
param autoShutdownEnabled = true
param autoShutdownTime = '1800'
param autoShutdownTimezone = 'UTC'
param autoShutdownEmailRecipient = ''

**Expected behavior**
When using a non-default _param namingPrefix_, the pre-deployment script for Hyper-V should have attached F:\Virtual Machines\[prefix]-SQL.vhdx instead of F:\Virtual Machines\ArcBox-SQL.vhdx

**Comment by janegilring** [comment]
The issue is now resolved.
