### ISSUE TITLE
node(s) had volume node affinity conflict

### ISSUE THREAD

**Issue by katomel4** [microsoft/azure_arc#304]
**Describe the bug**
from azure data studio and AKS spans on availability zones.
deploying any data controller or any SQL instance (MI, PG)  result almost every time with error "node(s) had volume node affinity conflict".
specially when the AKS cluster need to scale into more nodes. as I understand it is happening because the managed discs for some pods are being deployed on a different zone than their pods (nodes).
some times I can fix it by delete the pod and let it recreate.

**Comment by likamrat** [comment]
Thanks @katomel4.
Currently, AKS with AZ is not supported as stated in the release notes.
https://docs.microsoft.com/en-us/azure/azure-arc/data/release-notes#known-issues

**Comment by katomel4** [comment]
yep see it now :)
