### ISSUE TITLE
Data Controller Terraform plan for EKS - no Windows 2019 client created

### ISSUE THREAD

**Issue by chrisadkin** [microsoft/azure_arc#309]
**Describe the bug**
No Terraform language to create the Windows 2019 client EC2 instance.

**To Reproduce**
I run through the instructions detailed on the blog and when the terraform apply completes, there is password_decrypted output, I've then gone through each .tf file and I cannot find anything in any of them that would create the Windows 2019 client on EC2, I suspect that this is missing.

**Expected behavior**
When terraform apply completes, which it does without any errors, per the instructions in the repo, I expect a line at the end for password_decrypted . Also when I go into the AWS Console I expect to be able to find an EC2 instance corresponding to the Windows 2019 client.

**Comment by likamrat** [comment]
Thanks @chrisadkin. Do you mind sharing your plan output?

The tf flie for the [client vm is here](https://github.com/microsoft/azure_arc/blob/main/azure_arc_data_jumpstart/eks/terraform/client_vm.tf) and should be executed when running the ```terraform apply``` command from the *azure_arc_data_jumpstart/eks/terraform* folder.

**Comment by chrisadkin** [comment]
Closing this looks like I was trying to deploy the arc controller from the wrong directory, thanks for your help.
