### ISSUE TITLE
Data Controller Terraform plan - EKS Perms need adding

### ISSUE THREAD

**Issue by chrisadkin** [microsoft/azure_arc#310]
**Describe the bug**
Following the instructions verbatim, terraform plan fails when executing the providers.tf file, stating that the necessary permissions to list available regions (line 6) are missing, this is rectified by adding an inline policy to the EKS user in the AWS console such that the arcdemo user has explicit permissions to perform actions on EKS objects.

**To Reproduce**
Run commands as detailed in repo.

**Expected behavior**
terraform apply to complete without any errors.

Addendum

The issue appears when you run terraform apply or terraform plan as per the instructions in the repo, I no longer have the screen shot, suffice it say it clearly states that the necessary permissions to list available regions per line 6 of the providers.tf file do not exist.

**Comment by likamrat** [comment]
Thank you @chrisadkin. Do you mind sharing your plan error output and screenshots?
The *providers.tf* files will be used by the *terraform init* command so not sure what are you trying to run and what is failing.

**Comment by chrisadkin** [comment]
Closing this, may be related to the fact that I was running terraform apply from the wrong directory, thanks for your help.
