### ISSUE TITLE
Support for MicroK8s Deployment guide with Arc connectivity

### ISSUE THREAD

**Issue by likamrat** [microsoft/azure_arc#32]
### Description
Support for a lightweight MicroK8s deployment guide with Arc connectivity

### Implementation Requirements

- Lightweight for fast provisioning
- Parameterize deployment wherever possible
- Azure Arc connectivity instructions
- Detailed README
- Clear screenshots
- Reference in the main README

**Comment by shoegazerpt** [comment]
@likamrat can I take this one?
