### ISSUE TITLE
SQL Server EC2 instance

### ISSUE THREAD

**Issue by spotakash** [microsoft/azure_arc#337]
**Describe the bug**
I run SQL Server on AWS simulation. Everything went smooth and things got provision as per documentation and server started showing up in Arc. Only thing which went missing is SQL server did not show up Arc or even in Resource Group. Thus, SQL server assessment did not work. 

Screenshot,
![image](https://user-images.githubusercontent.com/7689697/103734468-01dadf80-5027-11eb-86f4-58533aaaccfe.png)

**Comment by likamrat** [comment]
Thank you @spotakash . There were some major changes to the SQL Arc onboarding script. I will issue a PR soon so you can try again.

**Comment by likamrat** [comment]
@spotakash can you please pull the latest, retry and report back?

**Comment by spotakash** [comment]
It worked perfectly now.
