### ISSUE TITLE
k3s deployment using ARM template is failing.

### ISSUE THREAD

**Issue by sowsan** [microsoft/azure_arc#348]
**Describe the bug**
k3s deployment using ARM template is failing.

**To Reproduce**
https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/rancher_k3s/azure_arm_template/

**Screenshots**

**Additional context**
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "VMExtensionProvisioningError",
      "message": "VM has reported a failure when processing extension 'installscript_k3s'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=1\n[stdout]\np://azure.archive.ubuntu.com/ubuntu bionic-backports InRelease\nHit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease\nReading package lists...\nHit:1 http://azure.archive.ubuntu.com/ubuntu bionic InRelease\nHit:2 http://azure.archive.ubuntu.com/ubuntu bionic-updates InRelease\nHit:3 http://azure.archive.ubuntu.com/ubuntu bionic-backports InRelease\nHit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease\nReading package lists...\nReading package lists...\nBuilding dependency tree...\nReading state information...\nlsb-release is already the newest version (9.20170808ubuntu1).\nlsb-release set to manually installed.\ncurl is already the newest version (7.58.0-2ubuntu3.12).\ncurl set to manually installed.\ngnupg is already the newest version (2.2.4-1ubuntu1.3).\ngnupg set to manually installed.\nThe following package was automatically installed and is no longer required:\n  linux-headers-4.15.0-124\nUse 'apt autoremove' to remove it.\nThe following NEW packages will be installed:\n  apt-transport-https\n0 upgraded, 1 newly installed, 0 to remove and 7 not upgraded.\nNeed to get 1696 B of archives.\nAfter this operation, 153 kB of additional disk space will be used.\nGet:1 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 apt-transport-https all 1.6.12ubuntu0.2 [1696 B]\nFetched 1696 B in 0s (0 B/s)\nSelecting previously unselected package apt-transport-https.\r\n(Reading database ... \r(Reading database ... 5%\r(Reading database ... 10%\r(Reading database ... 15%\r(Reading database ... 20%\r(Reading database ... 25%\r(Reading database ... 30%\r(Reading database ... 35%\r(Reading database ... 40%\r(Reading database ... 45%\r(Reading database ... 50%\r(Reading database ... 55%\r(Reading database ... 60%\r(Reading database ... 65%\r(Reading database ... 70%\r(Reading database ... 75%\r(Reading database ... 80%\r(Reading database ... 85%\r(Reading database ... 90%\r(Reading database ... 95%\r(Reading database ... 100%\r(Reading database ... 76696 files and directories currently installed.)\r\nPreparing to unpack .../apt-transport-https_1.6.12ubuntu0.2_all.deb ...\r\nUnpacking apt-transport-https (1.6.12ubuntu0.2) ...\r\nSetting up apt-transport-https (1.6.12ubuntu0.2) ...\r\nHit:1 http://azure.archive.ubuntu.com/ubuntu bionic InRelease\nHit:2 http://azure.archive.ubuntu.com/ubuntu bionic-updates InRelease\nHit:3 http://azure.archive.ubuntu.com/ubuntu bionic-backports InRelease\nHit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease\nGet:5 https://packages.microsoft.com/repos/azure-cli bionic InRelease [3964 B]\nGet:6 https://packages.microsoft.com/repos/azure-cli bionic/main amd64 Packages [12.0 kB]\nFetched 15.9 kB in 1s (24.8 kB/s)\nReading package lists...\nReading package lists...\nBuilding dependency tree...\nReading state information...\nThe following package was automatically installed and is no longer required:\n  linux-headers-4.15.0-124\nUse 'apt autoremove' to remove it.\nThe following NEW packages will be installed:\n  azure-cli\n0 upgraded, 1 newly installed, 0 to remove and 7 not upgraded.\nNeed to get 49.9 MB of archives.\nAfter this operation, 615 MB of additional disk space will be used.\nGet:1 https://packages.microsoft.com/repos/azure-cli bionic/main amd64 azure-cli all 2.16.0-1~bionic [49.9 MB]\nFetched 49.9 MB in 1s (50.9 MB/s)\nSelecting previously unselected package azure-cli.\r\n(Reading database ... \r(Reading database ... 5%\r(Reading database ... 10%\r(Reading database ... 15%\r(Reading database ... 20%\r(Reading database ... 25%\r(Reading database ... 30%\r(Reading database ... 35%\r(Reading database ... 40%\r(Reading database ... 45%\r(Reading database ... 50%\r(Reading database ... 55%\r(Reading database ... 60%\r(Reading database ... 65%\r(Reading database ... 70%\r(Reading database ... 75%\r(Reading database ... 80%\r(Reading database ... 85%\r(Reading database ... 90%\r(Reading database ... 95%\r(Reading database ... 100%\r(Reading database ... 76700 files and directories currently installed.)\r\nPreparing to unpack .../azure-cli_2.16.0-1~bionic_all.deb ...\r\nUnpacking azure-cli (2.16.0-1~bionic) ...\r\nSetting up azure-cli (2.16.0-1~bionic) ...\r\n\n[stderr]\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100    12  100    12    0     0   1714      0 --:--:-- --:--:-- --:--:--  1714\nsudo: unknown user: sowmyans\nsudo: unable to initialize policy plugin\ncp: cannot stat 'k3sup': No such file or directory\n2020/12/14 19:32:20 40.87.5.204\nCreated symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.\ncp: cannot create regular file '/home/sowmyans/.kube/config': No such file or directory\nchown: invalid user: ‘sowmyans’\nsudo: unknown user: sowmyans\nsudo: unable to initialize policy plugin\nsudo: unknown user: sowmyans\nsudo: unable to initialize policy plugin\nsudo: unknown user: sowmyans\nsudo: unable to initialize policy plugin\nsudo: unknown user: sowmyans\nsudo: unable to initialize policy plugin\nsudo: unknown user: sowmyans\nsudo: unable to initialize policy plugin\ncp: cannot create regular file '/home/sowmyans/hello-kubernetes.yaml': No such file or directory\n\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "
    }
  ]
}

**Comment by likamrat** [comment]
@sowsan I wasn't able to repro. Would you mind sharing your parameters file?
