### ISSUE TITLE
SQL Server Virtual Machine

### ISSUE THREAD

**Issue by sqlgirl3** [microsoft/azure_arc#355]
**Describe the bug**
Error on the end the deployment with the following error : 
" VM has reported a failure when processing extension 'ClientTools'. Error message: "Failed to download all specified files. Exiting. Error Message:
The remote server returned an error: (404) Not Found."
"More information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot"

**To Reproduce**
1. Go to Azure cloud shell and run the following command : 
"az deployment group create --resource-group Arc-SQL-Demo --name arcsqlsrvdemo --template-uri https://raw.githubusercontent.com/microsoft/azure_arc/main/azure_arc_sqlsrv_jumpstart/azure/arm_template/azuredeploy.json --parameters azuredeploy.parameters.json"

**Expected behavior**

**Screenshots**

**Additional context**
The scenario is Azure Arc for SQLServer

**Comment by likamrat** [comment]
Thank you @sqlgirl3. Can you please try and report back?

**Comment by sqlgirl3** [comment]
Hi @likamrat , It WORK FINE now. THANK YOU for your quick fix!
