### ISSUE TITLE
debootstrap/chroot/docker/... installs

### ISSUE THREAD

**Issue by jimdigriz** [microsoft/azure_arc#358]
**Describe the bug**
Not clear where I can submit bugs/issues with `azcmagent` so using here, do point me elsewhere if I am in the wrong place.

When building images from scratch (using debootstrap, chroot, docker, ...) `azcmagent` fails to install as it needlessly expects an active running `systemd` (or upstart).

For Debian/Ubuntu the needless constraints kick in at:

 * `/var/lib/dpkg/info/azcmagent.postinst`
     * calls to `systemctl daemon-{reload,reexec}` and `systemctl start ...`
 * `/opt/GC_Service/GC/service_scripts/gca_service_controller`
     * `get_system_service_controller()` expects pid 1 to be `systemd` or `init` (upstart)

**To Reproduce**
Steps to reproduce the behavio*u*r:
1. `docker run -it --rm ubuntu:bionic`
1. `apt-get update && apt-get install systemd-sysv ...`
1. add `/etc/apt/sources.list.d/microsoft-prod.list`
    * `. /etc/os-release && echo "deb [signed-by=/etc/apt/trusted.gpg.d/microsoft.gpg.asc] https://packages.microsoft.com/$ID/$VERSION_ID/prod $VERSION_CODENAME main" > /etc/apt/sources.list.d/microsoft-prod.list`
1. `apt-get update && apt-get install azcmagent`

**Expected behavior**
Installation should not abort just because systemd (or upstart) is not actively running; it will be running later once the image is committed and booted.

It is safe to just continue the installation if `systemd` is not running.

**Additional context**
At the moment I have to use the following awful workaround in my installation script:
```
...

mv /bin/systemctl /bin/systemctl.orig
cat <<'EOF' > /bin/systemctl
#!/bin/sh

set -eu

case ${1:-} in
daemon-*|start) exit 0;;
esac

exec "$0.orig" "$@"
EOF
chmod +x /bin/systemctl

apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \
                --option=Dpkg::options::=--force-unsafe-io install --no-install-recommends \
        azcmagent

mv /bin/systemctl.orig /bin/systemctl

...
```

I also have to start Docker with the following to trick `gca_service_controller` into believing systemd is running:
```
docker run ... --entrypoint=/bin/sh -- ubuntu:bionic -c 'printf systemd-fake > /proc/$$/comm && /bin/sh'
```

After these hacks I can then boot my image for the first time and then run `azcmagent connect ...` to plumb it into Azure.

**Comment by palladia** [comment]
I've opened a work item to track this:  https://msazure.visualstudio.com/One/_workitems/edit/9166720

**Comment by dkirby-ms** [comment]
Hi @jimdigriz , thank you for this feedback. We have passed this on to the Azure engineering team.
