### ISSUE TITLE
SQL Managed Instance ARM Template

### ISSUE THREAD

**Issue by sqlgirl3** [microsoft/azure_arc#360]
**Describe the bug**
When executing the Deployment command : "az deployment group create --resource-group arc_aks_mi --name arcdatasqlmidemo --template-uri https://raw.githubusercontent.com/microsoft/azure_arc/main/azure_arc_data_jumpstart/aks/arm_template/mssql_mi/azuredeploy.json    --parameters azuredeploy.parameters.json"

The FOLLOWING ERROR is returned : "{"error":{"code":"InvalidTemplateDeployment","message":"The template deployment 'arcdatasqlmidemo' is not valid according to the validation procedure. The tracking id is '332ec992-4e4f-43a0-a417-49a66c1c9caa'. See inner errors for details.","details":[{"code":"InvalidParameter","message":"Provisioning of resource(s) for container service Arc-Data-SQLMI-AKS in resource group arc_aks_mi failed. Message: {\n  \"code\": \"InvalidParameter\",\n  \"message\": \"The value of parameter linuxProfile.ssh.publicKeys.keyData is invalid. Please see https://aka.ms/aks-naming-rules for more details.\",\n  \"target\": \"linuxProfile.ssh.publicKeys.keyData\"\n }. Details: "}]}}"

**To Reproduce**
1. Go to AZ cli command line 
2. Run the command : az deployment group create --resource-group arc_aks_mi --name arcdatasqlmidemo --template-uri https://raw.githubusercontent.com/microsoft/azure_arc/main/azure_arc_data_jumpstart/aks/arm_template/mssql_mi/azuredeploy.json  --parameters azuredeploy.parameters.json

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by likamrat** [comment]
@sqlgirl3 this looks like an issue with your ssh public key not being valid.

**Comment by sqlgirl3** [comment]
Oh Thanks @likamrat . I re-create the SSH with the Azure Portal instead of toscript it. And yes with the new key. It works. Thank you so much.
