### ISSUE TITLE
Deploy a GCP instance with Windows Server & Microsoft SQL Server and connect it to Azure Arc using Terraform

### ISSUE THREAD

**Issue by aseemamitesh** [microsoft/azure_arc#364]
**Scenario which you are working on**
https://github.com/microsoft/azure_arc/blob/main/docs/azure_arc_jumpstart/azure_arc_sqlsrv/gcp/gcp_terraform_winsrv/_index.md

**Describe the bug**
Only able to see the Arc server and log analytics workspace. SQL Server-Arc is not visible.

**To Reproduce**
Follow the steps as given in the link. Post the SQL server check in the server come back to Azure Portal, check the resource group and you will not find SQL Server-Azure Arc as one of the resource. Only Server and Log Analytics workspace is available. Just two resources instead of three.

**Expected behavior**
Resource Group should have 3 resources, Server Arc, SQL Server Arc and Log Analytics workspace

**Screenshots**
![image](https://user-images.githubusercontent.com/76992645/105129761-ca326400-5b0b-11eb-8898-f02c085246ef.png)

**Additional context**

**Comment by likamrat** [comment]
Just making sure here. Can you please if by any chance you have the SQL resource deployed in a different resource group?

**Comment by aseemamitesh** [comment]
No I can see only the 2 resources as shown in the snap. I also checked Azure Arc SQL Servers but found no resources.

**Comment by likamrat** [comment]
Can you please share the input of `az provider show -n Microsoft.AzureArcData -o table`? 

If not installed:
1. Run `az provider register --namespace Microsoft.AzureArcData`
2. Delete the environment using the `terraform destroy` command
3. Redeploy

Azure Arc enabled SQL server introduced a new requirement around this so I will also update the guide accordenly.
