### ISSUE TITLE
use helm newest version can't access a repo

### ISSUE THREAD

**Issue by azurepeterli** [microsoft/azure_arc#367]
**Scenario which you are working on**
A link to the Jumpstart scenario you are working on.

I was trying to create a custom location to onboard a k8s cluster.

**Describe the bug**

It's an issue with the helm version. I install helm 3.5.0 (with the binary), and try to access this repo, and got an error

helm repo add azurearcfork8sdev https://azurearcfork8sdev.azurecr.io/helm/v1/repo
Error: looks like "https://azurearcfork8sdev.azurecr.io/helm/v1/repo" is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: unknown field "acrMetadata"

helm version
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}

The problem is similar to this issue,
https://github.com/helm/helm/issues/8761#issuecomment-695099518

After I downgrade helm to 3.2.4 (replace the binary file), it worked.
helm repo add azurearcfork8sdev https://azurearcfork8sdev.azurecr.io/helm/v1/repo
"azurearcfork8sdev" has been added to your repositories

In the website, we mentioned helm 3. Perhaps more specific version it should be for example 3.2.4 because latest 3.5.0 will have this issue

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by likamrat** [comment]
@azurepeterli I am not following. Which scenario you are working against?

**Comment by azurepeterli** [comment]
Hi thanks for getting back to me. I can't find the exact web page which mentioned "Helm 3" somehow.

I was creating a K8s connected cluster and I need install helm for k8s package management according to the document.
But it didn't specify the exact version (or only helm 3), so I install helm with newest version 3.5.0, but it would run into an issue when trying to access this repo.

helm repo add azurearcfork8sdev https://azurearcfork8sdev.azurecr.io/helm/v1/repo
Error: looks like "https://azurearcfork8sdev.azurecr.io/helm/v1/repo" is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: unknown field "acrMetadata"

After I downgrade helm from 3.5.0 to 3.2.4 (simply replace the binary file), I could access that repo.

This problem was with helm 3.5.0, and there was a similar issue reported here,
https://github.com/helm/helm/issues/8761

I suggest in our document, if we mentioned "helm" or "helm 3", we add a note that latest Helm 3.5.0 may be problematic when accessing some repos, if this happens,  try downgrade helm to an older version such as 3.2.4 (simply replace the binary file)

**Comment by likamrat** [comment]
My question is in what scenario you are trying to run since none of the k8s scenarios are using these helm repo. Can you please clarify? Do you have an issue with helm 3.5 and a scenario? 

This does not look like an Azure Arc Jumpstart issue and it looks you are trying something that is not supported.

**Comment by azurepeterli** [comment]
I was trying to create a k8s connected cluster using AKS, and onboard it through Arc.

Here is the document mentioned helm v3,
https://docs.microsoft.com/en-us/azure/aks/quickstart-helm

You're right looks like it's an AKS document, not Arc Jumpstart issue. 

I'll close the issue, thanks!
