### ISSUE TITLE
Enabling Update Management for Azure Arc servers

### ISSUE THREAD

**Issue by giovannifl** [microsoft/azure_arc#372]
I'm trying to manage Non Azure Servers ( running in AWS or Digital Ocean) using Azure ARC Server and Update Management. They've been successfully imported into Azure using Azure ARC Server and after deploying Log Analytic agent they appear into Update Management dashboard but they're showed as green and missing updates are not showed. Any suggestion ?

**Comment by dkirby-ms** [comment]
What server OS are you using? Can you share screenshots of your update management dashboard and server?

Also note that update management can take time to process before updates are reflected in the dashboard.

**Comment by giovannifl** [comment]
Hi @dkirby-ms , after some digging, it has been identifued that python2 has not been installed on the Linux server which is a requirement to enable  Update Management

**Comment by dkirby-ms** [comment]
We will update the scenario to note that servers used in this scenario must meet system requirements for Update Management (such as Python 2.x). 

Thanks for submitting the issue.
