### ISSUE TITLE
Demo - Integrating Azure Monitor with a Azure Arc enabled GKE Cluster

### ISSUE THREAD

**Issue by sowsan** [microsoft/azure_arc#380]
**Demo abstraction:**
In this demo, we will show how to enable Azure Monitor for containers on a Google Kubernetes Engine (GKE) cluster onboarded as an Azure Arc enabled Kubernetes cluster.

**Comment by likamrat** [comment]
Suggested abstract:
In this demo, we will show how to enable Azure Monitor for containers on a Google Kubernetes Engine (GKE) cluster onboarded as an Azure Arc enabled Kubernetes cluster.
