### ISSUE TITLE
Monitoring Agent Extension -  ARM parameter file should reference deploymentParameters.json schema

### ISSUE THREAD

**Issue by bfrankMS** [microsoft/azure_arc#390]
**Scenario which you are working on**
Jumpstart Scenarios -> Azure Arc enabled servers -> Unified Operations Use Cases ->Monitoring Agent Extension
(https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_servers/day2/arc_vm_extension_mma_arm/#deploy-monitoring-agent-extension-on-azure-arc-linux-and-windows-servers-using-extension-management)

**Describe the bug**
The file:
azure_arc_servers_jumpstart\extensions\arm\log_analytics-template.parameters.json
is a parameter file. However it references a deploymentTemplate:
   "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
it should reference the parameter schema:
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
...

**To Reproduce**
1. Go to azure_arc_servers_jumpstart\extensions\arm\log_analytics-template.parameters.json
2. Look at line 2. :     "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
3. VS Code delivers error: "Template validation failed: The template resource '' at line '28' and column '36' is not valid. The name property cannot be null or empty. Please see https://aka.ms/arm-template/#resources for usage details."

**Expected behavior**
Should be     "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",

Screenshot
![image](https://user-images.githubusercontent.com/41586338/107011077-73798b00-6797-11eb-9693-956a395dbb1f.png)

**Comment by dkirby-ms** [comment]
Thanks for submitting. We will fix.
