### ISSUE TITLE
Jumpstart scenario for Container Service for Kubernetes in Alibaba Cloud

### ISSUE THREAD

**Issue by sowsan** [microsoft/azure_arc#394]
New Jumpstart Scenario: Azure Arc Integration with Alibaba Kubernetes Service

**Describe the solution you'd like**
A jumpstart scenario to integrate basic Azure Arc integration for managing the Kubernetes Managed cluster in Alibaba cloud
https://www.alibabacloud.com/product/kubernetes

**Comment by KaiWalter** [comment]
@sowsan @likamrat @denniszielke - I am currently in evaluation of bringing Alibaba Cloud managed Kubernetes into Azure Arc : https://github.com/KaiWalter/AzureArc-Alibaba-K8S

I would happy to participate & share.

**Comment by lkamrat** [comment]
@KaiWalter that's great, we would love for you to contribute and create a Jumpstart scenario for it. Please take a look at our write-up guidelines and let me know if you are ready to commit.

https://azurearcjumpstart.io/scenario_guidelines/

**Comment by KaiWalter** [comment]
@lkamrat I still have some issue with my setup - should I raise those here are rather in separate linked issues?

**Comment by likamrat** [comment]
@KaiWalter Are these issues with a published Jumpstart scenario? If so, open another issue. 
This issue is for the maintainers to track a new scenario buildout.
