### ISSUE TITLE
Demo - Deploy Open Service Mesh with Azure Arc enabled K8S cluster : AKS - GKE - EKS

### ISSUE THREAD

**Issue by ezYakaEagle442** [microsoft/azure_arc#395]
**Is your feature request related to a problem? Please describe.**
Demo - Deploy Open Service Mesh with Azure Arc enabled K8S cluster : AKS - GKE - EKS

@likamrat

**Comment by likamrat** [comment]
@ezYakaEagle442 since OSM with Azure Arc is currently in private preview, we cannot add this scenario. Once OSM with Arc will be in the public preview phase we will publish this scenario.

**Comment by likamrat** [comment]
https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/day2/cluster_api/cluster_api_osm_extension/
