### ISSUE TITLE
Not able to register the resource provider kubernetesconfiguration in my subscription

### ISSUE THREAD

**Issue by nitinkansal1984** [microsoft/azure_arc#403]
**Scenario which you are working on**
A link to the Jumpstart scenario you are working on.

**Describe the bug**

**To Reproduce**
I run command to register the resource provider but it keeps on waiting and showing state as registering.

> Get-AzResourceProvider -ProviderNamespace Microsoft.KubernetesConfiguration

ProviderNamespace : Microsoft.KubernetesConfiguration
RegistrationState : Registering
ResourceTypes     : {sourceControlConfigurations}
Locations         : {East US, West Europe, West Central US, West US 2…}

ProviderNamespace : Microsoft.KubernetesConfiguration
RegistrationState : Registering
ResourceTypes     : {operations}
Locations         : {}

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by likamrat** [comment]
Thank you @nitinkansal1984 

This is not really a Jumpstart scenario issue. Can you please validate you have sufficient permission on your subscription to register a provider as described [here](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-providers-and-types#register-resource-provider)? 

If the problem still persists, please open an Azure support ticket.
