### ISSUE TITLE
Existing Windows server - permissions on the resource group?

### ISSUE THREAD

**Issue by andrePKI** [microsoft/azure_arc#404]
What permissions are required? It is just stated "Create a new Azure resource group where you want your machine(s) to show up." In my enterprise, I don't create my own RGs. So somebody else does it for me. What permissions do I need on the RG?
Also, what about the **Azure Connected Machine Resource Administrator role** or the **Azure Connected Machine Onboarding role**

**Scenario which you are working on**
[Existing Windows server](https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_servers/general/onboard_server_win/#connect-an-existing-windows-server-to-azure-arc)

**Describe the bug**
Documentation is too brief

**Comment by lanicolas** [comment]
You can use a pre-existing RG for this automation, you would only need to include it as part of the environment variables. The permissions required to onboard machines, you are a member of the Azure Connected Machine Onboarding role, you can find additional details here: https://docs.microsoft.com/en-us/azure/azure-arc/servers/agent-overview#required-permissions

**Comment by andrePKI** [comment]
Thank you, but IMHO the information is not complete. I run into issues like "The client 'ad0xxxxx@[redacted].com' with object id '[redacted]' does not have authorization to perform action 'Microsoft.PolicyInsights/policyStates/summarize/read' over scope '/subscriptions/17[redacted]1f/resourceGroups/[redacted]/providers/Microsoft.HybridCompute/machines/[redacted]/providers/Microsoft.PolicyInsights/policyStates/latest' or the scope is invalid. If access was recently granted, please refresh your credentials." If what you refer to is complete (I knew of that article of course), I will file a support case and if anything interesting, I will post it here.

**Comment by lanicolas** [comment]
I was not able to reproduce this issue in my environment, I was able to onboard a server with only the Azure Connected Machine Onboarding role at the RG level. Please if you file a support case let us know the findings.

**Comment by andrePKI** [comment]
Well, onboarding is not the issue. That works. But then, when going into the Arc-Servers blade and using things like Insights etc access denied messages appear.

**Comment by lanicolas** [comment]
Hi, the scenario is focused on onboarding and for that specific use case you will need the Azure Connect Machine Onboarding role. Since I cannot reproduce your issue or setup please I suggest you open a support case so the team can identified the minimum roles you need.

**Comment by andrePKI** [comment]
After opening a support ticket and working with a Micrsoft engineer I now know that one needs owner or contributor rights to the subscription (not just log analytics workspaces) because at least two resource providers need to be registered ('Microsoft.WorkloadMonitor and Microsoft.ChangeAnalysis). 
Next to that we added Monitor contributor role to two resource groups (one holding the VM object and the other the Log analytics workspace), but I don't know if that is really required. 

I received the pointer to the documents from the engineer. I could not find these at first, as I was searching for Arc related documentation.

_For the VM insights specifically we have the following documentation where it mentions the requirements and we try to have explicit error for each scenario:_
[Required resource providers](https://docs.microsoft.com/en-us/azure/azure-monitor/vm/vminsights-health-enable?tabs=powershell#register-required-azure-resource-providers)

_For Change Analysis enablement we have this documentation where it mentions which RP we need to register to benefit of this product:_
[ChangeAnalysis](https://docs.microsoft.com/en-us/azure/azure-monitor/vm/vminsights-change-analysis#enabling-change-analysis
)

**Comment by likamrat** [comment]
Thank you @andrePKI. This is actually documented in the Jumpstart scenario as but thx for the update!

![SNAG-0674](https://user-images.githubusercontent.com/46730876/112548612-b8727480-8d79-11eb-958d-0760faf890e4.jpg)

**Comment by andrePKI** [comment]
well, @likamrat, I believe that's for onboarding into Arc. I had no problems with that. But after I had onboarded an on prem server, I ran into issues with a.o. Insights.
For that one needs the extras I describe.
Up to now I did not need a service principal, as I onboarded 1 server manually using my personal account.
