### ISSUE TITLE
SECURITY vulnerability in Azure ARM/Linux

### ISSUE THREAD

**Issue by ezYakaEagle442** [microsoft/azure_arc#409]
**Scenario which you are working on**
A link to the Jumpstart scenario you are working on: [https://github.com/microsoft/azure_arc/blob/main/azure_arc_servers_jumpstart/azure/linux/arm_template/azuredeploy.parameters.example.json](https://github.com/microsoft/azure_arc/blob/main/azure_arc_servers_jumpstart/azure/linux/arm_template/azuredeploy.parameters.example.json)

**Describe the bug**
This Arc for server on Azure Linux VM results in having password to authenticate to the VM :

```sh
cat /etc/ssh/sshd_config
```

```console
# To disable tunneled clear text passwords, change to no here!
PasswordAuthentication yes
#PermitEmptyPasswords no
```

**Expected behavior**
The ARM Template should use SSH Keys

"osProfile": {
                    "computerName": "[parameters('virtualMachines_vm_azarc_xxxxxx')]",
                    "adminUsername": "azarc-admin",
                    "linuxConfiguration": {
                        "disablePasswordAuthentication": **true**,
                        "**ssh**": {
                            "**publicKeys**": [
                                {
                                    "path": "/home/azarc-admin/.ssh/authorized_keys",
                                    "keyData": "ssh-rsa xxxxxxxxxxxx"
                                }
                            ]
                        },
                        "provisionVMAgent": true
                    },
                    "secrets": [],
                    "allowExtensionOperations": true,
                    "requireGuestProvisionSignal": true
                },

And /etc/ssh/sshd_config content should be :

PasswordAuthentication **no**
#PermitEmptyPasswords no

**Additional context**
This is not compliant with MSIT policies and triggers MS Digital Security and Risk Engineering scanning alert

@likamrat

**Comment by likamrat** [comment]
Thank you @ezYakaEagle442. As stated on the project homepage, our 1st priority is ease of use. The scenarios in the Jumpstart are designed to be used in a rapid, non-complex fashion. 

![image](https://user-images.githubusercontent.com/46730876/109169287-7f23f600-7734-11eb-92aa-72d3f05bb888.png)

If you'd like, we would love for you to submit a PR that addresses this issue as well updating the guide. I will go ahead and close this for now.
