### ISSUE TITLE
Support for onboarding Log Analytics agent (MMA extension) for Linux VMs projected in Azure

### ISSUE THREAD

**Issue by youf05** [microsoft/azure_arc#42]
### Description
Support for onboarding Log Analytics agent (MMA extension) for Linux VMs projected in Azure from AWS/GCP 

### Implementation Requirements
- Onboard Linux VMs with Log analytics agent using az cli
- Detailed README
- Clear screenshots
- Reference in the main README

**Comment by likamrat** [comment]
Closing #71
