### ISSUE TITLE
Controlling Access to the Remote Cluster's Kubernetes API

### ISSUE THREAD

**Issue by alihhussain** [microsoft/azure_arc#43]
**Is your feature request related to a problem? Please describe.**
Users access the API using kubectl, client libraries, or by making REST requests. Both human users and Kubernetes service accounts can be authorized for API access. How do I restrict/manage that once the K8s cluster is a registered Arc cluster.

**A clear and concise description of what you want to happen.**
Documentation to illustrate how this can be enabled and a demo scenario that showcases this happening.

**Describe alternatives you've considered**
Can this be done via an AAD integrated cluster? If so then that can be an alternative if the K8s identities are managed by AAD and the enforcing agent against K8s API is Azure RBAC policy on AAD identities. 

**Implementation Requirements**
Template/script that sets up remote Arc for K8s cluster to adhere to this requirement.
Sample App to illustrate RBAC enforcing functionality.
Template/script to deploy sample app and its configuration.

**Additional context**

![image](https://user-images.githubusercontent.com/13628297/84310084-f0276d00-ab15-11ea-90dd-87148485638d.png)

**Comment by likamrat** [comment]
Archiving for now
