### ISSUE TITLE
PostgreSQL Hyperscale ARM Template

### ISSUE THREAD

**Issue by AlexanderTodorovic** [microsoft/azure_arc#435]
**Scenario which you are working on**
[Deploy an Azure PostgreSQL Hyperscale on AKS using an ARM Template](https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_data/aks/aks_postgresql_hyperscale_arm_template/#re-deploy-azure-arc-data-controller--postgres)

**Describe the bug**
I've successfully run all scripts to Deploy an Azure PostgreSQL Hyperscale on AKS using an ARM Template. However the Azure Arc Data Controller is not visible in the Azure Portal in the new resource group as shown in the Jumpstart scenario.

**To Reproduce**
1. Follow all steps in [Deploy an Azure PostgreSQL Hyperscale on AKS using an ARM Template](https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_data/aks/aks_postgresql_hyperscale_arm_template/#re-deploy-azure-arc-data-controller--postgres)

**Expected behavior**
I've expected the Azure Arc data controller is visible in the portal under the new resource group as shown in the Jumpstart scenario.

**Screenshots**
Please see attached screenshots. 
![AzureArcJumpstartDoc](https://user-images.githubusercontent.com/7408389/110654140-36267400-8201-11eb-834d-4283e157db1c.jpg)
![AzureArcJumpstartmydeployment](https://user-images.githubusercontent.com/7408389/110654149-3757a100-8201-11eb-991b-35cd1651abed.jpg)

**Additional context**

**Comment by likamrat** [comment]
Thx @AlexanderTodorovic we are aware. Look at the comment I add in the PR
