### ISSUE TITLE
SQL MI AKS ARM Template

### ISSUE THREAD

**Issue by smitzlroy** [microsoft/azure_arc#437]
**Scenario which you are working on**
https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_data/aks/aks_mssql_mi_arm_template/

**Describe the bug**
I've successfully run all scripts to Deploy an Azure SQL MI on AKS using an ARM Template. However the Azure Arc Data Controller is not visible in the Azure Portal in the new resource group as shown in the Jumpstart scenario.

**To Reproduce**
Follow steps on https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_data/aks/aks_mssql_mi_arm_template/

**Expected behavior**
For the Arc Data controller to be visible as an Azure resource and for ADS on the Azure MGMT VM to have the correct connection settings to the MS and the Arc Data Controller added.

**Screenshots**
![image](https://user-images.githubusercontent.com/11997825/110807120-a02f2f80-827a-11eb-9dd8-631503bfe732.png)

![image](https://user-images.githubusercontent.com/11997825/110807409-ebe1d900-827a-11eb-9305-d01f98ee02f6.png)

**Additional context**

**Comment by likamrat** [comment]
@smitzlroy can you please test new version?

**Comment by smitzlroy** [comment]
Updates have made a difference. I am now able to connect to the SQL MI and see the DB (AdventureWorks2019) - all good there. However still not able to connect to the Arc Controller in ADS and the Controller not visible in the Azure Resource Group or listed in the Arc > Data Controllers blade. Potentially this is expected behavior right now at preview?

![image](https://user-images.githubusercontent.com/11997825/111668232-74c5bb00-880d-11eb-8613-c80dbeed7b83.png)

**Comment by likamrat** [comment]
@smitzlroy Yes, this due to version rollout. This functionality will be restored in the next itteration.
