### ISSUE TITLE
PostgreSQL Hyperscale ARM Template - adventureworks demo

### ISSUE THREAD

**Issue by AlexanderTodorovic** [microsoft/azure_arc#449]
**Scenario which you are working on**
[Deploy an Azure PostgreSQL Hyperscale on AKS using an ARM Template](https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_data/aks/aks_postgresql_hyperscale_arm_template/)

**Describe the bug**
The online documentation shows an screenshot with adventureworks installed, but after I've ran the installation scripts there is no adventureworks sample database.

**To Reproduce**
1. Follow all steps in [Deploy an Azure PostgreSQL Hyperscale on AKS using an ARM Template](https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_data/aks/aks_postgresql_hyperscale_arm_template/)

**Expected behavior**
An installed sample database. Any sample DB would be fine e.g. like DVD rental database.

**Screenshots**
Online documentation
![onlinedoc_adventureworks](https://user-images.githubusercontent.com/7408389/111025699-3bfe9e00-8429-11eb-8625-278c1bb00d02.jpg)
After deployment
![no_adventureworks](https://user-images.githubusercontent.com/7408389/111025753-8b44ce80-8429-11eb-9f0e-dff9cd246122.jpg)

**Additional context**
Would be great if any sample database would be installed after deployment.

**Comment by likamrat** [comment]
@AlexanderTodorovic I am not able to repro but we are seeing some weird behavior with _kubectl exec_. 

![SNAG-0593](https://user-images.githubusercontent.com/46730876/111033044-2f942a00-83c4-11eb-82d6-e9967d1f0fce.jpg)

Did the PowerShell scripts sessions close automatically for you followed by Azure Data Studio opening up?

**Comment by AlexanderTodorovic** [comment]
@likamrat 
1. I ran `git clone https://github.com/microsoft/azure_arc.git` again.
2. Then `az deployment group create --resource-group rgazurearcalexnew --name arcdatapostgresdemo --template-uri https://raw.githubusercontent.com/microsoft/azure_arc/main/azure_arc_data_jumpstart/aks/arm_template/postgres_hs/azuredeploy.json --parameters azuredeploy.parameters.json`
Yes it closed automatically and opened automatically Azure Data Studio.
4. Now adventureworks is there.
Thank you!
