### ISSUE TITLE
PostgreSQL Hyperscale ARM Template -  no data tables in Adventureworks

### ISSUE THREAD

**Issue by AlexanderTodorovic** [microsoft/azure_arc#451]
**Scenario which you are working on**
[Deploy an Azure PostgreSQL Hyperscale on AKS using an ARM Template](https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_data/aks/aks_postgresql_hyperscale_arm_template/)

**Describe the bug**
Adventureworks sample database is deployed. However no data tables are in. There are only meta data tables respectively system tables. There should be tables like Customer, Product, SalesOrderDetail etc.

**To Reproduce**
1. Run all steps in [Deploy an Azure PostgreSQL Hyperscale on AKS using an ARM Template](https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_data/aks/aks_postgresql_hyperscale_arm_template/)

**Expected behavior**
Adventureworks data tables should be in the database. e.g. `select distinct table_name from information_schema.columns order by 1` does not return tables of the Adventureworks database.

**Screenshots**
![adventureworks_onlymetadata](https://user-images.githubusercontent.com/7408389/111070200-d1765c80-8513-11eb-9d5f-0cee9f0e3e8f.jpg)

**Additional context**
-

**Comment by AlexanderTodorovic** [comment]
With the latest repo update git clone `https://github.com/microsoft/azure_arc.git` the issue was fixed. Thank you!

![awt](https://user-images.githubusercontent.com/7408389/111401414-9ab76680-870c-11eb-91c9-8767c92d401f.jpg)

**Comment by likamrat** [comment]
Thx for the update @AlexanderTodorovic! 
We are currently working on some optimizations for the data services scenarios as well as adding some features to align with the services rollouts.
