### ISSUE TITLE
GKE cluster Terraform plan - az_connect_gke.sh link

### ISSUE THREAD

**Issue by frteles** [microsoft/azure_arc#455]
**Scenario which you are working on**

https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/gke/gke_terraform/

**Describe the bug**

URL to  az_connect_gke.sh file is not correct

**To Reproduce**
Just click in the hyperlink and you'll be forwarded to a URL that doesn't exist: https://github.com/microsoft/azure_arc/blob/main/azure_arc_k8s_jumpstart/gke/dc_vanilla/terraform/scripts/az_connect_gke.sh

**Expected behavior**
We should be forwarded to the following path: https://github.com/microsoft/azure_arc/blob/main/azure_arc_k8s_jumpstart/gke/terraform/scripts/az_connect_gke.sh

**Screenshots**

**Additional context**

**Comment by likamrat** [comment]
Thank you. Fixed
