### ISSUE TITLE
Create cluster with arc_capi_azure.sh hangs when vm SKU of control plane and node are not the same

### ISSUE THREAD

**Issue by patrick138** [microsoft/azure_arc#480]
**Scenario which you are working on**
A link to the Jumpstart scenario you are working on.
https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/cluster_api/capi_azure/

**Describe the bug**

**To Reproduce**
1 Edit arc_cap_azure_sh and add 
AZURE_CONTROL_PLANE_MACHINE_TYPE="Standard_D2_v3"
AZURE_NODE_MACHINE_TYPE="Standard_D4s_v3"
Roll out the cluster. This will hang for ever. Changing the control plane to
AZURE_CONTROL_PLANE_MACHINE_TYPE="Standard_D4s_v3
will resolve it.

**Expected behavior**
You should be able to deploy a cluster where the control plane is a different VM sku than the  nodes.

**Screenshots**
N/A

**Additional context**

**Comment by craiglpeters** [comment]
@devigned can you take a look at this?

**Comment by devigned** [comment]
There isn't anything that ties the SKU for control planes to worker nodes. I'm first inclined to think that the issue is a lack of SKU available to you in a given region which causes the control plane deployment not to complete.

I'd be able to say definitively if you can provide the log from the CAPZ provider. [These docs](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/docs/troubleshooting.md#looking-at-controller-logs) will help you gather those logs.

**Comment by likamrat** [comment]
Hi @patrick138 I wasn't able to repro. As @devigned suggested, do you mind check VM type region availability?

![SNAG-0757](https://user-images.githubusercontent.com/46730876/113525550-6942f580-956a-11eb-97ea-01cd7970e2b2.jpg)
![SNAG-0758](https://user-images.githubusercontent.com/46730876/113525556-6cd67c80-956a-11eb-9b80-0af929f6c595.jpg)
![SNAG-0759](https://user-images.githubusercontent.com/46730876/113525558-6f38d680-956a-11eb-8aba-56a40093e1b5.jpg)

**Comment by patrick138** [comment]
Hi,

Thanks so much, I didn't know how to get the logs, but this really helps. The log is pretty clear:

failed to create virtual machine: failed to create VM arc-patmand2-control-plane-lb7nh in resource group arc-patmand2: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code=\"InvalidParameter\" Message=\"Requested operation cannot be performed because the VM size Standard_D2_v3 does not support the storage account type Premium_LRS of disk 'arc-patmand2-control-plane-lb7nh_OSDisk'. Consider updating the VM to a size that supports Premium storage.\" Target=\"osDisk.managedDisk.storageAccountType\"" "controller"="azuremachine" "name"="arc-patmand2-control-plane-lb7nh" "namespace"="default"

**Comment by likamrat** [comment]
@patrick138 thx for the update, I added some clarifications.
