### ISSUE TITLE
Data Client VM ARM template has inbound ports open for MSSQL and PostGres

### ISSUE THREAD

**Issue by mdrakiburrahman** [microsoft/azure_arc#497]
I noticed that the Data Client VM's has **Inbound** ports open in the ARM template for SQL (`1433`) and PostGres (`5432`):
![image](https://user-images.githubusercontent.com/46581776/114312760-c9352100-9ac1-11eb-9a96-c454ae430b05.png)

Which results in the following Inbound rules on the NSG:
![image](https://user-images.githubusercontent.com/46581776/114312867-32b52f80-9ac2-11eb-8845-530bb8abb386.png)

Curious why this is in there - since it's just a jumpbox for the deployment and we're not establishing inbound connectivity to AKS Data Pods through here. 

Also since Outbound `AllowInternetOutBound` is already enabled, doesn't seem like this would be required regardless?

**Comment by likamrat** [comment]
Thank you @mdrakiburrahman, These are in fact leftovers from the testing when the scenario was created. I will make a PR for it.
