### ISSUE TITLE
Data Studio generates buggy syntax for Postgres materialized view querying

### ISSUE THREAD

**Issue by mdrakiburrahman** [microsoft/azure_arc#498]
This may not be related to Arc, but I noticed that when you attempt to query the Materialized View created as part of the Postgresql Adventureworks restore, the TSQL syntax generated is buggy, and doesn't let you query the view:

![syntax-1](https://user-images.githubusercontent.com/46581776/114315507-45813180-9acd-11eb-80a7-32c38a2b33a8.gif)

This is the syntax it creates (no space before `from`):
```sql
select  stateprovinceid
,stateprovincecode
,isonlystateprovinceflag
,stateprovincename
,territoryid
,countryregioncode
,countryregionnamefrom person.vstateprovincecountryregion # There should be a space before "from"
LIMIT 1000
```
Trying to run the query by manually adding the space also hangs:
![syntax-2](https://user-images.githubusercontent.com/46581776/114315516-50d45d00-9acd-11eb-9b88-44ee034eb1bb.gif)

Shutting down Data Studio and, running the above query from scratch, with space before the `from` in New query Window works fine:
![syntax-3](https://user-images.githubusercontent.com/46581776/114315587-9e50ca00-9acd-11eb-930e-ff8f5ed5b931.gif)

**Comment by likamrat** [comment]
Thank you @mdrakiburrahman. @twright-msft any thoughts?

**Comment by bergeron** [comment]
I think this is best tracked in the repository for the ADS Postgres extension.  I filed a bug there.  https://github.com/microsoft/azuredatastudio-postgresql/issues/270

**Comment by likamrat** [comment]
Thank you @bergeron. @mdrakiburrahman I will go ahead and close this issue for now.
