### ISSUE TITLE
wrong uri

### ISSUE THREAD

**Issue by AwdotiaRomanowna** [microsoft/azure_arc#511]
**Scenario which you are working on**
https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_data/aks/aks_postgresql_hyperscale_arm_template/

**Describe the bug**
wrong uri -  additional string is added: postgres_hs/azuredeploy.json
so the uri fails

az group create --name <Name of the Azure resource group> --location <Azure Region>
az deployment group create \
--resource-group <Name of the Azure resource group> \
--name <The name of this deployment> \
--template-uri https://raw.githubusercontent.com/microsoft/azure_arc/main/azure_arc_data_jumpstart/aks/arm_template/postgres_hs/azuredeploy.json**postgres_hs/azuredeploy.json** \
--parameters <The *azuredeploy.parameters.json* parameters file location>

**Comment by likamrat** [comment]
Thank you @AwdotiaRomanowna but I am not following. What and where do you see an additional string being added? are you referring to the asterix? that looks like an issue with your copy or something. 

As you can see from the scenario, there are no strings added.

![image](https://user-images.githubusercontent.com/46730876/115405131-d2e61500-a1a2-11eb-8fd2-124ee38f7134.png)

**Comment by AwdotiaRomanowna** [comment]
please take a look at this screenshot:

![image](https://user-images.githubusercontent.com/17368813/115408087-e029f080-a1f0-11eb-8935-286d7cb0f884.png)

the first link is wrong: https://raw.githubusercontent.com/microsoft/azure_arc/main/azure_arc_data_jumpstart/aks/arm_template/postgres_hs/azuredeploy.jsonpostgres_hs/azuredeploy.json

the "postgres_hs/azuredeploy.json" should be removed from the end

**Comment by likamrat** [comment]
Ha ok, good catch. Let me fix it...
