### ISSUE TITLE
adding psql to client vm

### ISSUE THREAD

**Issue by AwdotiaRomanowna** [microsoft/azure_arc#519]
scenario: https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_data/aks/aks_postgresql_hyperscale_arm_template/

would it be possible to add psql client on client vm? this is a very basic tool commonly used for postgres.
it is nice to have azure data studio but psql would be really appreciated.
the installer from EDB has got the quiet mode to be used in the automated installations

**Comment by likamrat** [comment]
Yes. We will include this in our May Jumpstart release. /cc @dkirby-ms
