### ISSUE TITLE
Arc DataService on GCP-GKE - no successful deployment - free account is not enough

### ISSUE THREAD

**Issue by sql-aus-hh** [microsoft/azure_arc#520]
**Scenario which you are working on**
Deploy an Azure Arc Data Controller (Vanilla) on GKE using Terraform

**Describe the bug**
Documentation is fine and everything is running smoothly, but during deployment, I got the message that it is not possible to deploy a Windows virtual machine with a Google free account.
K8s cluster is up and running, but there is no virtual Windows machine

google_container_node_pool.primary_preemptible_nodes: Creation complete after 2m14s [id=projects/azure-arc-demo-311319/locations/us-west1/clusters/arc-data-gke/nodePools/arcdemo-node-pool]

Error: Error creating instance: googleapi: Error 400: Windows VM instances are not included with the free trial. To use them, first enable billing on your account. You'll still be able to apply your free trial credits to eligible products and services., windowsVmNotAllowedInFreeTrialProject

  on client_vm.tf line 23, in resource "google_compute_instance" "default":
  23: resource "google_compute_instance" "default" {

**Screenshots**
![0145](https://user-images.githubusercontent.com/20439825/115506697-74409a00-a27b-11eb-87ee-b4c6528c742c.png)

**Comment by dkirby-ms** [comment]
Hi @sql-aus-hh,

We do mention in the readme prerequisites that you will need to enable billing on your GCP account for Windows scenarios. https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_servers/gcp/gcp_terraform_windows/#prerequisites

I will add another highlighted note to call this out.

Thank you,
Dale

**Comment by sql-aus-hh** [comment]
Hi Dale,

then this was something that I read over because my eyes just catched that link to “Create your free account”.

It should be more highlighted that you need a GCP-Payg account in order to deploy that windows machine.

Best regards
Bjoern

Von: Dale Kirby ***@***.***>
Gesendet: Montag, 26. April 2021 17:53
An: microsoft/azure_arc ***@***.***>
Cc: SQL_aus_HH ***@***.***>; Mention ***@***.***>
Betreff: Re: [microsoft/azure_arc] Arc DataService on GCP-GKE - no successful deployment - free account is not enough (#520)


Hi @sql-aus-hh<https://github.com/sql-aus-hh>,

We do mention in the readme prerequisites that you will need to enable billing on your GCP account for Windows scenarios. https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_servers/gcp/gcp_terraform_windows/#prerequisites

I will add another highlighted note to call this out.

Thank you,
Dale

**Comment by sql-aus-hh** [comment]
Hi Dale,

then this was something that I read over because my eyes just caught that link to “Create your free account”.

It should be more highlighted that you need a GCP-Payg account in order to deploy that windows machine.

Best regards
Bjoern

Von: Dale Kirby ***@***.***>
Gesendet: Montag, 26. April 2021 17:53
An: microsoft/azure_arc ***@***.***>
Cc: SQL_aus_HH ***@***.***>; Mention ***@***.***>
Betreff: Re: [microsoft/azure_arc] Arc DataService on GCP-GKE - no successful deployment - free account is not enough (#520)


Hi @sql-aus-hh<https://github.com/sql-aus-hh>,

We do mention in the readme prerequisites that you will need to enable billing on your GCP account for Windows scenarios. https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_servers/gcp/gcp_terraform_windows/#prerequisites

I will add another highlighted note to call this out.

Thank you,
Dale
