### ISSUE TITLE
EKS cluster Terraform plan

### ISSUE THREAD

**Issue by VictorPareja-Microsoft** [microsoft/azure_arc#521]
**Scenario which you are working on**
https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/eks/eks_terraform/

**Describe the bug**
When executing the Terraform plan I get a warning and an error related to deprecated constraints and a deprecated function (see below)

**To Reproduce**

**Expected behavior**

**Screenshots**
 Warning: Version constraints inside provider configuration blocks are deprecated
│ 
│   on providers.tf line 7, in provider "aws":
│    7:   version    = "~> 2.38.0"
│ 
│ Terraform 0.13 and earlier allowed provider version constraints inside the provider configuration block, but that is
│ now deprecated and will be removed in a future version of Terraform. To silence this warning, move the provider
│ version constraint into the required_providers block.
╵
╷
│ Error: Error in function call
│ 
│   on vpc.tf line 12, in resource "aws_vpc" "arcdemo":
│   12:   tags = map(
│   13:     "Name", "terraform-eks-arcdemo-node",
│   14:     "kubernetes.io/cluster/${var.cluster-name}", "shared",
│   15:   )
│     ├────────────────
│     │ var.cluster-name is a string, known only after apply
│ 
│ Call to function "map" failed: the "map" function was deprecated in Terraform v0.12 and is no longer available; use
│ tomap({ ... }) syntax to write a literal map.

**Additional context**

**Comment by dkirby-ms** [comment]
This is a bug introduced with Terraform v.15. We will update the calls to map() to use the new tomap() function.
