### ISSUE TITLE
Arc-enabled AKSengine cluster

### ISSUE THREAD

**Issue by erjosito** [microsoft/azure_arc#532]
**Is your feature request related to a new Jumpstart scenario you would like to contribute?**
Yes

**Is your feature request related to a problem? Please describe.**
No existing scenario covering AKS engine

**Describe the solution you'd like**
Arc-enabled aks-engine cluster with monitor/defender/policy instructions using Azure CLI

**Describe alternatives you've considered**
New cluster with kube-admin, but IMHO aksengine is easier for Azure admins

**Additional context**

**Comment by likamrat** [comment]
Closing due to lack of response
