### ISSUE TITLE
ARM templates - MMA for Servers

### ISSUE THREAD

**Issue by lanicolas** [microsoft/azure_arc#54]
**Is your feature request related to a problem? Please describe.**
Onboard Azure Arc enabled VMs on Azure Services such as Monitoring, Sentinel, Security Center, etc as first class citizens in Azure. 

**Describe the solution you'd like**
Create documentation on how to use an ARM template to deploy the MMA to Azure Arc connected VMs. Automating the onboarding on non-Azure VMs both Linux and Windows.

**Describe alternatives you've considered**
ARM template to define the resource and Azure CLI for the deployment. 

**Additional context**
N/A

**Comment by likamrat** [comment]
Closed #58
