### ISSUE TITLE
User Assigned Managed Identity support for ARC connectedk8s clusters

### ISSUE THREAD

**Issue by SatyKrish** [microsoft/azure_arc#550]
As a user of ARC connectedK8s cluster I would like to use User Assigned Managed Identity (UAMI) for authenticating with Azure services.

We are using Pod Identity feature in our AKS clusters for assigning UAMI to the pods accessing Hashicorp Vault and  Azure services. We would like similar support for ARC connectedK8s clusters on-premise. This will ensure we have a standard integration approach for apps deployed to K8s on-prem and cloud.

[Use Azure Active Directory pod-managed identities in Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity)

**Comment by shashankbarsin** [comment]
@SatyKrish we have user assigned managed identity and support for AAD pod identity in our roadmap. Can you open an issue here on UserVoice - https://feedback.azure.com/forums/925690-azure-arc. If other folks upvote the same ask, it can help our team prioritize this ask
