### ISSUE TITLE
Deploy GitOps configurations and perform basic GitOps flow on AKS on Azure Stack HCI as an Azure Arc Connected Cluster

### ISSUE THREAD

**Issue by antoniachen** [microsoft/azure_arc#552]
**Scenario which you are working on**
A link to the Jumpstart scenario you are working on.
https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/day2/aks_stack_hci/aks_hci_gitops_basic/

**Describe the bug**
Hi All,
I completed the Azure Arc Kubernetes GitOps Configuration by running the powershell script, az_k8sconfig_aks_hci.ps1
However I cannot reach the application website at the external IP of the nginx-ingress-controller.
Instead I get a 404 Not Found.

I've reviewed the Kubernetes resources deployed by running the following kubectl commands. And everything seems to be fine, except for that the nginx ingree doesn't seem to reflect an address. However from a quick search this seems to be normal?

![image](https://user-images.githubusercontent.com/42491413/118589958-0af96b80-b7d4-11eb-879a-2dc7d530e253.png)
![image](https://user-images.githubusercontent.com/42491413/118589863-d2f22880-b7d3-11eb-9e37-0fc60b2e03af.png)

**To Reproduce**
I ran the az_k8sconfig_aks_hci.ps1

**Expected behavior**
Expect to see the Hello Arc application 

**Additional context**
I am running a AKS-HCI cluster on a VM. It is arc connected.
![image](https://user-images.githubusercontent.com/42491413/118590168-80fdd280-b7d4-11eb-874e-83444279fe11.png)

**Comment by lanicolas** [comment]
Hi @antoniachen we are updating the scenario to the newest version of AKS on HCI we will change this automation to match the new version sorry for the inconvenience
