### ISSUE TITLE
Azure Policies and Remediation

### ISSUE THREAD

**Issue by lanicolas** [microsoft/azure_arc#56]
**Is your feature request related to a problem? Please describe.**
Use Azure Policies to onboard Azure Arc enabled VMs on Azure Services such as Monitoring, Sentinel, Security Center, etc as first class citizens in Azure. 

**Describe the solution you'd like**
Create documentation on how to use an Azure Policy  to deploy the MMA to Azure Arc connected VMs. Automating the onboarding on non-Azure VMs both Linux and Windows.

**Describe alternatives you've considered**
Using Azure CLI to assign the policy and remmediation task. The policy will be an initiative "Enable Azure Monitor" 

**Additional context**
N/A

**Comment by likamrat** [comment]
Closed #57
