### ISSUE TITLE
SQL MI Server alias for connection contains wrong value - Azure Arc enabled data services - SQLMI Jumpstart

### ISSUE THREAD

**Issue by Haroon-1** [microsoft/azure_arc#561]
**Scenario which you are working on**
https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_data/aks/aks_mssql_mi_arm_template/

**Describe the bug**
Towards the last step of the 2nd script (MSSQL_MI_Deploy.ps1), the $sql variable at Line 32 refers to both the SQL Server Name and the Endpoint Address. So once the Azure Data Studio tries to connect to the SQL Server, it cannot reach it at "hostname XX.XX.XX.XX" address. Thus the $sql variable should have the value set to only the Endpoint IP address.

**To Reproduce**
1. Go to the jumpstart [here](https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_data/aks/aks_mssql_mi_arm_template/) and follow the steps all the way to the [Windows Login and Deployment](https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_data/aks/aks_mssql_mi_arm_template/#windows-login--post-deployment). Wait for the Windows VM scripts to complete.
2. Click on Connections in Azure Data Studio
3. You'll find that the connection could not be established.
4. See error (notice the hostname has both the hostname and the ip address listed, whilst only 1 is required)

**Expected behavior**
Expectation as per the jumpstart is when you log in to the Windows VM, after the 2 scripts finish running, the Azure Data studio would launch and successfully connect to the SQL server. 

**Screenshots**
![image](https://user-images.githubusercontent.com/58454207/119068197-07115780-ba27-11eb-9163-aa74fa2d922b.png)

**Comment by likamrat** [comment]
@Haroon-1 do you mind giving it a go again?

**Comment by Haroon-1** [comment]
@likamrat I can confirm this works now.

**Comment by likamrat** [comment]
Thx for confirming @Haroon-1. Closing this for now
