### ISSUE TITLE
Jumpstart ArcBox - Overview

### ISSUE THREAD

**Issue by unattendcode** [microsoft/azure_arc#582]
**Scenario which you are working on**
https://azurearcjumpstart.io/azure_jumpstart_arcbox/

**Describe the bug**
Missing guidelines in prereq. The guidelines states to check subscription limit over 52 vCPU, my limit was 100, but installation fails running custom extensions on Linux VMs. 

**To Reproduce**
Under subscription usage+quota, I can see that I have used 64 vCPUs already. Tried another subscription (same Offer ID - Microsoft IUR) and it worked. So not a direct bug, but a suggestion to the docs.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dkirby-ms** [comment]
Hi, the prerequisites state that 52 vCPUs are required. Could you perhaps provide some additional detail on what you would like to see improved here? I am pasting the relevant text from the guide below.

> ArcBox requires 52 vCPUs when deploying with default parameters such as VM series/size. Ensure you have sufficient vCPU quota available in your Azure subscription and the region where you plan to deploy ArcBox. You can use the below Az CLI command to check your vCPU utilization.
