### ISSUE TITLE
existing kube config is overwritten instead of merged

### ISSUE THREAD

**Issue by foliba** [microsoft/azure_arc#586]
**Scenario which you are working on**
https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/alibaba/alibaba_terraform/

**Describe the bug**
Once you apply the terraform plan, your existing kube config in ~/.kube/config is overwritten instead of merged. Resulting in loosing all of your existing kube configs.

**To Reproduce**
1. apply the plan
2. see the created kubeconfig file to overwrite exising configs

**Expected behavior**
The new kubeconfig should be merged with the old one.
The old one should not be overwritten. As I loose all my existing configurations.

**Comment by likamrat** [comment]
Looping @KaiWalter

**Comment by KaiWalter** [comment]
@foliba found the RC and is working on a fix: [terraform plan](https://github.com/microsoft/azure_arc/blob/0f408daa5aa746531133971b8f466741f0ec4626/azure_arc_k8s_jumpstart/alibaba/terraform/main.tf#L13) is overwriting the complete `kubeconfig`
