### ISSUE TITLE
Jumpstart ArcBox - Overview

### ISSUE THREAD

**Issue by cmendible** [microsoft/azure_arc#609]
Hi Team,

**Scenario which you are working on**
ArcBox  Deployment 

**Describe the bug**
The provided post deployment scripts did not work until I manually registered the following providers:

``` shell
  az provider register --namespace Microsoft.HybridCompute
  az provider register --namespace Microsoft.Kubernetes
  az provider register --namespace Microsoft.KubernetesConfiguration
  az provider register --namespace Microsoft.ExtendedLocation
```

and created everything from scratch.

**Expected behavior**
Installation should register all the providers or the prerequisites documentation (https://azurearcjumpstart.io/azure_jumpstart_arcbox/#prerequisites) should ask for the providers.

**Comment by cmendible** [comment]
@likamrat I ran the scripts on Saturday and failed with current instructions. If the solution is to improve the docs I'll be happy to add a PR.

**Comment by dkirby-ms** [comment]
Thank you for the submission @cmendible.  We have an open PR that adds registration of the resource providers so this will be addressed shortly.

**Comment by cmendible** [comment]
Great! If already closed can you add reference to it here?

**Comment by dkirby-ms** [comment]
#606 addresses this
