### ISSUE TITLE
Error when checking initialize status of K8SE stamp with kubectl Unexpected output from kubectl.exe when getting pod statuses

### ISSUE THREAD

**Issue by borjasanes** [microsoft/azure_arc#621]
**Scenario which you are working on**
https://github.com/microsoft/azure_arc/tree/main/azure_arc_app_services_jumpstart

**Describe the bug**
I'm facing an issue when trying to create the App Service Kubernetes environment following the script.[AppServicesLogonScript.ps1](https://github.com/microsoft/azure_arc/blob/main/azure_arc_app_services_jumpstart/aks/app_service/arm_template/scripts/AppServicesLogonScript.ps1)

Despite the environment is being created in Azure Portal I'm getting an error message and I'm not able to create LogicApps in that custom location.

Error log:

_az appservice kube create --resource-group smartbuilding-bgarcia-0000 --name smartbuildingaks --custom-location /subscriptions/f4f0bcc8-6cb9-4a1c-a6be-bb58bc118319/resourcegroups/smartbuilding-bgarcia-0000/providers/microsoft.extendedlocation/customlocations/appinnovation-cl --static-ip "52.178.119.156" --location "West Europe"
Command group 'appservice kube' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Deployment failed. Correlation ID: 31670727-8b83-460b-ac12-6d716096d427. Error when checking initialize status of K8SE stamp with kubectl Unexpected output from kubectl.exe when getting pod statuses
output:
error:_

**To Reproduce**
1. Created an Azure VM
2. Execute Bootstraping.ps1
3. Aks onboarded on Azure ARC
4. Registered app service extension
4. Created custom location appinnovation-cl
5. See error when executing az appservice kube create

**Screenshots**
<img width="958" alt="screencapture-ps-2021-06-30-13_25_56" src="https://user-images.githubusercontent.com/11957336/123965527-d3760580-d9b4-11eb-80e9-90f29540e5d4.png">
![screencapture-ms-portal-azure-2021-06-30-13_25_56](https://user-images.githubusercontent.com/11957336/123965534-d4a73280-d9b4-11eb-8b5b-6abb7ad7d433.png)
![screencapture-ms-portal-azure-2021-06-30-15_12_05](https://user-images.githubusercontent.com/11957336/123966384-abd36d00-d9b5-11eb-9d66-025b2e33215a.png)
![screencapture-ms-portal-azure-2021-06-30-15_12_29](https://user-images.githubusercontent.com/11957336/123966379-aaa24000-d9b5-11eb-817f-3f1c33a343d5.png)

**Comment by likamrat** [comment]
Hi @borjasanes,

This scenario is still under development and yet to be published in the Jumpstart. It expected to go live in the next few days.

**Comment by borjasanes** [comment]
Thanks for your quick response. I'll stay tuned.

**Comment by likamrat** [comment]
Closing this for now
