### ISSUE TITLE
ARM Template fails deployment Update Management on Azure Arc enabled servers 

### ISSUE THREAD

**Issue by PaulBendall** [microsoft/azure_arc#631]
**Scenario which you are working on**
https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_servers/day2/arc_updatemanagement/

**Describe the bug**
Deployment fails whilst creating Azure Automation Runbook(s)

**To Reproduce**
Running the supplied Azure CLI command 
"az deployment group create --resource-group ArcUpdateManagement \
    --template-file law-template.json \
    --parameters law-template.parameters.json"
Returns failed
See error

**Expected behavior**
No failure error, the successful creation of the Log Analytics Workspace, Automation Account and ancillary runbooks

**Screenshots**
![image](https://user-images.githubusercontent.com/22103900/124486351-6b089900-dda5-11eb-8606-e6871d32cf11.png)

**Additional context**
The log analytics workspace and automation account appear to get created just the workbooks fail

**Comment by lanicolas** [comment]
Hi  @PaulBendall could you please share your parameters file to test out your set up? Please make sure there is no sensitive information on it.

**Comment by PaulBendall** [comment]
Good morning @lanicolas, here is the contents of my parameter file:
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "workspaceName": {
            "value": "ArcLogAnalyticsWorkspace"
        },
        "sku": {
            "value": "pergb2018"
        },
        "automationAccountName": {
            "value": "ArcAutomationAccount"
        },
        "arcVmName": {
            "value": "W2K19_Core"
        },
        "arcVmResourceGroup": {
            "value": "az-arc-rg"
        }
    }
}
