### ISSUE TITLE
Kubernetes Azure Arc status is stuck at Connecting for on-prem cluster, config-agent deployment fails with PowerShell

### ISSUE THREAD

**Issue by betrayz** [microsoft/azure_arc#644]
**Scenario which you are working on**
https://docs.microsoft.com/en-us/azure/azure-arc/kubernetes/quickstart-connect-cluster?tabs=azure-powershell

**Describe the bug**
Azure portal shows the on-prem cluster in Kubernetes - Azure Arc status as 'Connecting' after several hours.

**To Reproduce**
1. Follow the steps in the Quickstart link above.

**Expected behavior**
The Azure portal will show the Kubernetes cluster status as 'Connected' and display meta for the Kubernetes cluster.

All 'azure-arc' namespace Kubernetes objects will be successfully deployed.

**Screenshots**

![image](https://user-images.githubusercontent.com/13547008/125197015-109a8d00-e22a-11eb-98bd-ea2452ce5682.png)

![image](https://user-images.githubusercontent.com/13547008/125196303-66ba0100-e227-11eb-8020-570d885d13f5.png)

clusteridentityoperator manager container error for failing to parse PEM block containing the key

![image](https://user-images.githubusercontent.com/13547008/125196616-8dc50280-e228-11eb-8be5-68ddd4a11427.png)

config-agent container errors

![image](https://user-images.githubusercontent.com/13547008/125196906-9833cc00-e229-11eb-981a-20a1de3622fe.png)

DNS is OK

![image](https://user-images.githubusercontent.com/13547008/125197921-ad125e80-e22d-11eb-9482-f021d976bcd8.png)

**Additional context**

Attempted to clean-up and re-connect the on-prem cluster using different resource groups and locations.

User role assigned is 'Owner'.

**Comment by punkinnovation** [comment]
To update this issue, the config-agent deployment was successful when using the az CLI.

![image](https://user-images.githubusercontent.com/13547008/125219068-2c397e00-e292-11eb-82a1-a136b8121761.png)

kubernetes version:

$ kubectl get nodes
NAME    STATUS   ROLES                  AGE   VERSION
k8s01   Ready    control-plane,master   29h   v1.21.2
k8s02   Ready    <none>                 29h   v1.21.2
k8s03   Ready    <none>                 29h   v1.21.2

This worked:
$ az connectedk8s connect --name ArcK8sCrawford --resource-group arc_rg

az cli version

$ az version
{
  "azure-cli": "2.26.0",
  "azure-cli-core": "2.26.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "connectedk8s": "1.1.5",
    "k8s-extension": "0.5.1"
  }
}


This did not work with multiple attempts, config-agent deployment always failed:

PS > New-AzConnectedKubernetes -ClusterName K8sArcCrawford -ResourceGroupName arc_rg -Location eastus2

PS version used:
$ pwsh
PowerShell 7.1.3

**Comment by shashankbarsin** [comment]
@betrayz this seems like a core Arc enabled K8s related issue and not a Jumpstart issueok. Support issues on the same can be filed [here](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade) on official Azure support. Can you file the issue on Azure support and the support team can triage the same and help out?

**Comment by betrayz** [comment]
Thanks much. Not jumpstart issue, closing.
