### ISSUE TITLE
New scenario to support Azure Arc Enabled Kubernetes on Docker Desktop and WSL2

### ISSUE THREAD

**Issue by toddwhitehead** [microsoft/azure_arc#660]
**Is your feature request related to a new Jumpstart scenario you would like to contribute?**
That's great! Use our Jumpstart Scenario Write-up Guidelines
https://azurearcjumpstart.io/scenario_guidelines

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
An end to end scenario for developers to deploy Azure Arc for Kubernetes to a development machine using Docker Desktop Kubernetes and WSL2 as this is a very common scenario for developers and it pros to evaluate Arc.

**Describe alternatives you've considered**
None identified

**Additional context**
Prakash Beegala has put together an internal doc that goes along way to helping so this could be the basis for it.

**Comment by likamrat** [comment]
Thank you @toddwhitehead. Following our conversation and after evaluating the scenario idea, we decided not to move forward with developing a scenario that is purely based on the user local environment presents complexities we believe are stronger than the ROI for this scenario.

1. Configuring Azure Arc-enabled Kubernetes on a local user dev environment might get you to a point you have an Azure Arc Kubernetes cluster based on Docker and WSL onboarded, but this cluster is most likely to experience many operational and performance issues once you will want to use it for other Azure Arc technologies such as Azure Arc-enabled data services, app services, and ML. 

2. Designing a scenario that is based on the user's local environment can create many potential issues that are out of our control and present Jumpstart reliability risk. 

3. As an alternative, we have many other Jumpstart scenarios that should be considered and are based on various Kubernetes lightweight such as [Rancher K3s](https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/rancher_k3s/), [KinD](https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/kind/), and [MicroK8s](https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/microk8s/).

I will go ahead and close this for now and please reach out for any questions or comments.
