### ISSUE TITLE
Azure Arc for SQL Server gives ResourceGraph throttling error

### ISSUE THREAD

**Issue by cenkersoy** [microsoft/azure_arc#666]
Hi,

When I deploy Azure Arc for SQL demo, the deployment finishes fine and the initial script inside the Azure VM runs.

However, Arc related resources are not created in the resource group.

When I go into Azure Arc in Azure portal, I see the attached error with (Code:RateLimiting)

An error occurred when trying to fetch resources. Additional details from the underlying API that might be helpful.
Please see https://aka.ms/resourcegraph-throttling for help. (Code:RateLimiting)

Thanks
Cenk Ersoy
![error](https://user-images.githubusercontent.com/16318859/126554881-56eb6032-4988-4f12-bdc9-2e59bb3c037d.jpg)

**Comment by lanicolas** [comment]
Hello @cenkersoy I believe the problem has bee resolved can we close this issue?

**Comment by cenkersoy** [comment]
Yes pls.

**Comment by lanicolas** [comment]
Closing issue as it has been resolved
