### ISSUE TITLE
Store sample database backups in central artifacts folder

### ISSUE THREAD

**Issue by mdrakiburrahman** [microsoft/azure_arc#671]
Currently the SQL MI and Postgres backup files are duplicated across the scenarios - this increases time taken to clone the repo etc.  Also requires per scenario localizations which adds overhead.

Perhaps the backups should be moved into `arc_data_services` as they won't change across the scenarios.

**Comment by likamrat** [comment]
@mdrakiburrahman @dkirby-ms let's start working on moving this DB to the Jumpstart storage account
