### ISSUE TITLE
Jumpstart ArcBox - Subscription missing Azure ARC server resource providers pre-requesite 

### ISSUE THREAD

**Issue by cbezenco** [microsoft/azure_arc#672]
**Scenario which you are working on**
A link to the Jumpstart scenario you are working on.
https://azurearcjumpstart.io/azure_jumpstart_arcbox/#start-post-deployment-automation

**Describe the bug**
ARC serverr registration failed due to missing pre-requesite resource provider.
The subscription is not registered to use namespace 'Microsoft.HybridCompute'

**To Reproduce**

**Expected behavior**
Proper registration of Azure ARC Servers by including pre-requesite: https://docs.microsoft.com/en-us/azure/azure-arc/servers/learn/quick-enable-hybrid-vm#register-azure-resource-providers

az provider register --namespace 'Microsoft.HybridCompute'
az provider register --namespace 'Microsoft.GuestConfiguration'

**Screenshots**

**Additional context**

**Comment by dkirby-ms** [comment]
Resolved with #684
