### ISSUE TITLE
Strengthen ARCbox security posture leveraging my IP address to avoid open Internet exposure 

### ISSUE THREAD

**Issue by cbezenco** [microsoft/azure_arc#687]
**Is your feature request related to a new Jumpstart scenario you would like to contribute?**
That's great! Use our Jumpstart Scenario Write-up Guidelines
https://azurearcjumpstart.io/scenario_guidelines

**Is your feature request related to a problem? Please describe.**
Azure ARCBox deployment is triggering alerts from my Security Operation Center due to open port to the Internet.

**Describe the solution you'd like**
Leverage My IP address parameter provided during ARCBox provision to restrict network security rules and avoid open Internet access during default installation (at least for SQL and PostreSQL - port 5432 and 1433) 

**Describe alternatives you've considered**
Doing it manually but it is prone to error and I suspect my SOC team will be fed up as there will be more colleague who will experiment with ARCBox

**Additional context**

**Comment by likamrat** [comment]
Thank you @cbezenco, makes sense. 
@dkirby-ms @mdrakiburrahman we need to implement this for ArcBox and the Azure-based data scenarios for now. After that, we should assess the impact on app services scenarios.
