### ISSUE TITLE
failed to get file "infrastructure-components.yaml"

### ISSUE THREAD

**Issue by henrikmotzkus** [microsoft/azure_arc#688]
**Scenario which you are working on**

Deployment via Azure Portal

**Describe the bug**
I trie to to deploy the complete script but the CAPI.MGMT portion seem to failing.

arcdemo@ArcBox-CAPI-MGMT:~$ clusterctl init --infrastructure azure
Fetching providers
Error: failed to get provider components for the "azure" provider: failed to read "infrastructure-components.yaml" from provider's repository "infrastructure-azure": failed to download files from GitHub release v0.5.1: failed to get file "infrastructure-components.yaml" from "v0.5.1" release

**To Reproduce**

Click on Deploy to Azure

**Expected behavior**

Deployment of the ARM script should be successful and the VM should be configured properly

**Screenshots**

Look the error above

**Additional context**

**Comment by likamrat** [comment]
Thank you @henrikmotzkus . It looks like the new CAPZ 0.5.1 provider [released yesterday](https://github.com/kubernetes-sigs/cluster-api-provider-azure/releases/tag/v0.5.1) is breaking automation. We are working on a fix...
