### ISSUE TITLE
ArcBox Lite

### ISSUE THREAD

**Issue by mdowst** [microsoft/azure_arc#721]
**Is your feature request related to a new Jumpstart scenario you would like to contribute?**
Not a new scenario as much as a reduction of resources or a new deployment model. I would be willing to contribute on updating the templates. 

**Is your feature request related to a problem? Please describe.**
I would like to use ArcBox for training, demos, and POCs. However, the compute cost that it deploys with are way too high. If I where to leave it at the default size and not configure auto-shutdown, I'd be looking at $2k worth of compute charges. The majority of this is coming from the Kubernetes cluster. 

**Describe the solution you'd like**
I would like to be able to deploy the individual pieces so I could exclude the Kubernetes cluster, or maybe even parts of it. We could add parameters to the main deployment ARM template to be able to exclude parts and/or potentially reduce compute requirements. For example, I was able to reduce the client VM from a D16s_v3 to a D4s_v3 which is over $700 a month cheaper to run, but still lets me replicate an on-prem environment with hyper-v. 

**Describe alternatives you've considered**
Since the client VM is depended on the Kubernetes cluster VMs, the only alternatives are to build the environment out manually whenever I need it, or run the ArcBox template, then go back in and remove all the unneeded resources from Azure, manually resize the client VMs, then manually resize the hyper-v VMs, disable the the deployment script scheduled task, and set an auto-shutdown on the client VM. 

**Additional context**
Even after the resizing, setting the auto-shutdown, and removing of the additional VMs that were deployed outside of the ARM templates, my consumption hit $100 after 3 days. I would hate to see what it would have been if I just left it running as is.

**Comment by dkirby-ms** [comment]
@mdowst, 

Thank you for this suggested improvement. This is something we have considered building before. We have already taken some steps to further modularize ArcBox to make it easy to scale down or up the deployment based on resource constraints or other needs. 

We have some workstreams currently in place to address some of these concerns and give additional options to users to scale their ArcBox deployment appropriately. Please stay tuned. I'll leave this issue open and we will track against it for this feature.

**Comment by likamrat** [comment]
Hey @mdowst, I wanted to let you know we haven't forgotten about you. 

As part of our internal Azure Arc Enterprise-Scale workstream, we will be developing focused versions of ArcBox (aka "flavors"). I am working with @dkirby-ms on this and we will update this thread as we go.
