### ISSUE TITLE
Update Management

### ISSUE THREAD

**Issue by vparna** [microsoft/azure_arc#725]
**Scenario which you are working on**
Trying to create update management for the Azure Arc Server to perform patching using update management using the below link:  https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_servers/day2/arc_updatemanagement/

**Describe the bug**
was able to deploy update management on a test Azure Arc ON-Perm Server but the Runbooks, Log analytics solutions didn't get created even though the automation account, Log Analytics workspace got created successfully, also deployment says successful.

**To Reproduce**
1. clone the azure arc repository
2. open the Azure CLI and cd to the azure_Arc_Servers_Jumpstart\updateManagement folder
3. execute az deployment group create --resource-group <ResourceGroupName> --template-file law-template.json --parameters law-template.parameters.json 

**Expected behavior**
As per the documentation I did expected to see the runbooks and the update management solution mentioned in the documentation link https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_servers/day2/arc_updatemanagement/ after successful deployment. 

**Screenshots**

**Additional context**
as the update management solution is not available i was not able to move to the next steps in the documentation, please provide troubleshooting steps.

**Comment by dkirby-ms** [comment]
@vparna can you please provide some details: 

What Azure region are you using?
Provide the error message from the deployment where the Update Management solution is failing.

**Comment by vparna** [comment]
i am currently using West US 2 region., i dont see any error message on the Azure portal or on the Azure CLI command prompt. the deployment succeeded but the runbooks, update management solutions aren't created in the resource group.

**Comment by dkirby-ms** [comment]
If the deployment is succeeding and not showing any error, then the resources should be created including the Update Management solution.

Is the resource group where your Azure Arc-enabled server resides the same resource group you are using to deploy the law-template.json from the Update Management scenario?

**Comment by dkirby-ms** [comment]
I was able to reproduce this. I will update the thread when I understand the root cause and have a fix.

**Comment by dkirby-ms** [comment]
This has been addressed. Note that in the updated version, the runbooks are no longer deployed with the template as they are not necessary for the scenario.

**Comment by vparna** [comment]
thank you for the updating the documentation. but I don't see the log Analytics solution created. can you check ?

**Comment by dkirby-ms** [comment]
There is a screenshot in this link that shows the Log Analytics workspace, automation account, and update management solution.

https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_servers/day2/arc_updatemanagement/
