### ISSUE TITLE
Azure Security Center onboarding for Azure Arc connected Machines

### ISSUE THREAD

**Issue by lanicolas** [microsoft/azure_arc#75]
**Is your feature request related to a problem? Please describe.**
Automate and describe the onboarding of Azure Arc connected machines on Azure Security Center

**Describe the solution you'd like**
Create documentation on how to enable Azure Security Center within an Azure Arc connected machine. Also create documentation demoing a scenario enabled by Azure Security Center

**Describe alternatives you've considered**
ARM template 
leverage already existing scenarios

**Additional context**
N/A

**Comment by likamrat** [comment]
Completed by @lanicolas 
https://github.com/microsoft/azure_arc/blob/master/azure_arc_servers_jumpstart/docs/arc_securitycenter.md
