### ISSUE TITLE
error when installing AZURE ML training model piece

### ISSUE THREAD

**Issue by arturoqu77** [microsoft/azure_arc#758]
I was getting an error when azuremllogonscript.ps1 was running and trying to use grep in one line, but it could not find grep anywhere. So, I installed grep via chocolatey, and now the script goes further to line 267,and gives me the error below.

grep executes but now the error says "Dataset with name 'mnist_opendataset' is not found".

Any help troubleshooting this error will be appreciated, I am trying to demo this to a customer. next week.

**TEXT of the OUTPUT when error is encountered:**

Installing amlarc-compute K8s extension was successful.

Warning: Falling back to use azure cli login credentials.
If you run your code in unattended mode, i.e., where you can't give a user input, then we recommend to use ServicePrincipalAuthentication or MsiAuthentication.
Please refer to aka.ms/aml-notebook-auth for different authentication mechanisms in azureml-sdk.
Library configuration succeeded

Warning: Falling back to use azure cli login credentials.
If you run your code in unattended mode, i.e., where you can't give a user input, then we recommend to use ServicePrincipalAuthentication or MsiAuthentication.

Please refer to aka.ms/aml-notebook-auth for different authentication mechanisms in azureml-sdk.
Class KubernetesCompute: This is an experimental class, and may change at any time. Please see https://aka.ms/azuremlexperimental for more information.
Class KubernetesCompute: This is an experimental class, and may change at any time. Please see https://aka.ms/azuremlexperimental for more information.
found compute target: ARC-ml
"
 Training model:
                               
            .....                                             .....
         .........                                           .........
        .........                 (((((((((##                 .........
       .....                      (((((((####                      .....
      ......                      #((########                      ......
     ....... .............        ###########        ............. .......
     ......................       ###########       ......................
    .................*.....       ###########       ....,*.................
    .........*******......       (((((((((((         ......*******.........
         ............          (((((((((((     (.         ............
                            .(((((((((((     (((((/
                          ((((((((((((     #(((((((##
                        ////(((((((*     ##############
                      //////(((((.         ,#############.
                   ,**///////((               #############/
                    *////////&%%%%%%%%%%%%%%%%%%%##########
                    ///////&&&%&%%%%%%%%%%%%%%%&%&&#######(
                     ////&&&&&&&%%%%%%%%%%%%%&&&&&&&&%####
                     .(&&&&&&&&&&&&&&%%%%%%&&&&&&&&&&&&&#.

"
Warning: Falling back to use azure cli login credentials.
If you run your code in unattended mode, i.e., where you can't give a user input, then we recommend to use ServicePrincipalAuthentication or MsiAuthentication.
Please refer to aka.ms/aml-notebook-auth for different authentication mechanisms in azureml-sdk.
WARNING: Command group 'ml job' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Uploading src:   0%|                                                                                                                                | 0.00/3.08k [00:00<?, ?B/s]

**ERROR: Code: UserError**
**Message: Dataset with name 'mnist_opendataset' is not found.**
**You cannot call a method on a null-valued expression.**
**At C:\Temp\AzureMLLogonScript.ps1:267 char:4**
**+    $RunId = ($Job | grep '\"name\":').Split('\"')[3]**
**+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~**
    **+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException**
    **+ FullyQualifiedErrorId : InvokeMethodOnNull**

**RunId:**
**Training model, hold tight...**
**ERROR: argument --name/-n: expected one argument**_****

TRY THIS:
az ml job show --name my-job-id --query "{Name:name,Jobstatus:status}" --output table --resource-group my-resource-group --workspace-name my-workspace
Show the status of a job using --query argument to execute a JMESPath query on the results of commands.

https://aka.ms/cli_ref
Read more about the command in reference docs
Job Status:
ERROR: argument --name/-n: expected one argument

TRY THIS:
az ml job show --name my-job-id --query "{Name:name,Jobstatus:status}" --output table --resource-group my-resource-group --workspace-name my-workspace
Show the status of a job using --query argument to execute a JMESPath query on the results of commands.

https://aka.ms/cli_ref
Read more about the command in reference docs
Job Status:
ERROR: argument --name/-n: expected one argument

TRY THIS:
az ml job show --name my-job-id --query "{Name:name,Jobstatus:status}" --output table --resource-group my-resource-group --workspace-name my-workspace
Show the status of a job using --query argument to execute a JMESPath query on the results of commands.

**Comment by mdrakiburrahman** [comment]
Hi @arturoqu77 - thanks for reaching out. We tried to repro this issue but couldn't.

This [line of code](https://github.com/microsoft/azure_arc/blob/a322f4915a72f860779e4d92d7d111848883a344/azure_arc_ml_jumpstart/aks/arm_template/artifacts/AzureMLLogonScript.ps1#L266) leverages grep to parse the file name. `grep` should have been installed as part of the [bootstrap](https://github.com/microsoft/azure_arc/blob/a322f4915a72f860779e4d92d7d111848883a344/azure_arc_ml_jumpstart/aks/arm_template/artifacts/Bootstrap.ps1#L73). If  `grep` wasn't installed, this implies something must have interrupted the install before it got there.

Did you by any chance RDP into the VM before the Deployment was fully finished? That would cause the chocolatey install flow to break - which would also explain why the Training above isn't working. 

Are you seeing Postman installed - this happens [after `grep`](https://github.com/microsoft/azure_arc/blob/a322f4915a72f860779e4d92d7d111848883a344/azure_arc_ml_jumpstart/aks/arm_template/artifacts/Bootstrap.ps1#L73)? If not, this is probably what happened.

Could you try the deployment in a new RG, but this time ensuring you RDP in once ARM returns success (and the Bootstrap script is successful in running - you can see this in the ARM deployment status from the RG)? If you can't repro this issue once more, we can eliminate the above.

**Comment by arturoqu77** [comment]
Hello,

Thank you for your reply. I may have logged on before the bootstrap completed, I re-started the deployment to a new RG and seems to be working now.

Thanks for the help.

Regards

***@***.***
Arturo Quiroga
Sr. Cloud Solutions Architect (CSA)
Azure Applications & Infrastructure
***@***.******@***.***>
[MSFT_logo_Gray DE sized SIG1.png]


From: Raki ***@***.***>
Date: Tuesday, September 14, 2021 at 6:22 PM
To: microsoft/azure_arc ***@***.***>
Cc: Arturo Quiroga ***@***.***>, Mention ***@***.***>
Subject: Re: [microsoft/azure_arc] error when installing AZURE ML training model piece (#758)

Hi @arturoqu77<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Farturoqu77&data=04%7C01%7Carturoqu%40microsoft.com%7C4df75e22c063478509d008d977ce2b14%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637672549666347896%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=r1kAuKxYlYhONjoSTk83SERggUvNcbP1Hr4vmNh29io%3D&reserved=0> - thanks for reaching out. We tried to repro this issue but couldn't.

This line of code<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fazure_arc%2Fblob%2Fa322f4915a72f860779e4d92d7d111848883a344%2Fazure_arc_ml_jumpstart%2Faks%2Farm_template%2Fartifacts%2FAzureMLLogonScript.ps1%23L266&data=04%7C01%7Carturoqu%40microsoft.com%7C4df75e22c063478509d008d977ce2b14%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637672549666357889%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oAjL%2BfBBF4QXfnwN9gcM9UqEB4OA0ZZrzMuKilatz5A%3D&reserved=0> leverages grep to parse the file name. grep should have been installed as part of the bootstrap<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fazure_arc%2Fblob%2Fa322f4915a72f860779e4d92d7d111848883a344%2Fazure_arc_ml_jumpstart%2Faks%2Farm_template%2Fartifacts%2FBootstrap.ps1%23L73&data=04%7C01%7Carturoqu%40microsoft.com%7C4df75e22c063478509d008d977ce2b14%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637672549666357889%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=V8dzJxj3W5a6IL8T%2BvB0mijBm5Ng4G46bb%2Fcdo2uvz4%3D&reserved=0>. If grep wasn't installed, this implies something must have interrupted the install before it got there.

Did you by any chance RDP into the VM before the Deployment was fully finished? That would cause the chocolatey install flow to break - which would also explain why the Training above isn't working.

Are you seeing Postman installed - this happens after grep<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fazure_arc%2Fblob%2Fa322f4915a72f860779e4d92d7d111848883a344%2Fazure_arc_ml_jumpstart%2Faks%2Farm_template%2Fartifacts%2FBootstrap.ps1%23L73&data=04%7C01%7Carturoqu%40microsoft.com%7C4df75e22c063478509d008d977ce2b14%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637672549666367883%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XvpeFo2T7Kjr4qrIZYKO7eM0khlOddES9O3DGaw1yZ4%3D&reserved=0>? If not, this is probably what happened.

Could you try the deployment in a new RG, but this time ensuring you RDP in once ARM returns success (and the Bootstrap script is successful in running - you can see this in the ARM deployment status from the RG)? If you can't repro this issue once more, we can eliminate the above.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fazure_arc%2Fissues%2F758%23issuecomment-919554382&data=04%7C01%7Carturoqu%40microsoft.com%7C4df75e22c063478509d008d977ce2b14%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637672549666367883%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZBGNkrDGFcqvrdWHXy5iEGluQiq2Ph%2BZnfosqC3qTTU%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHV4QUFA72NR7CEJ3UPS5NLUB7DLDANCNFSM5D6SSBHA&data=04%7C01%7Carturoqu%40microsoft.com%7C4df75e22c063478509d008d977ce2b14%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637672549666377877%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ctEevpiqzC%2FQnTc6ho2hfr2PVGA%2FqwGJzj1pPUCEylY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Carturoqu%40microsoft.com%7C4df75e22c063478509d008d977ce2b14%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637672549666377877%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cMCZqYPB6q8c9n%2BgPTk9f3MCQr%2BlV4GsOW9iPFSZtgE%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Carturoqu%40microsoft.com%7C4df75e22c063478509d008d977ce2b14%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637672549666387876%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6B5T09q%2Bx2Q2rWftui6b32lD1VLrCRMPiLSrTUS7xnI%3D&reserved=0>.

**Comment by mdrakiburrahman** [comment]
Great!
