### ISSUE TITLE
Failed during the Azure Connected Machine Agent installation

### ISSUE THREAD

**Issue by elijah-0221** [microsoft/azure_arc#771]
We are executing this following cmd when install the connected machine agent on to the servers, and get some exception.
AzureConnectedMachineAgent.msi /l*v C:\Temp\Installationlog.txt /qn

WixQuietExec64:  VERBOSE: In Enable-ExtensionService
WixQuietExec64:  VERBOSE: In Start-ServiceInternal
WixQuietExec64:  VERBOSE: Retry Count 4
WixQuietExec64:  WARNING: Service 'Guest Configuration Extension service (ExtensionService)' 
WixQuietExec64:  cannot be started due to the following error: Cannot start service 
WixQuietExec64:  ExtensionService on computer '.'.
WixQuietExec64:  VERBOSE: CPU Usage : '51.5%'
WixQuietExec64:  VERBOSE: Memory Usage : '48.327646548493%'
WixQuietExec64:  VERBOSE: Invoke-ScriptWithRetry:: End time : 9/25/2021 4:25:21 PM
WixQuietExec64:  Start-Service : Service 'Guest Configuration Extension service 
WixQuietExec64:  (ExtensionService)' cannot be started due to the following error: Cannot start 
WixQuietExec64:  service ExtensionService on computer '.'.
WixQuietExec64:  At C:\Program Files\AzureConnectedMachineAgent\ExtensionService\GC\Modules\Exte
WixQuietExec64:  nsionService\ServiceHelper.psm1:367 char:5
WixQuietExec64:  +     Start-Service $serviceName
WixQuietExec64:  +     ~~~~~~~~~~~~~~~~~~~~~~~~~~
WixQuietExec64:      + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceControl 
WixQuietExec64:     ler:ServiceController) , ServiceCommandException
WixQuietExec64:      + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Comman 
WixQuietExec6
[Installationlog.txt](https://github.com/microsoft/azure_arc/files/7231037/Installationlog.txt)
4:     ds.StartServiceCommand
WixQuietExec64:   
WixQuietExec64:  Error 0x80070001: Command line returned an error.
WixQuietExec64:  Error 0x80070001: QuietExec64 Failed
WixQuietExec64:  Error 0x80070001: Failed in ExecCommon method
CustomAction InstallExtensionService returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 16:25:21: InstallFinalize. Return value 3.

**Comment by elijah-0221** [comment]
[Installationlog.txt](https://github.com/microsoft/azure_arc/files/7231048/Installationlog.txt)

**Comment by likamrat** [comment]
@elijah-0221 can you please follow the [issue template](https://github.com/microsoft/azure_arc/issues/new?assignees=&labels=bug%2Ctriage&template=bug_report.md&title=)?

If this is not related to a Jumpstart scenario, I would ask you to open a support ticket.

Thank you

**Comment by likamrat** [comment]
@elijah-0221 I will go ahead and close this issue for now. Please reply here if needs to be re-open.
