### ISSUE TITLE
 Scenario for Azure Arc enabled Kubernetes environment based on Platform9 Managed Kubernetes

### ISSUE THREAD

**Issue by johnjamie** [microsoft/azure_arc#774]
Documentation on how to deploy a Azure Arc enabled Kubernetes environment based on Platform9 Managed Kubernetes.
![Platform9 Managed Kubernetes Clusters with Azure Arc](https://user-images.githubusercontent.com/1527364/134827425-c8ea0425-00ca-416b-8daa-a4c5d2d60a57.png)

**Comment by likamrat** [comment]
@johnjamie thank you. Can you please use the ["Feature Request" template](https://github.com/microsoft/azure_arc/issues/new?assignees=&labels=&template=feature_request.md&title=) for this one? We would love to see the Platform9 team contribute with a Jumpstart scenario.

**Comment by johnjamie** [comment]
Hi @likamrat my colleague @deepuks will be completing the Jumpstart scenario.
