### ISSUE TITLE
Azure Arc app services extension fails to deploy

### ISSUE THREAD

**Issue by arturoqu77** [microsoft/azure_arc#793]
**Scenario which you are working on**
I have an on-premises bare metal server which is running the latest version of the AZURE STACK DEVELOPER KIT (ASDK), and in it I have deployed an AKS-ENGINE K8S cluster with 3 master nodes and 7 worker nodes. 

With Arc, I am able to onboard to Azure the windows host running ASDK, as well as a LINUX VM running there which is acting as my development box and which I used to deploy the AKS-ENGINE cluster. 

I am also able to onboard with Arc the AKS-ENGINE cluster on premises to Azure, and I have enabled AZURE MONITOR on that cluster. I have enabled GITOPS in the cluster and I have also deployed the Azure Arc Data controller to it, I created a custom location and deployed a SQL MI instance there. 

I was also able to install the Azure Arc Event grid extension to the cluster. Will deploy a custom location and a topic soon.

However, now that I am trying to deploy the Azure Arc App services extension to the cluster and then create a custom location for it, the following happens (which I have recreated at least 10 times, always the same result), see bug description below.

**Describe the bug**
The problem is that I get an error that the Azure Arc App extension failed, as follows:  **"Error: {failed to install chart from path [] for release [appservices-oakville]: err [release appservices-oakville failed, and has been uninstalled due to atomic being set: timed out waiting for the condition]} occurred while doing the operation : {Installing the extension} on the config"**

![arc5](https://user-images.githubusercontent.com/32229456/136219256-5facb66d-9489-422d-b521-160ada4720b9.PNG)
![arc4](https://user-images.githubusercontent.com/32229456/136219345-78550ad3-5c23-4ec7-be23-7a6e35cf6bb1.PNG)

However, eventually all pods end up running, although by the time all pods run the deployment has timed out and the portal shows the error above.

![arc1](https://user-images.githubusercontent.com/32229456/136219569-0f388f2d-4a4c-4310-ad93-9c385585ffc8.PNG)
![arc2](https://user-images.githubusercontent.com/32229456/136219614-2e77b390-b202-476c-9475-91dfdf973288.PNG)

This is the command I used (verbatim from the script provided by the portal):

![arc3](https://user-images.githubusercontent.com/32229456/136219868-0f13f78c-74d6-4fe6-a6c5-0355962edf7c.PNG)

COMMENT ==> The IP address I used is the one that the LB of the AKS-ENGINE cluster (192.168.102.34), should I use another IP?, the JUMPSTART example and the examples in the AZURE DOCS all only cover the use case of using an AKS cluster in Azure (fake on-premises cluster), whereas in my case I am using a real on-premises cluster. I am assuming I am using the right IP Address.

Now, if I let the pods continue to exist, after the deployment failed, they run for about 15 minutes, then all are deleted and recreated and all eventually run again, and this gets repeated until I delete the namespace.

**Expected behavior**
Why does the deployment timeout, when all pods eventually run?, is there a way to extend the timeout period for the helm chart deployment to complete?

This environment is being used for many customer demos, it would be great if I can get some assistance here.

Regards,

ARTURO QUIROGA

**Comment by arturoqu77** [comment]
this is the view of the LB in front of the AKS-ENGINE cluster deployed to Azure Stack Hub (ASDK):


![arc8](https://user-images.githubusercontent.com/32229456/136259782-39f4f297-90cf-4074-8b53-2acaa4f06c27.PNG)

**Comment by apwestgarth** [comment]
@arturoqu77 this is a capability we are close to completing roll out of, I'm glad it was able to help you at this point.  Docs will be updated soon and there are a number of updates to the portal experience in final validation ahead of roll out on top of this update.
