### ISSUE TITLE
Azure Arc Jumpbox deployment failure - mgmtArtifactsAndPolicyDeployment  FAILED

### ISSUE THREAD

**Issue by captainlaw** [microsoft/azure_arc#813]
**Scenario which you are working on**
Following the guide to provision the Azure Arcbox environment but has deployment error.

**Describe the bug**
Following the guide to provision the Azure Arcbox environment but has deployment error.
Tried both the Azure Portal / CLI deployment option both failed at the same stage

**Verified**
- Has sufficient VCore quota
- Some Azure resources are successfully provisioned (Service Principal) is working

**Detail Error**
ERROR:
mgmtArtifactsAndPolicyDeployment  FAILED
--> Security(myarcboxnamemasked)  Microsoft.OperationsManagement/solutions BadRequest

**Provisioning operation**
Create
**Status**
BadRequest
**Status message**
{
    "status": "Failed",
    "error": {
        "code": "BadRequest",
        "message": ""
    }
}
**Type**
Microsoft.OperationsManagement/solutions

**Step to Reproduce**
Follow the Deployment https://azurearcjumpstart.io/azure_jumpstart_arcbox/

**Comment by dkirby-ms** [comment]
@captainlaw are you still seeing this issue?

**Comment by captainlaw** [comment]
The error occurs on  target resource group's location is  AustraliaEast, but no problem in EastUS / SoutheastAsia

**Comment by dkirby-ms** [comment]
> The error occurs on target resource group's location is AustraliaEast, but no problem in EastUS / SoutheastAsia

I was able to reproduce this in Australia East. It looks like AustraliaEast throws a "BadRequest" error when attempting deployment of the Security solution in a log analytics workspace. I dont see any documentation stating that we either support or don't support Security solution in LA workspace in AustraliaEast. However, given that we are seeing this issue, I am going to remove Australia East as a supported region for ArcBox deployments.

**Comment by captainlaw** [comment]
@dkirby-ms  thanks for verify this. But interestingly i found the LA workspace is provisioned successfully
