### ISSUE TITLE
Deployment Guide for  Azure Database for PostgreSQL Hyperscale Server on Azure Arc (AKS)

### ISSUE THREAD

**Issue by izzymsft** [microsoft/azure_arc#82]
**Is your feature request related to a problem? Please describe.**
No, it is not.

**Describe the solution you'd like**
This describes how to deploy a "Ready-to-Go" environment with PostgreSQL Hyperscale server group deployed on Azure Arc

**Describe alternatives you've considered**
Not applicable to this feature

**Additional context**
The environment for this scenario is the Azure Kubernetes Service

**Comment by likamrat** [comment]
Completed
https://github.com/microsoft/azure_arc/blob/master/azure_arc_data_jumpstart/docs/aks_postgresql_hyperscale_arm_template.md
