### ISSUE TITLE
Logic Apps on AKS scenario fails to complete on client VM

### ISSUE THREAD

**Issue by msamta** [microsoft/azure_arc#837]
**Scenario which you are working on**
https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_app_svc/aks/aks_logic_app_arm_template/

**Describe the bug**
After logging into the client VM and initialising the AppSvc logon PS, deployment seems to be restarting the log processor/ waiting for log-processor to become available for an abnormal amount of time. 

**Screenshots**
![image](https://user-images.githubusercontent.com/52723458/140386507-765db8ce-4647-4ae1-b6f2-a7b941dffa79.png)

**Comment by dkirby-ms** [comment]
Thanks for submitting this. We've merged a fix to address this. Please try to run the scenario again.

Thanks,
Dale
