### ISSUE TITLE
Error while provisioning Jumpstart ArcBox via the portal

### ISSUE THREAD

**Issue by mifung** [microsoft/azure_arc#850]
**Scenario which you are working on**
I’ve deployed the jumpstart arcbox via the Portal following the instructions from this URL: Jumpstart ArcBox - Overview | Azure Arc Jumpstart

**Describe the bug**
Upon deployment, I’ve ran into the following errors while trying to deploy:
•	ubuntuRancherDeployment
•	ubuntuCAPIDeployment

**To Reproduce**
From this URL https://azurearcjumpstart.io/azure_jumpstart_arcbox/
Select Deployment Option 1: Azure Portal 

**Expected behavior**
Results came back with error when deploying ubuntu resources: As stated above in 'Describe the bug' section

**Screenshots**
The error came back have the following status message
{
    "status": "Failed",
    "error": {
        "code": "InvalidTemplateDeployment",
        "message": "The template deployment 'ubuntuRancherDeployment' is not valid according to the validation procedure. The tracking id is '38111fe9-9fed-4060-a5fc-b530191cb3e7'. See inner errors for details.",
        "details": [
            {
                "code": "SecurityRuleInvalidAddressPrefix",
                "message": "Security rule /subscriptions/80cfcb97-091d-4cbf-b8f3-344c817c05dc/resourceGroups/AzureArcTest/providers/Microsoft.Network/networkSecurityGroups/ArcBox-K3s-NSG/securityRules/allow_SSH has invalid Address prefix. Value provided: arctest",
                "details": []
            }
        ]
    }
}
 

**Additional context**

**Comment by likamrat** [comment]
Thank you @mifung. Do you mind sharing your parameters files without the secrets?

**Comment by mifung** [comment]
Is this what you need?

***@***.***
