### ISSUE TITLE
ERROR: Operation returned an invalid status 'OK'

### ISSUE THREAD

**Issue by ronhowe** [microsoft/azure_arc#852]
Let me preface this with a statement that I am very inexperienced with Kubernetes, Docker, containers, etc.

I am running Windows 10.0.19043 Build 19043 with follow Az CLI and extensions.

![image](https://user-images.githubusercontent.com/5210043/141594949-632c0ede-93b1-4221-8380-2c91c765db66.png)

I am trying to install the Application services extension (Preview) by generally following along this YouTube video:

https://youtu.be/17-EADOoJv0

Things seem fine until az k8s-extension create command.

It spins for several minutes and then ends with a misleading ERROR: Operation returned an invalid status 'OK' message.

OK means good to me.

Here is a screenshot of the command error:

![image](https://user-images.githubusercontent.com/5210043/141594688-da7cac04-2869-4774-834b-7979441bb636.png)

Again, I may have absolutely gotten something wrong in my local Docker+Kubernetes+KIND configuration.

I was able to onboard my Kubernetes cluster into Azure Arc and even enable the Azure Defender for Kubernetes extension.

I'm not sure if I made a mistake or if there is a bug in this very new version of the extension.

**Comment by ronhowe** [comment]
Tried a few troubleshooting steps:

https://docs.microsoft.com/en-us/azure/azure-arc/kubernetes/troubleshooting

![image](https://user-images.githubusercontent.com/5210043/141596158-44d46693-5e12-450e-b75e-1be472545cac.png)

**Comment by likamrat** [comment]
Thank you @ronhowe. Although this is not part of a Jumpstart scenario you are trying here, I was able to repro the issue on both the CAPI and AKS-based scenarios we have for Azure Arc-enabled app services. 

<img width="428" alt="SNAG-1730" src="https://user-images.githubusercontent.com/46730876/142001010-52e0c1e9-c2c0-44ce-a07b-f865191e2786.png">

I am looping @apwestgarth for visibility and insights.

**Comment by ronhowe** [comment]
Thanks for following up!

**Comment by likamrat** [comment]
@ronhowe i followed up with the team. We have a Resource Provider (RP) that will be rolled out soon to fix the 'invalid status' error. The extension itself is working and installed, it's the API reporting-back that has the bug.

**Comment by ronhowe** [comment]
> @ronhowe i followed up with the team. We have a Resource Provider (RP) fix that will be rolled out soon to fix the 'invalid status' error. The extension itself is working and installed, it's the API reporting-back that has the bug.

Thanks!

Is there an ETA on that so that I can try things after it has been deployed?

**Comment by likamrat** [comment]
@ronhowe end of this week but let me update here and I can verify this in the Jumpstart automations

**Comment by ronhowe** [comment]
I may try tinkering again if I got confirmation of it being live.

I really appreciate the feedback.  I'm super new to Kubernetes, let along Azure Arc for Kubernetes.  I want to be sure I'm using good tooling so the only thing to blame for it not working is me!  :)

**Comment by likamrat** [comment]
@ronhowe since i was able to repro, you are fine. allow me a few more days to validate. 
Also, instead of doing this locally, I highly recommend using one of the Azure Arc-enabled app services Jumpstart scenarios [here](https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_app_svc/).

**Comment by likamrat** [comment]
@ronhowe can you confirm this is still happening?

**Comment by ronhowe** [comment]
> @ronhowe can you confirm this is still happening?

I've moved on from this project.  It will take me a bit of time to try again.  I'm interested in providing the feedback, but it will take me some time.  If I am not able to provide a response by end-of-week (2022-01-09), then assume I will be unable to provide additional feedback and you can resolve this issue or take other appropriate SDLC actions.

**Comment by likamrat** [comment]
Thank you @ronhowe, I will go ahead and close this for now.

**Comment by arnaud-tincelin** [comment]
I am still having the issue with az cli 2.71.0 
I am running commands from a Microsoft hosted ADO agent.
Either all 3 commands from the task end up with the message "ERROR: Operation returned an invalid status 'OK'", either they all succeed.
I checked the logs from the pod several times, everything always went well.
