### ISSUE TITLE
Service principle azure role doesn't have proper rights configured

### ISSUE THREAD

**Issue by stevelatta** [microsoft/azure_arc#861]
When attempting to link Arc to my EKS cluster, using the service principle role, I get the following error message:

Unable to fetch the Object ID of the Azure AD application used by Azure Arc service. Unable to enable the 'custom-locations' feature. Insufficient privileges to complete the operation.

I'm using a personal subscription, so I ended up just using my user login to create the linkage.  I wasn't able to determine exactly what priviledges were necessary to unblock the SP role from functioning

**Comment by likamrat** [comment]
Thank you @stevelatta. I pushed a PR to address the KUBECONFIG flag for the _connect_ command. In addition, @DCMattyG will be refreshing the entire EKS vanilla scenario (related to issue #870).

I will go ahead and close this for now to avoid dup
