### ISSUE TITLE
Creating data controller for the November release using kubectl

### ISSUE THREAD

**Issue by aheden** [microsoft/azure_arc#876]
Creating a data controller using native kubernetes tools (kubectl).  Using the guidelines from the docs site [Create Data Controller](https://docs.microsoft.com/en-us/azure/azure-arc/data/create-data-controller-using-kubernetes-native-tools). I fail  when setting up the webhook part.

Bug
When creating the webhook job for the November release the job is targeting a script that does not exist and changing this yaml to the correct one "/opt/webhook/create-and-deploy-webhook.sh" with required arguments namespace and name will produce another error about permissions for the services account.

Log information 
| INFO | Checking for existing webhook...
| ERROR | An error occurred when checking for an existing webhook...
| ERROR | Debug Info: 
{ "kind": "Status", "apiVersion": "v1", "metadata": { }, "status": "Failure", "message": "mutatingwebhookconfigurations.admissionregistration.k8s.io \"arcdata.microsoft.com-webhook-arc\" is forbidden: User \"system:serviceaccount:arc:sa-arc-webhook-job\" cannot get resource \"mutatingwebhookconfigurations\" in API group \"admissionregistration.k8s.io\" at the cluster scope", "reason": "Forbidden", "details": { "name": "arcdata.microsoft.com-webhook-arc", "group": "admissionregistration.k8s.io", "kind": "mutatingwebhookconfigurations" }, "code": 403 }

**Comment by aheden** [comment]
I've added the following to Role : role-arc-webhook-job

- apiGroups: ["*"]
  resources: ["secrets"]
  resourceNames: ["arc-webhook-secret"]
  verbs: ["get"]

It currently has delete, not sure if it is needed or not

This solved my issue together with the change of the script path.

**Comment by likamrat** [comment]
@aheden can you please verify the new release? @twright-msft pushed the changes

**Comment by aheden** [comment]
Hi,

The there were some issues with the clusterrole: cr-arc-webhook-job

From:
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-arc-webhook-job
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  resourceNames: ["arcdata.microsoft.com-{{namespace}}"]
  verbs: ["delete"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["create"]

To

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-arc-webhook-job
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  **resourceNames: ["arcdata.microsoft.com-webhook-{{namespace}}"]
  verbs: ["delete", "get"]**
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["create"]
**- apiGroups: ["*"]
  resources: ["namespaces"]
  resourceNames: ["{{namespace}}"]
  verbs: ["patch"]**

**Comment by likamrat** [comment]
Hey @aheden, we now have a merged December release. Do you mind re-deploy and reporting back?

**Comment by twright-msft** [comment]
I've submitted a PR to update to what @aheden commented and tested end:end.  Should be good to go now.
