### ISSUE TITLE
Python Function App on GKE - CrashLoopBackOff

### ISSUE THREAD

**Issue by benbhall** [microsoft/azure_arc#878]
**Scenario which you are working on**
Deploying a Python Function App to GKE via Azure Arc

Sorry not entirely sure what repository to pop this in but could do with some pointers to get it working.

**Describe the bug**
Using 0.10.0 preview `microsoft.web.appservice` extension for Azure Arc and deploying a Python Function App to GKE. After deployment I get intermittent availability of the Functions because they get restarted for failing the readiness/liveness probe.

```
  Warning  Unhealthy  23m                   kubelet            Liveness probe failed: dial tcp 10.72.3.16:80: connect: connection refused
  Warning  Unhealthy  18m (x179 over 23m)   kubelet            Readiness probe failed: dial tcp 10.72.3.16:80: connect: connection refused
  Warning  BackOff    3m27s (x60 over 17m)  kubelet            Back-off restarting failed container

```
Correct me if I am wrong but isn't the container and Kubernetes setup all done behind the scenes, so I am not able to change port rules or probe settings?

**Comment by likamrat** [comment]
Thank you @benbhall. @apwestgarth can you take a look?

**Comment by apwestgarth** [comment]
Hi @benbhall can you share any further details about the Function App and Function itself please?

Does the function operate initially?  What type of Function are you deploying?  Is it a code app or custom container?

Can you also confirm the Functions framework version is 3 and can you share the Azure Functions Core Tools version you are using, this can be gained by running func -v from the command line on the machine you are publishing from?

Thanks

**Comment by benbhall** [comment]
Hi @apwestgarth. Apologies for not putting this in originally - I had a couple more tests to run.

Function Tools locally is on `3.0.3904`. 

I'm using the template Python Functions for HTTP trigger and Blob trigger, unchanged, on Python 3.8.

Both Functions operate as expected locally and deployed normally to an Azure Function App.

When deployed to an Azure Arc-enabled Kubernetes (only tried Google Cloud), I get the CrashLoopBackOff issue only when the Blog trigger function is deployed. The HTTP trigger on its own is stable. 

Deployed together I can use hit the HTTP trigger in between the forced restarts and I _think_ that once I saw the Blog trigger working.

**Comment by benbhall** [comment]
Further digging into deployment events.

```
error parsing azure blob metadata: no blobContainerName given	KEDAScalerFailed
Failed to ensure HPA is correctly created for ScaledObject	ScaledObjectCheckFailed
```

I can eliminate the first error by setting `blobContainerName` in the function.json, which feels wrong but works? This is not documented for Azure Functions, it's a [KEDA thing](https://github.com/kedacore/keda/blob/0be808c823c1a19ccea8dcb141361b91471d7342/pkg/scalers/azure_blob_scaler.go#L97).

Looks like there was similar for working with KEDA directly: https://github.com/Azure/azure-functions-core-tools/issues/2435

No luck with the second error. Looks like a KEDA problem still. Looks like both errors are something that the k8s app service extension should be wrapping up?

**Comment by raorugan** [comment]
@benbhall can you please let us know the steps implemented to create the blob trigger? Secondly do you already have a blob container created in Azure? Can you please check this and let us know?

**Comment by benbhall** [comment]
Yep @raorugan. The container for the trigger definitely exists and setup for public access. Remember, this works fine when deployed to a standard Azure Function resource.

**Comment by raorugan** [comment]
Can you pls confirm its the same blob container that your cs code is calling into? @benbhall

**Comment by benbhall** [comment]
> Can you pls confirm its the same blob container that your cs code is calling into? @benbhall

Yes, the container name in the `path` matches the name of my container in the storage account (from the connection string in the app setting in `connection`):
```json
      "path": "test-container/{name}",
      "connection": "AzureWebJobsStorage",
```
See earlier [comment ](https://github.com/microsoft/azure_arc/issues/878#issuecomment-986227258), that i'm being forced to add the following too:

```json 
"blobContainerName": "test-container",
```

**Comment by mukundnigam** [comment]
@benbhall  
Can you attach the output of the following commands ?

kubectl get pods -A
kubectl get events -n appservice-ns
kubectl describe pod -n appservice-ns testpythonappblob-7cff686f8d-tdrnl
(replace the name of the application POD which is in CrashLoopBackOff)

kubectl get so -n appservice-ns
kubectl get hpa -n appservice-ns

kubectl logs -n appservice-ns limaarcncsenv5-kube-k8se-build-service-668b45df7d-shgpp build-service
(replace the above name with the name of your build-service POD)

kubectl logs -n appservice-ns limaarcncsenv5-kube-k8se-keda-operator-5967c97b54-q6jrl | findstr /i /C:<appname>
(replace the above with keda-operator POD in your case and <appname> with function app name)

I am assuming the name of namespace which has extension installed is "appservice-ns" otherwise replace with actual name in above commands.

Also, can you try to create a new function app and publish the default python blobtrigger function again? Please make sure before you publish to this function app for the first time, you have all the required properties present in function.json ( in this case "path","connection" and "blobContainerName") with proper values. function.json should look something like :-

{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "name": "myblob",
      "type": "blobTrigger",
      "direction": "in",
      "path": "samples-workitems/{name}",
      "connection": "AzureWebJobsStorage",
      "blobContainerName": "samples-workitems"
    }
  ]
}

**Comment by benbhall** [comment]
- Output of  `kubectl get pods -A`: [In this gist](https://gist.githubusercontent.com/benbhall/8c25dfa364560e4953c0f739e3a56dfa/raw/460bbb1c49dc0452adbc149a6a77e212b7901003/getpods.md)
- Output of ` kubectl get events -n arc-ns`: [In this gist](https://gist.githubusercontent.com/benbhall/3c42215e8cbf4c091be4af6b2e9a0638/raw/9ea8134d138e148765bd1855ab4422cd0a6d05fc/getevents.md)
- Output of `kubectl describe pod -n arc-ns arc-demo-function-b7d6d5987-2fbzc`: [In this gist](https://gist.githubusercontent.com/benbhall/73d01a28aac3173fd97a94bf1423de28/raw/60ef831f293693634460f597642c235c3bf5d757/describefunc)
- Output of `kubectl get so -n arc-ns`: [In this gist](https://gist.githubusercontent.com/benbhall/65487ff8471ec1c6c824585df0a692de/raw/b4cd8d4a483452b7db5577d0ef30f10c49956368/getso)
- Output of `kubectl get hpa -n arc-ns`: [In this gist](https://gist.githubusercontent.com/benbhall/ef79e260a54ae4582c2b8fdee9e8c659/raw/957f0f4e72440b49feb94e0d8628d5f0dc1c514b/gethpa)
- Output of `kubectl logs -n arc-ns arc-app-service-k8se-build-service-6fbd9d9898-zjgdt build-service`: [In this gist](https://gist.githubusercontent.com/benbhall/8ad6a708b043a47f92bbed00378d816e/raw/6867fcdcb5e849c17599504eb901b977decf6b4b/logsbuild)
- Output of `kubectl logs -n arc-ns arc-app-service-k8se-keda-operator-647b74c97-t7zcp | findstr /i /C:arc-demo-function`: [In this gist](https://gist.githubusercontent.com/benbhall/d20a8f09801e60d34dee1989a6c5946d/raw/edd1d8edfec6ac7914f2014078f22bd6a8aa7dec/kedafunclogs)

This is doing everything fresh - new cluster, new arc bits and pieces and a new function with the JSON as provided.

**Comment by raorugan** [comment]
@benbhall , please let us know if you are facing any other issues. After our call today hope you are able to test creating a container in storage account and see blob trigger execute.

**Comment by likamrat** [comment]
@benbhall i will be closing this for now. please reply if something else is needed regarding this issue.
