### ISSUE TITLE
Azure Sentinel onboarding of Azure Arc enabled Servers

### ISSUE THREAD

**Issue by lanicolas** [microsoft/azure_arc#88]
**Is your feature request related to a problem? Please describe.**
Add scenario for Azure Sentinel on Azure Arc enabled Servers

**Describe the solution you'd like**
Describe the onboarding experience of Azure Arc enabled Servers on Azure Sentinel, and showcase if there are any specific scenarios

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by likamrat** [comment]
Completed
https://github.com/lanicolas/azure_arc/blob/sentinel/azure_arc_servers_jumpstart/docs/arc_azuresentinel.md
