### ISSUE TITLE
Data Controller Azure VM ARM Template - KubeADM

### ISSUE THREAD

**Issue by mysoultan** [microsoft/azure_arc#884]
**Scenario which you are working on**
https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_data/kubeadm/kubeadm_dc_vanilla_arm_template/
A link to the Jumpstart scenario you are working on.

**Describe the bug**
The data controller is not created nor the automated script being run when logged in to the client vm

**To Reproduce**
1. Just Deploy the template
2. Define the required parameters
3. All the resources being created except the data controller 
4. When logged in to the client machine no automated scripts being run as well

**Expected behavior**
The data controller should be created, 
**Screenshots**
![image](https://user-images.githubusercontent.com/48092067/144759362-632d1de6-10d2-4043-a351-6169acb37f53.png)
![image](https://user-images.githubusercontent.com/48092067/144759383-c3e0b468-ac74-4861-8d35-cd65409536ce.png)

**Additional context**

**Comment by likamrat** [comment]
Hey @mysoultan, thx for that. We are actually considering deprecating this scenario since we have support for [CAPI-based scenarios](https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_data/cluster_api/). 

Any specific reason to go with kubeadm?
