### ISSUE TITLE
k3s Azure ARM template

### ISSUE THREAD

**Issue by jgezelscorp** [microsoft/azure_arc#885]
**Scenario which you are working on**
ARC Enabled K8S with Rancher

**Describe the bug**
The Arm template (script extension part) that points to the URL of the rancher install script has an error

**To Reproduce**
az deployment group create \
--resource-group Arc-K3s-Demo \
--name arck3sdemo01 \
--template-uri https://raw.githubusercontent.com/microsoft/azure_arc/main/azure_arc_k8s_jumpstart/rancher_k3s/azure/arm_template/azuredeploy.json \
--parameters azuredeploy.parameters.json

**Expected behavior**
Script install without error?

**Additional context**
I get a 404 error when the script is being downloaded for installation

**Screenshots**
![rancher_01](https://user-images.githubusercontent.com/87699445/144858968-3ab0abd2-f0e5-4918-a606-4d829f2546fe.png)
.
![rancher_02](https://user-images.githubusercontent.com/87699445/144858982-9ea27f5a-e49d-4f3b-847e-485cde3e641f.png)
![rancher_03](https://user-images.githubusercontent.com/87699445/144859002-394f695d-5c29-4287-b44a-612e3d12c662.png)

**Comment by likamrat** [comment]
Thank you for the catch @jgezelscorp. I've merged the fix
