### ISSUE TITLE
Change jumpstart for Azure Arc-enabled data services to account for managed identity support

### ISSUE THREAD

**Issue by rgward** [microsoft/azure_arc#903]
The jumpstart scenarios for Azure Arc-enabled data services still require a service principal. The latest updates have moved to a model that no longer requires this and can use managed identities. This would be a more secure way to deploy so suggest we modify the templates and scenarios to no longer require a SP.

**Comment by likamrat** [comment]
Hey @rgward, 

The SP in the scenarios is being used in other places and not required JUST for the data services portion. We need this for deploying the client VM and the K8s clusters (in the case of CAPI and AKS).

**Comment by likamrat** [comment]
I understand @rgward but there is a bigger picture here. The Jumpstart scenarios are designed to provide a rich and comprehensive experience. That is why we are not just deploying the data services, but we are also providing the client VM and the other resources to achieve such an experience, hence the requirement for a service principle. 

We will continue to investigate the managed identity path but it certainly should not be presented as a blocker for you not to work with the Jumpstart scenarios.

I understand you might be looking at this from MSLearn modules perspective, but we have a larger scope in that sense. I hope that helps clarify why this is not something the Jumpstart team considers a major issue. 

I will go ahead and close this one for now but feel free to respond or reach out for anything.
