### ISSUE TITLE
Jumpstart ArcBox - Overview

### ISSUE THREAD

**Issue by vanessabruwer** [microsoft/azure_arc#917]
**Scenario which you are working on**
A link to the Jumpstart scenario you are working on.

**Describe the bug**
Arcbox deployment failed on ubuntuCAPIDeployment and ubuntuRancherDeployment steps, regardless of region selected.

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"VMExtensionProvisioningTimeout","message":"Provisioning of VM extension installscript_CAPI has timed out. Extension provisioning has taken too long to complete. The extension last reported \"Plugin enabled\".\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot"}]}

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'installscript_k3s'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=2\n[stdout]\n\n[stderr]\n\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "}]}

**To Reproduce**
Click Deploy button, let deployment run.

**Expected behavior**
Completed with no errors

**Screenshots**

![Screenshot 2022-01-06 095455](https://user-images.githubusercontent.com/31765217/148364521-26f7eb3b-32e8-465a-963d-0972faa7d47f.png)

**Additional context**

**Comment by likamrat** [comment]
Thank you @vanessabruwer. Can you please share the _installCAPI.log_ output?
1. ssh to the _ArcBox-CAPI-MGMT_ VM
2. _sudo -s_
3. _cat /var/lib/waagent/custom-script/download/0/a/_installCAPI.log_

**Comment by vanessabruwer** [comment]
I'll need to redeploy, as I removed all resources post failure. Will revert with log file once done (may take a few days)

**Comment by likamrat** [comment]
Due to no response, the release of ArcBox 2.0 and unable to repro, I will go ahead and close this for now. Please comment if further assistance is required.
