### ISSUE TITLE
Windows Server Virtual Machine won't register to Azure Arc

### ISSUE THREAD

**Issue by alpaye** [microsoft/azure_arc#918]
**Scenario which you are working on**
[A link to the Jumpstart scenario you are working on.](https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_servers/azure/azure_arm_template_win/)

**Describe the bug**
Can not register Azure Windows Server as an Azure Arc resource, because Hybrid.Compute provider was not registered.

**To Reproduce**
Follow the steps in the jumpstart scenario. If the provider is not registered, action fails with error.

**Expected behavior**
Windows Server on Azure should be registered as an Azure Arc resource.

**Screenshots**

**Additional context**
Enabling the resource provider solved the problem, do you think we should add this as a note?
This is my first bug report on Github, so I am really sorry if things are not right.

**Comment by likamrat** [comment]
Thank you @alpaye, added this prereq to all servers scenarios
