### ISSUE TITLE
SecurityContextConstraints manifests are missing from OpenShift documentation

### ISSUE THREAD

**Issue by vinceho** [microsoft/azure_arc#920]
**Scenario which you are working on**
[Openshift Deployment](https://github.com/microsoft/azure_arc/blob/main/arc_data_services/deploy/yaml/README.md#security-context-constraint-for-openshift-deployments)

**Describe the bug**
The SecurityContextConstraints manifests that is required for Openshift deployment is missing from the recent update. The bootstrap deployment will fail without it when installing the Arc Data Services extension.

**To Reproduce**

1. Go to https://github.com/microsoft/azure_arc/blob/main/arc_data_services/deploy/yaml/README.md#security-context-constraint-for-openshift-deployments

**Expected behavior**
The SCC related manifests should be linked in the doc.

**Comment by dnethi** [comment]
hi @vinceho  scc's are not required anymore. Please follow the instructions at - https://docs.microsoft.com/en-us/azure/azure-arc/data/create-data-controller-using-kubernetes-native-tools

**Comment by likamrat** [comment]
Closing this for now. @vinceho please let us know if anything else is needed.
