### ISSUE TITLE
Installing App Service Extension onto CAPZ cluster failing

### ISSUE THREAD

**Issue by monojit18** [microsoft/azure_arc#929]
**Scenario which you are working on**
Trying to Install App Service Extension on CAPZ cluster
Versions attempted:
1.21.7
1.19.13

**Describe the bug**
App Service Extension installation failing with Error message:
<img width="1186" alt="Screenshot 2022-01-13 at 1 47 21 AM" src="https://user-images.githubusercontent.com/2395966/149364742-4f200f35-6786-4ea4-b456-85c6087752af.png">

Points to Note:
CAPZ cluster working fine
Pods are all in good state (_including those in _azure-arc_ namespace_)

**To Reproduce**
Setup a CAPZ cluster

Connect Azure Arc to CAPZ cluster using:
_az connectedk8s connect -g $arcK8sResourceGroup -n $connectedClusterName --distribution capz \
--kube-config $baseFolderPath/Setup/capz-k8s-cluster.kubeconfig \
--kube-context capz-k8s-cluster-admin@capz-k8s-cluster_

This command throws an exception; but completes eventually
_Failed to validate if the active namespace exists on the kubernetes cluster. Exception: local variable 'current_k8s_context' referenced before assignment_

Run _az connectedk8s list --resource-group $arcK8sResourceGroup --output table_
_Name          Location    ResourceGroup
------------  ----------  ---------------
arc-capz-k8s  eastus      arc-capz-k8s-rg_

Try to install App Service Extension onto CAPZ:
_az k8s-extension create \
--resource-group $arcK8sResourceGroup \
--name $appsvcExtensionName \
--cluster-type connectedClusters \
--cluster-name $connectedClusterName \
--extension-type 'Microsoft.Web.Appservice' \
--release-train stable \
--auto-upgrade-minor-version false \
--scope cluster \
--release-namespace $appsvcExtensionNamespace \
--configuration-settings "Microsoft.CustomLocation.ServiceAccount=default" \
--configuration-settings "appsNamespace=${appsvcExtensionNamespace}" \
--configuration-settings "clusterName=${appsvcExtensionName}" \
--configuration-settings "keda.enabled=true" \
--configuration-settings "buildService.storageClassName=managed-premium" \
--configuration-settings "buildService.storageAccessMode=ReadWriteOnce" \
--configuration-settings "customConfigMap=${appsvcExtensionNamespace}/kube-environment-config" \
--configuration-settings "envoy.annotations.service.beta.kubernetes.io/azure-load-balancer-resource-group=${capzResourceGroup}"_

Receive Error:
<img width="1186" alt="Screenshot 2022-01-13 at 1 47 21 AM" src="https://user-images.githubusercontent.com/2395966/149365893-2577a2c1-7afc-492f-a563-a104fb7ac9c4.png">

**Expected behavior**
Extension deployment should be successful

**Comment by likamrat** [comment]
Thank you @monojit18. Based on the versions, this does not look like part of the JS scenario. Can you try [this](https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_app_svc/cluster_api/)?
