### ISSUE TITLE
Ansible Onboarding Scenario

### ISSUE THREAD

**Issue by lanicolas** [microsoft/azure_arc#93]
**Is your feature request related to a problem? Please describe.**
Show the process of onboarding VMs on Azure Arc using Ansible

**Describe the solution you'd like**
Provide a playbook and a description on how to automate the onboarding of VMs on Azure Arc

**Describe alternatives you've considered**
One playbook and multiple tasks to be agnostic of the operating system. Make sure that for Linux it is agnostic of the distro

**Additional context**
NA

**Comment by likamrat** [comment]
#130 
Completed
