### ISSUE TITLE
Small problems with arc-enabled SQL Server installation

### ISSUE THREAD

**Issue by sdt-msft** [microsoft/azure_arc#936]
**Scenario which you are working on**
A link to the Jumpstart scenario you are working on.
azure_arc_sqlsrv_jumpstart (SQL server in a VM)
https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_sqlsrv/azure/azure_arm_template_winsrv/

**Describe the bug**
I found that to run the Arc-conctrolled SQL Server in a VM you have to also enable at the Subscription level the registration to the Microsoft.HybridCompute provider. This is not mentioned in the setup instructions and blocks installation.
Also the automated installation of the Microsoft Monitoring Agent is wrong; the right way to fix/setup is
in Azure Portal under machine_name (where SQL Server bits are installed)->"Server - AzureArc"->Extensions 
you need to install  "WindowsAgent.SqlServer" and "MicrosoftMonitoringAgent" extensions.

**To Reproduce**
The basic procedure described at
https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_sqlsrv/azure/azure_arm_template_winsrv/
does not work unless actions above are taken.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dkirby-ms** [comment]
Thanks for reporting this. We have some incoming changes to the SQL scenario that will be published in the next release and should address this.
