### ISSUE TITLE
Obtain internal IP address of ARC devices

### ISSUE THREAD

**Issue by chkp-jguo** [microsoft/azure_arc#944]
**Is your feature request related to a problem? Please describe.**
We would like to have the ability to extract internal IP address of ARC devices via an API call. This is currently not available. With this feature in place, it will allow security devices such as firewalls to dynamically update firewall rules. This will minimize operation overhead while maintaining security posture. 

Check Point currently has this ability to obtain internal ip address of hosts giving a tag value in public azure workloads. We would like to extend this feature to any ARC enabled devices.

**Comment by rpsqrd** [comment]
Hi @chkp-jguo -- can you submit this as an idea on the [Azure Feedback site](https://feedback.azure.com/d365community/forum/5c778dec-0625-ec11-b6e6-000d3a4f0858)? This will ensure it gets triaged and considered for future feature development.
