### ISSUE TITLE
SQL Managed Instance Azure DevOps Release

### ISSUE THREAD

**Issue by josephwoleary** [microsoft/azure_arc#948]
**Scenario which you are working on**

[Deploy Azure SQL Managed Instance on AKS using Azure DevOps Release Pipeline](https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_data/aks/aks_mssql_arm_template_ado/#deployment)

**Describe the bug**
I am trying to setup the Jumpstart for Azure SQL Managed instance on AKS using Azure DevOps.
During the Pipeline setup I copied the URLs for the ARM Template and the corresponding Parameters file.
Unfortunately these URLs seem to be a dead end.
###### Template file from documentation
```
https://raw.githubusercontent.com/microsoft/azure_arc/main/azure_arc_data_jumpstart/aks/arm_template/mssql_mi/azuredeploy.json
```
###### Parameters file from documentation
```
https://raw.githubusercontent.com/microsoft/azure_arc/main/azure_arc_data_jumpstart/aks/arm_template/mssql_mi/azuredeploy.parameters.json
```

**To Reproduce**

1. follow the documentation until the step in the screenshot
<img width="661" alt="image" src="https://user-images.githubusercontent.com/52332779/151016290-0b0ec61a-9ec9-4148-80fe-351fc377584a.png">

2. try to get the ARM template and parameters file
3. receive not found error

**Expected behavior**
The Raw reference to the GitHub repo returns a valid ARM Template needed to setup the Azure managed SQL setup.

**Comment by likamrat** [comment]
Thank you @josephwoleary. I will be updating this scenario in our current (February) sprint and will update the issue accordingly.

**Comment by likamrat** [comment]
@josephwoleary wanted to update you that @chintalavr will be picking up the task of refactoring both SQL MI and PostgreSQL Azure DevOps scenarios. 

This is related to #1019 and although took a bit longer than we wanted, now that we have refactored AKS scenarios, this issue can be unblocked. 

Thank you for your patience!
