### ISSUE TITLE
Scenario for Azure Arc-enabled servers - Azure Monitor

### ISSUE THREAD

**Issue by alsanch** [microsoft/azure_arc#964]
**Is your feature request related to a new Jumpstart scenario you would like to contribute?**
Yes, new scenario where Azure Monitor artifacts are deployed to demonstrate how to monitor Azure Arc-enabled servers.

**Is your feature request related to a problem? Please describe.**
This jumpstart scenario will show how to use Azure Monitor to get more insights of Azure Arc-enabled servers (which should be previously onboarded).

**Describe the solution you'd like**
A log analytics workspace will be deployed, along with its data sources. In addition, a set of OS alerts and workbooks will be created.

**Describe alternatives you've considered**
Not currently

**Additional context**
N/A

**Comment by likamrat** [comment]
closed via #1011
