### ISSUE TITLE
Azure Connected Machine agent for ARM64

### ISSUE THREAD

**Issue by syedhassaanahmed** [microsoft/azure_arc#966]
We'd like to collect log files (e.g. /var/log/*) from our Raspberry Pi 4 (ARM64) devices running Ubuntu 20.04. The destination of these logs is Azure Monitor, hence we're looking at the [Azure Monitor Agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-overview?tabs=PowerShellWindows) to support log collection. Since Raspberry Pi 4 is a non-Azure VM, installing Azure Monitor Agent requires us to configure an [Azure Arc-enabled server](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-manage?tabs=ARMAgentPowerShell%2CPowerShellWindows%2CPowerShellLinuxArc%2CCLIWindows%2CCLILinuxArc#install-on-azure-arc-enabled-servers-1) on the device. However, we're unable to install the [Azure Connected Machine agent](https://docs.microsoft.com/en-us/azure/azure-arc/servers/agent-overview) on the device, due to the error below.
```
/home/ubuntu/install_linux_azcmagent.sh: error: unsupported platform: aarch64:Linux
```

Ubuntu 20.04 seems to be a [supported OS](https://docs.microsoft.com/en-us/azure/azure-arc/servers/agent-overview#supported-operating-systems) for the Azure Connected Machine agent, but for x64 architecture. Are there plans to support ARM64 architecture? Is there an ETA you could share?

**Comment by likamrat** [comment]
Since this is not an Azure Arc Jumpstart issue or feature request, i will go ahead and close this for now.
