### ISSUE TITLE
Remove references to the acronym PSHS

### ISSUE THREAD

**Issue by TheJY** [microsoft/azure_arc#97]
The acronym PSHS is typically not used to refer to Postgres Hyperscale. There isn't actually an acronym for it. Some folks refer to Postgres as PG however, PG is not an official way to refer to the Postgres database engine. It is referred to Postgres or PostgreSQL. The Hyperscale name is coming from the integration in Azure of the Citus extension. In that context, the word Hyperscale is appended to Azure Postgres. 

I recommend you remove references to PSHS and instead use:

-  either the official full product name:  Azure Arc enabled PostgreSQL Hyperscale
-  or the official short product name: PostgreSQL Hyperscale - Azure Arc

Thank you

**Comment by likamrat** [comment]
@TheJY which acronym would work? PGHS?
For the automation, we need an acronym and can't use the full or the short product name you suggested. We can certainly use it in the actual doc.

**Comment by TheJY** [comment]
@likamrat , how many character can you use for the automation?

**Comment by likamrat** [comment]
@TheJY It's not a matter of how many, it's a matter of code readability and ease of use. I will set on pghs

**Comment by TheJY** [comment]
agreed, thanks
