### ISSUE TITLE
"ArcBox-K3s/installscript_k3s" Installation Issue

### ISSUE THREAD

**Issue by ceritmustafa** [microsoft/azure_arc#979]
**Scenario which you are working on**
A link to the Jumpstart scenario you are working on: https://azurearcjumpstart.io/azure_jumpstart_arcbox/full/

**Expected behavior**
***Although I try to deploy "Jumpstart ArcBox “Full” Edition" according to the instructions described here, I get an error here.
https://azurearcjumpstart.io/azure_jumpstart_arcbox/full/

`{
    "status": "Failed",
    "error": {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'installscript_k3s'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=2\n[stdout]\n\n[stderr]\n\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "
    }
}`

**Screenshots**
![image](https://user-images.githubusercontent.com/3519956/155341525-3bbc0275-5f3a-4b79-8ef5-537e2e242f1d.png)

**Comment by likamrat** [comment]
Thank you @ceritmustafa. Can you please follow the [Troubleshooting section](https://azurearcjumpstart.io/azure_jumpstart_arcbox/full/#basic-troubleshooting) and provide the installation log?

**Comment by ceritmustafa** [comment]
> Thank you @ceritmustafa. Can you please follow the [Troubleshooting section](https://azurearcjumpstart.io/azure_jumpstart_arcbox/full/#basic-troubleshooting) and provide the installation log?

Ok, when I collect the logs, I will share them with you. Thank you quick response.

**Comment by ceritmustafa** [comment]
> Thank you @ceritmustafa. Can you please follow the [Troubleshooting section](https://azurearcjumpstart.io/azure_jumpstart_arcbox/full/#basic-troubleshooting) and provide the installation log?

**I see the key invalid error for both deployments. But I think I entered the key correctly.**


`"ERROR: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '8fd1c5ae-44d7-4219-98ed-41a60ebdb9e8'."`


I have uploaded detailed logs here.

**installK3s.log** : [https://justpaste.it/39gy5](url)
**installCAPI.log** : [https://justpaste.it/4pfhs](url)

**Comment by ceritmustafa** [comment]
> Thank you @ceritmustafa. Can you please follow the [Troubleshooting section](https://azurearcjumpstart.io/azure_jumpstart_arcbox/full/#basic-troubleshooting) and provide the installation log?

> Thank you @ceritmustafa. Can you please follow the [Troubleshooting section](https://azurearcjumpstart.io/azure_jumpstart_arcbox/full/#basic-troubleshooting) and provide the installation log?

**I see the client secret key invalid error for both deployments. But I think I entered the key correctly.**


`"ERROR: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '8fd1c5ae-44d7-4219-98ed-41a60ebdb9e8'."`


I have uploaded detailed logs here.

**installK3s.log** : [https://justpaste.it/39gy5](https://justpaste.it/39gy5)
**installCAPI.log** : [https://justpaste.it/4pfhs](https://justpaste.it/4pfhs)

**Comment by likamrat** [comment]
it looks like you have _`_ at the beginning and " at the end. Double-check how the secret was copied.
Also, you can try to regenerate new secret and try again.

**Comment by ceritmustafa** [comment]
@likamrat thank you. As you said, the problem was a secret key typo.  In this attempt, the deployment was completed successfully.

**Comment by likamrat** [comment]
@ceritmustafa thank you for verifying. closing.
